### ISSUE TITLE
[Icon Request]Support for .gmx, .yy and .yyp

### ISSUE THREAD

**Issue by LiarOnce** [vscode-icons/vscode-icons#1010]
- [x] I'm sure this issue is not a duplicate.
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: `gml-gmx`
      - Sample original Icon : The same to `gml-gms`
      - Extensions: `.gmx`
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: `gml-yyp`
      - Sample original Icon : The same to `gml-gms2`
      - Extensions: `.yy` and `.yyp`

**Comment by jens1o** [comment]
You could also consider adding it to your extension, but I implemented it.

**Comment by LiarOnce** [comment]
Thanks!
