### ISSUE TITLE
Cannot disabled icon associations for specific extensions.

### ISSUE THREAD

**Issue by josh-sachs** [vscode-icons/vscode-icons#1013]
- [X] I'm sure this issue is not a *duplicate*?

```
"vsicons.projectDetection.disableDetect": true,
"vsicons.associations.folders": [
    { "extensions": ["src"], "icon": "src", "format": "svg", "disabled": false },
    { "extensions": ["source", "sources"], "icon": "src", "format": "svg", "disabled": true }
],
```

Trying to disable theme icons by overriding the folder association entries does not appear to work.   In this case I am trying to remove the "src" icon association to folders named "source" and "sources".

**Comment by jens1o** [comment]
Did you execute `Icons: Apply Icons Customization`?

**Comment by josh-sachs** [comment]
yes - as well as restarting vscode.

**Comment by jens1o** [comment]
Okay, I try to reproduce.

**Comment by jens1o** [comment]
Could reproduce this:

Even when I do: 
```json
"vsicons.associations.folders": [
        {
            "icon": "src", 
            "extensions": ["src", "source", "sources"],
            "format": "svg",
            "disabled": true
        },
        {
            "icon": "src", 
            "extensions": ["source", "sources"],
            "format": "svg"
        }
    ]
```

**Comment by robertohuertasm** [comment]
Disabling will always disable the icon in all the extensions it is applied so it's only purpose is to completely hide the icon.

If you want to partially apply the icon, the recommended way to do this is to use the `overrides` property.

For your case, it would be something like this:

```
"vsicons.associations.folders": [
    { "extensions": ["src"], "icon": "src", "format": "svg", "disabled": false, "overrides": "src" }
]
```

**Comment by jens1o** [comment]
I think we should update the README in this case(even I didn't know about that...).

**Comment by josh-sachs** [comment]
@robertohuertasm this worked - so I guess the issue is the documentation.

**Comment by robertohuertasm** [comment]
We'll update the docs with a few more examples so this can be achieved without problems.

**Comment by jens1o** [comment]
Who'll do that?

**Comment by robertohuertasm** [comment]
I'll do it. No problem. 😁

**Comment by jens1o** [comment]
*feeling relieved*

**Comment by JimiC** [comment]
Really edge case but we still covering it as @robertohuertasm demonstrated.

**Comment by jens1o** [comment]
Yep

**Comment by jens1o** [comment]
Thanks @josh-sachs for bringing this to our attention!
