### ISSUE TITLE
[Icon Request] html and scss icons for Angular (+2)

### ISSUE THREAD

**Issue by michaeljota** [vscode-icons/vscode-icons#1016]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: `extension`
      - Icon Name: `angular-template`
      - Sample original Icon (32x32/svg/transparent whenever possible): [url]
      - Extensions: [ `*.component.html`, `*.component.scss` ] 

I think this could be just the `*.component.ts`, with the Angular red logo but with the HTML5, and SCSS as subindex.

**Comment by JimiC** [comment]
We have already talked about those icons and we have decided not to go forward with it.
@robertohuertasm Are you thinking it?

**Comment by robertohuertasm** [comment]
My first reaction has been to say "create your own custom icons for this" but... I'm actually thinking about this and, to be frank, I don´t have a clear idea in my mind. 

One should argue that this would be following the same pattern we started with `.component.ts`... but then I think that if we start down this road we´ll end up with lots of angular icons everywhere (i.e. `.component.spec.ts` probably should be also considered) and we'll lose the point of spotting the angular files. 

Let's play with this idea a little more time before deciding what to do. @jens1o, @JimiC what is your point of view, if any?

**Comment by jens1o** [comment]
I think at some time, it is unmaintainable and too complicated for the user, I don't think we need the icons.

**Comment by robertohuertasm** [comment]
![image](https://user-images.githubusercontent.com/696981/26989794-b2a3bd20-4d54-11e7-87d1-9f1b6b8ced07.png)

vs

![image](https://user-images.githubusercontent.com/696981/26989831-da061372-4d54-11e7-9b55-952ba89ddfc4.png)

**Comment by jens1o** [comment]
I somehow don't get the point... I don't know why we should introduce this, because this is true, but on the other side, it will look the same. I can't decide, but I think we don't need them.

**Comment by robertohuertasm** [comment]
![vs_ang](https://user-images.githubusercontent.com/696981/26989989-72877ac8-4d55-11e7-97b4-ab65cca6ce33.png)

**Comment by robertohuertasm** [comment]
Here I posted another one with more files, just to see the contrast and how easy is to spot them in a real project loaded with lots of icons.

The current one is clear. The proposed one is not as clear but it's very uniform and makes the component folders to look nicely structured.

**Comment by JimiC** [comment]
For the history, I was the one that proposed to add `Angular` specific icons for `html` and `css`.
But @robertohuertasm convinced me that there is no point in doing it because:
1. It will confuse users as it will not be clear which file is which.
2. `Angular` `html` file is still an `html` file and so is a `css` one. There isn't any fundamental syntax chance in them (yes I know that you have `Angular` directives as attributes in them but the file is still an `html` one in most parts).

The `js`, `ts` (and we should have added the `dart` too) have a syntactic structure that is specific to `Angular` and that's the main reason they got a specific icon.

So my vote is to leave things as they are.

**Comment by jens1o** [comment]
I agree with @JimiC

**Comment by robertohuertasm** [comment]
I didn't remember that but that was indeed my first thought. For the record, [here is the link to the comments](https://github.com/vscode-icons/vscode-icons/issues/437#issuecomment-267143416) .

Anyway, if it's ok with you and given that we have second sets of icons, I'd propose to upload them in case anyone wants to use them and customize the experience. This will leave things as they are and allow angular fanboys to set their angular icons everywhere. Is this fair enough?

**Comment by jens1o** [comment]
> angular fanboys
*sigh*

Okay, but I'll stick to it: I don't need it.

**Comment by michaeljota** [comment]
You guys rock! Thank you!
