### ISSUE TITLE
[Task] Improve handling of manually set preset and association settings

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1019]
- [x] I'm sure this issue is not a *duplicate*?

As mentioned in #1015 there is need to better handle and improve the UX when a `preset` or `association` is manually set.

**Comment by JimiC** [comment]
@robertohuertasm @jens1o Regarding the 
> 2. Allow the user to turn on/off this behavior.

is `dontShowConfigManuallyChangedMessage` as property name acceptable?

Does `"If set to true, when manually changing the configurations, the 'restart' message won't be shown."` satisfy as a description?

**Comment by jens1o** [comment]
I'm fine with this.

**Comment by robertohuertasm** [comment]
:+1:  for the message. 

What about `skipConfigManuallyChangedMessage` not the best but at least a little bit shorter.

**Comment by JimiC** [comment]
Was trying to be in line with `dontShowNewVersionMessage`.

**Comment by JimiC** [comment]
So what will be, cause apart from naming I have a PR waiting?

**Comment by robertohuertasm** [comment]
Ok. Leave it with `dontShow` then. :+1:
