### ISSUE TITLE
[Icon Request] Support for 'modules/models/controllers/router' folder

### ISSUE THREAD

**Issue by 1312682** [vscode-icons/vscode-icons#1022]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [folder]
      - Icon Name: [modules, models, controllers, router]
      - Sample original Icon: 
https://maxcdn.icons8.com/Share/icon/Programming//module1600.png
https://openclipart.org/image/2400px/svg_to_png/202776/pawn.png
http://www.endlessicons.com/wp-content/uploads/2013/05/continuous-play-icon-solid.png
http://www.iconarchive.com/download/i91409/icons8/windows-8/Network-Router.ico
      - Extensions: modules/module, model/models. controllers, router
Thank you.

**Comment by JimiC** [comment]
Please see #650.
