### ISSUE TITLE
No icons are showing.

### ISSUE THREAD

**Issue by vikasingh34** [vscode-icons/vscode-icons#1030]
i just installed it now. Uninstalled it. Let me know when this bug fixed.
i have done every exactly as said in instruction. Started as administrator and instaled it. then restared the VCS but for some reason nothing seems to work.

**Comment by JimiC** [comment]
Please see: https://github.com/vscode-icons/vscode-icons#enable-the-extension

**Comment by vikasingh34** [comment]
I had done the same, but was not working but now working flowless after restarting my PC.
Thank You Sir. :)
