### ISSUE TITLE
Cannot find  File > Preferences > "File Icon Theme" VSC 1.3.1

### ISSUE THREAD

**Issue by NoahHuynh** [vscode-icons/vscode-icons#1032]
Hi after I installed the icons pack with quick open I cannot find "File Icon Theme"  in File > Preferences.  Is this a common issue?  Any possible solutions?

**Screenshots are more than welcome!**
![image](https://user-images.githubusercontent.com/10272229/27436945-6419062a-5726-11e7-97be-2f0a7b2affcd.png)

**Thanks :smile:**

**Checklist:**

- [ ] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):
      - Type: [extension/folder]
      - Icon Name: [name]
      - Sample original Icon (32x32/svg/transparent whenever possible): [url]
      - Extensions: .just, .a, .bunch, .of, .extensions

**Comment by jens1o** [comment]
What version did you installed? Can you try install the latest version?

**Comment by NoahHuynh** [comment]
Thanks I found out there's a bug in my application for some reason when I go to help and search for an update I get a prompt that shows I have the latest version.  However when I look deeper into the issue I have the version from 2016 (-_-) lol
![image](https://user-images.githubusercontent.com/10272229/27437994-906d706e-5729-11e7-92a4-9e064654d514.png)

**Comment by jens1o** [comment]
Download it again from https://code.visualstudio.com

**Comment by NoahHuynh** [comment]
Yeap problem solved thanks.
