### ISSUE TITLE
[Icon Request] MJML folder

### ISSUE THREAD

**Issue by jmbelloteau** [vscode-icons/vscode-icons#1034]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [folder]
      - Icon Name: [mjml]
      - Sample original Icon (32x32/svg/transparent whenever possible): [don't know any]
      - Extensions: .mjml

**Comment by JimiC** [comment]
Please see #650.

**Comment by jens1o** [comment]
Sorry ^^

**Comment by jmbelloteau** [comment]
@JimiC sure sorry for this 😄 !

**Comment by jmbelloteau** [comment]
@JimiC done!
