### ISSUE TITLE
[Icon Request] Support for vendor folder

### ISSUE THREAD

**Issue by jmbelloteau** [vscode-icons/vscode-icons#1035]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [folder]
      - Icon Name: [vendor]
      - Sample original Icon (32x32/svg/transparent whenever possible): [don't know any]
      - Extensions: vendor

**Comment by robertohuertasm** [comment]
@jmbelloteau thanks for opening this issue but as stated in the issue template all folder requests must be added to #650.

**Comment by jmbelloteau** [comment]
@robertohuertasm  done! thanks for the advice 😄  !
