### ISSUE TITLE
[Icon Request] Support for robots.txt

### ISSUE THREAD

**Issue by jmbelloteau** [vscode-icons/vscode-icons#1036]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [extension]
      - Icon Name: [robots]
      - Sample original Icon (32x32/svg/transparent whenever possible): [don't know any]
      - Extensions: .txt

**Comment by JimiC** [comment]
Duplicate #1023.
