### ISSUE TITLE
[Icon Request] Extend docker-compose icon to docker-compose.*.yml

### ISSUE THREAD

**Issue by mmisztal1980** [vscode-icons/vscode-icons#1037]
As title says,

My tooling generates a bunch of docker-compose files, such as:

- docker-compose.ci-build.yml
- docker-compose.override.yml
- docker-compose.vs.debug.yml
- docker-compose.vs.release.yml

All of the above are displaying the generic YAML icon. IMHO, the experience would be far better if they'd display the icon used for docker-compose.

Best regards,
Maciej

**Comment by jens1o** [comment]
Will do this tomorrow, I'm tired atm.

**Comment by robertohuertasm** [comment]
@mmisztal1980, this is not possible at the moment. As you can see here in [vscode#12493](https://github.com/Microsoft/vscode/issues/12493) this feature has been requested long time ago.

@jens1o I'm not sure we should be implementing these filenames as I'm not sure if they're very common or just the ones that @mmisztal1980 is using. 

@mmisztal1980 you should be able to add these custom extensions yourself to your vscode settings and you will be able to have the icons. Please, take a look at this [part of the readme](https://github.com/vscode-icons/vscode-icons#fine-tuning).

**Comment by mmisztal1980** [comment]
They're being generated by the Visual Studio 2017's official Docker tooling, so I'd say they're becoming pretty common

**Comment by jens1o** [comment]
Yep, he's right, they are common, I saw them, but I never thought somebody will use it using `vscode` when it was generated by the big brother... But this turns out to also be wrong.
