### ISSUE TITLE
The extensions is always asking for a Restart when having a workspace customization

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#1042]
VSCode: 1.13.1 & 1.14.0-insider

Since 7.10.0 has been published it seems that we introduced some kind of bug and the extension is always asking me for a restart when I'm working in my Angular project. 

This doesn't happen in any other kind of projects.

I think the project detection system is messing with the `manual change detection` in the settings.

For the moment, I have to completely disable the new feature 😢 

It's strange because I never observed this behavior when developing or testing.

**Comment by JimiC** [comment]
Any reproduction steps?

**Comment by robertohuertasm** [comment]
I just open the angular project and start into a restart loop without end. The weird thing is I open the same exact project debugging the extension and it doesn't ask for a restart.

At the moment this is all the information I have. I'll check it out again tonight if I find some quiet moment.

**Comment by robertohuertasm** [comment]
I've tested with a Nativescript project (which uses Angular) and I'm not having the issue so must be something specific about my project.

**Comment by JimiC** [comment]
OK then. The debugging of the issue is all yours. :)

**Comment by robertohuertasm** [comment]
It seems that in order to reproduce this you have to have some icon customizations in your `workspace` settings:

```
"vsicons.associations.files": [
    { "icon": "karma",  "extensions": ["karma.conf.gitlab.js"], "filename": true, "format": "svg" }
  ]
```

**Comment by robertohuertasm** [comment]
Indeed, it is not only affecting Angular projects but any project with workspace customizations.

**Comment by rnemec** [comment]
Confirming here too: icon customizations in workspace settings => "Restart" looping.

**Comment by robertohuertasm** [comment]
@rnemec, @JimiC already provided a fix. We'll be publishing it tomorrow.

**Comment by rnemec** [comment]
@robertohuertasm - thank you. I guess you have it fully under control now, but FYI an additional test case is editing workspace settings - each Save triggers that "Reload" popup.

**Comment by robertohuertasm** [comment]
@JimiC, it seems that it's still not working. I've just tested it before publishing but I keep receiving the same error.

**Comment by robertohuertasm** [comment]
Fixed it in latest PR. Already published.
