### ISSUE TITLE
Correct nested folders indentation

### ISSUE THREAD

**Issue by glaszczyk** [vscode-icons/vscode-icons#1048]
Maybe it would be great to make more unified indentation for folders and files. For now sometimes there is difficult to see which folder contains files.

Here is how it looks with vscode icons
![icons](https://user-images.githubusercontent.com/16131329/27624216-02602350-5be0-11e7-90ff-55dbd01330d7.png)

Maybe with files icons aligned with folder's names it would be easier to locate nesting levels. Something like this.
![untitled](https://user-images.githubusercontent.com/16131329/27624838-ad09c80e-5be2-11e7-8a32-8557872a9c55.png)

**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

**Comment by robertohuertasm** [comment]
I think this is not possible with the current `Visual Studio Code` api. The only thing we could do would be to modify the size of the icons but this would make the icons to be disaligned in tabs.

I think you should raise this issue into the `vscode` repo.
