### ISSUE TITLE
Can I use these icon set for other purposes ?

### ISSUE THREAD

**Issue by Xsmael** [vscode-icons/vscode-icons#1051]
- [x] I'm sure this issue is not a *duplicate*?

Can I use these icon set for other purposes?  outside of vscode in my own projects ?

**Comment by jens1o** [comment]
Depends. Some icons are created by @JimiC and some are copied from their webpages... I don't know.

**Comment by Xsmael** [comment]
but the project is under MIT license, 
btw I'm not asking of the possibility technically, i know how to do it.

**Comment by jens1o** [comment]
I think @robertohuertasm will know what to say.
I believe we can't release the trademarks of companies under the MIT License, I think we should say that only the code itself(excluding the icons) are under the MIT License.

**Comment by robertohuertasm** [comment]
@Xsmael, the project is adscribed to MIT licensing so, essentially, you can do whatever you want as long as you give credit to the original source. There are, indeed, other projects that are already using some of the icons: i.e [file icons for vs](marketplace.visualstudio.com/items?itemName=MadsKristensen.FileIcons).

**Comment by Xsmael** [comment]
Alright, that's what i wanted to know, thanks. However, the link isyou gave is broken.

**Comment by robertohuertasm** [comment]
I fixed it. Sorry I wrote it in my mobile phone 😉
