### ISSUE TITLE
.m files have generic icon instead of desired Matlab icon

### ISSUE THREAD

**Issue by irlsmith** [vscode-icons/vscode-icons#1053]
I'm completely new to GitHub but I noticed a thread here relevant to my problem. I use Matlab and not XCode (except for a few things like looking at plists).  I want my Matlab m-files to have the Matlab m-file icon (here it is, copied out of matlab.app):
![matlab m-file icon](https://user-images.githubusercontent.com/29843600/27773304-9d93628a-5f44-11e7-9174-c40741681466.png)
Instead I get the XCode m-file icon:
![c m-file icon](https://user-images.githubusercontent.com/29843600/27773300-692b8400-5f44-11e7-9876-3fdc876997c7.png)
These files do open Matlab when double-clicked (I did the Info box dance) but the icon is not from matlab.app. 
I did manually modify (via the Info box) one of my m-files (the top one here):
![matlab icon problem](https://user-images.githubusercontent.com/29843600/27773155-66b8a14c-5f41-11e7-9050-5fc44afc7e9f.png)
Note that the middle one, a .fig file, has the correct Matlab icon, so the OS certainly knows about Matlab. But the bottom one is what all my other m-files look like.
I have tried using Terminal to delete the icon cache and a few other things (details on request) and even reinstalled Matlab. No joy so far. Any help would be appreciated.

**Comment by robertohuertasm** [comment]
Hi @irlsmith, `m` extension is supported via `language id`. Just install any extension supporting Matlab from the Marketplace.

You can use [this](https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab) for instance.

**Comment by irlsmith** [comment]
Dear Roberto,
  I took a look at the linked document you suggest. It appears that it will let me use vscode (whatever that is; as I noted, I'm new to GitHub, and I also have never learned any variant of C) to context-color Matlab. But that's not my problem. I have a problem with OS X Finder display of icons for .m files. Maybe I just didn't understand your comment ...
===========
|   Irl Smith <opticsmith@mindspring.com> 
|   978-371-1060 (cell: 978-270-1905)
|   Concord, Massachusetts
===========

**Comment by irlsmith** [comment]
P.S. Maybe I shouldn't have posted my question/comment in this thread. Is there a mechanism for issuing a general question? I used this thread because it came up in a Google search for conflicts between XCode and Matlab m files. (I did read the newbie-instructions for GitHub but it wasn't terribly clear what to do with a general question.)

**Comment by robertohuertasm** [comment]
I see.  The thing is that this is a thread from a specific repository and project, which intends to provide icons for `vscode`.

Yours is a problem with XCode so I guess you should be addressing this to Apple in [one of their forums dedicated to support their products](https://developer.apple.com/support/xcode/), not in Github. 

Github is just an index of code repositories dedicated to very different purposes.

Hope you find your solution. 😉

**Comment by irlsmith** [comment]
Thanks!
===========
|   Irl Smith <opticsmith@mindspring.com> 
|   978-371-1060 (cell: 978-270-1905)
|   Concord, Massachusetts
===========

**Comment by planetrocky** [comment]
It's even worse with the latest update(s)

'.m' files are now showing as [C],  '.m' is the main file extension for Matlab and isn't even listed in the wiki as a supported type...

**Comment by JimiC** [comment]
Your allegations aren't correct. `.m` is not associated with any icon in our extension. An icon is only shown when you have installed a syntax highlighting extension from the marketplace and it's totally controlled by those.

**Comment by planetrocky** [comment]
Look at your own wiki and go down to the Matlab entry:

https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

**Comment by planetrocky** [comment]
'.m' is the main file extension for Matlab and isn't even listed in the wiki as a supported type...

**Comment by JimiC** [comment]
Obviously, you don't know how our extension works so please refrain from making wrong allegations.

**Comment by planetrocky** [comment]
obviously you are rude and wrong

**Comment by planetrocky** [comment]
blocked!

**Comment by irlsmith** [comment]
Gentlemen, please. Rocky needs an explanation and Jimi should provide it. FWIW, searching the link for "matlab" I see a number of file types listed, but .m is not one of them. It's unfortunate that Matlab's designers chose such a possibly-ambiguous extension for their most common file type, but that's water under the dam at this point.
===========
|   Irl Smith <opticsmith@mindspring.com> 
|   978-371-1060 (cell: 978-270-1905)
|   Concord, Massachusetts
===========

**Comment by JimiC** [comment]
@irlsmith Those extensions are additional file extensions that we directly support because no 3rd party syntax highlighting extension includes them. `.m` is supported directly from those extensions. You just need to install that extension.
Proof: https://github.com/Gimly/vscode-matlab/blob/master/package.json#L36

**Comment by robertohuertasm** [comment]
I've just seen the emails!  Where did the messages go? They have disappeared.

**Comment by irlsmith** [comment]
Can you please clarify what "install" means in this context? OS X 10.11.6, Matlab r2017a. I suspect "install" means into some software development package I don't have.
===========
|   Irl Smith <opticsmith@mindspring.com> 
|   978-371-1060 (cell: 978-270-1905)
|   Concord, Massachusetts
===========

**Comment by robertohuertasm** [comment]
@irlsmith, @JimiC is talking about a `Visual Studio Code` extension like [this one](https://marketplace.visualstudio.com/items?itemName=Gimly81.matlab). 

You need to install this extension into Visual Studio Code for our extension to activate the `Matlab` icon.

**Comment by irlsmith** [comment]
Thanks!
===========
|   Irl Smith <opticsmith@mindspring.com> 
|   978-371-1060 (cell: 978-270-1905)
|   Concord, Massachusetts
===========
