### ISSUE TITLE
[Icon Request] Support for OpenEdge ABL

### ISSUE THREAD

**Issue by jousmo** [vscode-icons/vscode-icons#1054]
Edited by @JimiC

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `openedge`
      - Sample original Icon: ![openedge](https://zvg.gallerycdn.vsassets.io/extensions/zvg/vscode-oeabl/0.2.2/1476355167049/Microsoft.VisualStudio.Services.Icons.Default)
      - Extensions: support via `language id`

Extension on marketplace: https://marketplace.visualstudio.com/items?itemName=zvg.vscode-oeabl

More info @ https://www.progress.com/openedge

**Comment by jens1o** [comment]
May you please use the issue template? It's not that hard and provides some nice overview to work with.

**Comment by diegoclair** [comment]
abl to OpenEdge language, the files have '.p' extensions.. but in the vscode-icons, the '.p' is recognition for prolog and the icon-image is wrong. Or maybe I'm confused. Can you see please?
