### ISSUE TITLE
[Icon request] Alternative php icon

### ISSUE THREAD

**Issue by Chris2011** [vscode-icons/vscode-icons#1056]
As you have this already for JS, JSON and some other file types I think, you have the official icon and alternatives for those so it would be cool if we can have a second alternative PHP icon which looks more modern. The official looks old, the elephant ks funny but I prefer only a light purle PHP like for JS, C, C++, C# etc.

Regards

Chris

**Comment by jens1o** [comment]
(In the meantime, we got two php icon files where you can decide...)
https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_php.svg
and https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_php2.svg

**Comment by Chris2011** [comment]
Yes I already know it, but I prefer smth like this to have: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_js.svg but with php in the purple color. Looks similar to TS, JS etc.

**Comment by jens1o** [comment]
@Chris2011 Are you fine with the upcoming addition?

**Comment by Chris2011** [comment]
Yes, great. Thx :)
