### ISSUE TITLE
How to change size for icon

### ISSUE THREAD

**Issue by hoangnamitc** [vscode-icons/vscode-icons#1070]
Hi adm,

I want size up large icon. How to?

Thanks !

**Comment by jens1o** [comment]
You want to have the icons a little bit bigger? I'm afraid, but this is not possible with our implementation... You may want to suggest that change at `vscode`'s repo and link it here, so we can track the status, too.

**Comment by JimiC** [comment]
The icons have a fixed size of 32x32 in Zoom 0 mode. You can increase/decrease the size by zooming in and out (Ctrl - -, Ctrl - +, or navigate to `View`).

**Comment by syedsimanta03** [comment]
> The icons have a fixed size of 32x32 px in Zoom 0 mode. You can increase/decrease the size by zooming in and out (Ctrl - -, Ctrl - +, or navigate to `View`).

I need icon size change option. Only icon and folder icon size NOT ZOOM.

**Comment by blitzvb** [comment]
Same here.

**Comment by adamreisnz** [comment]
I too would like to see larger icons.

Compare VSCode to Atom, the icons in Atom are much clearer, while VS Code has a lot of wasted space around them:

![image](https://user-images.githubusercontent.com/490562/59136731-88a58180-89d8-11e9-87ff-d8ac1323c5df.png)

![image](https://user-images.githubusercontent.com/490562/59136735-8d6a3580-89d8-11e9-9519-4c4f1aa16f64.png)

**Comment by RecodeExistence** [comment]
It's 2020 and we still need larger icons.  Please implement?  Thanks!

**Comment by KingDarBoja** [comment]
This is out of scope for this extension, it requires VSCode official Team to tackle down things like this.

**Comment by RecodeExistence** [comment]
No problem, thanks.  I was just hopeful.  I even considered going to look
see if I could program it myself, but I've not contributed to open source
yet, so I wouldn't be entirely sure what I was looking for.

**Comment by dpeligio** [comment]
You can use zoom and adjust the editor font size

![Screenshot from 2020-03-19 16-24-55](https://user-images.githubusercontent.com/35830062/77046613-45b01a00-69fe-11ea-9587-1e98f478e877.png)

![Screenshot from 2020-03-19 16-24-32](https://user-images.githubusercontent.com/35830062/77046607-421c9300-69fe-11ea-971e-91413856073f.png)

**Comment by anselmobattisti** [comment]
> The icons have a fixed size of 32x32 px in Zoom 0 mode. You can increase/decrease the size by zooming in and out (Ctrl - -, Ctrl - +, or navigate to `View`).

Man you saved my morning! For some reason the zoom was if below 0 and they was really small!!!!!

Ctrl ++ solve the problem!

**Comment by FradSer** [comment]
Try `"window.zoomLevel": 0.3,`:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/1439628/96282804-c7583c80-100d-11eb-9ffd-54e2bf5f7c51.png">

**Comment by bruno-brant** [comment]
I created a feature request for vscode, track it at microsoft/vscode#129771

**Comment by tsp1998** [comment]
Please refer this answer: https://stackoverflow.com/a/73754045/12804254

**Comment by ftp5500** [comment]
use mac: `cmd + + ` , in win: `ctrl ++` to change icons size ; font size it would be  changed also in editor , so you need to change font size , just go to settings the chose Text Editor then change the font size

**Comment by efibutov** [comment]
> It's 2020 and we still need larger icons. Please implement? Thanks!

It's 2024 and still no news

**Comment by alihesari** [comment]
I have updated the `Zoom Level` to 1 in the settings, which is now better.

<img width="1488" alt="Image" src="https://github.com/user-attachments/assets/b36d6b60-a30f-4b07-b3d1-b62786715dd4" />
