### ISSUE TITLE
[Icon Request] Support for ANTLR

### ISSUE THREAD

**Issue by Chris2011** [vscode-icons/vscode-icons#1077]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `antlr`
      - Sample original Icon (32x32/svg/transparent whenever possible): https://github.com/antlr/intellij-plugin-v4/blob/master/resources/icons/org/antlr/intellij/plugin/antlr%402x.png
      - Extensions: Support via `language id: antlr`

As I discovered, that VSCode can't handle g4 files (This will handled by a 3rd-party-plugin), .g4 and .tokens files don't have an icon (With the 3rd-party-plugin, they don't have it too). So as a suggestion from an IntelliJ plugin, which already has this icon, is it possible to reuse it? I couldn't find a common on google, which is small enough, but in general, it is an orange circle with the A inside.

Regards

Chris

**Comment by JimiC** [comment]
Please provide more info about `.tokens` file extensions.

**Comment by Chris2011** [comment]
As from a thread here: https://groups.google.com/forum/#!topic/antlr-discussion/AJbaufL5m0k

`ANTLRCreates a tokens file for each grammar that it encounters.`

Is this enough?

**Comment by JimiC** [comment]
Quoting from the same discussion.
> The file is a temporary file created during the build process. It’s not checked into source control, and it’s not distributed with the final application or library which uses ANTLR.

So I don't think the extension should be bind to `ANTLR`.
@robertohuertasm What do you think?

**Comment by JimiC** [comment]
Even `vscode`[ANTRL](https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4) extension doesn't bind `.tokens`, only `.g` and `.g4`.

**Comment by Chris2011** [comment]
ok, than I'm fine for an Icon for .g and .g4 files.

**Comment by robertohuertasm** [comment]
I agree with you @JimiC, let's follow the lead of the [ANTRL ](https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4) extension.
