### ISSUE TITLE
cfm file extension different somehow

### ISSUE THREAD

**Issue by dariusj18** [vscode-icons/vscode-icons#1079]
- [X] I'm sure this issue is not a *duplicate*?

Something has changed with the cfm file extension.  I was able to restore icons to .cfm files by editing the icons.json and languages.js files and changing instances of "lang-cfml" to just "cfml"

**Comment by JimiC** [comment]
`Coldfusion` icons are supported via 3rd party extensions like https://marketplace.visualstudio.com/items?itemName=ilich8086.ColdFusion.

Generally, I would advise against tampering with the extension's code.

**Comment by dariusj18** [comment]
It looks like that repo changed their language definition to "cfml" from "lang-cfml"
so we might want to add an id  to https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/languages.ts

` coldfusion: { ids: ['lang-cfml', 'cfml'], defaultExtension: 'cfml' },`

**Comment by JimiC** [comment]
They rolled back the change (https://github.com/ilich/vscode-coldfusion/commit/fc835ec06f946cf3830cbd2245e3a72afdb2adf8)
