### ISSUE TITLE
[Icon Request] Support for .interceptor.ts in Angular 4.3+

### ISSUE THREAD

**Issue by juergenzimmermann** [vscode-icons/vscode-icons#1080]
Angular 4.3+ provides interceptors which are typically implemented in files with the extension .interceptor.ts. It would be nice if VSCode Icons would support these files.

**Comment by JimiC** [comment]
@robertohuertasm Do you have an idea for an icon?

**Comment by robertohuertasm** [comment]
I was thinking of using some other color, not a specific icon.

**Comment by JimiC** [comment]
Yeah. That's what I meant.

**Comment by robertohuertasm** [comment]
Then no... I have not thought of or test any color yet. Do you have one in mind?

**Comment by JimiC** [comment]
I'm baffled, that's why I'm asking you.

**Comment by JimiC** [comment]
How about those?
![interceptor-js](https://user-images.githubusercontent.com/1716442/31623659-d733e084-b2a8-11e7-836e-fe22dd8d8e4f.png)![interceptor-ts](https://user-images.githubusercontent.com/1716442/31623667-de88a914-b2a8-11e7-9e7b-7d3bcfb66359.png)

**Comment by robertohuertasm** [comment]
LGTM! 👍
