### ISSUE TITLE
[Icon Request] Supprt for kubernetes

### ISSUE THREAD

**Issue by whitecolor** [vscode-icons/vscode-icons#1082]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: `folder`
      - Icon Name: `kubernetes`
      - Sample original Icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.svg
      - Names: `kubernetes`, `k8s`, probably `kube`

**Comment by JimiC** [comment]
Moved to #650.
