### ISSUE TITLE
js icon is too ugly!

### ISSUE THREAD

**Issue by xgqfrms-gildata** [vscode-icons/vscode-icons#1094]
# js icon is too ugly!

![image](https://user-images.githubusercontent.com/29531779/28565254-3f98b2b2-715e-11e7-8103-73ab4d290d06.png)

**Comment by xgqfrms-gildata** [comment]
# how can roll back to the old version?

**Comment by JimiC** [comment]
Not our theme. Please activate `vscode-icons` theme (a.k.a. `VSCode Icons`).

**Comment by xgqfrms-gildata** [comment]
# ok, it's my VSCode loading icons with some delay!
