### ISSUE TITLE
Make a list of all icons: searchable

### ISSUE THREAD

**Issue by vajahath** [vscode-icons/vscode-icons#1095]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

It would be awesome if the library has a page, listing all folder/file names with corresponding icon: so that we can quickly search the list to find an apt folder/file name that has an icon assigned.

like:

| file name   | preview           | tags                   |
|-------------|-------------------|------------------------|
| src, source | <preview_of_icon> | source                 |
| test, tests | <preview_of_icon> | test                   |
| typings     | <preview_of_icon> | typescript, javascript |
| typescript  | <preview_of_icon> | typescript, javascript |
| *.d.ts      | <preview_of_icon> | typescript, javascript |
| ...         | ...               | ...                    |

**Comment by JimiC** [comment]
Looking at https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts for files and https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedFolders.ts for folders is quite easy to read in my opinion.
It's also linked in the `README` file.
