### ISSUE TITLE
[Icon Request] Support for yeoman

### ISSUE THREAD

**Issue by vajahath** [vscode-icons/vscode-icons#1096]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension/filename`
      - Icon Name: `yeoman`
      - Sample original Icon: 
![image](https://user-images.githubusercontent.com/12165822/28567968-d857c39c-7151-11e7-9d51-a450f54fefe3.png)
      - Extensions: `.yo-rc.json`

**Comment by JimiC** [comment]
I'ld prefer to use ![icon](http://yeoman.io/static/tool-yo.4ed95cac73.png)
