### ISSUE TITLE
Activate message always shows at startup in Insiders

### ISSUE THREAD

**Issue by yageek** [vscode-icons/vscode-icons#1097]
- [x] I'm sure this issue is not a *duplicate*?

I just switched to the insiders versions. The version is the following:
```
Version 1.15.0-insider (1.15.0-insider)
ae73f8ee6f8ddb87b5e30d31655d9f55a53f4a95
2017-07-26T07:33:29.308Z
```

Overtime I start the editor, I have the informations message asking me if I want to activate the extension: 
![capture d ecran 2017-07-26 a 14 21 46](https://user-images.githubusercontent.com/170917/28620574-cfc1e732-720d-11e7-8fef-d6fb8c307e4c.png)

Whatever I click, the message does not disappear. The same if I uninstall and reinstall.
I also tried to set the following parameters to false:

```
"vsicons.dontShowNewVersionMessage": true,
"vsicons.dontShowConfigManuallyChangedMessage": true
```

**Comment by JimiC** [comment]
The cause is a crash when `vscode` is trying to determine the version of the extension.
The actual error is : 
>Activating extension `robertohuertasm.vscode-icons` failed:  Invalid Version: 0

I know exactly what is going on and I'll provide a fix soon.

**Comment by ostrgard** [comment]
This issue returned for me after upgrading to 7.13.0.

**Comment by jens1o** [comment]
@ostrgard May you create a new issue please? I cannot reproduce.
