### ISSUE TITLE
Can't find vsicons.settings.json

### ISSUE THREAD

**Issue by kkwapnioski** [vscode-icons/vscode-icons#1101]
The company I work for compiles and uses their own customized version of the open source vscode. With the open source version, the path vscode-icons is looking for *vsicons.settings.json* is incorrect. (In my case it should be looking in 
*APP_DATA_PATH/Code - OSS/User/vsicons.settings.json*)

![image](https://user-images.githubusercontent.com/9012126/28684625-ab097a8c-72ca-11e7-87cc-3d5d5b1ed158.png)

From what I could find, there is no official API in vscode to get the correct AppData path, however, I believe this path is defined by the *name* property in vscode's package.json (*VSCODE_INSTALL_PATH*/resources/app/package.json)

I think reading this property to build the AppData path could also simplify the logic with *standard* and *insiders* versions of VS Code as well.

**Checklist:**
- [x] I'm sure this issue is not a *duplicate*

**Comment by JimiC** [comment]
We'll definitely have a look on that one.

**Comment by JimiC** [comment]
Actually `vscode` has an API for this called [env.appName](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_env). Just need to find how the self-build version is called and we can add that to our logic.

**Comment by JimiC** [comment]
@kkwapnioski To save us the hassle can you tell us what is the value of the `name` property in the `package.json` for self-build `vscode` instances?

**Comment by kkwapnioski** [comment]
package.json = `Code - OSS`
env.appName = `VSCode OSS`

**Comment by JimiC** [comment]
Looks like the info can also be found [here](https://github.com/Microsoft/vscode/blob/master/product.json).

**Comment by JimiC** [comment]
@kkwapnioski Let us now if it works for you.

**Comment by kkwapnioski** [comment]
Ya, everything looks fine.
