### ISSUE TITLE
[Icon request] .yaml is not recognized, .yml is

### ISSUE THREAD

**Issue by sanderma** [vscode-icons/vscode-icons#1105]
- [x] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request

When using the default settings, the `.yaml` extension is not recognized, `.yml` is.

![image](https://user-images.githubusercontent.com/13538978/28716276-9b0a9d28-739c-11e7-86d5-e9b55d6e114c.png)

Can `.yaml` and `.yml` both be shown as `.yml` now is?

Best regards!
Sander.

**Comment by jens1o** [comment]
Err, that's not our theme, that's the default one. You may [want to activate our theme?](https://github.com/vscode-icons/vscode-icons#enable-the-extension) or file an issue at the [original repository](https://github.com/jesseweed/seti-ui/issues/new)?
