### ISSUE TITLE
Improve Babel Icon

### ISSUE THREAD

**Issue by devmattrick** [vscode-icons/vscode-icons#1106]
- [x] I'm sure this issue is not a *duplicate*?

The Babel icon is a [bit small](https://i.imgur.com/scrV2jP.png), in my opinion. Perhaps changing it to just the letter "B" would make it a bit more visible?

**Comment by jens1o** [comment]
That's true from my point of view. Thoughts? @robertohuertasm @JimiC

**Comment by JimiC** [comment]
Yes. `babel` icon need to improve but being an icon for only one specific filename, it ain't worth my time to come up with another artwork. Maybe that's a job for the `babel` team, to provide a better/alternative logo.

**Comment by hzoo** [comment]
can use the B in our favicon https://github.com/babel/babel.github.io/pull/1269 cc @sarupbanskota @existentialism (maybe should be added to https://github.com/babel/logo)

**Comment by JimiC** [comment]
@hzoo That would do, I think. Thanks for pointing is out.
