### ISSUE TITLE
[Icon Request] Support for Edge templating engine

### ISSUE THREAD

**Issue by RomainLanz** [vscode-icons/vscode-icons#1119]
Hey everyone ! 👋 

Edge is the new templating engine used by AdonisJs, could be cool to have his icon available directly from this package!

Official website: http://edge.adonisjs.com/

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - **Type**: `extension`
      - **Icon Name**: `Edge`
      - **Sample original Icon**: https://github.com/file-icons/source/blob/master/svg/Edge.svg
      - **Extension**: `.edge`

**Comment by thetutlage** [comment]
Also it's part of this repo if that helps https://github.com/file-icons/source/blob/master/svg/Edge.svg

**Comment by RomainLanz** [comment]
One more thing, the official colour of the icon should be #d8563a 👍

**Comment by jens1o** [comment]
Great, thanks for the heads up. We'll do it when we have more time. We're all busy nowadays. :/
