### ISSUE TITLE
Allow 'doc' to use the same icon as 'docs'

### ISSUE THREAD

**Issue by cjdrake** [vscode-icons/vscode-icons#1120]
- [x] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request(if not, remove these lines below):

Currently, only naming a documentation folder `docs` will give it a custom icon. Using just `doc` doesn't work.

Rather than discussing the *one, true way* of using plurals in file/directory names, I just want to point out several instances where vscode-icons already supports both the singular and plural names:
* font, fonts
* image, images
* icon, icons
* include, includes
* locale, locales
* log, logs
* package, packages
* plugin, plugins
* script, scripts
* source, sources
* style, styles
* test, tests
* tool, tools

Hopefully this is a simple request. Can we add 'doc' to the list of names that uses the custom documentation folder icon?

**Comment by jens1o** [comment]
This should be an quite easy task, as long as there is no other meaning for doc. If you like to, you can also file that pr. :)

**Comment by robertohuertasm** [comment]
Sorry @jens1o, I didn't see that you were assigned! 😱
