### ISSUE TITLE
Annoying 'info' popup appears on every launch of vscode

### ISSUE THREAD

**Issue by joealden** [vscode-icons/vscode-icons#1123]
- [x] I'm sure this issue is not a *duplicate*?
- [ ] I want to create an icon request

When launching vscode, a very annoying 'info' banner appears saying 'vscode-icons now ships with official API support.'

![image](https://user-images.githubusercontent.com/10297243/29051404-5723d0c0-7bda-11e7-9f31-0f668995eaae.png)

Also, when 'Learn more about File & Folder icons' or 'Learn about this extension', nothing happens and the info banner remains there.

I am running on Linux if that is any help.

**Comment by robertohuertasm** [comment]
Which vscode version are you using? Extension version?

**Comment by joealden** [comment]
Vscode version 1.14.2
Vscode-icons version 7.12.0

**Comment by jens1o** [comment]
@joealden Are there any errors when you toggle the developers tool?
`Help > Toggle Developers Tool`. Something like settings.json not found?

**Comment by joealden** [comment]
![image](https://user-images.githubusercontent.com/10297243/29070288-9d8bd9f2-7c36-11e7-9d89-c0521a5e5407.png)

It looks like you are correct, looking at the top two errors in the console.

**Comment by jens1o** [comment]
Can you verify the folder `/home/jalden/.config/Code/User` has read, write and execute permissions?

**Comment by joealden** [comment]
It appears that my vscode config directory is called 'Code - OSS' instead of 'Code' which sounds like an issue. I have created a copy of the contents inside my 'Code - OSS' dir to a 'Code' dir and it has solved the issue.

I am guessing that this is an issue with my distributions naming of folders / config of vscode itself.

**Comment by joealden** [comment]
Finished build of what? The extension? And where would I find this file?

**Comment by robertohuertasm** [comment]
It seems that you're using a special build of VSCode. The original issue: #1101.

**Comment by joealden** [comment]
Yes it looks that way, most packages in my distros repo are built from source, so it would explain it. However, from that linked issue, it sounds as though it was fixed?

**Comment by jens1o** [comment]
Originally, yes, it was.

I mean the `package.json` of your build of `vscode`. There should be a name that differs from what we've had implemented.

**Comment by joealden** [comment]
Is this the file you are looking for? https://dev.solus-project.com/source/vscode/browse/master/files/product.json

**Comment by jens1o** [comment]
That's strange, from my eyes, that should be fine.

@JimiC Maybe you can help here?

**Comment by joealden** [comment]
I thought so too, do you think that it would be worth contacting the vscode maintainer of my distro?

**Comment by jens1o** [comment]
Personally I would do it, yes.

**Comment by robertohuertasm** [comment]
For what I see, your vscode distro it's using the official name. That's why we detect it as `Code` and not `Code - OSS`.

[Here ](https://dev.solus-project.com/source/vscode/browse/master/files/vscode-oss.desktop) you have a file that seems to be expecting another installation path.

Contact your vscode distro mantainer and ask him about this incongruence.

**Comment by joealden** [comment]
Thank you for the info, will do.

**Comment by thewinger** [comment]
I'm also having this issue. 
Every time I open VSCode the popup shows. I clic Activate but next time it shows again.

<img width="1680" alt="screen shot 2017-09-19 at 08 58 02" src="https://user-images.githubusercontent.com/121455/30579374-b68c3c32-9d18-11e7-8f0b-72a62d485829.png">

**Comment by JimiC** [comment]
@thewinger Take another screeny of the `Console` after you click on `Activate`, and be so kind to tell us what version of the extension you have installed.

**Comment by thewinger** [comment]
After clicking `Activate` nothing happens in the `Console`.
vscode-icons version: 7.13.0

**Comment by JimiC** [comment]
Do the following:
1. Close `vscode`.
2. Locate `/Users/<your_user>/Library/Application Support/<Code Folder>/User/vsicons.settings.json` file.
3. Delete `vsicons.settings.json` file.
4. Restart `vscode`.

If `vscode-icons` is already present in your `workspace` settings the info message should not appear.
In case it appears, click on `Activate` and repeat step 4.
After that the info message should not appear again.

**Comment by thewinger** [comment]
It doesn't appear anymore.

Thank you very much

**Comment by avih** [comment]
I'm on Windows 8.1, vscode 1.16.1, vscode-icons 7.13.0 .

I've had vscode-icons installed for several vscode versions now, but It's not my default icons theme (occasionally I check it out after an update though). I don't recall such infobar issues in the past.

After the last vscode-icons update, the infobar showed (eventhough it wasn't set as my default icons theme - I think it shouldn't pop on such case). I dismissed it and it showed again on next startup. I chose "Activate", closed vscode, started it again (no infobar now), reverted to my other preferred icons theme, started vscode, and the infobar popped again.

> Do the following:
> 
>     Close vscode.
>     Locate /Users/<your_user>/Library/Application Support/Code/User/vsicons.settings.json file.
>     Delete vsicons.settings.json file.
>     Restart vscode.

Deleting the file (at `.../AppData/Roaming/Code/User/vsicons.settings.json` ) does not help. It's recreated on startup and has this content:
```json
{"version":"7.13.0","status":2,"welcomeShown":true}
```

Despite `welcomeShown` being true, the infobar still pops on startup after I change to another icon theme.

> In case it appears, click on Activate and repeat step 4.
> After that, the info message should not appear again.

I have, it didn't help.

Any chance you could fix it in an update without needing to manually touch config files?

**Comment by linonetwo** [comment]
This is so annoying!!!

If I click the 'activated', then icon gets ugly.

<img width="948" alt="wx20170920-130350 2x" src="https://user-images.githubusercontent.com/3746270/30627729-ac95b914-9e04-11e7-89ee-8fff4628edd9.png">

**Comment by JimiC** [comment]
@avih In your case, the extension is working as intended. If you don't want the info message to show when you use another file icon theme, then disable the extension from the `Extensions` section (use either `Disable (Workspace)` or `Disable (Always)`). When you want to use our extension again just re-enable it.

There is nothing to fix here.

P.S. The extension settings file will also be written to disk as long as the extension is enabled.

**Comment by robertohuertasm** [comment]
@JimiC, I was also confronted with this behavior yesterday while using the Insiders version. I think we should provide a way to disable this warning. Something like a button `Never warn me about this again` or something similar. I like to change my icon theme just to see how other packages are doing and , IMHO, it seems like a little bit excessive to have to disable the extension in order to avoid this message.

I think it has a minor impact in our development effort and a major impact in terms of user experience.

**Comment by JimiC** [comment]
@robertohuertasm Then change the condition in https://github.com/vscode-icons/vscode-icons/blob/master/src/init/welcome.ts#L13 from `OR` to `AND`.

**Comment by avih** [comment]
> @avih In your case, the extension is working as intended.

OK, this is surprising.

> If you don't want the info message to show when you use another file icon theme

Wait, you mean there's at least one person who actually wants to see that info bar on each startup when vscode-icons is not the active theme? is "vscode-icons now ships with official API support." such an important message for end users? It doesn't strike me as such, personally.

Additionally, it behaves unlike all other (icon)themes. With all other colors/icons themes, you can have several installed and not disabled, but just one active. There's even a dedicated menu item to choose the active one among the installed ones. The non active ones shouldn't bug me, and certainly not more than once.

> then disable the extension from the Extensions

I did already earlier. It's too annoying otherwise.

> There is nothing to fix here.

There is. The design.

**Comment by robertohuertasm** [comment]
@avih, I understand your concern, but please let's  be more peaceful in our comments and try to not get out of normal tone (English is not my mother tongue so I don't know if I expressed this with the right amount of finesse, no intention to offend anyone here).

We really appreciate your insights and will certainly take a look at this issue and try to improve its user experience. I encourage you to share your opinions about the extension and give us more points of improvement so we can discuss it.

**Comment by avih** [comment]
It was a minor sarcasm, come on ;) and not even in vain. Otherwise, I don't have anything further to add to my previous post.

**Comment by linonetwo** [comment]
Seems it pop up when another icon theme is on, this will ask to be activated.

**Comment by isti37** [comment]
It pops up with VSCode Great Icons theme. I really don't like the default vscode-icons theme.

**Comment by jens1o** [comment]
@isti37 You're free to look into this issue, we plan to get rid of that excessive messaging: #1176
