### ISSUE TITLE
Unclear configurations settings.

### ISSUE THREAD

**Issue by MonsieurMan** [vscode-icons/vscode-icons#1130]
### This issue references #1129 PR.
While translating the configurations I was not really sure about what those settings do and how :   

- _configuration.associations.fileDefault.file.description_  
- _configuration.associations.fileDefault.file_light.description_  
- _configuration.associations.fileDefault.folder.description_  
- _configuration.associations.fileDefault.folder_light.description_

The description being: _"This setting will let you change default dark file icon."_  

What I understand from it is that by giving a path you can define custom icon for the dark file icon.  
 
I think the description should be changed independently of this being wrong or not as I was unable to figure out what the setting was even by reading it.

**Comment by jens1o** [comment]
Yes, you're right. Basically, it means: `Give me an icon name and an extension, and we set it as the icon, when nothing else matches,`

It's here, when you scroll a little, but yes, that could be improved.

**Comment by MonsieurMan** [comment]
Ok I see, thank you.
I suggest adding an example to the description then : 
`This setting will let you change default dark file icon: { "icon": "myFilePath", "format": "svg | png" }`
It makes it clear and doesn't add that much length.

**Comment by jens1o** [comment]
Well, I think @robertohuertasm and @JimiC should say their opinions on this first, otherwise you may do work we'd like to solve differently. :)

**Comment by JimiC** [comment]
I think @MonsieurMan has a point. The current wording isn't providing a clear meaning. `dark` and `light` refers to the theme the setting controls.

I think the sentence `This setting will let you change the default file icon for dark themes.` is more appropriate.

**Comment by robertohuertasm** [comment]
I'm not sure if @MonsieurMan will be happy with @JimiC's proposal but it seems ok to me.

**Comment by JimiC** [comment]
@MonsieurMan Any feedback on this?

**Comment by MonsieurMan** [comment]
@JimiC Clean and simple ! I like it. I'm updating my pull request according to it.
I was just thinking about something, do you have something to keep track of translation validity?

**Comment by JimiC** [comment]
@MonsieurMan Unfortunately, no. Do you have a suggestion?

**Comment by MonsieurMan** [comment]
I was thinking of calculating a hash from the langEn const then adding it as another const alongside.
We can then define a not up to date translation as a translation file that has a versionHash not corresponding to the master one. 
Then we just have to warn the user if the translation is not up to date, we could even ask them if they're willing to help updating/checking the translation.
To update a translation simply check the translation, eventually make changes, then change the versionHash accordingly.
@JimiC What do you think of it?

**Comment by robertohuertasm** [comment]
In my opinion, this seems a little bit too much work for the benefit it provides. I'm thinking that we would have to maintain the hashes just to keep track of the files with pending translations, an even this way we wouldn't exactly  know what translation field/s are missing. I think is simpler to keep an issue open with the missing translations whenever this happens. Otherwise, we have to implement all these validation tools just for the sake of knowing which files are out of date when a simple issue is far to more explicit about the fields missing.

**Comment by JimiC** [comment]
I'm with @robertohuertasm.

**Comment by MonsieurMan** [comment]
You're right. It bugs me though. I'll keep the problem somewhere in my head and see if I can come up with a package for vs-code extensions in general. It could be useful for a lot of people.

**Comment by robertohuertasm** [comment]
@MonsieurMan I'll be more than glad to see your new extension working! Thanks for the PR and for the suggestions!
