### ISSUE TITLE
[Icon Request] CircleCI folder

### ISSUE THREAD

**Issue by eddiemoore** [vscode-icons/vscode-icons#1133]
CircleCI released v2 of their CI. With that the config now moves into a folder called `.circleci` instead of the old `circle.yml`

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: folder
      - Icon Name: circleci
      - Sample original Icon (32x32/svg/transparent whenever possible): https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_circleci.svg
      - Extensions: .circleci

**Comment by JimiC** [comment]
Moved to #650.
