### ISSUE TITLE
[Icon Request] Support for .http files

### ISSUE THREAD

**Issue by RobPethick** [vscode-icons/vscode-icons#1137]
This would be to support HTTP request files, for use with the extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client 

Maybe take the extensions icon as inspiration (though that kinda implies JSON which is no limitation of the extension or filetype in general) or an up-down arrow pair to symbolise request response?

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [extension]
      - Icon Name: [http]
      - Extensions: .http, .rest

Originally raised here: #748 but as requested I created a new request.

**Comment by JimiC** [comment]
@RobPethick Thanks for the clarification. I wonder why @Huachao didn't provide it when requested.

**Comment by Huachao** [comment]
@JimiC I forgot to mention this :stuck_out_tongue_winking_eye:

**Comment by JimiC** [comment]
@Huachao You see, now I have a good idea for an icon.
