### ISSUE TITLE
[Task] Update to new vscode logo

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1146]
- [x] I'm sure this issue is not a *duplicate*?

`vscode` is getting a new logo, noticeable in the latest insiders version ([press release](https://mspoweruser.com/visual-studio-code-getting-new-logo/)). 

Main logo
----
![logo](http://svgshare.com/i/2iV.svg)

Context menu logo
----
![logo](http://svgshare.com/i/2jX.svg)

For better visibility and clarity I suggest we use the "Context menu logo" for `vscode` related files.

@robertohuertasm @jens1o Thoughts?

**Comment by jens1o** [comment]
Hmm... Personally, I hate the new icon.... But I agree with you because of the consistency... 😢

**Comment by robertohuertasm** [comment]
It seems that this will be released to the stable version in September so I'm in for the change!

**Comment by robertohuertasm** [comment]
Agree on using the `context icon` 👍

**Comment by JimiC** [comment]
Just an update. Insiders icon was switched to green color instead of orange, probably to keep color consistency with previous separate `vscode` distros. Don't know if `vscode` team will switch to blue for the stable distro or keep the orange one.

**Comment by PKief** [comment]
It's hopefully not a joke, but they plan to return to blue colors. 😆 

![image](https://user-images.githubusercontent.com/12248527/31983687-92c01ad2-b95e-11e7-99d4-7464e0cfb81f.png)

https://code.visualstudio.com/blogs/2017/10/24/theicon
https://twitter.com/code/status/922903776465362944

**Comment by JimiC** [comment]
We know. It's not a joke.
