### ISSUE TITLE
[Icon Request] Java Server Pages

### ISSUE THREAD

**Issue by WeslleyNasRocha** [vscode-icons/vscode-icons#1152]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: jsp
      - Sample original Icon : [Java Server Pages](https://image.flaticon.com/icons/png/512/28/28968.png)
      - Extensions: .jsp

**Comment by robertohuertasm** [comment]
We are already supporting the `jsp` extension. I guess you're requesting a logo change, aren't you? Do you happen to have your suggested icon in `svg`?

**Comment by JimiC** [comment]
To be honest the icon needs a revamp.

**Comment by WeslleyNasRocha** [comment]
Yes, it really needs a revamp. In fact, that one its an png, i will look for an svg sample.

**Comment by JimiC** [comment]
I think this one is better (https://www.brandsoftheworld.com/logo/jsp)

**Comment by WeslleyNasRocha** [comment]
I found the link to the flaticons.com, but the free download said you must credit the author, so i dont how to do that

[Here`s it](https://www.flaticon.com/free-icon/jsp-open-file-format-with-java-logo_28968)

**Comment by WeslleyNasRocha** [comment]
I really liked that black one, but now i`m thinking it may not show properly with dark themes of vscode

**Comment by JimiC** [comment]
Or even the letter from this one. ![logo](http://fedil.ukneeq.com/wp-content/uploads/2014/01/jsp-icon-163x300.png).

**Comment by WeslleyNasRocha** [comment]
Huuum, yes, i guess only the letter will do it

**Comment by JimiC** [comment]
> I really liked that black one, but now i`m thinking it may not show properly with dark themes of vscode

Bingo.

**Comment by WeslleyNasRocha** [comment]
So, pick one of those, its gonna be awesome.

**Comment by robertohuertasm** [comment]
About the color, it can be easily changed depending on the theme so... I guess the problem is more about the icon license. I also like the `black one` but I think that using the `JSP` letters with that font will be recognizable enough, too, so 👍
