### ISSUE TITLE
[Task] Support root folder icons

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1168]
With the introduction of multi-workspace `root-folder` in `vscode`, we should support specifying an icon for that.

**Comment by JimiC** [comment]
Concept Art Proposal
---
**1. Using web root symbol**
![root1](https://user-images.githubusercontent.com/1716442/30317576-2014ff2e-97b3-11e7-9f16-c97fa075d674.png)![root1_opened](https://user-images.githubusercontent.com/1716442/30317580-23c54354-97b3-11e7-96ac-eb3c990df10b.png)

**2. Using math root symbol**
![root2](https://user-images.githubusercontent.com/1716442/30317620-4b2d97fc-97b3-11e7-937d-f19681699db7.png)![root2_opened](https://user-images.githubusercontent.com/1716442/30317650-60d1afc6-97b3-11e7-8bc6-24ecfa7a4da7.png)

Note: The symbols used are a play on the word `root`. I'm open to other symbol and color matching suggestions.

**Comment by robertohuertasm** [comment]
I certainly prefer number 1. Number too is too much geeky for my taste 😁. Although I like it I would suggest to use the same kind of icon that Visual Studio Code chose: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_15.md#icon-for-root-folders (this kind of concentric circles)

**Comment by JimiC** [comment]
@robertohuertasm The `minimal` icons are available [here](https://github.com/Microsoft/vscode/tree/master/extensions/theme-defaults/fileicons/images). Although I thought about it, I believe our art concept is to differentiate from other icon themes.

**Comment by robertohuertasm** [comment]
I also have thought about it and I agree with you in the differentiation point. Indeed, I'm not strongly suggesting to use the `default one`. I didn't correctly express myself: I was doubting about it. Basically, my point is that using the same icon will make it easier for people to understand the concept as they would be familiar with the standard icon that the IDE has chosen. On the other hand, I also think that we'll be losing our specific touch of originality.

To be honest, after thinking of this for a while, I think your idea in number 1 is far more appealing to me than the concentric circles as it recalls the root in a path, something every developer should be familiar with. Let's try this. We could even propose the circles as a `2 disabled' option as we do for many other icons.
