### ISSUE TITLE
[Icon Request] Support for mathematica and wolfram language

### ISSUE THREAD

**Issue by Stone-Zeng** [vscode-icons/vscode-icons#1174]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: [extension]
      - Icon Name: [mathematica]
      - Extensions: .nb, .m, .cdf
      - Sample original Icon:
      ![mathematica](http://www.wolfram.com/common/images/gl-logo-spikey.zh.png)
- [x] I want to create an icon request:
      - Type: [extension]
      - Icon Name: [wolfram language]
      - Extensions: .wl, .wls
      - Sample original Icon:
      ![wolfram-language](http://www.wolfram.com/language/img/wolfram-language-logo-home.png)

Note: Both can be supported via language id `wolfram`.
https://marketplace.visualstudio.com/items?itemName=flipphillips.wolfram-language

**Comment by Stone-Zeng** [comment]
`.m` extension maybe conflict with MATLAB and Objective-C. (Why people *all* use this?)

**Comment by JimiC** [comment]
@Stone-Zeng Because, people, in general, are stupid (me included). 👅

**Comment by JimiC** [comment]
After consulting `Wikipedia` about `Wolfram Language`:
>The language was officially named in June 2013 although, as the programming language of Mathematica, it has been in use in various forms for over 30 years since Mathematica's initial release. Before 2013, it was internally referred to by several names, such as "M" and "Wolfram Language." Other possible names Wolfram Research considered include "Lingua" and "Express."

Therefore, we are going to use the `Mathematica` icon.

**Comment by robertohuertasm** [comment]
I think there would be no conflict if these icons are going to be supported via language id.

**Comment by JimiC** [comment]
@robertohuertasm The extension that supports the language highlighting supports the combination of both requested file extensions. Therefore both will be supported via one language id and I tend to use the `Mathematica` icon.

**Comment by 2-5** [comment]
The fix only added support for the .wl extension

Please also add support for the .nb extension, it doesn't conflict any other one.
