### ISSUE TITLE
JS Icon is the React Icon?

### ISSUE THREAD

**Issue by abinavseelan** [vscode-icons/vscode-icons#1175]
- [x] I'm sure this issue is not a *duplicate*

# JS Icon is the React Icon?

Firstly, :heart: the extension! Really like your work! :smile:

## Context

I got a prompt today that VSCode icons had updated, so I reloaded VSCode. However, it looks like the icon for `.js` files is now the React icon by default? (See screenshot below)

![image](https://user-images.githubusercontent.com/6417910/30628674-51a1b620-9df5-11e7-8f1d-2ede1ed49ed1.png)

These files are pure JS files.

Wondering if this is expected behaviour or if the icons are wonky for `.js` files? 🤔 

FYI - I've also tried the `Toggle official JS Preset` command. 

🙂

**Comment by JimiC** [comment]
@abinavseelan Check your settings (Workspace) there should be an entry there that associates the `js` extension to `reactjs`. Probably, this is done by another extension you have installed.

**Comment by abinavseelan** [comment]
Ah ha! That was it! 🎉 😄 

Thank you! Closing the issue. 🙇

**Comment by robertohuertasm** [comment]
@abinavseelan, just out of curiosity. Which black theme are you using?

**Comment by abinavseelan** [comment]
@robertohuertasm 

[Ayu Dark](https://github.com/viatsko/awesome-vscode#ayu) 😄

**Comment by LautaroRk** [comment]
@abinavseelan where was that entry? I cant find it on my VSCode settings. Had the same issue after i used create-react-app for the first time

**Comment by elefantelimpio** [comment]
@abinavseelan could you please tell me how did you solve it? I've just opened VS Code and every .js file is associated to react 😄 
![image](https://user-images.githubusercontent.com/11888892/64970667-9061a580-d8a6-11e9-807e-af9736ed7dfd.png)

**Comment by PaulPCIO** [comment]
Maybe you have changed this in your default settings? 

it should read
```
settings.json
{
  "files.associations": {
    "*.js": "javascript",
    "*.jsx": "javascriptreact",
    "*.ts": "typescript",
    "*.tsx": "typescriptreact"
  }
}
```
