### ISSUE TITLE
Improve welcome and activation message experience

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#1176]
Related to #1123, specifically [here](https://github.com/vscode-icons/vscode-icons/issues/1123#issuecomment-330693647).

It seems that we have to find a way to be less invasive with this message so it would be nice to provide a way to disable it if the user feels like it. Let's discuss also the content of the welcome message which is also obsolete by now.

**Comment by JimiC** [comment]
@robertohuertasm I'm fine with any changes you guys decide. I believe that my [suggested change](https://github.com/vscode-icons/vscode-icons/issues/1123#issuecomment-330791877) solved the issue.
