### ISSUE TITLE
[Icon Request] Support for tag (riotjs)

### ISSUE THREAD

**Issue by MattiaCostamagna** [vscode-icons/vscode-icons#1180]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension\filename`
      - Icon Name: `tag`
      - Sample original Icon: ![alt text](http://riotjs.com/img/logo/riot60x.png "http://riotjs.com") \(sorry, I could not find a 32x32 svg image, but here is the official logo\)
      - Extensions: `.tag` 
      - JS framework website: http://riotjs.com

**Comment by JimiC** [comment]
Already supported (https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L343).
You need to use a language highlighting extension for the icon to light up.
