### ISSUE TITLE
question: what did you use to create the animated gif?

### ISSUE THREAD

**Issue by gregorleban** [vscode-icons/vscode-icons#1186]
This is not an issue - just a question. 

Could you please let me know what tool and procedure did you use to create the animated gif? I'm also creating an extension but my gifs look of lower quality so I would appreciate the info.

Best,
Gregor

**Comment by robertohuertasm** [comment]
@gregorleban unfortunately I uninstalled the tool and can't remember the name 😞 I'll come back to you if I remember it, sorry!

**Comment by JimiC** [comment]
Could it have been [ScreenToGif](http://www.screentogif.com/)?

**Comment by robertohuertasm** [comment]
I was doubting about it but I'm not really sure...

**Comment by robertohuertasm** [comment]
I can tell you it wasn't ScreenToGif. I think I recorded a video using [OBS Studio](https://obsproject.com/download) and then used some other software to get the animated gif from the video.

**Comment by jens1o** [comment]
(FFMpeg can create a GIF out of a mp4 for example)

**Comment by gregorleban** [comment]
great, thank you all for the info!

**Comment by nocke** [comment]
@gregorleban 
![answer](https://user-images.githubusercontent.com/21154106/32003955-f3cd20f8-b9a0-11e7-9cac-cc0a11d505f1.gif)
→ also see on Stackexchange: https://askubuntu.com/a/833995/479118
