### ISSUE TITLE
Coffeescript icon is too dark to see in any dark themes

### ISSUE THREAD

**Issue by yydmay** [vscode-icons/vscode-icons#1206]
Hi there,

I use vscode-icons with One Dark Pro theme. Coffeescript icon is too dark to see in pretty much any dark themes, is it possible to make it brighter?

Thanks

![image](https://user-images.githubusercontent.com/7885095/31193601-986b1e8e-a912-11e7-8fbe-1d2e04622dce.png)

**Comment by jens1o** [comment]
@JimiC This is not an icon request, but instead a bug request. I think we should consider this as soon as possible. :)

**Comment by JimiC** [comment]
@jens1o It's not a bug request. It relates to a file icon and is just a request to improve the coloring.
