### ISSUE TITLE
Jest icon not showing for jest.config.json

### ISSUE THREAD

**Issue by aymericbouzy** [vscode-icons/vscode-icons#1208]
- [x] I'm sure this issue is not a _duplicate_.

According to https://github.com/vscode-icons/vscode-icons/blob/a9eb06966d82f06444733a8fe759c40062f80c43/src/icon-manifest/supportedExtensions.ts#L233, jest icons are supported

but I'm seeing this : 

<img width="185" alt="screen shot 2017-10-05 at 16 52 48" src="https://user-images.githubusercontent.com/8168981/31233999-11bca2ea-a9ee-11e7-939f-51c65f7530aa.png">

VSCode version 1.16.1

**Comment by jens1o** [comment]
I cannot reproduce on Insiders: 
![image](https://user-images.githubusercontent.com/11234139/31235135-f2a3c8ae-a9f0-11e7-9ad5-d5af96bdd467.png)

**Comment by aymericbouzy** [comment]
I'm new to VSCode, please give me steps, I confirm I'm seeing it happen right now.

**Comment by jens1o** [comment]
Did you activated the Icon Theme like shown in the gif in the README file?

**Comment by aymericbouzy** [comment]
Sorry I didn't realise it was an extension 😅 so sorry, I installed and everything is working fine. What confused me was that a lot of icons (babel, ESlint, Yarn ...) were already showing by default ... What you do is awesome 👍

**Comment by jens1o** [comment]
Alright, thanks. Welcome to our community. :)
