### ISSUE TITLE
Add typescript extension (.ts) to karma and protractor icon

### ISSUE THREAD

**Issue by rfrancisco** [vscode-icons/vscode-icons#1218]
Please add typescript (.ts) extension to the karma and protractor icons. Typescript is a very common way to write this configuration files in.

From:
{ icon: 'karma', extensions: ['karma.conf.js', 'karma.conf.coffee'], filename: true, format: FileFormat.svg },
{ icon: 'protractor', extensions: ['protractor.conf.js'], filename: true, format: FileFormat.svg }

To:
{ icon: 'karma', extensions: ['karma.conf.js', 'karma.conf.ts', 'karma.conf.coffee'], filename: true, format: FileFormat.svg },
{ icon: 'protractor', extensions: ['protractor.conf.js', 'protractor.conf.ts'], filename: true, format: FileFormat.svg }

Thanks

**Comment by jens1o** [comment]
That sounds valid. Do you want to do that? That's a quite good first Pull Request. :)

**Comment by rfrancisco** [comment]
Sure
