### ISSUE TITLE
[Proposal] Expand supportExtensions API

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1230]
- [x] I'm sure this issue is not a _duplicate_.

While looking at `supportExtensions` file, I can't help it being annoyed by the lengthy entries for some extensions, especially `webpack`.

So I'm thinking of introducing a set of additional API attributes like `filenamesGlob` and `extensionsGlob` and assign those and we programmatically produce the combination of those. The benefit is that we'll have a reduced declaration entry.

i.e.
```js
{
      icon: 'webpack',
      extensions: [],
      filenamesGlob: [
        'webpack.base.conf',
        'webpack.common',
        'webpack.config',
        'webpack.config.base',
        'webpack.config.common',
        'webpack.config.dev',
        'webpack.config.development',
        'webpack.config.staging',
        'webpack.config.test',
        'webpack.config.prod',
        'webpack.config.production',
        'webpack.config.babel',
        'webpack.config.base.babel',
        'webpack.config.common.babel',
        'webpack.config.dev.babel',
        'webpack.config.development.babel',
        'webpack.config.staging.babel',
        'webpack.config.test.babel',
        'webpack.config.prod.babel',
        'webpack.config.production.babel',
        'webpack.dev',
        'webpack.dev.conf',
        'webpack.prod',
        'webpack.mix',
        'webpack.test.conf',
      ],
      extensionsGlob: ['js', 'coffee', 'ts'],
      filename: true,
      format: FileFormat.svg,
}
```
Note that the above is the entire declaration of `webpack` and instead of 67 lines we only have 34.
This also keeps backward compatibility.

Thoughts? Suggestions?

**Comment by jens1o** [comment]
I think this is a great idea, I actually thought of this, but I thought that I would need to implement that :/

**Comment by JimiC** [comment]
@robertohuertasm your thoughts about this or do you need some time to think about it?

**Comment by robertohuertasm** [comment]
@JimiC I'm in!
