### ISSUE TITLE
[Proposal] Rename displayed name from 'vscode-icons' to 'VSCode Icons' 

### ISSUE THREAD

**Issue by torn4dom4n** [vscode-icons/vscode-icons#1232]
`displayName` is the display name for the extension used in the Marketplace, see https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_fields and https://code.visualstudio.com/docs/extensionAPI/extension-manifest#_example. So I think to use **VSCode icons** should be used to instead of **vscode-icons** in `displayName`. For me, **vscode-icons** is only an extensions name.  I can see you use **VSCode Icons** to `Preferences: File Icon Theme`:

![image](https://user-images.githubusercontent.com/27698189/31370196-d8cd1acc-adb3-11e7-9611-cb92a1336d34.png)

BTW, other File Icon Themes often don't use `name`  for `displayName`.

![image](https://user-images.githubusercontent.com/27698189/31370449-60277ac0-adb5-11e7-8205-d789fdac3ea3.png)

In addition, I favor removing `preview` tag,  **VSCode Icons** is good enough to use.
Move over from: https://github.com/vscode-icons/vscode-icons/pull/1231#discussion_r143550280
cc @robertohuertasm @JimiC @jens1o

**Comment by jens1o** [comment]
Personally, I disagree with it. Tradition and wonderful feelings connected with this name 😍

**Comment by torn4dom4n** [comment]
So why doesn't **vscode-icons** use to `Preferences: File Icon Theme`?

**Comment by JimiC** [comment]
Because @robertohuertasm was the first to add file/folder icons in `vscode` before this even was a thing. And this is how he wanted to name it.
If you sit down and really think of it, it's really a trivial thing. And I do understand you. O.C.D. is a bitch. I fight with it too.

**Comment by JimiC** [comment]
Closing as stale. If you believe that it should not be close then please re-open the issue.

**Comment by sinamobashery** [comment]
> And I do understand you. O.C.D. is a bitch. I fight with it too.

I kinda have O.C.D. too but sometimes it's a valid thing :) take look at this:

![Screenshot from 2022-12-05 23-14-10](https://user-images.githubusercontent.com/60809106/205730693-a2a6dc21-c8fd-4f26-b757-b2e27f9bf3a5.png)

all of them follow a naming convention and it's good to keep things clean, and definitely, it feels clean and in sync with others, maybe people are aware of it unconsciously too.
