### ISSUE TITLE
Standard folder icons not displayed 

### ISSUE THREAD

**Issue by vgammieri** [vscode-icons/vscode-icons#1234]
With latest version of VS Code (1.17.1) the extension doesn't show the icon for standard folder.

![screen shot 2017-10-12 at 12 43 19 pm](https://user-images.githubusercontent.com/363278/31492412-20b017de-af4b-11e7-8473-7b5cd5c730f9.png)

**Comment by JimiC** [comment]
1. Press `F1`
2. Type `Icons`
3. Select `Toggle Folder Icons Visibility (User Level)`
4. Press `Restart`.

**Comment by vgammieri** [comment]
Reinstallation solved the problem. Thanks
