### ISSUE TITLE
Check out how new multi-root feature will affect our use of the settings API

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#1236]
Hey @team we've been contacted by @seanmcbreen from the `VS Code` team regarding the new `multi-root` feature that they're going to be release in the next iteration.

The thing is that although we're supporting icons for root folders we didn't check out how the new settings API is going to affect us. I guess it will affect mostly to PAD but I've not looked into it.

Anyway, I've posted here the email so we all can have it and take a look if we need it.

> As I’m sure you know we are very close to releasing a significant new feature for VS Code - Multi-root Workspaces - which is the most requested missing feature. If you have not heard of multi-root workspaces we have described this in several of our recent updates.  Today it's only enabled in our insiders release but our intent is to enable it for all users in our next update, targeted for release in the first week of November.
 

> This is a pretty significant change and over the last four months we have updated pretty much all of VS Code to be Multi-root aware as well as updated all of our own extensions.  In the process of doing this we have created a set of guidelines for Extension Authors to follow to ensure their extension can fully leverage the awesomeness that is Multi-root workspaces.

> Given the broad usage of VS Code Icons it would be great to ensure we have fully tested (and made any required changes for) Multi-root Workspace support.  We have partnered on changes before and we would love to do so again.
 
 

> Our Request:
> Having looked at your extension we think changes are required to how you manage/change settings.  Specifically, you need to review whether some of the settings can be applied on a resource (= file location) level instead of being global (= workspace level).
 
 
> How Can We Help/Resources:
> We realize we are asking for your help here - our goal is to make sure that your extensions works well with multi-root and continues to be loved by the community.  The guide above outlines the changes that are required and we have a samples as well.
 
> But we are sure you will have questions and we thought one way we could look to help is by getting a number of the team members (myself included) to be ready to respond to questions on a Slack Channel that we will dedicate to this issue.  To join that Slack group, simply follow this link and look for the #vscode-multi-root channel.
 
 
> Again thank you for being part of the VS Code community - we appreciate everything you have done.  With the release of Multi-root Workspaces we will be shipping our most requested feature, together we can really help this feature light up for users.
 
> Happy Coding!
> Sean McBreen

//cc @JimiC @jens1o

**Comment by JimiC** [comment]
I'm confident that we are ready. PAD already looks in all folders to spot a project that needs special icons and I have already tested that user customization is working with root folder icon. Additional testing  though would not hurt.

**Comment by JimiC** [comment]
OK. One issue I found is that now that `multiroot` doesn't require a reload in order to be created, PAD doesn't catch that. So we'll have to look into that.

**Comment by JimiC** [comment]
I found two additional issues.
1. There is a logic bug in the `results` iteration to determine the project info.
2. Although we should only do detection on `NodeJS` projects, the current code on works correctly on `Unix` like OS.
For both issues, it's me to blame.
I have already fixed issue `1.
Regarding issue `2`, if fixed, (and by fixed I mean restrict detection to `NodeJS`projects only) it will be a problem as it will not be able to support `multi-root` workspaces. On the other hand, I'm thinking that we should remove that restriction and allow detection also for projects that are not solely `NodeJS`. One example can be web apps that have `Angular` as front-end and another language as back-end. Thoughts?

**Comment by jens1o** [comment]
I will test the changes if you'd like to.

**Comment by JimiC** [comment]
My only concern is whether to remove the restriction or not. I can't fully remember why I added it. I slightly remember that @robertohuertasm had some issues with PAD on some none `NodeJS` projects.

**Comment by JimiC** [comment]
OK. I looked into the repo history and remembered why I added the restriction. It had to do with the case when the user opened a folder where a `package.json` was not in the root folder (a non-`NodeJS` project) and a `package.json` was found in a subfolder that had `angular` icons, resulting in a `Restart`.
Now with `multi-root` support, this restriction has to go (don't ask me where, but certainly not in this repo).

**Comment by seanmcbreen** [comment]
**Request:** if you have prepared your extension for Multi-root Workspaces we would love you to add multi-root ready to your `package.json` i.e. `"keywords": ["multi-root ready"]`. If you upgrade to `VSCE 1.32.0` this can be added to any existing keywords and will not be counted against the maximum of 5 allowed keywords.

This will help us keep track of adoptions and also help users know which extensions have been fully tested.   Remember we are here to help should you need it on the Slack channel.

Happy Coding
Sean McBreen

**Comment by JimiC** [comment]
@seanmcbreen Thanks for letting us know.
