### ISSUE TITLE
[Icon Request] Support for Kivy

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1251]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request:
  - Type: `extension`
  - Icon Name: `kivy`
  - Sample original Icon: https://kivy.org/logos/kivy-logo-black-64.png
  - Language ids: `kivy`

- More info: https://kivy.org/
- Language Extensions: https://marketplace.visualstudio.com/items?itemName=BattleBas.kivy-vscode

**Comment by dessant** [comment]
Btw, the website and the logo are outdated, the current logo has a flatter design: https://github.com/kivy/kivy/blob/master/kivy/data/logo/kivy-icon-128.png. The updated version is in the discussed AI file.

**Comment by JimiC** [comment]
Thanks for the heads up. I've already grabbed the `ai` file.
