### ISSUE TITLE
[Proposal] Move info from README to wiki

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1262]
Since we are still adding new icons to the extension and adding content to the `README`, this file is getting bigger and bigger with a lot of info and users tend not to read through the entire documentation, resulting sometimes in unnecessary support. 

I'm proposing to move the majority of the content to the wiki section and keep in `README` links to the content. `GitHub` wiki provides a more categorized structure, which I believe enhances the UX.

# Pros
- Categorized content
- List of supported file icons
- List of supported folder icons
- List of file icons supported via `language ids`

**Comment by robertohuertasm** [comment]
It seems a good idea to me! 👍

**Comment by JimiC** [comment]
This will also satisfy #1095.

**Comment by JimiC** [comment]
Closing in favor of #1285.
