### ISSUE TITLE
[Icon Request] Support for BibTeX

### ISSUE THREAD

**Issue by torn4dom4n** [vscode-icons/vscode-icons#1270]
- [x] I'm sure this issue is not a duplicate.
 - [x] I want to create an icon request:
- Type: `extension`
 - Icon Name: `bibtex`
 - Sample original Icon: https://commons.wikimedia.org/wiki/File:BibTeX_logo.svg, 
 - Language ids: `bibtex`
 - More info: https://en.wikipedia.org/wiki/BibTeX

Language Extensions: https://marketplace.visualstudio.com/items?itemName=torn4dom4n.latex-support

**Comment by JimiC** [comment]
@torn4dom4n Is it OK with to associate those with the `tex` icon?

**Comment by torn4dom4n** [comment]
You associate `LaTeX` with the `tex` icon, the answer is YES for me!
