### ISSUE TITLE
[Icon Request] Support for LaTeX Beamer, LaTeX Log, LaTeX Memoir

### ISSUE THREAD

**Issue by torn4dom4n** [vscode-icons/vscode-icons#1271]
- [x] I'm sure this issue is not a duplicate.

- [x] I want to create an icon request:
 - Type: `extension`
 - Icon Name: `tex`
 - Sample Icon: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_light_tex.svg
 - Language ids: `latex beamer`, `latex log`, `latex memoir`

Language Extensions: https://marketplace.visualstudio.com/items?itemName=torn4dom4n.latex-support and https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop

**Comment by JimiC** [comment]
@torn4dom4n Is it OK with to associate those with the `tex` icon?

**Comment by JimiC** [comment]
Looking at the `package.json` of both extensions I notice that there are no extensions defined to those ids. So the issue is kinda invalid.

**Comment by torn4dom4n** [comment]
I am not sure about extensions for this. Can you enable icons without extensions defined?

**Comment by JimiC** [comment]
No. For icons to light up they need to be associated with a file, either whole filename or extension.

**Comment by torn4dom4n** [comment]
@JimiC Thank for that. I will close this issue!
