### ISSUE TITLE
Optional Angular Icons

### ISSUE THREAD

**Issue by cgatian** [vscode-icons/vscode-icons#1279]
- [x] I'm sure this issue is not a _duplicate_.

The Optional Angular icons are too close in color.  The tiny little badges for each shield are cute but are so hard to read they don't really provide assistance.

![image](https://user-images.githubusercontent.com/1752170/31816140-1cd8116c-b55d-11e7-9819-de18e8b6d1f3.png)

The two options I see are:
* Change the Angular shield to the color of the backing technology (e.g orange for HTML, pink for Scss)
* Use the HTML/Scss icons as a base and apply a tiny angular shield in the lower right. (basically invert the design) To me this actually makes a bit of sense. Its not really an Angular file, its a html file thats used by Angular.

- More info: https://github.com/vscode-icons/vscode-icons#optional-angular-icons

**Comment by JimiC** [comment]
@cgatian The thing is that `Optional Angular Icons` are optional. If you don't like them just remove the declarations from your settings and the icons shown will be the default of their file extension.

**Comment by cgatian** [comment]
No shit.

**Comment by cgatian** [comment]
The thing is. The icons are small and indistinguishable. If I don't like  them Maybe I should use a different icon pack.

**Comment by robertohuertasm** [comment]
@cgatian, just some considerations:

1. You can use the icons you like most and associate them to your preferred file extensions by using our [custom icons functionality](https://github.com/vscode-icons/vscode-icons/wiki/Custom).

1. I see that you have a point and we could certainly try your second proposal about inverting the icons. Nevertheless, I suspect we'll end up inverting the problem and some people may complain about the Angular icon being indistinguishable but, at least, if we have the 2 options people will be able to choose.

1. Finally, changing the icon set is indeed another option to consider and we encourage you to do so if you're not happy with the one you're using. I don't certainly understand why people uses this as some kind of threat in OSS projects. Plus, when they know (I see you contribute to some projects) that this is maintained by people dedicating their free time to a tool being used for free by anyone who is willing to do so.

That being said, I really think it's worth the effort to make a second optional Angular icon pack so users can have more options (this would include myself as an Angular dev :wink: ).

**Comment by robertohuertasm** [comment]
Closing this for good.
