### ISSUE TITLE
[Task] Move README content to wiki

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1285]
As we have discussed and agreed upon, the content of the `README` has to be moved to the wiki section.

**Comment by JimiC** [comment]
A first iteration can be found @ https://github.com/JimiC/vscode-icons/blob/readme2wiki/README.md

A preview of the wiki can be found @ https://github.com/JimiC/vscode-icons/wiki

**Comment by JimiC** [comment]
I have started to add more content to the wiki. Specifically, I'm building the list of the supported file and folder icons.
@robertohuertasm @jens1o Are you OK with the structure I'm using?

* https://github.com/JimiC/vscode-icons/wiki/ListOfFiles
* https://github.com/JimiC/vscode-icons/wiki/ListOfFolders

**Comment by robertohuertasm** [comment]
@JimiC, I'm ok with the new structure. I would add, though,  some information about the features of the extension (PAD, customization, presets, docker...). Just a mention linking to the proper wiki page. That would convince some of the possible users of installing it provided that we not only provide a usual icon file theme but one that can be customized and adds some cool features as PAD. With the new structure you can't see anything of this in the main README.md file and it's hidden so I vote for giving these features some visibility there.

**Comment by robertohuertasm** [comment]
Another concern I have is having to maintain those list of icons... Every time we now make a change or addition we have to go there and edit those files. I guess is the price we have to pay but it would be awesome if this work could be automated somehow (I don't know if wiki pages can be automatically generated)

**Comment by jens1o** [comment]
I like the new wiki :)

**Comment by JimiC** [comment]
@robertohuertasm The content is yet incomplete. I merely moved the content of the `README` to their own files just to make the scaffold. Indeed the `README` seems kinda naked now, but we definitely can enrich it.
Now as for auto generating the wiki pages, I'll have to investigate the possibility. If there's not tool we'll code one.

**Comment by JimiC** [comment]
I updated the `README` following these [guides](https://guides.github.com/features/wikis/). How do you like it now?

**Comment by jens1o** [comment]
I think it's great, I just lack of time to contribute to you 😭

**Comment by JimiC** [comment]
I just submitted my final proposed version for the lists. Note that files list is in small fonts in order for the entire list to fit the page. My first approach was to has `Extensions`, `Filenames` and `Language IDs` in separate columns but the width was being overflown.
I think this is the best result that can be achieved.

Thoughts?

**Comment by robertohuertasm** [comment]
Awesome job @JimiC! I really love it! ❤️

**Comment by JimiC** [comment]
OK. I'll do the move first thing in the morning. I'll submit a PR for the README file change tool.
The PR for the generator tool will come on a later date as it's not crucial for the next release.
