### ISSUE TITLE
[Icon Request] Support for LiveScript Language

### ISSUE THREAD

**Issue by HosseinAgha** [vscode-icons/vscode-icons#1286]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request:
  - Type: `extension`
  - Icon Name: `livescript`
  - Sample original Ico: https://avatars3.githubusercontent.com/u/25471216?v=4&s=200
  - Extensions: `ls`

- More info: http://livescript.net/

**Comment by JimiC** [comment]
@HosseinAgha We would have really appreciated if you had filled the provided template. We do love protocol.
