### ISSUE TITLE
[Icon Request] Update stylus icon

### ISSUE THREAD

**Issue by eddiemoore** [vscode-icons/vscode-icons#1293]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request (if not, remove these lines below):
  - Sample original Icon: [Old logo](https://github.com/vscode-icons/vscode-icons/blob/9609119cf80fc6f4eb102fb63f81a39f4bbb3889/icons/file_type_stylus.svg) [New Logo](http://stylus-lang.com/img/stylus-logo.svg)

- More info: http://stylus-lang.com/

**Comment by JimiC** [comment]
@eddiemoore I'm only keeping the request to update to the new logo.
