### ISSUE TITLE
Empty translation file makes many warnings

### ISSUE THREAD

**Issue by kimushu** [vscode-icons/vscode-icons#1301]
- [x] I'm sure this issue is not a _duplicate_.

I'm an author of VSCode extension.
VSCode in extension development host mode makes many warnings related to vscode-icons at startup.

Screenshot (language: japanese):
![vscodeicons_warnings](https://user-images.githubusercontent.com/1642194/32034210-3a71b9dc-ba4c-11e7-89de-c15020b2e62a.png)

Since 7.16.0, several translations (package.nls.xx.json) added but some translation lacks their content (ja, ko and zh-tw)
For example, `package.nls.ja.json` exists but the values of all keys are empty string.
Could you add suitable content instead of empty string or remove translation files which have no effective content?
(I'm a Japanese and I can contribute for ja translation, but cannot for other languages...)

**Comment by JimiC** [comment]
@kimushu We would really appreciate if you could contribute the `ja` translations. Head to https://crowdin.com/project/vscode-icons-i18n and add your translations. You can use your `GitHub` account to sign up with `Crowdin`.
Thanks in advance.

**Comment by JimiC** [comment]
On topic now, indeed `nls` doesn't handle correctly languages with empty strings, something that we do in our `i18n` implementation.
To resolve this we either have to remove the `nls` files that have no translations or contribute the fix to the `nls` repo.

**Comment by JimiC** [comment]
I opened an issue with `vscod-nls` https://github.com/Microsoft/vscode-nls/issues/15 for tracking.

**Comment by JimiC** [comment]
@kimushu We also need translations for the `lang.ja.json` file (https://crowdin.com/translate/vscode-icons-i18n/6/en-ja).

**Comment by JimiC** [comment]
@kimushu Any news on completing the `ja` translations?

**Comment by kimushu** [comment]
@JimiC Sorry, I'm busy on exhibition of my extension now...
I'll provide the remainder part in next week.

**Comment by kimushu** [comment]
@JimiC `ja` translation complete :-)

**Comment by JimiC** [comment]
@kimushu Great work mate. Sorry you missed the release by hours.
