### ISSUE TITLE
Project detection popup every window reload

### ISSUE THREAD

**Issue by csvn** [vscode-icons/vscode-icons#1311]
- [X] I'm sure this issue is not a _duplicate_.

Whenever I open/reload the VSCode window, I get the "vscode-icons has detected a non Angular project..." message, even though I have disabled the detection. This has been happening for a little while now, I would guess since v7.15.0.

![infinite-popup-on-reload](https://user-images.githubusercontent.com/8770194/32077463-d63ecfc4-baa3-11e7-9ac8-b5276b843bd6.gif)

If I change the `disableDetect` to `false`, I no longer get the message at all (in my Angular project). But this means I see the message for every non-angular project I open (with the reload/auto-reload buttons).
I prefer to always have the same icon sets, as most projects I currently work on is Angular related. Most other projects will not collide with the Angular naming standard, and for those that do I have the option to use `vscicons.presets.angular: false` in the workspace settings.

The `vsicons` settings I use in my user settings are the following:
```
    "vsicons.projectDetection.autoReload": false,
    "vsicons.projectDetection.disableDetect": true,
    "vsicons.presets.angular": true,
    "vsicons.presets.jsOfficial": true,
    "vsicons.presets.tsOfficial": true,
```

VSCode version: 1.17.2
vscode-icons version: 7.16.0
OS: Windows 10

Thanks for a great project!

**Comment by robertohuertasm** [comment]
Hi @csvn, thanks for the accurate report! I've identified the issue and will provide a fix soon. I hope to be able to make an early release to solve this tomorrow.

**Comment by JimiC** [comment]
@csvn :+1: for providing a meaningful bug report.

**Comment by csvn** [comment]
No problem, thanks for the quick work gentlemen! 😄
