### ISSUE TITLE
Cake Icon not showing

### ISSUE THREAD

**Issue by gep13** [vscode-icons/vscode-icons#1321]
- [x] I'm sure this issue is not a _duplicate_.

Last year, an issue was created to support Cake files with the Cake Icon: https://github.com/vscode-icons/vscode-icons/issues/16

In the latest version of VSCode (1.17.2) and vscode-icons (7.17.0), the Cake Icon is no longer showing up properly, instead, we are getting the C# icon:

![image](https://user-images.githubusercontent.com/1271146/32142542-4d794314-bc91-11e7-8293-7eea640cb3f0.png)

I suspect that this is due to a recent change in VSCode to support .cake files as C# so that we can light up intellisense support.

Is there a way to override this in vscode-icons, if an alternative is supplied?

Thanks

**Comment by robertohuertasm** [comment]
@gep13, yes, you're right. It seems that the `cake` extension  doesn't support `cake` language id anymore and `.cake` files are managed by the `c#` language id. We'll fix that in our side and will be served in the next release. In the meantime, you can add this to your user settings and, hopefully, it will make the icon appear again:
```
"vsicons.associations.files": [
  { "icon": "cake", "extensions": ["cake"], "format": "svg" }
]
```

**Comment by gep13** [comment]
@robertohuertasm thanks for getting back to me so quickly, really appreciate it!

I have just tried your workaround, but it doesn't seem to have any effect.  After adding the suggestion, and restarting VSCode, the same C# icon is still displayed.

If I change the Icon theme to Seti, I get their stylised version of the Cake Icon:

![image](https://user-images.githubusercontent.com/1271146/32159644-41119bca-bd46-11e7-9490-920d91f9782d.png)

But nothing when I switch to the C# icon.

I am happy to wait until the next release of vscode-icon, I just wanted to make you aware of this in case it had a bearing on your fix.

**Comment by JimiC** [comment]
@gep13 I just tested it and it works. When I added @robertohuertasm snippet I was presented with a message to restart `vscode` in order for the icon manifest to be regenerated. Upon restarting the `cake` icon was shown. Probably you have the message disabled so you need to `Apply` the change manually by doing `F1 > Icons > Apply Icons Customization`.

**Comment by JimiC** [comment]
Tracing the history of this change I wonder why @DustinCampbell added the `cake` extension in `vscode` `csharp` extension (https://github.com/Microsoft/vscode/commit/4c3ddf7e4c30542dbcc2447738612e094e1ac2de) since `cake` had its own extension. I do get that `cake` is based on `C#` but I remember when the `vscode` team removed the `vue` extension from their `html` extension support to give room to the 3rd party `Vue` extension. @gep13 Was this a collaborated change?

**Comment by gep13** [comment]
@JimiC nope, I got the same message pop up and I said yes to go ahead and change it.

>@JimiC said...
Was this a collaborated change?

Yes, this was a collaborated change.  It was for a couple reasons, but it comes down to getting intellisense/debugging support working for Cake.  In order to make this happen, we needed to have .Cake files recognised as C# scripting files, in the same way that `.csx` files are.

**Comment by JimiC** [comment]
@gep13 Do a manual apply anyways but keep the snippet in `User settings`.

Regarding the change in `language id`, it's understandable. No biggie.

**Comment by gep13** [comment]
@JimiC so this is what I have in my User Settings file:

![image](https://user-images.githubusercontent.com/1271146/32163837-848b34ce-bd55-11e7-9208-d86c265a6311.png)

I run the `Apply Icon Customization` command and I am prompted with this:

![image](https://user-images.githubusercontent.com/1271146/32163886-ae295edc-bd55-11e7-993f-8e596c848674.png)

I click restart, but I still see this:

![image](https://user-images.githubusercontent.com/1271146/32163909-c59c4b06-bd55-11e7-8607-56bf91b4dfaa.png)

Any ideas?

**Comment by JimiC** [comment]
@gep13 It's really weird. It works on `insiders` but not on the`stable`. `vscode` bug?

**Comment by JimiC** [comment]
@gep13 It's due to this `vscode` [bug](https://github.com/Microsoft/vscode/issues/27475). The fix hasn't found it's way to the stable release yet. Patients.

**Comment by gep13** [comment]
Gotcha! That makes sense, I don't run insiders on this laptop.  Thanks for digging into this.

Happy to wait for resolution, keep up the great work!  For me, this is a mandatory extension for VSCode 😄

**Comment by gep13** [comment]
@robertohuertasm woo hoo! Thank you!

Do you guys have an ETA on when you are pushing out your next release?

**Comment by robertohuertasm** [comment]
@gep13 our next milestone is set to 11 Nov but we may release it this weekend.

**Comment by gep13** [comment]
Great news! I will keep an eye out for it!

Thanks again!

**Comment by JimiC** [comment]
There is also a chance to wait for the next stable vscode release in order to include the icon change.

**Comment by gep13** [comment]
@JimiC understood.  I will keep you posted on how it goes.
