### ISSUE TITLE
Not supporting hyphen separators in patterns?

### ISSUE THREAD

**Issue by rndmerle** [vscode-icons/vscode-icons#1323]
Hi.

I wanted to define some custom rules for `*-diff.png` and `*-snap.png` so I checked how it was done (the "testts" rule for instance) but didn't get it to work.

Then I realized that actually, the "testts" rule doesn't match `*-test.ts` files and that hyphens separator are maybe not supported at all in patterns. Is this the case?

**Comment by JimiC** [comment]
Glob pattern is not support from `vscode` yet.

**Comment by robertohuertasm** [comment]
Hi @rndmerle, `hyphens` are indeed supported. What is not supported at all is wildcards! This is due to a know limitation in the [VSCode API](https://github.com/Microsoft/vscode/issues/12493#issuecomment-249117649)

**Comment by rndmerle** [comment]
Ok I see. Thanks for the quick answers
