### ISSUE TITLE
[Icon Request] Support for Nestjs

### ISSUE THREAD

**Issue by MonsieurMan** [vscode-icons/vscode-icons#1324]
Nestjs is a nodejs *framework* based on angular modular architecture, _(also built with ts ❤️)_, so it would require the same work as Angular projects as there are kind of the same extensions.

- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request
  - Type: `extension`
  - Icon Name: `name`
  - Sample original Icon:  ![nest](https://user-images.githubusercontent.com/13108166/32161516-25ee8a3c-bd56-11e7-9d49-76faed577e1a.png)

  - Extensions: 
    - *.controller.ts
    - *.module.ts
    - *.service.ts
    - *.guard.ts
    - *.pipe.ts
    - *.decorator.ts
    - *.interceptor.ts
    - *.filter.ts
    - *.gateway.ts
    - *.adapter.ts
    - *.middleware.ts
  - Filenames: `nestconfig.json`
  - Language ids: `*ts* or *js*`

- More info: [docs]( https://docs.nestjs.com/)
> @kamilmysliwiec I think this could be nice for vscode user. Also, did I missed / added extensions ? _e.g. I was unsure about .entity.ts as this is more coupled to typeorm_
> edit: Also do you have svg available ?

**Comment by JimiC** [comment]
I got my hands on the `SVG` icon.

**Comment by MonsieurMan** [comment]
Nice ! By the way does the logic behind reloading icons like you do for angular projects needs a serious amount of work to support other kind of projects like this one ?  
If yes I could help but I won't have much time until 2018.

**Comment by JimiC** [comment]
It requires knowledge of how `PAD` and our `i18n` service work. So I guess if you haven't familiarized yourself yet with the codebase then it's quite an amount.

**Comment by avatsaev** [comment]
This framework is awesome btw

**Comment by KingDarBoja** [comment]
@JimiC Have you done any progress with this icon request? I am willing to do some work on it ❤️ (Angular Fan here).

**Comment by JimiC** [comment]
This requires `PAD` (project auto detection) knowledge so I wouldn't recommend getting involved.
