### ISSUE TITLE
.ml and .make don't show icons

### ISSUE THREAD

**Issue by wolf99** [vscode-icons/vscode-icons#1331]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I want to create an icon request

Neither *.ml nor *.make file types are recognised. The ml files I see are ocaml, though the internet says they can be for other ml languages also. An ocaml icon is already listed. Given both these points I'm unsure if this is a icon request or not. Please advise if issue is incorrect, happy to edit or change as needed.

**Comment by JimiC** [comment]
`ml` is supported via the `ocaml` extension.
Not sure what uses `make` file extensions.

**Comment by JimiC** [comment]
@wolf99 If by `make` you mean `makefile` then its support via `makefile` extension.
Checkout https://marketplace.visualstudio.com/items?itemName=naereen.makefiles-support-for-vscode

**Comment by wolf99** [comment]
Thanks for the heads up on the make extension. I'm not seeing the correct icon for ml, just the default file icon. I'll double check this when I get home though 😀

**Comment by JimiC** [comment]
`ml` icon will only light up if a syntax highlighting extension you install declares it.
