### ISSUE TITLE
Riot tag template icon is missing

### ISSUE THREAD

**Issue by dmnrmr** [vscode-icons/vscode-icons#1334]
- [x] I'm sure this issue is not a _duplicate_.

![image](https://user-images.githubusercontent.com/7805266/32489615-3a023d02-c3b9-11e7-8901-b8a434043358.png)
![image](https://user-images.githubusercontent.com/7805266/32489637-4a38ab20-c3b9-11e7-968d-8ac8c6d257ee.png)
![image](https://user-images.githubusercontent.com/7805266/32489685-63f63640-c3b9-11e7-9c96-de7c21c37962.png)

- vscode version: 1.18.0-insider
- Language Extensions: [riot-tag](https://github.com/crisward/riot-tag)

**Comment by JimiC** [comment]
We support the `riot` [language id](https://github.com/vscode-icons/vscode-icons/blob/v7.17.0/src/icon-manifest/languages.ts#L140) which will be the new `language id` to be used by the `Riot-tag` extension (https://github.com/crisward/riot-tag/commit/4dbb8273359218a4a6ca01273901b65569c0258d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Currently that extension uses `jadetag` and `htmltag` as `language id` to support `tag` file extensions.
I suggest asking the author to make a new release.
/cc @crisward

**Comment by dmnrmr** [comment]
By manually installing `riot-tag` 1.0.8 this problem was resolved.

**Comment by JimiC** [comment]
Actually, the version should be `0.1.8`.

**Comment by dmnrmr** [comment]
It was just a typo.
