### ISSUE TITLE
[Feature Request] Hide explorer folder arrows

### ISSUE THREAD

**Issue by ooJerryLeeoo** [vscode-icons/vscode-icons#1337]
Is it possible to hide the explorer folder arrows ? ![screen shot 2017-11-09 at 09 10 00](https://user-images.githubusercontent.com/20783502/32583289-ca108398-c52d-11e7-8bc6-b80ce500e2e5.png)

**Comment by JimiC** [comment]
No, sorry. This is a direct ui feature of `vscode` and specifically the explorer `tree` module.

**Comment by JimiC** [comment]
I'm reopening this because as of `vscode` 1.18 this possible. It's a good `feature` candidate for this extension.

**Comment by jens1o** [comment]
Something like this?

**Comment by peabnuts123** [comment]
Would LOVE this. The triangles in Vscode really confuse me, and I would love to see this controlled via a setting on vscode-icons.
