### ISSUE TITLE
[Icon Request] Support for .prettierignore

### ISSUE THREAD

**Issue by vajahath** [vscode-icons/vscode-icons#1338]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request (if not, remove these lines below):
  - Type: `.prettierignore`
  - Icon Name: `Prettier`
  - Extensions: 
  - Filenames: `.prettierignore`
  
- More info: I think we can assign the `.prettierrc`'s icon to `.prettierignore` also.

**Comment by JimiC** [comment]
@jens1o Can you do this? I'll be away for the weekend.

**Comment by jens1o** [comment]
Yeah, I'm taking a shot :)
