### ISSUE TITLE
Git Indicator colors

### ISSUE THREAD

**Issue by DanielRios549** [vscode-icons/vscode-icons#1349]
VS Code introduces Git indicator color on explorer with the version 1.18, I think an option to use the same color as the Git indicator, would be a good feature, either the default or the user's custom color, maybe the unchanged folders and files with monochromatic icons.

**Comment by JimiC** [comment]
I think your request is irrelevant to this extension. This is a `File Icon Theme` and not a `Color Theme` extension.
If you still believe your request is relevant please elaborate and provide more info on it.

**Comment by JimiC** [comment]
What I found so far about this is:
* https://code.visualstudio.com/updates/v1_18#_git-status-in-file-explorer
* https://code.visualstudio.com/docs/getstarted/theme-color-reference#_git-colors

Both are referring to `Color Theme` authors.

**Comment by DanielRios549** [comment]
I'm speaking about an option to change the icons color to these colors that VS Code uses for Git modifications in the explorer and git tab, not by default, but only an option to active in the settings, e.g: when I add a file, the explorer foreground is green (the text and the label in the right side), the icon would be green as well, only if it is an modification, if it was added, the icon is green, if it was modified, the icon is yellow.

**Comment by JimiC** [comment]
@DanielRios549 I'm afraid this is not possible. `vscode` doesn't give the ability to change the file icons programmatically or has properties in the icons manifest to support that.
File icons are being loaded from a static `json` file when `vscode` starts and any change to that file requires a `vscode` restart.

**Comment by JimiC** [comment]
We could though "inject" our own `css` to achieve this but we don't want to deviate from what `vscode` officially supports.

**Comment by DanielRios549** [comment]
Ok man, I understand, thanks for all.
