### ISSUE TITLE
Folder Icons Keep Breaking

### ISSUE THREAD

**Issue by atom0s** [vscode-icons/vscode-icons#1353]
- [x] I'm sure this issue is not a _duplicate_.

Over the last few updates to this extension I have noticed that every single time the extension updates for me, it completely breaks folder icons. This, as of late, has been nearly every day / every other day or similar. 

The only way I find myself able to fix this issue is to completely uninstall the extension and reinstall it. But since the extension is updated frequently (not complaining about that at all) this is rather annoying to have to do each time I open VSCode. 

While there are other tickets similar to this about the folder icons going missing, for me, it has been an every-update recurring issue.

**Comment by robertohuertasm** [comment]
Can you provide more info about your system? OS, vscode version? Maybe even a capture of your dev tools console?

**Comment by JimiC** [comment]
I guess this must be the issue where the package isn't downloaded correctly leading to icon files missing and resulting in them not showing up in the explorer. This may be a case in slow network connections as the package contains over 600 icons.
Unfortunately, I'm afraid that there isn't anything that we can do about it.

**Comment by atom0s** [comment]
This happens on both of my machines in the house, 1 laptop and 1 desktop.

Laptop: https://i.imgur.com/SVGtssT.png
Desktop: https://i.imgur.com/G05kfTW.png

Both systems have the latest version of VSCode installed and always stay up to date anytime either are informed to update. Here is a pic of the dev console just after icons updated again and are broken:
https://i.imgur.com/xBybMXu.png

Icons were working fine before the update/reload and now they are broken again until I reinstall.

**Comment by JimiC** [comment]
@atom0s I understand your frustration, but this is an issue with the `vscode` extension downloader and not with the extension. Again, there isn't anything we can do, really.

**Comment by atom0s** [comment]
Is there a specific location you mentioned that the folder icons are downloaded to that I can check and see if they are missing?

**Comment by JimiC** [comment]
The extension is downloaded as an `vsix` package. It then gets inflated and placed into `%USERPROFILE%\.vscode\extensions` folder. This extension folder name is `robertohuertasm.vscode-icons-%version%`.

**Comment by atom0s** [comment]
First thing I noticed is that there are two vsicon folders in my extensions folder.
robertohuertasm.vscode-icons-7.17.0
robertohuertasm.vscode-icons-7.18.1

The 7.18.1 version has 637 icons (svg) within the icons folder, including folder_ prefixed icons so it does not look like anything is missing due to downloading.

**Comment by JimiC** [comment]
Maybe the case is that you have 2 copies of the same extension in the folder. Manually delete the `7.17.0` version and restart `vscode`.

**Comment by atom0s** [comment]
Still have no folder icons showing up after manually removing the older extension folder.

**Comment by JimiC** [comment]
Don't tell me that that you have disabled the folder icons via the extension feature (facepalm). Press F1 > Icons > Toggle Folder Icons visibility and follow the instructions.

**Comment by atom0s** [comment]
No, this setting is set to allow icons to show. And the settings.json file setting "vsicons.presets.hideFolders" is set to false.

**Comment by JimiC** [comment]
Check that there is a `default_folder. svg` icon in icons folder.

**Comment by atom0s** [comment]
Yes, it is. https://i.imgur.com/R0vpoNu.png

**Comment by JimiC** [comment]
Well, I have exposed my troubleshooting knowledge. Your issue is beyond me. Try uninstalling and delete the folder from ` extensions` in case it's still there. There re-install.

**Comment by robertohuertasm** [comment]
Also I see you're using the `sync` extension, so I guess you have all your computers with `vscode` and the same set of extensions. Maybe there's one extension causing the conflict. You should try to install the extension in an isolated mode to discard some possible interferences from any other extension.

**Comment by atom0s** [comment]
I actually just uninstalled sync within the last hour as the newest version is causing a lot of errors. However, even with it uninstalled and restarted fully, the folder icons are still missing until I reinstall vsicons fully.

**Comment by robertohuertasm** [comment]
I meant uninstalling or disabling all the extensions. Not just sync.

**Comment by JimiC** [comment]
@atom0s Has your issue been resolved?

**Comment by atom0s** [comment]
No this is still an issue.

**Comment by robertohuertasm** [comment]
@atom0s Is this issue still going on? Did you try disabling all the extensions but ours?

**Comment by atom0s** [comment]
Yeah it is still happening. Tried removing everything but vsicons as suggested but its still happening.

**Comment by mcarpenterjr** [comment]
I have this same issue beginning to occur on my Windows 10 instance. 

Version 1.20.0-insider
Commit 52d0befdb31841cbebd7aec20cfffc932f1c02ec
Date 2018-01-04T05:14:02.889Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by icanos** [comment]
I'm experiencing the same issue on Windows 8.1 with vscode 1.19.2 (x86).

I've only got the following extensions installed:
 - Git Easy
 - One Dark Pro
 - PowerShell
 - vscode-icons

**Comment by qazyn951230** [comment]
Command `>Reinstall Extension` may be help.

**Comment by JimiC** [comment]
Another cause may be a corrupted `vscode` installation. Other than that, I'm clueless.

**Comment by andrewmeissner** [comment]
@qazyn951230 thanks!  That solved my issue!

**Comment by atom0s** [comment]
> Command >Reinstall Extension may be help.

The only issue with this, as I mentioned above, is that while it does fix the issue it's only temporary. The issue will come back and start happening again after another update generally to the extension. 

I have installed VSCode completely over on another system with similar specs and such above and the issue still persists on that machine too. So for me, this is an issue across 3 separate machines now.

**Comment by steelkorbin** [comment]
I just experienced this issue on Ubuntu 16.04 and the Command `>Reinstall Extension` @qazyn951230 mentioned just fixed it for me.  Thanks.

**Comment by JimiC** [comment]
Hopefully, this will be resolved with `v9`.

**Comment by JimiC** [comment]
Btw, come to think of it this issue may be related to a bug we had when updating to a new version and the uninstall script was cleaning up everything `vsicons` related. This has been fixed now since several releases.
