### ISSUE TITLE
[Icon Request] Support for Cargo.lock

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#1367]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request (if not, remove these lines below):
  - Type: `filename`
  - Icon Name: `cargo`
  - Sample original Icon (32x32/svg/transparent whenever possible): [https://crates.io/](https://crates.io/) [png](https://crates.io/assets/Cargo-Logo-Small-c39abeb466d747f3be442698662c5260.png)
  - Filenames:  `Cargo.lock`, `Cargo.toml`

This is a `rust` associated file but it's something used by its package manager called `Cargo`.

**Comment by ivanovaleksey** [comment]
Hello @robertohuertasm, as I can see @wifelette kindly helped us with the icons!
Do you need any help to add files?
By the way, that would be icons for both Cargo.toml and Cargo.lock?

**Comment by JimiC** [comment]
@ivanovaleksey I added `Cargo.toml` to the `to be` supported list.

**Comment by robertohuertasm** [comment]
I deliberately left out `Cargo.toml` as this is just a `toml` file which we support via language id.

**Comment by robertohuertasm** [comment]
@ivanovaleksey, I personally use [this extension](https://marketplace.visualstudio.com/items?itemName=bungcip.better-toml) for `toml`. You'll get syntax highlighting along with our `toml` icon.

**Comment by JimiC** [comment]
@robertohuertasm I believe that although it's a `toml` file it deserves the `Cargo` icon.

**Comment by robertohuertasm** [comment]
On second thought, I think you both are right!

**Comment by ivanovaleksey** [comment]
Thank you guys.
I've just noticed that both Bundler's Gemfile and Gemfile.lock have the same icon.
And I thought it would be nice to have the same for Cargo. It just emphasizes that file are closely related to each other.
