### ISSUE TITLE
[Icon Request] tsconfig new extensions

### ISSUE THREAD

**Issue by msqaddura** [vscode-icons/vscode-icons#1379]
https://github.com/vscode-icons/vscode-icons/blob/6f7c1e5d4ee00581ae7e05de9259e0e8710cc8d5/src/icon-manifest/supportedExtensions.ts#L493

Hello, 
tsconfig.dev.json & tsconfig.prod.json are missing (maybe more are needed). It would be really great to have them, since tsconfigs can are similar to webpack configs in terms of extending. 
webpack.config.* is working pretty well.

Thank you in advance and keep the great work up!

**Comment by jens1o** [comment]
@msqaddura Do you want to file a pr? :)

**Comment by msqaddura** [comment]
Please find it here:
https://github.com/vscode-icons/vscode-icons/pull/1384

I also wanted to add that in your wiki to build the code it says : 
- npm install -d
- npm run build

I think there should be these two scripts in package.json (if am not getting something wrong)
```
        "preinstall": "npm run git:submodules",
        "git:submodules": "git submodule update --init --recursive",
```

**Comment by JimiC** [comment]
@msqaddura Wiki pages are automatically generated by our tool. You don't need to do anything.

**Comment by msqaddura** [comment]
@JimiC 
I do understand that, but what i mean is in this link
https://github.com/vscode-icons/vscode-icons/wiki/Build

it doesnt say anything about the submodules, which the error i was getting while trying to build. some git clients do not recursively clone submodules and maybe someone will get into that. I dont know it might not be that necessary to do so but still maybe some people will run into that so i just felt like pointing it out.

**Comment by JimiC** [comment]
I see your point. I'll look into it.

**Comment by JimiC** [comment]
@msqaddura Please see #1393.
