### ISSUE TITLE
BUG: default folder icon is empty after updating extension

### ISSUE THREAD

**Issue by pmunin** [vscode-icons/vscode-icons#1391]
Just update to the latest version and I see that regardless of the settings, the default folder icon is blank:

![image](https://user-images.githubusercontent.com/7120440/33521681-db816bac-d7a6-11e7-94ec-fd3e71551df1.png)

**Comment by jens1o** [comment]
Could you try uninstalling and reinstalling the extension? We had that problems several times in the past, that your client downloads not any data, but only a part of it.

**Comment by pmunin** [comment]
Thanks, this worked. However I should notice that right after reinstalling and reopening vscode in my workspace another issue showed up - it didn't activate my customization stored in workspace settings. So after some experiments i was able to fix that, buy changing some other setting of vscode-icons (not yet used in my workspace settings) and then removing it. This triggered vscode-icons detecting settings changes and showing restart request message. After restarting It applied all my settings.

**Comment by jens1o** [comment]
The vscode update routine is sometimes a quirk, unfortunately. :/

**Comment by JimiC** [comment]
Auto applying the customizations is only triggered by a new version update. In your case you only need to press `F1 > Icons: Apply Icons Customization`
