### ISSUE TITLE
.htaccess is not displaying icons

### ISSUE THREAD

**Issue by MythicAngel** [vscode-icons/vscode-icons#1400]
From #41, it seems that .htaccess icon was provided. But it is not working on my VSCode repository. 

Also, from icons folder, I didn't find any file_type_htaccess, so is it available yet or I should open a feature request for it?

.htaccess is quite essential for any hosting platform / wordpress etc. area. So, it has merit obviously.

Thanks, big fan of this project.

**Comment by jens1o** [comment]
Could you please use the issue template? You need to install an extension to get the icon.

Duplicate of #870
