### ISSUE TITLE
[Icon Request] Support for NGINX .conf files

### ISSUE THREAD

**Issue by skeltonm** [vscode-icons/vscode-icons#1404]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request (if not, remove these lines below):
  - Type: `conf/*`
  - Icon Name: `nginx`
  - Sample original Icon: (https://gist.github.com/skeltonm/d91ebd3f11b554f34faa626368e39002)
  - Extensions: `conf`
  - Filenames: `*`

- More info: [nginx.com](https://www.nginx.com/)

**Comment by JimiC** [comment]
@skeltonm Thank you for submitting an icon request.
There are some issues with your request though that I like to clarify.

1. Not all files with a `conf` extension are `nginx` files.
2. I'm sure there is a conventional name for an `nginx` config file (maybe it's `nginx.conf` ?).
3. If the above is true then `Type` should be changed to `filename` as the request type is to support a `filename`, `Extensions` should be removed and `Filenames` should list the requested filename.
4. I think [this](https://cdn-1.wp.nginx.com/wp-content/themes/nginx-theme/assets/img/nginx-favicon.png) is a more suitable icon.

**Comment by JimiC** [comment]
Turns out I'm right about the filename (https://www.nginx.com/resources/admin-guide/configuration-files/)

**Comment by JimiC** [comment]
Additionally, we could also add support for a `nginx` specific folder to facilitate when having a set of feature-specific config files in that folder.
