### ISSUE TITLE
[Icon request] please support RStudio project files `.Rproj` and folder `.Rproj.user/`

### ISSUE THREAD

**Issue by psychelzh** [vscode-icons/vscode-icons#1408]
# Issue Template

THIS IS AN EXAMPLE TEMPLATE

Make sure the following boxes are checked (and the placeholders replaced) BEFORE submitting this issue.

Screenshots are more than welcome!

Please remove any unused content (including these instructions) before submitting your issue.

IMPORTANT: For folder icon requests please first see issue: [650](https://github.com/vscode-icons/vscode-icons/issues/650)

Thanks.

Note: Always remove this line and all above.

- [x] I'm sure this issue is not a _duplicate_.
- [x] I want to create an icon request (if not, remove these lines below):
  - Type: `.Rproj`, `.Rproj.user/`
  - Icon Name: `RStudio project`
  - Sample original Icon (32x32/svg/transparent whenever possible): [url]
  - Extensions: `.Rproj`, `.Rproj.user/`
  - Filenames: `comma separated list of filenames`
  - Language ids: `R`

- Language Extensions: [url to `vscode` extensions that support language highlighting](https://marketplace.visualstudio.com/items?itemName=Ikuyadeu.r#overview)

**Comment by jens1o** [comment]
Please file the folder icon request to #650
