### ISSUE TITLE
question about variable substitution in `vsicons.customIconFolderPath`

### ISSUE THREAD

**Issue by gerardmrk** [vscode-icons/vscode-icons#1416]
I have a custom icon folder in my project directory that I would like to add into version control, but it seems I'm unable to utilize variable substitution in the `vsicons.customIconFolderPath` setting.

I've tried **${workspaceRoot}**, **${workspaceFolder}** and even a relative path (relative from `.vscode/settings.json`), and none of them works. But specifying the full absolute path to the directory works (using `pwd`). I would like to know if variable substitution is possible, thanks

**Comment by JimiC** [comment]
Have you read https://github.com/vscode-icons/vscode-icons/wiki/Custom?

**Comment by gerardmrk** [comment]
@JimiC yes I have, the doc implies absolute path has to be specified. The configuration is not shareable across multiple machines that way, e.g. `/Users/gerard/Documents/DevProjects/src/github.com/gerardmrk/xo` isn't the same for other users' OS if they're using the same repo.

**Comment by JimiC** [comment]
Have you tried using a path relative to the project's root directory?

**Comment by JimiC** [comment]
@gerardmrk So it turns out that this feature indeed works only with an absolute path to the `vscode-custom-icons` folder. ANd in your case, yes it will not work.
I'll see what I can do to add something that uses relative paths.

**Comment by JimiC** [comment]
@gerardmrk I'm gonna close this issue as it's out of my current abilities to make this work with relative paths. You see the extension needs to know the absolute path where the custom icons folder is in order to use the custom icons. Searching from where the extension is to where the custom icons folder is, in order to figure out the relative path, means that we must use an algorithm that scans your entire file system to locate it, something that isn't efficient at all.

If anyone has another idea, pleae share.

**Comment by JimiC** [comment]
I'm experimenting to see if I can come up with something, using `workspaceRoot` and `workspaceFolder`.
Will post back if I have something worth mentioning.

**Comment by radziksh** [comment]
@gerardmrk I added in `projectFolder/.vscode/settings.json` these lines:
```
"vsicons.customIconFolderPath": "./.vscode",
 "vsicons.associations.files": [
        { "icon": "formRelated", "extensions": ["form-container.tsx"], "filename": true, "format": "png", "overrides": "form-container.tsx" },
        { "icon": "formRelated", "extensions": ["form-view.tsx"], "filename": true, "format": "png", "overrides": "form-view.tsx" }
    ],
```

next I added `vsicons-custom-icons` folder and `file_type_formRelated.png` (32x32 px) file in it.
`projectFolder/.vscode/vsicons-custom-icons/file_type_formRelated.png`

Press `F1` > `Icons: Apply Icons Customization`

works for me.

**Comment by radziksh** [comment]
@JimiC would like to point out that https://github.com/vscode-icons/vscode-icons/wiki/Custom

> If you want to take advantage of this feature, just go to your settings and set vsicons.customIconFolderPath with the path to the folder containing the vscode-custom-icons folder.
> 
> ***Note that the name of the folder containing the icons must be vscode-custom-icons.***

doesn't work for me but `vsicons-custom-icons` works. Maybe it's typo?

**Comment by JimiC** [comment]
@radziksh Good catch. Corrected.
