### ISSUE TITLE
[Icon Request] Support for RStudio project file

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1418]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `rproj`
  - Sample original Icon: ![logo](https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-125.png)
  - Extensions: `.Rproj`

- More info: https://www.rstudio.com/products/rstudio/

**Comment by JimiC** [comment]
@psychelzh This is the proper way to request an icon.

Just for future reference instructions can be found @ https://github.com/vscode-icons/vscode-icons/wiki/Issue and by carefully reading what's is written in the template.

Thank you.

**Comment by psychelzh** [comment]
@JimiC Thank you. I now got it.
