### ISSUE TITLE
[Icon Request] Support  for Stylus

### ISSUE THREAD

**Issue by tatwd** [vscode-icons/vscode-icons#1428]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `stylus`
  - Sample original Icon: ![logo](http://stylus-lang.com/img/stylus-logo.svg)
  - Extensions: `.styl`

- More info: http://stylus-lang.com/

**Comment by jens1o** [comment]
@tatwd Why did you closed the issue?

**Comment by tatwd** [comment]
Because i found this icon already exists. :relieved:

![screendshot-stylus-1](https://user-images.githubusercontent.com/16670044/35469850-2cc2c5da-0379-11e8-8ff3-d9e2189ee289.png)

But in my vscode, this icon is not linked to `.styl` file when extension named [language-stylus](https://github.com/d4rkr00t/language-stylus) is not installed.

![screendshot-stylus-3](https://user-images.githubusercontent.com/16670044/35470021-11f84312-037c-11e8-962e-e6978f9cd355.png)

if i install the extension, this icon shows up: 

![screendshot-stylus-2](https://user-images.githubusercontent.com/16670044/35469928-935dd91e-037a-11e8-95e3-f92cfb5defe6.png)

**Comment by jens1o** [comment]
> So i should go find vscode team in trouble, i think! 💣

No, you should not. That's by purpose from us. Otherwise, we would need to worry about each language extensions. That would be unmaintainable. An extension, that is dedicated to this file type, is able to know the names, so we rely on that. But in general, I didn't checked it up.

Thanks for your time!
