### ISSUE TITLE
[Icon Request] Please finish up swig file icon

### ISSUE THREAD

**Issue by tatwd** [vscode-icons/vscode-icons#1433]
The request already exist(#711) but is not linked to `.swig` files now.

![screenshot-swig](https://user-images.githubusercontent.com/16670044/35469712-6c41777c-0376-11e8-9bd6-fad60b189cda.png)

Is it possible to finish up it, please? Thank you very much!

**Comment by jens1o** [comment]
Actually, the request is still open. Perhaps you want to bring in a pr?

**Comment by JimiC** [comment]
There is no official icon for swig. I have one idea but didn't had the time to do the art work. Please be patient.
