### ISSUE TITLE
[Task] Improve docker image

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1437]
- [x] I'm sure this issue is not a _duplicate_.

As mentioned in #1431 the `docker` image needs improvements in order to suit our needs.

**Comment by JimiC** [comment]
@vscode-icons/development I have a proposition branch @ https://github.com/JimiC/vscode-icons/tree/docker/docker
I would like your review and suggestions before I submit a PR.

**Comment by jens1o** [comment]
I do not have any experiences with docker unfortunately :/

**Comment by JimiC** [comment]
I didn't have any also, until last Friday. It's not hard or too late to get started. As an added motivator let me tell you that all cloud service apps are moving to containerization. It saves tremendous machine resources.

**Comment by jens1o** [comment]
> As an added motivator let me tell you that all cloud service apps are moving to containerization. It saves tremendous machine resources.

my cpu does not support virtualization :c

**Comment by JimiC** [comment]
Then you should ask "dad" to invest in you if you are serious about becoming a prof dev.

**Comment by jens1o** [comment]
ha, lol.

**Comment by JimiC** [comment]
@dderevjanik May this interests you too. I'ld really like your input on this.

**Comment by JimiC** [comment]
If anyone needs more info on the proposed changes please feel free to ask.

**Comment by JimiC** [comment]
@dderevjanik I'm trying to determine what kind of `vsi` docker images we will need to build via CI.
I have currently setup the pipelines for building `vsi:latest`.
Will your extension project benefit from a tagged image every time we do a release, (like `vsi:7.19.0`)?

/cc @robertohuertasm

**Comment by JimiC** [comment]
I can show you also how we can automate your release whenever we do one.

**Comment by dderevjanik** [comment]
That would be really great to include it into `travis` :)
Otherwise, I have a weird feeling about building image first... you know, you're compiling and building extension every release, so why not just upload `icons.json` somewhere ?
My point is, building Image on my own (which includes `pull`-ing whole repo, doing `npm i` and other stuff) sounds like a little bit overhead. Everything I need to update icons (`icons.json`), you already did.

**Comment by JimiC** [comment]
We just don't prefer that kind of solution. I can show you through how you can automate the entire procedure with `travis`. Just wait till we merge the restructuring PR.

**Comment by dderevjanik** [comment]
Ok, thank you very much :)

**Comment by dderevjanik** [comment]
@JimiC I created library [vscode-icons-js](https://github.com/dderevjanik/vscode-icons-js) (inspired by [file-icons-js](https://github.com/websemantics/file-icons-js)), which generates dictionaries of filenames and their representative icons. It would be great to automate that one.

_That means, I'm going to refactor github-vscode-icons to fully depends on vscode-icons-js._

**Comment by JimiC** [comment]
@dderevjanik Great! Will try to have a look at it tomorrow. Otherwise, I'll try to do so on the weekend.

**Comment by JimiC** [comment]
@dderevjanik I took a peek at [vscode-icons-js](https://github.com/dderevjanik/vscode-icons-js). I figure you still need a way to get our `icons.json` in the `data/generated` folder, right?
