### ISSUE TITLE
[Icon Request] Support for SystemVerilog

### ISSUE THREAD

**Issue by mrvkino** [vscode-icons/vscode-icons#1442]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id `
  - Icon Name: `SystemVerilog`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/file-icons/source/master/svg/SystemVerilog.svg?sanitize=true)
  - Language ids: `systemverilog`

- Language Extensions:
https://marketplace.visualstudio.com/items?itemName=eirikpre.systemverilog
https://marketplace.visualstudio.com/items?itemName=mshr-h.SystemVerilog
- More info: [Good suggestion of color differentiation of extension sv and svh](https://github.com/file-icons/atom/issues/340)

**Comment by JimiC** [comment]
Fixed OP.

**Comment by JimiC** [comment]
Same as https://github.com/vscode-icons/vscode-icons/issues/1441#issuecomment-363821107
