### ISSUE TITLE
Assembly Icon not visible 

### ISSUE THREAD

**Issue by Flaires** [vscode-icons/vscode-icons#1449]
- [X] I'm sure this issue is not a _duplicate_.

- Language Extensions: asm (Assembly)
- More info: The Assembly icon isn't visible. I reinstalled the extension already but unfortunately with no result.   (Not sure if `.s` extension is supported, but afaik the `.asm` extension is supported)

![image](https://user-images.githubusercontent.com/27811860/36115581-c9973078-1033-11e8-9f0d-487ba62e810b.png)

**Comment by JimiC** [comment]
Install a syntax highlighting extension from the marketplace and it will show up.

**Comment by Flaires** [comment]
I already have [this ](https://marketplace.visualstudio.com/items?itemName=13xforever.language-x86-64-assembly)extension installed but it didn't work.

**Comment by JimiC** [comment]
This extension uses `asm` as a language id. We will have to add that to our collection.

**Comment by JimiC** [comment]
Btw the extension we currently support if [this](https://marketplace.visualstudio.com/items?itemName=dan-c-underwood.arm).

**Comment by Flaires** [comment]
Thanks for the info.
