### ISSUE TITLE
[Icon Request] Support for .env.dist

### ISSUE THREAD

**Issue by jens1o** [vscode-icons/vscode-icons#1457]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `config`
  - Sample original Icon: already included (see https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_config.svg)
  - Filenames: `.env.dist`, `.env.example`

This is used as a configuration file that is not suited for the specific system but can be uploaded to Git or other Source Control Managers.

Support for `.env` already exists, only an extension is missing.

**Comment by JimiC** [comment]
@jens1o I expected from you to know by now how to properly submit an issue 😞

**Comment by JimiC** [comment]
Any info regarding your request?

**Comment by JimiC** [comment]
By doing a research I guess this is a `filename` related icon request. Correcting the OP accordingly.
This can be assigned to the `config` icon that supports `filename`s (like `.env.example`).

**Comment by jens1o** [comment]
> @jens1o I expected from you to know by now how to properly submit an issue 😞

Come on, I just capitalized it wrong. No need to be disappointed ;)

> Any info regarding your request, online doc? Does it involve, extension or filename?

I know you dislike PHP and that stuff, but it's actual common not to put sensitive information into the code, but leave them into a `.env` file, which is protected by `.gitignore`, so what you commit are example values that everybody can has(so yes, it's a filename request).

**Comment by JimiC** [comment]
I wasn't disappointed by the title. The info filled in `Type` was wrong, not explicitly mention what type the request is for. You had both filled `Extensions` and `Filenames` which was also wrong. That lead me to confusion and I had to spend half an hour searching google to figure out what `.env.dist` is all about.
You should always have in mind that not everyone knows what you are talking about.It will help in your life.

**Comment by jens1o** [comment]
Oh, good point. I'm sorry :/
