### ISSUE TITLE
[Suggestion] Change Config.x Files To Show Configuration Icon

### ISSUE THREAD

**Issue by FireController1847** [vscode-icons/vscode-icons#1465]
I find it quite interesting that when I type `Config.js` or `Config.json`, it replaces it with the JS or JSON icon instead of a configuration icon, which would be preferable over the language on files like those. This suggestion is to suggest that the configuration icon shows up over the language for files named `config.*`.

- [x] I'm sure this issue is not a _duplicate_.

**Comment by JimiC** [comment]
`vscode` does not support glob for icon themes. When it will, we can discuss this again.

**Comment by jens1o** [comment]
@JimiC We could still dig around it and define global prefixes as a filename.

**Comment by JimiC** [comment]
Still not fond of the idea. After all `config.js` is a `js` file and `config.json` is a `json` file. If we start with this then we will have to cover all variants of `config.*.js` and `config.*.json` filenames.

**Comment by robertohuertasm** [comment]
I think the same way as @JimiC. Anyway, this is something that the user can customize for himself using our custom associations. I wouldn't walk this path because then we should have to cover other different use cases like `utils.*`  and so on. My vote is negative in this case.

**Comment by jens1o** [comment]
Personally, I would have no use cases for that, but I'm not bothered when this will be implemented.
