### ISSUE TITLE
[Icon Request] Support for Quasar Framework

### ISSUE THREAD

**Issue by leopiccionia** [vscode-icons/vscode-icons#1482]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `quasarframework`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/quasarframework/quasar-art/master/dist/svg/quasar-logo.svg?sanitize=true) (notice the white circle background is part of the logo)
  - Filenames: `quasar.conf.js`
- More info: http://quasar-framework.org/

**Comment by JimiC** [comment]
@leopiccionia Kudos for submitting a proper issue.
