### ISSUE TITLE
custom icon wont show up

### ISSUE THREAD

**Issue by Mcilie** [vscode-icons/vscode-icons#1489]
- [# ] I'm sure this issue is not a _duplicate_.

So I was searching up on how to add a custom icon. 
Im programming in Q#, microsoft's new quantum programming language.
Sadly there is no default icon for this so i made my own 256X256 png file 
Then I put it in the folder /Users/michaelilie/Library/Application Support/Code/User/vsicons-custom-icons , as I was told to do so in the following link: https://github.com/vscode-icons/vscode-icons/wiki/Custom . I restarted Vscode 3 times, and the icon isnt showing up. I am using the Vscode-icons file icon theme.  
Please help; How do I fix this?

**Comment by Mcilie** [comment]
Would this classify as an Icon request? I thought the extension allowed you to add your own custom icons for any file type?

**Comment by Mcilie** [comment]
Also I changed the size to 32X32, still doesnt work

**Comment by JimiC** [comment]
Have you followed https://github.com/vscode-icons/vscode-icons/wiki/FineTuning?

**Comment by Mcilie** [comment]
yes: {
    "python.pythonPath": "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6",
    "vsicons.associations.files": [
  { "icon": "qsharp", "extensions": ["qs", "file.qs"], "format": "svg" }
]
}

**Comment by Mcilie** [comment]
Am i supposed to put an actual file path in the "icon": value?

**Comment by JimiC** [comment]
By all means, did you performed `Apply Icons Customization` before restarting `vscode`? Just restarting `vscode` doesn't work.

**Comment by Mcilie** [comment]
now its showing up as a blank ,(no icon at all)

**Comment by JimiC** [comment]
> It's also important to say that if you choose to make a manual modification you will have to execute the Apply Icons Customization command (see below)

**Comment by Mcilie** [comment]
I got it to work. Idk why, but  instead of svg i have to call it a png, even though i converted it to png

**Comment by jens1o** [comment]
Could you try to open the Developer Tools, select the Console tab and execute the command? When there is an error output, show us the complete log.
If not, hit reload and report if the console is still empty.

**Comment by JimiC** [comment]
If the icon you provide is an `png` it's obvious that the file format has to be set to that.

**Comment by jens1o** [comment]
I think the issue can be closed as of now. :)

Thanks for using our extension. :)
