### ISSUE TITLE
Make `tsconfig.*.json` all use tsconfig.json icon

### ISSUE THREAD

**Issue by unional** [vscode-icons/vscode-icons#1490]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `tsconfig`
  - Icon Name: `tsconfig`
  - Extensions: `json`
  - Filenames: `tsconfig.*.json`
  - Language ids: `typescript`

- Language Extensions: TypeScript
- More info:

Right now `tsconfig.base.json` is using the icon. Want to expand it to any file matching `tsconfig.*.json`

**Comment by JimiC** [comment]
Not technically possible yet.

**Comment by unional** [comment]
Thanks for the quick update.
Would that be desirable and support that in the future?
If so, maybe you can keep this open for tracking. 🌷

**Comment by jens1o** [comment]
@unional Please upvote here: https://github.com/Microsoft/vscode/issues/12493

**Comment by JimiC** [comment]
@jens1o Exactly what I was looking for. Thanks

**Comment by jens1o** [comment]
Bookmarks are useful ;)
