### ISSUE TITLE
Extension's commands missing on command palette

### ISSUE THREAD

**Issue by adham-hajji** [vscode-icons/vscode-icons#1491]
- [x] I'm sure this issue is not a _duplicate_.

Hello.

I installed vscode-icons some time ago, and I tried to configure some custom bindings via the workspace settings. The JSON chunk of code was the following:

```json
"settings": {
  "vsicons.associations.folders": [
    { "icon": "www", "extensions": "sites", "format": "svg" }
  ]
}
```

In order to make those change appear on the editor, I followed the documentation: I pressed the `F1` button, then I tried to run the Activate command of the extension.

Unfortunately, I encountered an issue that. VSCode triggered this error:

> command 'vscode-icons.activateIcons' not found

I have my Visual Studio Code running as an administrator. I enabled Devtools and checked the Chrome console. Oddly, there isn't any error concerning a file missing. Instead, the console shows this exception:

```console
command 'vscode-icons.activateIcons' not found
e.doShow @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2925
````

All the others commands also don't work. What can cause this error?

Thank you for your help.  :)

(extracted from https://github.com/vscode-icons/vscode-icons/issues/26#issuecomment-370180683)

**Comment by jens1o** [comment]
Thank you for creating a new issue. This does indeed look strange to me. Perhaps @vscode-icons/development knows more?

**Comment by JimiC** [comment]
Usually, this means that an error has crashed the process that loads the extensions. Open `Developer Tools` of `vscode` and see what is causing the error. Most of the times it's another extension that crashed.

**Comment by JimiC** [comment]
Also, the correct command you are looking is `Apply Icons Customisation` and not `Activate Icons`.

**Comment by jens1o** [comment]
@Adham-Hajji Are you using the up2date extension versions? Which version of Visual Studio Code are you using?

**Comment by adham-hajji** [comment]
@JimiC Thanks for this precision. ;)

@jens1o I am using the version publicly released on the VSC extensions repository (7.20.0) My VSC is up2date, running the v1.20.1

I just restarted VSC, and some interesting errors were triggered by the Devtools console:

```console
[Extension Host] Activating extension `robertohuertasm.vscode-icons` failed:  Cannot find module 'semver'
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:253

[Extension Host] Here is the error stack:  Error: Cannot find module 'semver'
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (C:\Users\adham\.vscode\extensions\robertohuertasm.vscode-icons-7.20.0\out\src\settings\settingsManager.js:4:16)
	at Object.<anonymous> (C:\Users\adham\.vscode\extensions\robertohuertasm.vscode-icons-7.20.0\out\src\settings\settingsManager.js:93:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
```

Apparently, a module named `semver` cannot be loaded by the extension host

**Comment by jens1o** [comment]
I wonder whether  your installation is somehow corrupt. Could you try uninstalling and reinstalling the extension?

**Comment by JimiC** [comment]
That's a bad install. Uninstall, delete any remaining files of the extension in the `extensions` folder and re-install.

**Comment by adham-hajji** [comment]
I uninstalled, deleted any remaining files and installed it again. Unfortunately, the extension triggers the same error.

**Comment by jens1o** [comment]
Let's get a step deeper. Could you try removing Visual Studio Code and install it again? (Perhaps you want to [sync your settings ](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)before doing the try.)

**Comment by JimiC** [comment]
I just updated one of my instances from `7.19.0` to `7.20.0`. I checked the `node_modules` folder an `semver` is there, so there must be something on you side.

**Comment by JimiC** [comment]
Make sure there are no previous versions of the extension in the `extensions` folder.

**Comment by adham-hajji** [comment]
@jens1o I will do that. :)

It turns out that semver is the versioning manager of npm. If this extra info can help, I am using the npm@0.3.3 extension. Maybe it causes some conflicts?

@JimiC I checked the semver directory which exists. But I noticed there is no `vscode-icons`directory on the `extensions`, is it normal?

**Comment by JimiC** [comment]
The name of the folder should be `robertohuertasm.vscode-icons-7.20.0`.

**Comment by jens1o** [comment]
> Maybe it causes some conflicts?

Actually, any extension should have isolated sub-dependencies, so it should not be affected.

**Comment by JimiC** [comment]
I also use the `npm` extension so the issue doesn't lie there.

**Comment by adham-hajji** [comment]
The folder is missing. I am reinstalling VSC, maybe the previous installation was corrupted (I don't use checksums, my bad xD)

**Comment by jens1o** [comment]
Please use them this time, just to avoid spending time on something we can't influence ;)

**Comment by JimiC** [comment]
Backup the extensions folder and use a clean `vscode` and install `vscode-icons`. See what's happening.

**Comment by adham-hajji** [comment]
It was indeed a problem on my VSCode installation. It marvelously works now!

@JimiC 
@jens1o 
Thank you two ;)

**Comment by jens1o** [comment]
Glad that it works!
