### ISSUE TITLE
[Task] Consider using Wallaby.js

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1492]
Recently I stumbled across [Wallaby.js](https://wallabyjs.com/) and it looks like a good addition to our `DevOps`.

`VSCode Extension`: https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode

@vscode-icons/development What's your opinion?

**Comment by robertohuertasm** [comment]
If you want to give it a try, it's ok for me.

**Comment by JimiC** [comment]
Closing reason: https://wallabyjs.com/purchase/

**Comment by robertohuertasm** [comment]
I've sent them an email in case they have special licenses for OSS projects. I'll let you know when I have an answer.

**Comment by robertohuertasm** [comment]
Hey, guys we've got an answer from Wallaby and they have provide us with a license. I'll reach to you via Slack with the details!
