### ISSUE TITLE
[Task] Perform cleanup when extension gets uninstalled

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1499]
- [x] I'm sure this issue is not a _duplicate_.

We should explore the ability to add a cleanup process when the extension gets uninstalled.
Mainly what needs to be cleaned is the `vsicons.settings.json`.

Info: https://code.visualstudio.com/updates/v1_21#_extension-uninstall-hook

**Comment by jens1o** [comment]
I've mentioned that in Slack and I've been told we have no use for it?

**Comment by JimiC** [comment]
I can't recall we ever talked about that. Care to remind us?

**Comment by jens1o** [comment]
Nevermind, what are your concrete plans? The icon manifest is automatically deleted by vscode, isn't it?

**Comment by JimiC** [comment]
Yes. Only the mentioned file stays as carbage.
