### ISSUE TITLE
[Icon Request] Support for Pyret

### ISSUE THREAD

**Issue by SethPoulsen** [vscode-icons/vscode-icons#1502]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id`
  - Icon Name: `pyret`
  - Sample original Icon:  ![pyret-icon](https://raw.githubusercontent.com/brownplt/pyret-lang/master/img/pyret-icon.png)
  - Language Ids: `pyret` 

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=SethPoulsen.vscode-language-pyret
- More info: https://www.pyret.org

**Comment by JimiC** [comment]
@SethPoulsen Thanks for letting us know. Seen you support this via a `vscode` extension and a `languageid` I corrected your OP accordingly.

**Comment by robertohuertasm** [comment]
@JimiC, what's your opinion about it? @SethPoulsen, normally we prefer the official icon whenever is possible. To be honest, I haven't tested the icon myself so I have no idea how nice it looks when scaled. I'll try it out and let you know what I think.

**Comment by JimiC** [comment]
I have used a tweaked version of the `face detailed` icon. I have to see how it looks in the editor. The `faceless` logo is also an official one so there is no debate there. So I have no objections if it looks better.

**Comment by SethPoulsen** [comment]
Yea, its also an official icon used by the Pyret people for small icons. @jpolitz, one of the maintainers of the language, references it in this thread (https://github.com/brownplt/atom-language-pyret/issues/2):  

> There's a file called "pyret-icon.png" that we use for favicons that might be especially good for file logo since it avoids trying to scale down the details of the eyepatch

If you open www.pyret.org in Chrome and you'll see it in the tab at the top. 

@JimiC Sounds good, we'll have to see how it looks in the editor.  I'm afraid the detailed face might look a little cluttered.
