### ISSUE TITLE
No icons showing up - Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by cryodream** [vscode-icons/vscode-icons#1506]
- [x] I'm sure this issue is not a _duplicate_.

The extension stopped working. No icons show up at all.
Console is full of:
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
```
Also:
```
[Extension Host] Activating extension 'robertohuertasm.vscode-icons' failed: Cannot find module '../i18n'
Activating extension 'robertohuertasm.vscode-icons' failed: Cannot find module '../i18n'.
```
I tried to disable/enable, un-uninstall and re-install the extension - did not work.

Here's a screen:
![2018-03-11_20-19-24__code](https://user-images.githubusercontent.com/844036/37260765-37eadfae-256d-11e8-8646-4074ccbb3656.png)

OS: Windows 10 Pro x64

VS Code:
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T11:04:09.969Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Please, help.
I'm so used to the icons by now, it's really hard without them 😞

**Comment by alessandropietrobelli** [comment]
Same error here with:

OS: Mac OS X 10.13.3 (17D102)

VS Code:
Version 1.21.0
Commit 9a199d77c82fcb82f39c68bb33c614af01c111ba
Date 2018-03-07T10:49:32.212Z

**Comment by JimiC** [comment]
@cryodream Check at `%APPDATA%\.vscode\extensions` for any residual folders or files of the extension (extension folder name is `robertohuertasm.vscode-icons-x.x.x`). If you find any delete them and re-install.

@alessandropietrobelli Please do the same on `macos`. The path to the `extension` folder eludes me atm, so in case you can't find it post back, in case another team member knows it by heart.

**Comment by alessandropietrobelli** [comment]
@JimiC deleting and re-install works! Thank you!

**Comment by cryodream** [comment]
@JimiC thanks 
Same here, uninstalled the extension, deleted the folder, reinstalled - working 👍 
The folder was:
```
C:\Users\(username)\.vscode\extensions\robertohuertasm.vscode-icons-7.21
```

**Comment by JimiC** [comment]
Good to know guys. Memory fails me as of late (considering getting a DDR5 :laughing:).

**Comment by JimiC** [comment]
The correct way is to use `%USERPROFILE%`. I have updated my comment.
