### ISSUE TITLE
PostCSS icon not showing in Explore pane

### ISSUE THREAD

**Issue by megalofauna** [vscode-icons/vscode-icons#1507]
![postcss-icon-bug](https://user-images.githubusercontent.com/8394554/37261224-e15edfae-2568-11e8-91ee-1b81fbe279c7.jpg)

- [x] I'm fairly confident this issue is not a _duplicate_ of any other currently open issues.
- Language Extensions: .pcss
- More info:

I installed the [postcss language syntax extension](https://marketplace.visualstudio.com/items?itemName=ricard.PostCSS) and am wondering why the PostCSS icon isn't showing up in the Exlorer pane.

Disclaimer: New to VS Code, so I hope I'm not missing something obvious. 

As you can see from my screenshot, I've attempted to fix the issue by associating .pcss files with 'postcss'. No luck.

Suggestions?

**Comment by JimiC** [comment]
You are not using our icon extension.
Further more, `PostCSS` extension author suggests using 
```
{
  ...
  "files.associations": {
    "*.css": "postcss"
  }
  ...
}
```
to enable support for `.css` files.

Check which file icon theme you are using.

**Comment by megalofauna** [comment]
Well, I have it installed and am using  `.pcss` as my file type extension. But I hadn't "activated" vsicons, yet. Didn't know that was necessary. That was the obvious thing I was missing. Everything is right as rain now.

**Comment by JimiC** [comment]
Upon fresh installation, there is a notification on the low right side of the editor, telling you that you need to `Activate` the extension. Obviously, you missed that, not blaming you.

Glad it works for you now and thanks for using our extension :smile:
