### ISSUE TITLE
[Icon Request] Support for Apache maven

### ISSUE THREAD

**Issue by thiagogarbazza** [vscode-icons/vscode-icons#1508]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `maven`
  - Sample original Icon: ![logo](https://www.veracode.com/sites/default/files/maven-icon.png)
  - Filenames: `pom.xml`, `maven-wrapper.properties`, `maven.config`, `extensions.xml`

- More info: http://maven.apache.org/ and http://maven.apache.org/configure.html

**Comment by JimiC** [comment]
@thiagogarbazza For folder requests please see #650.

**Comment by JimiC** [comment]
@thiagogarbazza I'm going to exclude `maven-wrapper.properties` from the icon association. This file is from a plug-in and should have its own icon. Currently, it's supported via the config icon.
