### ISSUE TITLE
Icons not there on most recent build

### ISSUE THREAD

**Issue by blubberbo** [vscode-icons/vscode-icons#1520]
Since the most recent update of Visual Studio Code, the icons have disappeared (see attached image). 

I am in OSX, Visual Studio Code Version 1.21.1 (1.21.1), vscode-icons version 7.21.0

<img width="270" alt="screen shot 2018-03-18 at 12 11 13 am" src="https://user-images.githubusercontent.com/17286750/37563573-12eeca84-2a41-11e8-95b2-f22062c4092a.png">

**Comment by jens1o** [comment]
Hi,

could you please open the developer tools and report us whether there are any messages?

**Comment by ggvswild** [comment]
i have the same problem..

Here is some messages:

`Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_server.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_node.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_view.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
default_folder_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/default_file.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
8/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:2370 [Embedded Page] [object Object]
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/default_file.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_js.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
default_folder.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
default_folder_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_tools_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/folder_type_view_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_less.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_image.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/folder_type_images_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_audio.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_client_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/folder_type_dist.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/folder_type_vscode.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
/Users/we/.vscode/extensions/robertohuertasm.vscode-icons-7.21.0/icons/file_type_light_js.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_js.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_babel.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
default_folder.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_server.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_node.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_tools.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_style.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_view.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_tools_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
default_folder_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_images.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_audio.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_image.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
file_type_less.svg Failed to load resource: net::ERR_FILE_NOT_FOUND
folder_type_client_opened.svg Failed to load resource: net::ERR_FILE_NOT_FOUND`

**Comment by ggvswild** [comment]
@jens1o

**Comment by JimiC** [comment]
See #1506

**Comment by ggvswild** [comment]
Thx a lot！ @JimiC
