### ISSUE TITLE
[Task] Handle failed updates

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1538]
- [x] I'm sure this issue is not a _duplicate_.

It so happens that in some cases when the extension gets updated and the user does not restart (not reload) the editor, loading the extension again results to misbehavior.

We should add a handler for such cases that will clean up the mess and if needed prompt the user to restart the editor.

**Comment by JimiC** [comment]
@vscode-icons/development I was thinking of creating an integrity check of the icons folder content using [Nodejs crypto](https://nodejs.org/docs/v7.9.0/api/crypto.html). Any other suggestions?

**Comment by JimiC** [comment]
[Here](https://github.com/Microsoft/vscode/blob/010a5e6f780730ec415b532bba58dbc79de0ac48/build/gulpfile.vscode.js#L169) is an example how `vscode` is using the same idea.

**Comment by jens1o** [comment]
Hopefully we will not use `md5`. :/

**Comment by JimiC** [comment]
Why not? We don't need any special cryptography. I believe using `sha` is overkill.

**Comment by jens1o** [comment]
I'm afraid of hash collisions :/

**Comment by JimiC** [comment]
@robertohuertasm Are you OK with this concept?

**Comment by robertohuertasm** [comment]
Yes, no problem.

**Comment by JimiC** [comment]
Good, cause I have done half the coding.

**Comment by JimiC** [comment]
This is going to be covered by [nsri](https://www.npmjs.com/package/nsri) in `v9`. The default hash algorithm is `sha-1` for files and `sha-512` for directories.
