### ISSUE TITLE
Some icons not loading after update

### ISSUE THREAD

**Issue by KetillG** [vscode-icons/vscode-icons#1541]
- [x] I'm sure this issue is not a _duplicate_.

I opened VS Code this morning and got a notification that VS Code icons had been updated (v. 7.22.0). But now some icons aren't showing up. Here is are images showing the problem.

![image](https://user-images.githubusercontent.com/18271523/37798763-9e1dc6d2-2e15-11e8-95bf-5dae514a5345.png)
![image](https://user-images.githubusercontent.com/18271523/37798822-c6ffbc18-2e15-11e8-8f25-0ddb02df76e3.png)

I have tried restarting/reloading VS code and un/re installing VS Code icons.

**Comment by robertohuertasm** [comment]
Check [this](https://github.com/vscode-icons/vscode-icons/issues/1506#issuecomment-372248210) out

**Comment by KetillG** [comment]
Not sure how I didn't find this when I searched but that works. Thanks.
