### ISSUE TITLE
Shopify Liquid Icon

### ISSUE THREAD

**Issue by dmitrywebtalent** [vscode-icons/vscode-icons#1543]
I don't like current shopify liquid icon. 
Can you change it to the original shopify icon?

**Comment by jens1o** [comment]
Please understand that we do not handle multiple topics in one issue. So, please split your question issue into a new one.

--
Could you please elaborate and give us a link to the original icon?

Afaik, we do not support "shopify liquid icon" yet.

**Comment by dmitrywebtalent** [comment]
This looks good. https://ageverify.co/wp-content/uploads/2015/03/shopify.png

**Comment by jens1o** [comment]
We do not support it yet? Are you sure you're using vscode-icons and not the built in theme? When true, please use the issue template.

**Comment by JimiC** [comment]
He means the `liquid` icon. Can always use the Icons Customization feature.

**Comment by JimiC** [comment]
According to <https://www.shopify.com/partners/blog/115244038-an-overview-of-liquid-shopifys-templating-language> we are using the official logo of the language.

**Comment by dmitrywebtalent** [comment]
This is current supported liquid icon by vs-code icon theme. It's too dark.
![vs-code](https://user-images.githubusercontent.com/25903755/37864942-5eb81672-2fb0-11e8-9832-54d292c169a4.png)

I like all the other icons but don't like this liquid icon. So I suggest to change it to original vs code icon like below.
![original-icon](https://user-images.githubusercontent.com/25903755/37864930-21972aee-2fb0-11e8-8e98-0d1db0865de1.png)

**Comment by robertohuertasm** [comment]
@dmitrywebtalent, thanks for your request but we normally stick to the official logo. Being the case that `Liquid` was developed by `Shopify` doesn't mean that we have to use its logo. You can see [here](https://github.com/Shopify/liquid/wiki#who-uses-liquid) that are many other companies using `Liquid`.

Besides that, the extension provides a way to provide your own icons if you wish to change some of them. Just take the a look at the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/Custom)

**Comment by dmitrywebtalent** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/Custom
This wiki is not enough to get an idea.

file_type_<value_of_icon_property>.svg
Please share examples.

**Comment by jens1o** [comment]
The question has been seperated in #1544
