### ISSUE TITLE
Icon Customization

### ISSUE THREAD

**Issue by dmitrywebtalent** [vscode-icons/vscode-icons#1544]
https://github.com/vscode-icons/vscode-icons/wiki/Custom
This wiki is not enough to get an idea.

file_type_<value_of_icon_property>.svg
Please share examples.

**Comment by jens1o** [comment]
It's just the name of the icon, eg. `file_type_php.svg`. See https://github.com/vscode-icons/vscode-icons/tree/431966938662cdf4997387ae5d8b5268a75062db/icons

**Comment by robertohuertasm** [comment]
@dmitrywebtalent did you manage to make it work?

**Comment by robertohuertasm** [comment]
@dmitrywebtalent any feedback on this matter? If not the issue will be closed.
