### ISSUE TITLE
[Suggestion] Inverted-color icons

### ISSUE THREAD

**Issue by filleduchaos** [vscode-icons/vscode-icons#1553]
- [x] I'm sure this issue is not a _duplicate_.

This is specifically about the Crystal icon, although I think it extends to all black/almost-black icons.

The Crystal icon is literally impossible to see on High Contrast (my preferred theme, due to a visual impairment). It would be nice if there was a way to invert the color of an icon (or if there was a light version of the Crystal icon)

In the meantime, how would I go about changing the icon for dark themes only? The wiki is a bit impenetrable :(

Screenshot:
<img width="209" alt="screenshot 2018-04-11 12 55 09" src="https://user-images.githubusercontent.com/29291843/38615267-f3742078-3d87-11e8-9008-4c480359f867.png">

**Comment by jens1o** [comment]
This seems like a bug to me.
cc @JimiC

**Comment by JimiC** [comment]
Indeed I should have made a dark version icon. As soon as find some time I'll provide one.

Regarding the API you have a point. We haven't documented the `supported` object  properly. We'll see about adjusting that.

**Comment by filleduchaos** [comment]
Thanks @JimiC @jens1o :)
