### ISSUE TITLE
[Icon Request] Support for Maya

### ISSUE THREAD

**Issue by elpie89** [vscode-icons/vscode-icons#1564]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `maya`
  - Sample original Icon: [mel](https://gigahax.com/images/post-thumbnail-autodesk-maya.png?v=20180420)
  - Extensions: `mel`

**Comment by JimiC** [comment]
@elpie89 Please read https://github.com/vscode-icons/vscode-icons/wiki/Issue and adjust the issue accordingly.
