### ISSUE TITLE
Custom Icon and add / replacing existing icons 

### ISSUE THREAD

**Issue by SheepDomination** [vscode-icons/vscode-icons#1565]
How do I add my own custom icon and what are the requirements for a custom icon ? 

As well how do I change an icon, is it a simple as overwriting, if so; is there an option to add a second icon of similar name to choose between multiple icons of the same extension ?

**Comment by JimiC** [comment]
Please read:
- https://github.com/vscode-icons/vscode-icons/wiki/FineTuning
- https://github.com/vscode-icons/vscode-icons/wiki/Custom

**Comment by SheepDomination** [comment]
Visual Studio Code isn't located within the path specified for Windows on this page, atleast not in my case ?
- https://github.com/vscode-icons/vscode-icons/wiki/Custom

**Comment by robertohuertasm** [comment]
@SheepDomination is it a normal installation or you've got it installed by other means? That path is the normal installation for all users. Open a cmd and try this: ` where code`. You should get the path to your VSCode installation.

**Comment by JimiC** [comment]
`.vscode` is the folder where the extensions reside. Search for a folder named `Code` and post back the address, so we can help you further.

**Comment by SheepDomination** [comment]
I found the folder 👍 
What is meant by `Files: file_type_<value_of_icon_property>.svg` does it mean the icon size must be placed within the icon file name ?

**Comment by JimiC** [comment]
`<value_of_icon_property>` reflects the value you have given to then icon property in the declaration.
For example in `{ "icon": "js", "extensions": ["myExt1", "myExt2.custom.js"], "format": "svg" }` **js** is the value, so the file has to be named `file_type_js.svg`.

**Comment by SheepDomination** [comment]
Which declaration ?

**Comment by robertohuertasm** [comment]
@SheepDomination, you'll find the info [here for files](https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts) and [here for folders](https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedFolders.ts)

**Comment by SheepDomination** [comment]
@robertohuertasm If the icon is an 'ai' icon then the file must be named 'file_type_ai.svg' or 'FileFormat_ai.svg'  if it's a folder ?

**Comment by robertohuertasm** [comment]
@SheepDomination, `file_type_ai.svg` in case it's a file or `folder_type_ai.svg` & `folder_type_ai_opened.svg` if we're dealing with a folder.

Note that after adding your icons you will have to provide your custom manifest. See https://github.com/vscode-icons/vscode-icons/wiki/FineTuning to see what's your case.

**Comment by robertohuertasm** [comment]
@SheepDomination, did you manage to make it work?

**Comment by robertohuertasm** [comment]
@SheepDomination any feedback? If not we´ll proceed to close this thread.

**Comment by Traineratwot** [comment]
Hi, I am developing an extension for vsCode [stationeers-ic10](https://marketplace.visualstudio.com/items?itemName=Traineratwot.stationeers-ic10&ssr=false#overview) 
and I want to add an icon to my file extension. **Is there a possibility of integration?**

**Comment by fgclue** [comment]
but, what's the name of the file where you put the ICONS???
