### ISSUE TITLE
[Icon Request] Support for helm template

### ISSUE THREAD

**Issue by afeblot** [vscode-icons/vscode-icons#1569]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id`
  - Icon Name: `helm_template`
  - Sample original Icon: ![helm](https://www.helm.sh/assets/images/helm-logo.svg)
  - Language ids: `helm-template`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=technosophos.vscode-helm
- More info: https://docs.helm.sh/chart_template_guide/#the-chart-template-developer-s-guide

**Comment by JimiC** [comment]
Please read https://github.com/vscode-icons/vscode-icons/wiki/Issue

**Comment by JimiC** [comment]
@afeblot Much appreciated.
