### ISSUE TITLE
vsicons.presets.angular: false setting isn't working

### ISSUE THREAD

**Issue by kspearrin** [vscode-icons/vscode-icons#1575]
- [x] I'm sure this issue is not a _duplicate_. - Not 100% sure, but searched and didn't see anything.

- Language Extensions: `.ts`
- More info: 

I like the Angular icons, but the detection is picking up files that are not Angular related, so I am not trying to disable the feature altogether. I have `"vsicons.presets.angular": false` set in my user settings file, but it is still showing Angular related icons. Workspace and folder settings do not have any overrides in them for vsicons. I've restarted since changing the setting, but it didn't seem to help.

![image](https://user-images.githubusercontent.com/1190944/39825797-c19b6ad4-5380-11e8-8601-8db7357f6b7f.png)

![image](https://user-images.githubusercontent.com/1190944/39825814-cdd2badc-5380-11e8-963f-b1d53ab503cc.png)

**Comment by JimiC** [comment]
Quoted from https://github.com/vscode-icons/vscode-icons/wiki/Presets
>It's also important to say that if you choose to make a manual modification you will have to execute the Apply Icons Customization command (see below).

**Comment by kspearrin** [comment]
That did the trick. Thanks.

**Comment by didii** [comment]
This still seems to be an issue. Executing the command "Apply Icons Customization" works, but only for the current session. When restarting VSCode the setting is not honored and I'll have to execute the command again (without changing any setting).
Note that it takes some time to actually enable the Angular icons, so it probably detects it's an Angular project, then applies the icons without first checking the setting.

Also, the `vsicons.presets.angular` has as default value `false` when I think it should be `true` (or the setting should be inverted to `vsicons.presets.disableAngular`). This also might be the issue that some of the code thinks the default setting is `true`.
