### ISSUE TITLE
[Icon Request] Support for plist

### ISSUE THREAD

**Issue by kspearrin** [vscode-icons/vscode-icons#1576]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `plist`
  - Sample original Icon: X Code uses a generic file icon with a 4 cell "grid" on it. Example: ![screen shot 2018-05-09 at 4 49 27 pm](https://user-images.githubusercontent.com/1190944/39839119-2ac45458-53a9-11e8-9730-d1cf9c7ad4af.png)
  - Extensions: `.plist`

- More info:
Property list file (basically a manifest) from Apple. Commonly used in iOS apps, macOS apps, Safari extensions, etc. It's just an XML file with a `.plist` extension. Example: https://github.com/bitwarden/browser/blob/master/src/safari/Info.plist

**Comment by JimiC** [comment]
@vscode-icons/development I believe this could be associated to the [config](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles) icon. Thoughts?

**Comment by jens1o** [comment]
Yeah, good idea.

**Comment by JimiC** [comment]
@robertohuertasm Your opinion?

**Comment by robertohuertasm** [comment]
I left a +1 reaction so I'm OK with it. :wink:

**Comment by JimiC** [comment]
Apologies. Totally slipped me by.

**Comment by robertohuertasm** [comment]
Oh, no problem at all! I would have probably miss it myself!
