### ISSUE TITLE
[Icon Request] Support for Meson

### ISSUE THREAD

**Issue by ZanderBrown** [vscode-icons/vscode-icons#1578]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `meson`
  - Sample original Icon: [logo](https://github.com/mesonbuild/meson/blob/master/graphics/meson_logo.svg)
  - Language ids: `meson`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=asabil.meson
- More info: [Meson](http://mesonbuild.com/) is an increasingly popular build chain.

**Comment by JimiC** [comment]
Please separate the issues and follow https://github.com/vscode-icons/vscode-icons/wiki/Issue.

**Comment by ZanderBrown** [comment]
#1579 opened

**Comment by JimiC** [comment]
Yet you missed reading how to properly fill an issue.

**Comment by ZanderBrown** [comment]
> Yet you missed reading how to properly fill an issue.

You may need to be more specific, I've read that document twice now and i don't believe i've missed anything

**Comment by JimiC** [comment]
First of all, there are 3rd party extensions that support `Meson` (https://marketplace.visualstudio.com/search?term=meson&target=VSCode&category=All%20categories&sortBy=Relevance).
You should have filled the issue depending on that.

**Comment by JimiC** [comment]
If you believe we ask too much just let the OP as is and we will adjust it.
