### ISSUE TITLE
[Icon Request] Support for Nuxt.js

### ISSUE THREAD

**Issue by dojineko** [vscode-icons/vscode-icons#1581]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `nuxt`
  - Sample original Icon: ![logo](https://avatars2.githubusercontent.com/u/23360933?s=200&v=4)
  - Filenames: `nuxt.config.js` (if possible `nuxt.config.ts`, or should i use [fine tuning?](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning))

- More info: https://nuxtjs.org/

**Comment by JimiC** [comment]
SVG logo @ https://seeklogo.com/vector-logo/328204/nuxt
