### ISSUE TITLE
[Task] Support Jenkins via languageId

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1605]
`jenkinsfile` should be supported via the `languageId` from the following extensions:

 - https://marketplace.visualstudio.com/items?itemName=secanis.jenkinsfile-support
- https://marketplace.visualstudio.com/items?itemName=jmMeessen.jenkins-declarative-support

**Comment by otorrillas** [comment]
Can I pick this up and raise a PR to complete it, @JimiC ? Thanks

**Comment by JimiC** [comment]
If you think you can do it, why not. Your PR was partially incomplete, so I assumed that you had a hard time figuring out how to properly implement this.
