### ISSUE TITLE
Update icon of AL language

### ISSUE THREAD

**Issue by ajkauffmann** [vscode-icons/vscode-icons#1606]
Icon of AL language has changed over time, please update it to the latest version.

- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `al`
  - Sample original Icon: 
![image](https://user-images.githubusercontent.com/19155831/40709476-6de3d8f0-63f6-11e8-904e-86c24be9fbc8.png)

  - Extensions: `al`,`dal`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al
- More info: https://github.com/Microsoft/AL

**Comment by JimiC** [comment]
Thanks for the heads up.

**Comment by ajkauffmann** [comment]
How long does it normally take to update an icon?

**Comment by JimiC** [comment]
Usually 2 weeks. But your request happens to be caught between RL and RL.

**Comment by ajkauffmann** [comment]
Thanks for your quick answer!
Not sure what you mean with RL (sorry for my lack of knowledge of some terms...)
Will it be picked up shortly?

**Comment by JimiC** [comment]
RL = Real Life

**Comment by ajkauffmann** [comment]
Thought as much ;-)

Thanks for looking at it anyway, would love to see it coming. We are now looking at an outdated icon...

**Comment by JimiC** [comment]
Yeah, We know and we are sorry it's taking soooo long to update.
