### ISSUE TITLE
[Icon Request] Add support to Dart files 

### ISSUE THREAD

**Issue by hericlesme** [vscode-icons/vscode-icons#1608]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `dart`
  - Sample original Icon: ![logo](https://cdn-images-1.medium.com/fit/c/120/120/1*pnXLk7ddXxZWySDc7s3LOA.png)
  - Extensions: `.dart`

- More info: [dartlang.com](https://www.dartlang.org/)

**Comment by JimiC** [comment]
Already supported. Use language highlighting extension from the marketplace in order for the icon to show.
