### ISSUE TITLE
[Task] Install Travis-CI from GitHub Marketplace

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1610]
Switch from using `Travis-CI` as a [service](https://github.com/vscode-icons/vscode-icons/settings/installations) to the available GitHub App from the [GitHub Marketplace](https://github.com/marketplace/travis-ci).

**Comment by robertohuertasm** [comment]
I have installed the app but it seems that the migration process is automatic and we'll get a notification once it's done.

**Comment by JimiC** [comment]
Better to be ready.
