### ISSUE TITLE
Examples folder

### ISSUE THREAD

**Issue by mpodciwinski** [vscode-icons/vscode-icons#1612]
Can You add or public link to all examples files and folder icon?

I want to make some modifications in the icons so that they show pixel perfect. But I'm not especially technical and I can not generate them using the "examples-generator". When I'm finished, I'll share them later.
Thanks!

**Comment by JimiC** [comment]
The majority of our icons are in `SVG` format. I don't think they need any modification.
Care to explain what drives you to want to do that?

**Comment by mpodciwinski** [comment]
I agrees, they are in svg. But they do not display exactly in vscode.
#### See this example:
this is actual icon
![zrzut ekranu 2018-06-01 o 14 43 19](https://user-images.githubusercontent.com/39386011/40841682-97373790-65ab-11e8-8629-83ef4b79da7e.png)

and this is icon after modification to pixel perfect:
![zrzut ekranu 2018-06-01 o 14 50 46](https://user-images.githubusercontent.com/39386011/40841720-b45eaf7e-65ab-11e8-87b1-8479f9f8e979.png)

This is actual icon in zoom:
![zrzut ekranu 2018-06-01 o 15 02 06](https://user-images.githubusercontent.com/39386011/40842076-f20d57b6-65ac-11e8-9e8f-0722e27f8e72.png)

you see the half pixels around?
this is ugly :)

And This is pixel perfect:
![zrzut ekranu 2018-06-01 o 15 05 37](https://user-images.githubusercontent.com/39386011/40842189-554fc408-65ad-11e8-8a4a-a9675030b6e7.png)

do you see the difference?

I want to do it because it stings my eyes.
i Hope you undertand.

**Comment by JimiC** [comment]
How do you practice the zooming? You know `vscode` has zoom in/out capabilities (Ctrl +/- or from the `View` menu). Having pixel perfect icons when zooming was the cause we switched to `SVG`.

**Comment by mpodciwinski** [comment]
If i zooming in vscode half pixel still exist. This is not solve the problem beacause icon they were not prepared with the rules of pp.

**Comment by JimiC** [comment]
This is how the icons are displayed in full zoom. I really don't understand your issue. Obviously I'm missing something you fail to explain to me.

![image](https://user-images.githubusercontent.com/1716442/40843928-44eb6f64-65bb-11e8-8b91-ee430bf604cc.png)

**Comment by JimiC** [comment]
@mpodciwinski It would be best if you provide us with replication steps so we can fully understand the issue you are experiencing.

**Comment by mpodciwinski** [comment]
There is good overview: https://www.youtube.com/watch?v=KYpVtDj-xQs
Pixel Perfect essentials include : Sharp edges, perfect alignment and spacing between elements. I this method they can not perform half pixel. And i don't see this in several vscode-icons. it is difficult to explain how someone can not see it.
Did you help me with this and upload examples folder?

**Comment by JimiC** [comment]
All icons are listed in the wiki. But still I would appreciate if you provide reproduction steps. I hate for you to make any effort that we will not accept at the end.

**Comment by JimiC** [comment]
@mpodciwinski After finding some time to watch the video you linked and loading up some of our icons on `Ai`, following the guides from the video, I finally understood what you were talking about.

As the unofficial "art director" of this project, I'm OK with your suggestion to adjust the icons to pixel perfect. I have opened #1613 to track the task.
