### ISSUE TITLE
Always notification is displayed when opened non-angular project

### ISSUE THREAD

**Issue by bhaskarmac** [vscode-icons/vscode-icons#1616]
- [X] I'm sure this issue is not a _duplicate_.

Always notification is displayed when opened non-angular project

VSCode Version:
Version 1.23.1
Commit d0182c3
Date 2018-05-10T17:11:38.209Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

OS Version:
Windows 7 Ultimate

Steps to Reproduce:

1. Open any Angular project
2. Now open the non-Angular project folder using "Open recent" from File menu.
3. Observe the notification is displayed as
![restartdialog](https://user-images.githubusercontent.com/4056847/40873510-dfa8f2c4-667e-11e8-8827-bbabac0226e8.PNG)

**Comment by JimiC** [comment]
I can't reproduce following your steps. Are you sure that the `non-Angular` project does not have a `package.json` anywhere in the folder tree that contains `@angular/core` as a dependency?

**Comment by bhaskarmac** [comment]
Hi @JimiC 

Yes, I am sure this `non-Angular` project doesn't have a `package.json`. There is no dependency as `@angular/core`

**Comment by JimiC** [comment]
Can you share on which repo you are seeing this behavior or is it a private one?

**Comment by bhaskarmac** [comment]
It is a just simple project with some `php` and `html, css & js` files

**Comment by JimiC** [comment]
Sorry, but I can't help you any further.

**Comment by robertohuertasm** [comment]
@bhaskarmac, as @JimiC pointed out, this behavior only should be expected in case you have some `package.json` somewhere with an `angular` dependency. Is there any way to have access to your repo to see what's going on? Or maybe could you create one replicating the issue?

If not it will be difficult to try to replicate this. As a drastic solution, try to disable this functionality.

**Comment by Everspace** [comment]
I just had it. 

I'm not sure what went wrong. It seems to happen randomly, since I shuffled a file or two and it stopped alerting me.

**Comment by bhaskarmac** [comment]
@Everspace  Yes same with me, I don't have any proper steps to reproduce the bug

**Comment by JimiC** [comment]
Closing as stale. If you believe that it should not be close then please re-open the issue.
