### ISSUE TITLE
Official icon presets are not working

### ISSUE THREAD

**Issue by zalishchuk** [vscode-icons/vscode-icons#1637]
- [x] I'm sure this issue is not a _duplicate_.

- More info:

`jsOfficial` and `jsonOfficial` presets (neither `true` nor `false` value) are not working for me after after upgrade to `v7.24.0`.

```json
{
  "vsicons.presets.jsOfficial": true,
  "vsicons.presets.jsonOfficial": true
}
```

![image](https://user-images.githubusercontent.com/2690794/41747882-3d85be70-75b8-11e8-902e-d3af3405500b.png)

**Comment by zalishchuk** [comment]
Ok, it changed after I switched workspace, but didn't work after reloading.

**Comment by JimiC** [comment]
This is a limitation of the way we can reload custom icon configuration.
You see, after an update, you need to `Reload` the editor for the new version to get loaded.
After the `Reload` the extension detects the configuration and re-builds a new icon set.
In that step, it's mandatory to reload the editor for the re-build icon set to take effect.
If `vscode` had an API, so we could reload the re-build icon set on the fly, it would solve many issues for us.
