### ISSUE TITLE
[Icon Update] Update Icon for Golang

### ISSUE THREAD

**Issue by Vorror** [vscode-icons/vscode-icons#1638]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `go`
  - Icon Name: ``
  - Sample original Icon: 
![go-logo_blue](https://user-images.githubusercontent.com/3613230/41752586-476b0b24-7596-11e8-95fe-8fd3faa21e8a.png)

  - Extensions: `go`
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
Golang updated their logo : https://blog.golang.org/go-brand
Link to new logo files: https://blog.golang.org/go-brand/Go-Logo/SVG/

**Comment by Vorror** [comment]
To be more specific, Golang had a _mascot_ not a logo(until now). Going forward the logo listed above will be what's used on the official site & marketing material — so vscode-icons should be updated accordingly.

**Comment by drdgvhbh** [comment]
Can there be an option to go back to the old one :(

**Comment by JimiC** [comment]
The old icon is still in our collection. Use the customization feature to enable it. Read all about it in the wiki.
