### ISSUE TITLE
SAS Language icon

### ISSUE THREAD

**Issue by SoleSensei** [vscode-icons/vscode-icons#1639]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions: .sas
- More info:

**Comment by JimiC** [comment]
Unacceptable. Please read https://github.com/vscode-icons/vscode-icons/wiki/Issue.
