### ISSUE TITLE
[Icon Request] Support for Web-Assembly

### ISSUE THREAD

**Issue by Stephan-kashkarov** [vscode-icons/vscode-icons#1641]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id`
  - Icon Name: `wasm`
  - Sample original Icon: 
![wasmlogo](https://webassembly.org/css/webassembly.svg)
  - Language ids: `wasm`

- Language Extensions: https://marketplace.visualstudio.com/search?term=wasm&target=VSCode&category=All%20categories&sortBy=Relevance

- More info: https://webassembly.org/

**Comment by JimiC** [comment]
@Stephan-kashkarov This is how a proper icon request issue should look like.
