### ISSUE TITLE
File/folder icons for code completion

### ISSUE THREAD

**Issue by svipas** [vscode-icons/vscode-icons#1648]
Hi, it's possible somehow to enable file/folder icons for code completion?

How it's right now:

![before](https://user-images.githubusercontent.com/10441177/42449735-7daf2132-838a-11e8-8d04-349d4ab0c005.png)

How it can look like:

![after](https://user-images.githubusercontent.com/10441177/42449749-886e43aa-838a-11e8-99ee-1dbe52db8da2.png)

**Comment by robertohuertasm** [comment]
As far as I know this is not available right now in the VS Code API.

I think you should post this into `VS Code` repository and ask there for the implementation of this feature. It would be awesome!

**Comment by svipben** [comment]
You're right. I already opened an issue https://github.com/Microsoft/vscode/issues/53538

**Comment by octref** [comment]
FYI https://github.com/Microsoft/vscode/issues/44860

**Comment by JimiC** [comment]
This is available now in `vscode`.
