### ISSUE TITLE
This plugin causing an annoying white flash project reload when I open a project

### ISSUE THREAD

**Issue by swilliams-a3digital** [vscode-icons/vscode-icons#1654]
When I open vs code on my macbook a project will load, then 3 seconds later I get an annoying white flash and the projects reloads.  This doesn't happen if I disable the vscode-icons extension.

**Comment by JimiC** [comment]
You have the [Project Auto Detection](https://github.com/vscode-icons/vscode-icons/wiki/Pad) feature enabled and `vscode-icons` is rebuilding the icon manifest file whenever you are switching between Angular and non-Angular projects.

**Comment by swilliams-a3digital** [comment]
Thanks for the tip.
Adding this setting: 

"vsicons.projectDetection.disableDetect": true

stopped the flashing.  I had the auto-restart option on.  With auto-restart on, the flash reload happens everything you switch projects, regardless of switching from angular to non-angular project.  Why does vscode icons need to do something when you switch projects?  The annoying project reload flash outweighs the benefits of the fancy icons.

**Comment by JimiC** [comment]
Support https://github.com/Microsoft/vscode/issues/45963
