### ISSUE TITLE
Icon Request for State-folders

### ISSUE THREAD

**Issue by JohanG2012** [vscode-icons/vscode-icons#1655]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `State folder`
  - Extensions: `none`
  - Filenames: `State (Folder name)`
  - Language ids: `none`

- Language Extensions:
- More info:
I would like an icon for folders named "State" used when working with component libraries who handles state such as React/Redux.

**Comment by JimiC** [comment]
Please see #650
