### ISSUE TITLE
Support for San

### ISSUE THREAD

**Issue by HandsomeHan515** [vscode-icons/vscode-icons#1657]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: ``
  - Icon Name: `san`
  - Sample original Icon: ![logo](https://baidu.github.io/san/img/logo.svg)
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions: san
- More info:

**Comment by robertohuertasm** [comment]
@HandsomeHan515 can you provide more info? url?

**Comment by HandsomeHan515** [comment]
page: https://baidu.github.io/san/
github: https://github.com/baidu/san/

**Comment by HandsomeHan515** [comment]
@robertohuertasm 
page: https://baidu.github.io/san/
github: https://github.com/baidu/san/

**Comment by KingDarBoja** [comment]
I have no idea how to proceed with this logo, there is no info at the website about the extension, so I will just let the svg code here in case you guys want to solve this issue.

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>file_type_san</title><path d="M30,17.832,2,23.28V30l28-5.447ZM30,7.253,2,12.7v6.72l28-5.447Z" style="fill:#295892"/><path d="M30,13.992,2,8.721V2L30,7.271Zm0,10.579L2,19.3V12.58l28,5.27Z" style="fill:#a1e0ff"/></svg>
```

**Note:** It is already "pixel perfect".

**Comment by JimiC** [comment]
@KingDarBoja There is a `vscode` extension for [San](https://github.com/zhanfang/vscode-san/blob/master/package.json#L25). Use that to incorporate the icon. Awaiting PR on this.
