### ISSUE TITLE
[Icon Request] Folder icon for Azure

### ISSUE THREAD

**Issue by nlarzon** [vscode-icons/vscode-icons#1658]
- [ ] I'm sure this issue is not a _duplicate_.
- [ x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `Azure`
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
Great to show Microsoft and Azure some love
https://images.duckduckgo.com/iu/?u=https%3A%2F%2Fmspoweruser.com%2Fwp-content%2Fuploads%2F2017%2F09%2Fazure-1.png&f=1

**Comment by jens1o** [comment]
invalid. See #650

**Comment by nlarzon** [comment]
Thanks sorry for mistake, tricky to find :)
