### ISSUE TITLE
Add icon for .mock.*

### ISSUE THREAD

**Issue by kbradl16** [vscode-icons/vscode-icons#1680]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension `
  - Icon Name: `mock`
  - Sample original Icon: ![logo]()
  - Extensions: `.mock.*`

- More info:

**Comment by JimiC** [comment]
Please provide more info or argument on this request.

**Comment by JimiC** [comment]
Closing due to lack of follow up.

**Comment by bfunc** [comment]
It would be nice to have icon for mocks

**Comment by sasial-dev** [comment]
I'd file a new issue here! As it's 4 years later :)
