### ISSUE TITLE
Support for Ansible file icons

### ISSUE THREAD

**Issue by kylix3511** [vscode-icons/vscode-icons#1681]
- [yes ] I'm sure this issue is not a _duplicate_.
- [yes] I'm submitting an icon request: Ansible
  - Type: `.yaml, .yml`
  - Icon Name: `ansible`
  - Extensions: `.yaml, .yml` 
  - Filenames: `.yaml, .yml` 
  - Language ids: ``

- Language Extensions: `.yaml, .yml` 
- More info:
https://github.com/file-icons/atom/issues/751

 - Sample original Icon: ![tdnf_bcq_400x400](https://user-images.githubusercontent.com/38637223/44164304-83a6c880-a07a-11e8-9e88-a68225815756.png)

**Comment by robertohuertasm** [comment]
Ansible is already supported through language id. See [here](https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L289-L294).

You have to install [some extension providing support for this language](https://marketplace.visualstudio.com/search?term=ansible&target=VSCode&category=All%20categories&sortBy=Relevance).

**Comment by robertohuertasm** [comment]
That's because `.yml` is not an `Ansible` extension. You can associate your `.yml` files with `Ansible` in `VSCode`. Look at your bottom bar in the right and press the `YAML` text. A menu will open and you can there access to file extension association.

**Comment by kylix3511** [comment]
Hi Roberto, 

Then something else wrong in the icons, I can’t see/view the Ansible icons 





In the Atom Editor, i can see it.

**Comment by robertohuertasm** [comment]
Is nothing wrong with the icons. `.yml` is not `.ansible`. If you want to make this kind of association you can, by following the instructions I provided to you 😉
