### ISSUE TITLE
[Icon Request] Support for serverless.yml

### ISSUE THREAD

**Issue by glyphCezilleSantillan** [vscode-icons/vscode-icons#1696]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `serverless.yml`
  - Sample original Icon: ![logo](https://serverless.com/_/src/assets/images/favicon.b90358f37ac017157f26e8bc617e2023.ico)
  - Filenames: `serverless.yml`

- More info: Serverless can be used with multiple languages across multiple platforms; I initially just wanted a general YML icon, but since there are specific ones, I'd like to request one for serverless. :)

**Comment by glyphCezilleSantillan** [comment]
Welp, I spoke too soon. There was a generic YML icon after all. Great work you guys! :D

**Comment by KingDarBoja** [comment]
@JimiC @robertohuertasm 

After a quick look at google: [Serverless Framework](https://serverless.com/)

Based on that, we should research a bit more to provide support based on the framework filenames.
Also, here is the [marketplace extension](https://marketplace.visualstudio.com/items?itemName=frankschmid.serverless-vscode).

Cheers!

**Comment by JimiC** [comment]
We only need to support `serverless.yml` at this point.

**Comment by JimiC** [comment]
The `vscode` extension you linked is not a syntax highlighting one. It has no `language id` defined so it's out of our scope.

**Comment by KingDarBoja** [comment]
Oops! Sorry for that, didn't noticed the link was actually another stuff related to `serverless.yml` instead of syntax highlighting. So anything I can do with this issue?

**Comment by JimiC** [comment]
Just the usual. Should I assign it to you?

**Comment by KingDarBoja** [comment]
@JimiC Yeah, no problem with that :D I will made some issues this weekend including this.
