### ISSUE TITLE
Is there any way to have the folder open/closed triangle a +/- instead?

### ISSUE THREAD

**Issue by danechitoaie** [vscode-icons/vscode-icons#1698]
Is there any way to have the folder open/closed triangle a +/- instead?

I've attached a image to show what I mean.
<img width="232" alt="screen shot 2018-08-30 at 20 31 35" src="https://user-images.githubusercontent.com/10779010/44868568-de077200-ac93-11e8-9a08-5095eb22cfd6.png">

Can those icons be replaced with a `[+]` when folder is closed and a `[-]` when folder is expanded?

**Comment by JimiC** [comment]
I'm afraid not. This is not technically achievable by any extension that sticks to the official API, (without `js` injection that is). You can only hide the `arrow`.

**Comment by cipri-tom** [comment]
so this setting is controlled by VSCode ? If so, do you know what it is named ? Or in which file this is setup? I would be happy to modify it locally in some files
