### ISSUE TITLE
[Icon Request] Support for `.vsts-ci.yml`

### ISSUE THREAD

**Issue by daB0bby** [vscode-icons/vscode-icons#1701]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `vsts-ci`
  - Sample original Icon: ![logo](https://user-images.githubusercontent.com/2941389/41596976-6102b51c-73cc-11e8-89d7-76c99ebea970.png)
  - Extensions: `yml`
  - Filenames: `.vsts-ci`
  - Language ids: `yml`

**Comment by robertohuertasm** [comment]
@daB0bby is this extension still supported now that the service has changed its name to `Azure Devops`?

**Comment by JimiC** [comment]
@robertohuertasm What about those projects that still use this, or is the switch mandatory?

**Comment by robertohuertasm** [comment]
That was precisely my doubt.

By looking at https://docs.microsoft.com/en-us/azure/devops/release-notes/2017/nov-28-vsts, I guess both extensions are valid for the moment, so I think that just adding this filename to the current azure devops icon would suffice.

**Comment by KingDarBoja** [comment]
Gonna need some guidance on how tackle this issue.
