### ISSUE TITLE
Open Folder v.s. Closed Folder shade

### ISSUE THREAD

**Issue by jansenfuller** [vscode-icons/vscode-icons#1702]
- [X] I'm sure this issue is not a _duplicate_.

It looks like the icon for a closed folder and an open fold are not the same kind of brown.

The closed folder color being slightly darker than the open folder icon. Is it possible to change the closed folder icon to match the shade of the open folder icon?

![Different Colored Browns](https://user-images.githubusercontent.com/4349372/44937166-30e53600-ad35-11e8-877b-fc4af377bdd2.png)

**Comment by JimiC** [comment]
This is intentional. You can use the customization feature to assign your own icons.

**Comment by robertohuertasm** [comment]
@jansenfuller, as @JimiC already pointed out this is part of how we use to deal with folder icons. You can take a look [here](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) to learn how to customize the file associations to make your folders look the way you want.
