### ISSUE TITLE
[Icon Request] Support for `tera`

### ISSUE THREAD

**Issue by jens1o** [vscode-icons/vscode-icons#1703]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `tera`
  - Sample original Icon: https://karunamurti.gallerycdn.vsassets.io/extensions/karunamurti/tera/0.0.2/1514878699316/Microsoft.VisualStudio.Services.Icons.Default
  - Extensions: `.tera`
  - Language ids: `tera`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=karunamurti.tera
- More info: https://tera.netlify.com/

**Comment by jens1o** [comment]
Sorry, I missed

**Comment by KingDarBoja** [comment]
@jens1o If this icon is still wanted, I can do the svg version based on the font used at #1854 one, which is called "SegoeUI" (after checking the DOM at their website).
