### ISSUE TITLE
[Icon Request] Support for `dotjs`

### ISSUE THREAD

**Issue by Xiongqi-XQ** [vscode-icons/vscode-icons#1707]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language id`
  - Icon Name: `dotjs`
  - Sample original Icon: ![logo](http://olado.github.io/doT/doT-js-100@2x.png)
  - Extensions: `.dot`
  - Language ids: `dotjs`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=allentong.dotjs
- More info: 
-- [dotjs](http://olado.github.io/doT/index.html)
-- There is a .dot icon which is the word type <img width=50 src="https://github.com/vscode-icons/vscode-icons/raw/master/icons/file_type_word.svg?sanitize=true" alt="word_dark"> And the dotjs file will use this icon too. It's wrong. Hope for fix this, thanks.

**Comment by KingDarBoja** [comment]
Not sure if worth adding since both the project along with the language extension are already inactive @JimiC

**Comment by JimiC** [comment]
I say it's worth.
