### ISSUE TITLE
Please provide some actual examples...

### ISSUE THREAD

**Issue by chilidad** [vscode-icons/vscode-icons#1711]
- [x] I'm sure this issue is not a _duplicate_.

Would you please provide some actual examples of how to use the "vsicons.associations.files" including actual full  path names and file names? I'm especially interested in "Changing the icon to an already supported icon," and "Adding a new extension." I've followed all of your symbolic examples, but I can't get any of them to work.  I've tried many ways to follow your naming conventions, but I must keep missing something. 

For example, in your instruction...
**_if you have declared a new icon like:_**
_**{ "icon": "my-awesome-icon", "extensions": ["mai"], "format": "svg" }
then for file icons the filename of the icon must be file_type_mai.svg**_
...it is too hard to decipher without a real example. And what does "declared a new icon" mean? Must I define an icon name in some file?

In my case, I tried using...
**_"vsicons.customIconFolderPath": "C:\\TEMPLATES (Local)\\CODING\\VSC-Themes",
"vsicons.associations.files": [
  { "icon": "C:\\TEMPLATES (Local)\\CODING\\VSC-Themes\\vsicons-custom-icons\\file_type_vb.png", "extensions": ["vbs"], "format": "png", "overrides": "vbs" }
],_**
...but it did not work. I also tried a dozen other versions of this code with no success.

Also, a possible bug (or clarification needed)...
If I make a custom change like switching the icon of .vb to that of java like...
**_"vsicons.associations.files": [
  { "icon": "java", "extensions": ["vbs"], "format": "svg", "overrides": "vbs" }
],_**
...and then hit F1 --> Icons: Apply Customization, VSC restarts, but nothing changes. I must hit "save" first, before it all works as intended. Saving first should be obvious, but it wasn't intuitive because I thought the "Icons: Apply..." automatically saved the file. 

Thankyou for your time.

**Comment by JimiC** [comment]
```
"vsicons.customIconFolderPath": "C:\TEMPLATES (Local)\CODING\VSC-Themes",
"vsicons.associations.files": [
{ "icon": "vb", "extensions": ["vbs"], "format": "png", "overrides": "vbs" }
],
```
Save. 
Hit F1 --> Icons: Apply Customization
Profit???

**Comment by JimiC** [comment]
I also corrected the wiki as you are right that the filenames were not reflected correctly.

**Comment by chilidad** [comment]
Jimi,


Since your wiki suggests svg as the preferred icon type, I converted my custom vb icon to svg. However, your suggested format only produced vsicon's default image for vb;  formatted as follows...

"vsicons.customIconFolderPath": "C:\TEMPLATES (Local)\CODING\VSC-Themes",
"vsicons.associations.files": [
{ "icon": "vb", "extensions": ["vbs"], "format": "svg", "overrides": "vbs" }
],

But, when I changed the name to file_type_vbR1.svg then it worked...

"vsicons.customIconFolderPath": "C:\\TEMPLATES (Local)\\CODING\\VSC-Themes\\",
"vsicons.associations.files": [
  { "icon": "vbR1", "extensions": ["vbs"], "format": "svg", "overrides": "vbs" }
],


Although I now understand your naming convention, you may still want to clarify the wiki with something like
...your filename must have the exact wording "file_type_" as a prefix.
I recommend this because, as a typical curious coder trying to figure out what I didn't know, I searched through vsicon's json files revealing
a naming convention following  JavaFile_16x.svg. So at first, I logically thought "file_" meant icon name and "type_" meant "16x" or
something.

Otherwise, thankyou for such a prompt reply and wiki fix 😎


-Chris


________________________________

**Comment by JimiC** [comment]
Probably because we don't a `vbs` icons. If you want to override the `vb` icon, then the declaration has to be:
```
"vsicons.customIconFolderPath": "C:\\TEMPLATES (Local)\\CODING\\VSC-Themes\\",
"vsicons.associations.files": [
  { "icon": "vb", "extensions": ["vbs"], "format": "svg", "overrides": "vb" }
],
```

You can use a `png` icon but it will not scale nicely when you zoom in/out.

**Comment by chilidad** [comment]
You do have one, it's file_type_vb.svg.

FWIW, here's the one I made...


________________________________

**Comment by JimiC** [comment]
Closing as stale. If you believe that it should not be close then please re-open the issue.
