### ISSUE TITLE
Files associations not being loaded on VSCode v1.27.1

### ISSUE THREAD

**Issue by lerran80** [vscode-icons/vscode-icons#1712]
- [x] I'm sure this issue is not a _duplicate_.
The configuration bellow was working properly before VSCode updated to v1.27.1:
```
"vsicons.associations.files": [
        {
            "icon": "source",
            "extensions": [
                ".step"
            ],
        },
        {
            "icon": "xml",
            "extensions": [
                ".page"
            ],
        },
        {
            "icon": "xsl",
            "extensions": [
                ".list"
            ]
        }
    ]
```
After the update, all these extensions use the `yaml` icon. Probably because of this config, that was already there before the update:
```
    "files.associations": {
        "*.step": "yaml",
        "*.page": "yaml",
        "*.list": "yaml"
    }
```
All vsicons settings are in user settings. Moving all of them to workspace does not change this behavior. I tested to be sure it had nothing to do with: https://github.com/vscode-icons/vscode-icons/issues/1686

**Comment by JimiC** [comment]
Have you tried `F1 -> Apply Icons Customization`?

**Comment by JimiC** [comment]
I just run a quick check and everything works as expected. Upon a new extension update, the icon manifest gets reset. When `vscode` got reloaded, you missed the message where we ask you to hit `Restart` to regenerate the icons manifest with your customizations (probably cause `vscode` showed you too many messages and you discarded them).

In those cases `F1 -> Apply Icons Customization` always restores the order.

**Comment by lerran80** [comment]
Hi, I haven't discarded any messages without reading when VSCode updated, but the message asking to `Restart` and regenerate the icons manifest appeared just now, and it worked. Thanks!
