### ISSUE TITLE
.bazel.rc and .bazel support

### ISSUE THREAD

**Issue by wayou** [vscode-icons/vscode-icons#1713]
[bazel](https://bazel.build/) files are already supported but `.bazel.rc` and `bazel.rc` are missing.

**Comment by JimiC** [comment]
Maybe this issue be better passed to the [bazel-code  extension](https://github.com/devoncarew/bazel-code) author?

/cc @devoncarew

**Comment by robertohuertasm** [comment]
@wayou I think it's ok to warn the authors of the extension. Nevertheless, for the moment,, I think it's ok to add this to our extension.

**Comment by wayou** [comment]
so, should i open an issue to that repo?

**Comment by robertohuertasm** [comment]
If you don't mind I think it would be great. Ideally, language extensions should expose all the possible extensions and filenames. Maybe there's a reason for that extension not providing these filenames.
