### ISSUE TITLE
[Icon Request] Folder icon for "blueprints"

### ISSUE THREAD

**Issue by muuvmuuv** [vscode-icons/vscode-icons#1719]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `blueprint`
  - Sample original Icon: ![Sample](http://icons.iconarchive.com/icons/artbees/bee-customized/256/Blueprint-Simple-icon.png)
  - Names `blueprints`, `blueprint`, `BP`

**Comment by JimiC** [comment]
Please see #650
