### ISSUE TITLE
HideFolders preset ignored

### ISSUE THREAD

**Issue by pcjmfranken** [vscode-icons/vscode-icons#1726]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

Since v7.27.0 `"vsicons.presets.hideFolders": true` seems to no longer work as I see custom folder icons again.

**Comment by robertohuertasm** [comment]
What OS are you using? Insiders or Stable version?

**Comment by pcjmfranken** [comment]
Thanks for your reply.

I'm running Windows 10 and VSCode stable version. Issue is reproducible on another system with the same configuration.

**Comment by robertohuertasm** [comment]
@pcjmfranken can you tell me exactly what you do? I can't reproduce it in a Windows 10 Stable. It seems to be working. Do you see the notification telling you that you should restart in order for the changes to take effect? If not, try `F1 > Icons: Apply Icons customization` 

Let me know if it works.

**Comment by pcjmfranken** [comment]
That did the trick on both systems, thanks!

It did tell me to restart to regenerate the manifest immediately after the extension was updated, which I did. I now do recall having two VSCode windows open at the time though, that may have caused the issue.
