### ISSUE TITLE
Extend "route" and "routes" icon to "router" folder as well

### ISSUE THREAD

**Issue by rhernandog** [vscode-icons/vscode-icons#1729]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
Quite simple, is it possible to use the `route` and `routes` icon on a folder named `router`? I'd like to have it extended to use that name as well.

Thanks!!

**Comment by JimiC** [comment]
Please see #650
