### ISSUE TITLE
[Icon Request] Support for .huskyrc

### ISSUE THREAD

**Issue by capaj** [vscode-icons/vscode-icons#1731]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `husky config`
  - Sample original Icon: this github :dog: icon is what husky uses
  - Filenames: `.huskyrc, husky.config.js, .huskyrc.json, or .huskyrc.y[a]ml`

- More info:

**Comment by JimiC** [comment]
Please provide a link to documentation or repo.

**Comment by capaj** [comment]
repo: https://github.com/typicode/husky

PR regarding the new file config: https://github.com/typicode/husky/pull/209

**Comment by KingDarBoja** [comment]
Since there isn't a official icon besides the github dog ( 🐶 ), I think we can use this one: [icon example](https://github.com/PKief/vscode-material-icon-theme/issues/355)

**Comment by JimiC** [comment]
I asked @Alhadis if we can use the [husky](https://github.com/file-icons/source/blob/0d7ec2caccbb81079a918cf180ffe38e2db4d2ff/svg/Husky.svg) icon. Lets's see what the verdict will be.

**Comment by Alhadis** [comment]
Take everything you want. :wink:

**Comment by JimiC** [comment]
@Alhadis Thanks a lot.
