### ISSUE TITLE
dosent work

### ISSUE THREAD

**Issue by hilmidnmz0** [vscode-icons/vscode-icons#1740]
- Extension Name: vscode-icons
- Extension Version: 7.27.0
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.28.0-insider

 We have written the needed data into your clipboard. Please paste:

**Comment by jens1o** [comment]
Please provide more information. :)

**Comment by JimiC** [comment]
Maybe [this](https://github.com/vscode-icons/vscode-icons#usage) can help you.
