### ISSUE TITLE
extension problem

### ISSUE THREAD

**Issue by EvyiLdaRkmaN** [vscode-icons/vscode-icons#1743]
- Extension Name: vscode-icons
- Extension Version: 7.27.0
- OS Version: Windows_NT x64 10.0.17134
- VSCode version: 1.28.0

```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 162,
		"activateCallTime": 6,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by JimiC** [comment]
What am I supposed to understand from that?

**Comment by JimiC** [comment]
@vscode-icons/development Turns out that the user is reporting [Performance issues](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions).

My tests show:

> - Extension Name: vscode-icons
> - Extension Version: 7.27.0
> - OS Version: Linux x64 4.15.0-1023-azure
> - VSCode version: 1.28.0
> 
> ```json 
> {
> 	"activationTimes": {
> 		"startup": true,
> 		"codeLoadingTime": 67,
> 		"activateCallTime": 1,
> 		"activateResolvedTime": 0,
> 		"activationEvent": "*"
> 	}
> }
> ```

**Comment by JimiC** [comment]
The average startup times are:
- Linux: 80ms
- Windows: 130ms

They are not so bad.

**Comment by JimiC** [comment]
I believe those times can be further improved by switching to async I/O, but this requires we merge `v8` first.

**Comment by JimiC** [comment]
I'm closing this as there isn't much we can do for now.
