### ISSUE TITLE
Extension Host is unresponsive

### ISSUE THREAD

**Issue by jiharal** [vscode-icons/vscode-icons#1748]
- Extension Name: vscode-icons
- Extension Version: 7.27.0
- OS Version: Darwin x64 18.0.0
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:
![image](https://user-images.githubusercontent.com/21150538/46731646-d2a95c80-ccbd-11e8-978f-52f3f09bf57c.png)

**Comment by JimiC** [comment]
Please read https://code.visualstudio.com/updates/v1_28#_extension-host-unresponsive
