### ISSUE TITLE
实打实地方

### ISSUE THREAD

**Issue by sunzhongt** [vscode-icons/vscode-icons#1750]
- Extension Name: vscode-icons
- Extension Version: 7.27.0
- OS Version: Windows_NT x64 6.1.7601
- VSCode version: 1.28.0

 We have written the needed data into your clipboard. Please paste:

**Comment by sunzhongt** [comment]
速度发顺丰

**Comment by robertohuertasm** [comment]
Please, could you use English?

**Comment by JimiC** [comment]
This another performance issue (sick and tired of it). Please do a search before posting.
