### ISSUE TITLE
No default folder icons after syncing settings with code-settings-sync plugin

### ISSUE THREAD

**Issue by AlexanderDerck** [vscode-icons/vscode-icons#1752]
- [x] I'm sure this issue is not a _duplicate_.

After restoring my settings with the [vscode sync settings plugin](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync), my folder icons weren't the default ones. The setting was correctly applied in my `settings.json` file but I still saw custom icons. I resolved it by setting it to false -> restart vscode -> set it to true -> restart vscode as described in [this thread](https://github.com/vscode-icons/vscode-icons/issues/1562#issuecomment-388784048).

**Comment by JimiC** [comment]
It's clearly stated in the wiki that any change to the settings requires the regeneration of the icons manifest via `F1 > Apply Icons Customization` and the restart of the editor.
