### ISSUE TITLE
Markdown icon is very hard to see

### ISSUE THREAD

**Issue by Dan503** [vscode-icons/vscode-icons#1753]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request.

The default icon used for markdown files is very difficult to see when using a dark theme in VS Code. It should be a much lighter color so that it contrasts strongly against the background color.

![VS Code extension mark down icon](https://user-images.githubusercontent.com/10610368/46902086-aafb0400-cf0a-11e8-8b1d-76015ef950a4.png)

If this issue is unlikely to get fixed, can you please explain to me how I can use the custom file associations feature to set the markdown icon to use the default VS Code markdown icon?

![default VS Code markdown icon](https://user-images.githubusercontent.com/10610368/46902197-b2231180-cf0c-11e8-9285-1123af6bc49b.png)

[The documentation](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) is extremely confusing. 😵

**Comment by robertohuertasm** [comment]
What's exactly you find confusing? Do you want to use a custom icon or substitute it by another of the provided icons?

Let's say you want to change the `md` icon with the `js` icon. As stated in the documentation, you must look into the [supportedFileExtensions file](https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L1657-L1662).

> Note that it's important to know what the current [supported file extensions / icons](https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts) and supported folder extensions / icons are.

Then it's just a matter of substituting the `icon` property and put this into your user settings file:

```json
"vsicons.associations.files": [
        {
            "icon": "js",
            "extensions": ["md", "mdown", "markdown"]
          },
    ]
```
If you want to provide your own icon, just follow this [guide](https://github.com/vscode-icons/vscode-icons/wiki/Custom), You will learn where to put your new icon. Then just do the same thing that we showed previously but use the name of your new icon instead of `js`.

**Comment by Dan503** [comment]
Ah right, I was reading the [FineTuning page](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) of the documentation thinking that it was explaining how to apply my own custom icons and I was getting super confused.

I think I would have been less lost and confused if there was a sentence at the top of the page saying something like "If you would like to use your own custom icons, read the [Custom icons guide](https://github.com/vscode-icons/vscode-icons/wiki/Custom).".

I would still like to see the default markdown icon made brighter but at least I have a work around for the issue now.

**Comment by Dan503** [comment]
The thing that confused me was that the page goes directly into the technical details of how to do stuff but I didn't understand (and still don't really understand) what the stuff that it is explaining is trying to accomplish.

For a user reading that page, what is the likely end goal of that user? What is the user able to do after reading that page that they couldn't do before knowing that information? That was not made clear to me at the start of that page of the documentation.

**Comment by robertohuertasm** [comment]
@Dan503 I've slightly modified the wiki pages according to your feedback. I hope it's a little more clear now. I'd really appreciate more of your feedback if you consider it's still not enough.

Regarding the color of the icon, I normally use a very dark theme and the contrast seems to be enough. Maybe this has to do with the contrast of your monitor... let's see what @vscode-icons/development  think of it before closing this.

**Comment by jens1o** [comment]
For me, the contrast is good enough, but I would not have problems to make it other, so it works better for Daniel.

**Comment by Dan503** [comment]
**Contrast ratio: 2.6:1** (Fails WCAG recommendation)

![mark down icon](https://user-images.githubusercontent.com/10610368/46902086-aafb0400-cf0a-11e8-8b1d-76015ef950a4.png)

**Contrast ratio: 5.3:1** (Passes WCAG contrast for small text)

![md-default-icon](https://user-images.githubusercontent.com/10610368/46902197-b2231180-cf0c-11e8-9285-1123af6bc49b.png)

At least aim for a 3:1 contrast ratio (the minimum WCAG contrast recommendation for icons). A 4.5:1 contrast ratio (The WCAG recommendation for text) would be better though and would be more visible against more dark themes.

You can use this online tool to check color contrast levels: https://webaim.org/resources/contrastchecker/

**Comment by jens1o** [comment]
So shall we make it white/grey, team?

**Comment by JimiC** [comment]
I have a different perspective.

**Comment by JimiC** [comment]
Closing as stale. If you believe that it should not be close then please re-open the issue.
