### ISSUE TITLE
yml has no icon?

### ISSUE THREAD

**Issue by ronag** [vscode-icons/vscode-icons#1755]
![screenshot 2018-10-17 at 10 59 16](https://user-images.githubusercontent.com/3065230/47074942-bd6f8900-d1fb-11e8-8758-b0af362832f8.png)

- [x] I'm sure this issue is not a _duplicate_.

Not sure what's going on here but this looks like the wrong icon?

**Comment by JimiC** [comment]
The icon does not belong to this extension.
