### ISSUE TITLE
[Icon Request] Support for Stata do-files

### ISSUE THREAD

**Issue by devon-ge** [vscode-icons/vscode-icons#1756]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `stata`
  - Sample original Icon: ![logo](https://www.stata.com/favicon-no-number.ico)
  - Extensions: `stata`
  - Filenames: `do`, `ado`
  - Language ids: `stata`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=kylebarron.stata-enhanced
- More info: `.do`  files contain executable commands. A `.ado` file is the source of user-defined command. (Supplement of #1253).

**Comment by JimiC** [comment]
Use https://marketplace.visualstudio.com/items?itemName=mdob2k.stata-language

**Comment by devon-ge** [comment]
@JimiC Thanks!
