### ISSUE TITLE
vscode-icons插件下的php图标非常丑

### ISSUE THREAD

**Issue by linjialiang** [vscode-icons/vscode-icons#1759]
Issue Type: <b>Feature Request</b>

vscode-icons插件下的php图标非常丑，能不能调整下

Extension version: 7.27.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.17134

**Comment by JimiC** [comment]
English please and follow the [guidelines](https://github.com/vscode-icons/vscode-icons/wiki/Issue)

**Comment by linjialiang** [comment]
@JimiC  `The PHP icon under the vscode-icons plug-in is very ugly, can it be adjusted`

**Comment by robertohuertasm** [comment]
@linjialiang we use the official icons when possible. If you're not happy with the icon, please make a proper argumentation based on something more empirical than your own test and/or provide an alternative so we can evaluate.

Regardless of that, you can use your own icon using our customization functionality. See the wiki.

**Comment by linjialiang** [comment]
ok

**Comment by jens1o** [comment]
Also, there are 3 php-icons to choose from.
