### ISSUE TITLE
Support for MDX

### ISSUE THREAD

**Issue by yduman** [vscode-icons/vscode-icons#1766]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `mdx`
  - Sample original Icon: [Example vscode-material-icon-theme](https://github.com/PKief/vscode-material-icon-theme/issues/295)
  - Extensions: `.mdx`

- More info: [MDX-Deck](https://github.com/jxnblk/mdx-deck)

**Comment by mzvast** [comment]
mdx is used in documentation orientation framework like Docz, I think this icon is quite useful.:P
