### ISSUE TITLE
[Icon Request] Add icon for partials and misc(elanous) folders

### ISSUE THREAD

**Issue by ndr3w221** [vscode-icons/vscode-icons#1767]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `Icon Request`
  - Icon Name: `partials & misc(elanous)`
  - Sample original Icon: -
  - Extensions: -
  - Filenames: - (Its folder)
  - Language ids: -

- Language Extensions:-
- More info:-

**Comment by JimiC** [comment]
Please see #650
