### ISSUE TITLE
Theme & Font info

### ISSUE THREAD

**Issue by kitkars** [vscode-icons/vscode-icons#1775]
It is a great project & You guys have done a great job. 

Sorry to ask this question here.

May i know the **theme** , **font** used in the below snapshot? It is just awesome

![](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/images/screenshot.gif)

**Comment by robertohuertasm** [comment]
Check out [this](https://github.com/vscode-icons/vscode-icons/issues/101#issuecomment-235625621). 😊

**Comment by kitkars** [comment]
@robertohuertasm  Thank you sir
