### ISSUE TITLE
PowerShell module icons

### ISSUE THREAD

**Issue by iricigor** [vscode-icons/vscode-icons#1779]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `PowerShell module`
  - Sample original Icon: 
  - Extensions: `.psm1`, `.psd1`
  - Filenames:
  - Language ids: `powershell`

- Language Extensions:
- More info:

PowerShell provides two extensions `.psm1` and `.psd1` for so called PowerShell [modules](https://docs.microsoft.com/en-us/powershell/developer/module/understanding-a-windows-powershell-module). Those are slightly more important than other `.ps1` files and usually there is only one `.psm1` and one `.psd1` file per project. It will be good to differentiate those. Simple color change would be good, as it is done for example in [`FileIcons`](https://marketplace.visualstudio.com/items?itemName=file-icons.file-icons) theme.

![image](https://user-images.githubusercontent.com/15923171/48648546-1b0c1680-e9f0-11e8-860e-03a45204eccf.png)

**Comment by JimiC** [comment]
Good idea.
