### ISSUE TITLE
[Icon Request] Generic .lock icon

### ISSUE THREAD

**Issue by Thiht** [vscode-icons/vscode-icons#1783]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `generic_lock`
  - Extensions: `*.lock`

- More info: .lock files are generated by several dependency managers:
  - dep (Golang) -> Gopkg.lock
  - gem (Ruby) -> Gemfile.lock
  - Cargo (Rust) -> Cargo.lock
  - ...

Some of them already have a specific icon (Gem, Cargo, ...) but some others don't. Could you add a default .lock icon to handle the general case?

**Comment by jens1o** [comment]
This is not possible. Please see https://github.com/Microsoft/vscode/issues/12493
