### ISSUE TITLE
[Icon Request] Support for Pony

### ISSUE THREAD

**Issue by gamebox** [vscode-icons/vscode-icons#1790]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `pony`
  - Sample original Icon: ![logo](https://d33wubrfki0l68.cloudfront.net/64f377d2086bbab73339860ae4022e5b321494c1/d06e5/assets/images/logo.png) 
  - Language ids: `pony`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=npruehs.pony
- More info: https://www.ponylang.io/

**Comment by JimiC** [comment]
@gamebox No offence but this is the correct way to submit an icon request.

**Comment by KingDarBoja** [comment]
This icon is barely legible due to its brown background colour and the ammount of details at the text "Pony".

![pony_sample](https://user-images.githubusercontent.com/30560560/52191255-bc498280-2811-11e9-8206-402e12295fa2.PNG)

Not sure if you guys wanna try another icon instead of the original one.

**Comment by JimiC** [comment]
@KingDarBoja Our principal is to use the official logo whenever there is one. Our primary concern is to make the file distinguishable among other files and not the readability of the icon itself. I admit that on high-resolution, small sized monitors the icons aren't that readable but with larger monitors or zoomed editors, the readability gets improved.

**Comment by KingDarBoja** [comment]
@JimiC Seems fair, gonna make the PR with the official icon so you guys can check if it is okay.

**Comment by gamebox** [comment]
Sorry, I stepped away from the project that lead me to open this PR(though I still think having an icon for Pony is a good idea). @JimiC You said "No offence(sp) but this is correct way..." I'm assuming by leading with "No offense" that you meant to say "This is NOT the correct way".   Could you point me to the document that details the correct procedure for submitting an icon request?  The template explicitly states "I'm submitting an icon request" and all of the fields are filled with accurate information, and I went through the trouble of putting the official icon in the correct format and dimensions.

**Comment by JimiC** [comment]
The template contains the following section 

```
<!-- Please first read how to submit an issue, if you haven't already done so.
https://github.com/vscode-icons/vscode-icons/wiki/Issue -->
```

that most people tend to discard.

**Comment by gamebox** [comment]
Ah, I think that's why I was confused.  I didn't see the edit.  Thank you for the correction.

**Comment by gamebox** [comment]
If there is anything else you would like me to provide or change for this icon's inclusion, please let me know.
