### ISSUE TITLE
[Icon Request] Support for nunjucks .njk

### ISSUE THREAD

**Issue by nofalx** [vscode-icons/vscode-icons#1812]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `nunjucks`
  - Extensions: `.njk`
  - Sample original Icon: ![logo](https://eseom.gallerycdn.vsassets.io/extensions/eseom/nunjucks-template/0.1.2/1541642015463/Microsoft.VisualStudio.Services.Icons.Default)

**Comment by JimiC** [comment]
Already supported. Use a 3rd party `vscode` syntax highlighting extension to get the icons shown.
