### ISSUE TITLE
[Icon Request] Support for cookbooks

### ISSUE THREAD

**Issue by brianmituka** [vscode-icons/vscode-icons#1817]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `cookbook`
  - Sample original Icon:

 ![412890](https://user-images.githubusercontent.com/21999457/50341020-496c9c80-052e-11e9-86d7-0ae828048d4d.png)

  - Extensions: `.ckbk`

  - Language ids: `cookbook`

**Comment by JimiC** [comment]
Which `vscode` extension uses `cookbook` as `languageid`?

**Comment by brianmituka** [comment]
It's our custom extension within our company. Do I need to upload it to the market place? It's called fsmscookbooks
