### ISSUE TITLE
[Icon Update] TikZ files should not use the Matlab logo

### ISSUE THREAD

**Issue by daniel-sch** [vscode-icons/vscode-icons#1818]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `tex`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_tex.svg)
  - Extensions: `.tikz`

- More info: Currently TikZ files use the Matlab icon, which is not correct, as Matlab doesn't use TikZ files. I suggest using the Tex logo instead, because I couldn't find a logo especially for TikZ and TikZ files are essentially Tex files.

**Comment by JimiC** [comment]
Thanks for letting us know.
//ref https://en.wikipedia.org/wiki/PGF/TikZ
