### ISSUE TITLE
Nunjucks icon missing extension .njk

### ISSUE THREAD

**Issue by nofalx** [vscode-icons/vscode-icons#1819]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
- Type: extension
 - Icon Name: nunjucks
 - Extensions: `.njk`
- More info:  

nunjucks icon is already supported, however in the list:
 https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles 
it doesnt show that the extension `.njk` is supported among the other nunjucks extensions.  
  
According to the following link it should be supported:
https://mozilla.github.io/nunjucks/templating.html
```
File Extensions

Although you are free to use any file extension you wish for your Nunjucks template files, the Nunjucks community has adopted .njk.

If you are developing tools or editor syntax helpers for Nunjucks, please include recognition of the .njk extension.
```

**Comment by JimiC** [comment]
Quoted from the wiki page
> Important! Icons that are supported via Language ID, require a syntax highlighting extension, that 
> registers that id, to be installed, for the icon to show.
Please stop opening invalid issues and read the wiki more carefully
