### ISSUE TITLE
ListOfFolders wiki page is broken on Safari on MacOS Mojave

### ISSUE THREAD

**Issue by balupton** [vscode-icons/vscode-icons#1821]
https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#html

<img width="1521" alt="screen shot 2018-12-31 at 1 32 44 pm" src="https://user-images.githubusercontent.com/61148/50553732-90ae1680-0d00-11e9-8b28-374f9295bea0.png">

**Comment by JimiC** [comment]
Look like an issue with our generation script. Thanks for bringing it to our attention.

**Comment by JimiC** [comment]
Fixed
