### ISSUE TITLE
[Icon Missing] Support for gulpfile folder

### ISSUE THREAD

**Issue by rivajunior** [vscode-icons/vscode-icons#1823]
- [x] I'm sure this issue is not a _duplicate_.

- More info:
I'm using gulp on a project and how the file become huge, I've splitted the file on separated files inside a folder named `gulpfile.babel.js` witch is listed on [ListOfFolders](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#gulp) like if already have an icon, but my folder is only with the default folder icon. This folder name that I've been using is covered by the gulp project as you can see on [their documentation](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#splitting-a-gulpfile).

When I use the same name on a file, it works, so the problem is only with folders.

**Comment by JimiC** [comment]
There is no icon for `gulp` folder. You can request one at #650. Unfortunately, the wiki page is displaying wrong data, something that we look into it. Thanks for bringing this to our attention.
