### ISSUE TITLE
[Icon Request] Support for Gatsby.js

### ISSUE THREAD

**Issue by JamesMessinger** [vscode-icons/vscode-icons#1825]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `gatsby`
  - Sample original Icon: ![logo](https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg)
  - Filenames: 
    - `gatsby-config.js` and `gatsby-config.ts`
    - `gatsby-node.js` and `gatsby-node.ts`
    - `gatsby-browser.js` and `gatsby-browser.ts`
    - `gatsby-ssr.js` and `gatsby-ssr.ts`
    - (or maybe just the `gatsby-*.{js,ts}`
  - More info: 
    - https://www.gatsbyjs.org/docs/gatsby-config/
    - https://www.gatsbyjs.org/docs/creating-slugs-for-pages/
    - https://www.gatsbyjs.org/docs/gatsby-project-structure/#files

**Comment by KingDarBoja** [comment]
@JimiC Gonna follow the same approach used at Angular icons, a tiny `JS`/`TS` over the `Gatsby` one.

Are you okay with that? :D

**Comment by JimiC** [comment]
No. Not OK. One icon to rule them all.
