### ISSUE TITLE
Icons not displayed after editor start

### ISSUE THREAD

**Issue by alexdevero** [vscode-icons/vscode-icons#1827]
- [X] I'm sure this issue is not a _duplicate_.

- More info:
Icons are not displayed after editor start if sidebar file tree is expanded.

Start editor with sidebar file tree expanded:
![icons-issue-1](https://user-images.githubusercontent.com/4237724/50721069-10e5ca80-10b9-11e9-928a-b91b5ffe9426.PNG)

Start editor with sidebar file tree **not** expanded, and then expand the tree:
![icons-issue-2](https://user-images.githubusercontent.com/4237724/50721070-10e5ca80-10b9-11e9-87d4-48648d424dc4.PNG)

Editor info:
Version: 1.31.0-insider
Commit: 7805023eaa46db45d3c24a4c38c0d07c087cf1b3
Date: 2019-01-03T06:20:50.629Z
Electron: 3.0.10
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
**Version: portable**

**Comment by JimiC** [comment]
Check with `stable` `vscode` version.

**Comment by alexdevero** [comment]
File associations:
```
"files.associations": {
    "*.tsx": "javascript",
    "*.css": "postcss"
}
```

**Comment by JimiC** [comment]
You should remove `"*.tsx": "javascript",`, then `vscode` will display the `typescriptreact` icon.

**Comment by alexdevero** [comment]
The problem is not incorrect icon (JS instead of TS). The problem is the icon in *Start editor with sidebar file tree expanded* screen.

**Comment by JimiC** [comment]
There is no problem. You are not telling `vscode-icons` that you have re-associated the file extension to another icon. See https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by JimiC** [comment]
@robertohuertasm This is a good case to implement a file association detection feature to automate this. Thoughts?

**Comment by alexdevero** [comment]
Thank you for the information about fine tuning. Question: why icons work correctly when sidebar tree is collapse on editor start?

**Comment by JimiC** [comment]
It's a `vscode` feature which detects the icon from the content and then knows what icon to display, but this requires that a file should be opened first.

**Comment by alexdevero** [comment]
So, that's why you mentioned the association detection feature. Yeah, that seems like a good idea.

**Comment by JimiC** [comment]
Closing this issue as the behavior has been resolved by `vscode` itself.
