### ISSUE TITLE
[Icon Request] Support for *-spec and *-test files.

### ISSUE THREAD

**Issue by def14nt** [vscode-icons/vscode-icons#1828]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `spec`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_testts.svg) but depending on file extension

- More info: Add support for `*-spec.(ts,js)` files, because people use that and you've added support for `*.spec` files. This could also apply to `*-test.(ts|js)` files too.

**Comment by JimiC** [comment]
Sorry but `vscode` doesn't support glob naming for icon themes (yet).
