### ISSUE TITLE
[Icon Request] Support for tailwind.js

### ISSUE THREAD

**Issue by jimblue** [vscode-icons/vscode-icons#1832]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename `
  - Icon Name: `tailwind`
  - Sample original Icon: ![logo](https://camo.githubusercontent.com/97517e40f9727cc4637bea2d0e1b813d4639f8b2/68747470733a2f2f7461696c77696e646373732e636f6d2f696d672f7461696c77696e642e737667)
  - Filenames: `tailwind.js`

 - More info: https://tailwindcss.com

**Comment by KingDarBoja** [comment]
This issue is already done so should be closed. @JimiC
