### ISSUE TITLE
[Icon Request] Support for go.mod and go.sum

### ISSUE THREAD

**Issue by huiyifyj** [vscode-icons/vscode-icons#1834]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `go mod`
  - Extensions: `golang`
  - Filenames: `go.mod` and `go.sum`

- Language Extensions: golang
- More info:
`go.mod` and `go.sum` is files that be created by `go module`.
And `go mdule` is the official support of the dependence manager tool.
For understand better: `go module` like `npm`, `go.mod` like `package.json`, and `go.sum` like `package-lock.json`.
Suggest personally you can use `go` icon, but different color.

**Comment by JimiC** [comment]
@robertohuertasm has something in the works.

**Comment by robertohuertasm** [comment]
Yes, I'm working on the `Go` icons and will take those files into consideration, too. We'll go with blue as the default color for the Go icon (as it seems to be the one favored in their style guides)  but will publish all colors so users can use our customization capabilities to change them accordingly to their personal preference. Stay tunned!
