### ISSUE TITLE
[Icon Request] Support for G-Code

### ISSUE THREAD

**Issue by mikecentola** [vscode-icons/vscode-icons#1841]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageid`
  - Icon Name: `gcode`
  - Sample original Icon: [icon svg](https://github.com/appliedengdesign/vscode-gcode-syntax/blob/master/images/vscode-gcode-syntax-icon.svg)
  - Extensions: `.nc, .gcode, .tap, .cls, .apt, .mpt, .fnc, .gc, .dnc, .cnc, .ncf, .ncc, .maz, hnc, .knc, .g00`
  - Language ids: `gcode`

- Language Extensions: [Link to Extension](https://marketplace.visualstudio.com/items?itemName=appliedengdesign.vscode-gcode-syntax)

- More info:

![logo](https://user-images.githubusercontent.com/12663057/51548768-fc366000-1e36-11e9-9558-82f77d26dcbb.png)

**Comment by mikecentola** [comment]
I can submit a PR for this if that's easier?

**Comment by Alhadis** [comment]
What's an `hnc` file?  Doesn't exist on [FileInfo.com](https://fileinfo.com/extension/hnc) and there are only [19 files](https://github.com/search?q=extension%3Ahnc+NOT+nothack&type=Code) which use that file-extension.

**Comment by JimiC** [comment]
Since there is a 3rd party extension in the `vscode` marketplace that makes use of a `language id`, the `type` strictly is `language id` and no 'Extensions' should be mentioned as that extension is responsible to declare them.

**Comment by JimiC** [comment]
In 'More Info' we'd like you to add a link to `G-Code` docs.

**Comment by mikecentola** [comment]
> In 'More Info' we'd like you to add a link to `G-Code` docs.

What do  you mean a link to `G-Code` docs?
