### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by duanxianze** [vscode-icons/vscode-icons#1851]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.0.0`
- OS Version: `Linux x64 4.15.0-29deepin-generic`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/duan/robertohuertasm.vscode-icons-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
#1743 #1747 #1748
