### ISSUE TITLE
[Icon Request] Support for ReasonML

### ISSUE THREAD

**Issue by dmtrKovalenko** [vscode-icons/vscode-icons#1854]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `.re`, `reason`
  - Icon Name: `reasonml`
  - Sample original Icon: ![logo](https://pbs.twimg.com/profile_images/1004185780313395200/ImZxrDWf.jpg)
  - Extensions: `re`
  - Filenames: `somefilename.re`
  - Language ids: `reason`

- Language Extensions: vscode-reasonml, reason-vscode

**Comment by JimiC** [comment]
@dmtrKovalenko Please read https://github.com/vscode-icons/vscode-icons/wiki/Issue and fix your OP accordingly.

**Comment by dmtrKovalenko** [comment]
Fixed

**Comment by JimiC** [comment]
It's far from fixed but what the hell, just leave it be, I'll fix it at some point.

**Comment by dmtrKovalenko** [comment]
Sorry, from where I stand issue completely matching the template :D

**Comment by JimiC** [comment]
You obviously didn't read the wiki I linked but it's OK.

**Comment by KingDarBoja** [comment]
After searching a bit about this "language": [ReasonML FAQ](https://reasonml.github.io/docs/en/faq).

I will make a PR with the icon request for the `.re` extension and also one for the `.rei`.

**Comment by JimiC** [comment]
We are already supporting `Reason` via the `reason` language id. Use a syntax highlighting extension from the marketplace, like: https://marketplace.visualstudio.com/items?itemName=freebroccolo.reasonml

**Comment by robertohuertasm** [comment]
See [this comment](https://github.com/vscode-icons/vscode-icons/pull/1868#issuecomment-462180466) to understand why this issue was reopened.

**Comment by KingDarBoja** [comment]
@robertohuertasm I agree with JimiC regarding contacting first the `Reason` extension authors in order to request any support and if possible, svg files for the Reason Interface. 

I am not an expert on the topic but tried to find the official `.rei` icon on their website and GitHub, but the only clue was at the nav bar when hovering on the `RE`. 

Anyway, if you guys need any changes on the icon, I am willing to help 😄 
Cheers!

**Comment by KingDarBoja** [comment]
Since ReasonML is already deprecated and we do support the new ReScript icon, I am going to close this issue for housekeeping purposes.
