### ISSUE TITLE
[Icon Request] Support for AngularDart plus extension files

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/vscode-icons#1861]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `angulardart, ng_*_dart`
  - Sample original Icon: ![logo](https://webdev.dartlang.org/assets/shared/angular/icon/default-77f530ea0ef7066f55bd9466f5b7c50201e2f33b6dff9897c46bfa28f78d4bd4.svg)
  - Filenames: `ng_component_dt, ng_guard_dt, ng_service_dt, ng_directive_dt, ng_pipe_dt, ng_routing_dt/ng_routes_dt`

- More info: [AngularDart](https://webdev.dartlang.org/angular)

You guys kinda did the same with the Angular files at this issue: #1016. I am making the custom AngularDart svg and will post soon an image with all the icons following the guidelines. 😄 

Note: There is no **Module** file at AngularDart since all the providers, imports, and so on are already placed at the component.

**Comment by robertohuertasm** [comment]
I don't think you need to do any custom AngularDart svg. It's just a matter of adding the `.dart` extension to the existing ones. Why would you need to create different icons?

**Comment by KingDarBoja** [comment]
What I meant, adding the little dart icon to the right bottom side of the icons.
