### ISSUE TITLE
Icon for next.js pages folder

### ISSUE THREAD

**Issue by xeoneux** [vscode-icons/vscode-icons#1864]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `pages`
  - Sample original Icon: [logo](https://github.com/PKief/vscode-material-icon-theme)
  - Extensions: `N/A`
  - Filenames: `N/A`
  - Language ids: `N/A`

- Language Extensions: N/A
- More info: next.js uses the pages folder to store all the routes that a user can visit.

**Comment by JimiC** [comment]
Please see #650.
