### ISSUE TITLE
vscode-icons is consuming a lot of CPU

### ISSUE THREAD

**Issue by samuelsonokoi** [vscode-icons/vscode-icons#1873]
You might want to go through my console for details on this

![console-log](https://user-images.githubusercontent.com/12806939/52903212-89908880-321a-11e9-91fc-a9e48f1c2a2f.png)

**Comment by JimiC** [comment]
Please provide reproduction steps.

**Comment by JimiC** [comment]
We will require the `.cpuprofile.txt` to investigate further.

**Comment by JimiC** [comment]
Closing due to lack of follow-up
