### ISSUE TITLE
Suggestion: Change the Matlab icon from png to svg

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/vscode-icons#1875]
- [x] I'm sure this issue is not a _duplicate_.

The current Matlab icon has **.png** extension and low quality if you start zooming in. I have done already (after 2 hours of work) an svg version. The file itself isn't perfect as I had to remove some points to reduce the size from 200 KB to 68 KB but the result can be seen below.

![wut](https://user-images.githubusercontent.com/30560560/52908401-734af280-3243-11e9-8c01-ff47b16da8a4.PNG)

Thoughts?

**Comment by JimiC** [comment]
Tried that 2 years ago. I abandoned every attempt. If the file isn't at max 2KB then it won't work.

**Comment by robertohuertasm** [comment]
Great work @KingDarBoja and thanks for the effort! Have you tried the performance of this icon as  @JimiC suggests? To be fair, a third of our icons is greater than 2KB, some of them are just `one-file-per-project` type but others don't. Anyway, on the range of ~60KB most of them are  `one-file-per-project` files. @KingDarBoja is there any possibility that you could reduce this?

**Comment by JimiC** [comment]
The icon has a lot of gradients which is the reason it gets so large. I'm not sure what the outcome would be and how the icon will look if we reduce those.

**Comment by KingDarBoja** [comment]
@robertohuertasm  I can try to reduce the gradients parts to make it smaller, but of course the quality gonna be slighty different. The good thing is that being just a vscode icon, it will look almost the same for most of us.

@JimiC Yeah, the official icon provided at the Matworks guidelines is just the embedded image on the svg (64-bits encoding). Most of my work was related to reducing the anchor points and merging some layers.

**Comment by esbeto** [comment]
You can also try to use [svgo](https://github.com/svg/svgo) to optimize the svg icon.

**Comment by JimiC** [comment]
@esbeto Thanks for the letting us know. Looks interesting.

**Comment by esbeto** [comment]
Where did you get the svg version of their logo? I cannot find it anywhere.

**Comment by JimiC** [comment]
There is none. Tried to make one from `Matlab` itself (yes it has a script that produces its logo) but it turned out to be multiple images added together.
So either someone will have to sit down and make one by hand or wait till somebody else does it for them.

**Comment by KingDarBoja** [comment]
Gonna try the svgo with the MatLab icon as soon as I get time.

@JimiC Did the same procedure and got same result and even bigger file.

**Comment by JimiC** [comment]
I don't believe that `svgo` will do any good on the `matlab` icon but I want to test it out and see if we can use it to standardize our `svg` format regardless the tool used to produce the `svg` icon.

**Comment by KingDarBoja** [comment]
Looks like svgo reduced it even more from 30 KB (hard simplified version) to 21 KB!

Here are the results on VS Code:
![zoomed_matlab](https://user-images.githubusercontent.com/30560560/57971838-20bfc600-7959-11e9-8591-77077d1334a3.PNG)

And if you curious how my hard simplified version + svgo treatment looks:
![svgo_matlab](https://user-images.githubusercontent.com/30560560/57971844-3634f000-7959-11e9-89eb-97fd23dbc974.PNG)

Anyway, the file size is still to big for the recommended size (<3 KB) and I don't think it could be reduced again. What is left is let the current icon as it is (`PNG`) or use a minimalist version like [this one](https://img.icons8.com/nolan/420/matlab.png)
