### ISSUE TITLE
vue icon dosent show

### ISSUE THREAD

**Issue by ElectFreak** [vscode-icons/vscode-icons#1876]
- [ x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: `vue`
  - Sample original Icon: ![logo]()
  - Extensions: `vue`
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info: sorry, I know english not very well and maybe I should not to create this issue, but .vue icons dosent backlint. I shure that I enable extension, other icons are good.

**Comment by robertohuertasm** [comment]
You need to install some `vuejs` extension. Try [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

**Comment by ElectFreak** [comment]
> You need to install some `vuejs` extension. Try [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur)

Sorry but you are wrong. 
I try this setting and icon was become. But how I understood this setting must be used for custom user settings or I didnt understand logic of this extension. Help me do it please, why this setting was help me?

![image](https://user-images.githubusercontent.com/30327603/52911945-96b18400-32bb-11e9-81fb-fffc6b71d0bc.png)

**Comment by JimiC** [comment]
Just install `vetur`. Remove the setting.

**Comment by robertohuertasm** [comment]
Some icons become active once you have the proper extension, like the VueJS one.

What you've done is just force the icon to be shown for vue extension regardless of you having the extension or not. 

As you said, this works but it's mainly designed for fine tuning and customization. Normally, if you use vuejs you will like to use some extension to give you syntax coloring and other stuff.

**Comment by ElectFreak** [comment]
> Some icons become active once you have the proper extension, like the VueJS one.
> 
> What you've done is just force the icon to be shown for vue extension regardless of you having the extension or not.
> 
> As you said, this works but it's mainly designed for fine tuning and customization. Normally, if you use vuejs you will like to use some extension to give you syntax coloring and other stuff.

thank you very much!
