### ISSUE TITLE
[Icon Request] Support for QML & Qbs

### ISSUE THREAD

**Issue by oltodo** [vscode-icons/vscode-icons#1887]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - __QML:__
    - Type: `languageId`, `extension`
    - Icon Name: `qml`
    - Sample original Icon: ![logo](https://user-images.githubusercontent.com/483842/53031923-1a12d700-346e-11e9-8496-8878d386f5ba.png)
    - Language ids: `qml`
    - Language Extensions: https://marketplace.visualstudio.com/items?itemName=bbenoist.QML (unmaintained since 3 years)
    - More info: https://doc.qt.io/qt-5/qtqml-index.html
  - __Qbs:__
    - Type: `extension`
    - Icon Name: `qbs`
    - Sample original Icon: ![logo](https://user-images.githubusercontent.com/483842/53033975-95768780-3472-11e9-9295-2402c0d27503.png)
    - Extensions: `qbs`
    - More info: https://doc.qt.io/qbs/index.html

**Comment by JimiC** [comment]
Since `qbs` is a file extension of a [`Qt` building tool](https://doc.qt.io/qbs/index.html) (I was forced to do my own research), II believe it deserves a separate icon to make it distinguishable, In lack of a unique icon for it we could use the same `Qt` icon with a different color.

**Comment by oltodo** [comment]
Ok no problem to remove `qbs` extension and create a separate icon. Actually I've never used this one, I was just referencing to the Github's linguist library:

https://github.com/github/linguist/blob/e4560984058b4726010ca4b8f03ed9d0f8f464db/lib/linguist/languages.yml#L3936-L3944

So I'm going to remove it.

**Comment by JimiC** [comment]
`qbs` probably means `Qt building script` and it's not a bad idea to support it with a separate icon.

**Comment by oltodo** [comment]
Should I integrate this directly in my PR and decide in what color the icon could be?

**Comment by JimiC** [comment]
Yes, integrate it. I would go with `purple` as there are not so many icons with that color.

**Comment by oltodo** [comment]
Something like that ?
 
![qbs](https://user-images.githubusercontent.com/483842/53033975-95768780-3472-11e9-9295-2402c0d27503.png)

**Comment by JimiC** [comment]
LGTM

**Comment by JimiC** [comment]
Intending to work on this on the weekend. Sorry for the delay.
