### ISSUE TITLE
[Icon Request] Support for XQuery

### ISSUE THREAD

**Issue by JanCervak** [vscode-icons/vscode-icons#1888]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId`
  - Icon Name: `XQuery`
  - Extensions: `xq`
  - Language ids: `xquery`

- Language Extensions:
https://marketplace.visualstudio.com/items?itemName=DotJoshJohnson.xml
- More info:
https://stackoverflow.com/q/51637619/2812063

**Comment by KingDarBoja** [comment]
@JimiC Assign this to me :D

**Comment by JimiC** [comment]
You can't be assigned "yet" but it's all yours.
