### ISSUE TITLE
[Icon Request] Buildkite

### ISSUE THREAD

**Issue by azz** [vscode-icons/vscode-icons#1898]
- [x] I'm sure this issue is not a _duplicate_.

- [x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `buildkite`
  - Sample original Icon: ![logo](https://buildkite.com/_next/static/assets/assets/images/brand-assets/buildkite-mark-on-light-1a26e5b7.svg)
  - Folders: `.buildkite/`
  - Extensions: n/a
  - Filenames: n/a
  - Language ids: n/a

- More info: https://buildkite.com

**Comment by JimiC** [comment]
Please fix the OP. "How" is provided in the comments of the template.

**Comment by azz** [comment]
Oops I totally missed the link in the comments, sorry!

I've commented at https://github.com/vscode-icons/vscode-icons/issues/650#issuecomment-468647133, should this issue be closed?
