### ISSUE TITLE
Could you please make it an npm library?

### ISSUE THREAD

**Issue by KingMario** [vscode-icons/vscode-icons#1900]
- [x] I'm sure this issue is not a _duplicate_.

- More info:

Could you please make it an npm library that contains all the svgs, so that all the icons will be importable in js and can be used together with vscode-icons-js.

Thanks.

**Comment by JimiC** [comment]
This extension is not meant to be an `npm` package. If you want to use it in your projects see the wiki on how you can use our docker image (https://github.com/vscode-icons/vscode-icons/wiki/Docker)
