### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cachoalbornoz** [vscode-icons/vscode-icons#1903]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.2.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/guillermo/robertohuertasm.vscode-icons-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
Attach a link to the file or your issue is useless to us.
