### ISSUE TITLE
How do you override a filenamesGlob icon entry with a custom icon?  

### ISSUE THREAD

**Issue by johnhamm** [vscode-icons/vscode-icons#1907]
- [x] I'm sure this issue is not a _duplicate_.
How do you override a filenamesGlob icon entry?  I'm trying to add a custom icon to my *.spec.ts files Here is the entry from the supported file extensions file:
```
{
      icon: 'testts',
      extensions: [],
      filenamesGlob: ['test', 'spec'],
      extensionsGlob: ['ts', 'tsx'],
      format: FileFormat.svg,
    },
```
And here is what I tried (with and without the "override" property specified:
```
{
            "icon": "spec_ts",
            "extensions": [],
            "filenamesGlob": [
                "test",
                "spec"
            ],
            "extensionsGlob": [
                "ts",
                "tsx"
            ],
            "overrides": "spec",
            "format": "svg"
        }
```

**Comment by JimiC** [comment]
Quoted from wiki:
>// Overriding an already supported icon.
// note: the difference between overrides and extends is that overrides will completely
// remove the older icon functionality while extends will keep older settings by
// putting yours on top.
"vsicons.associations.files": [
  { "icon": "myJs", "extensions": ["js", "custom.js"], "format": "svg", "overrides": "js" }
]

So, you are trying to override an existing supported icon. This can be accomplished in three simple steps.

1. You add in `settings.json`, if you don't already have it:
```
"vsicons.associations.files": []
```

2. You copy the supported icon declaration in it adjusting accordingly to be `json` compliant. Note: `format` can be either `string` (i.e. "svg") or the enum type `FileFormat` (i.e. "FileFormat.svg"):
```
{
      "icon": "testts",
      "filenamesGlob": [
        "test",
        "spec"
      ],
      "extensionsGlob": [
        "ts",
        "tsx"
      ],
      "format": "svg"
    }
```

3. You add the magic sause of `overrides` with the icon name of the overrided icon and change the `icon` value with your custom icon name:
```
{
      "icon": "spec_ts",
      "filenamesGlob": [
        "test",
        "spec"
      ],
      "extensionsGlob": [
        "ts",
        "tsx"
      ],
      "overrides": "testts"
      "format": "svg"
    }
```

Enjoy!

**Comment by JimiC** [comment]
Note here that the above can be accomplished must easier.

Quoted form wiki:
>// Changing the icon to an already supported icon.
"vsicons.associations.files": [
  { "icon": "newIcon", "extensions": [""], "format": "svg", "extends": "js" }
]

So in your case, it will be:
```
"vsicons.associations.files": [
  { "icon": "spec_ts", "format": "svg", "extends": "testts" }
]
```

Notice that `extensions` is optional.

**Comment by JimiC** [comment]
Note here that this can be accomplished easier by just using:
```
"vsicons.associations.files": [
    { "icon": "spec_ts", "extends": "testts",  "format": "svg" }
  ],
```

**Comment by JimiC** [comment]
Closing as answered
