### ISSUE TITLE
Unable to install: Infinite request to reload/restart

### ISSUE THREAD

**Issue by StJohn3D** [vscode-icons/vscode-icons#1908]
- [x] I'm sure this issue is not a _duplicate_.

I already had `robertohuertasm.vscode-icons` installed. Today I got a warning from my work-space recommendations that the extension didn't exist anymore. So I searched and found this one. I tried installing it (without first uninstalling the other one). Then began the endless alerts that a workspace recommendation is not installed - always prompting me to reload but never working.

Things I've already tried to resolve this.
Restarting PC
Going to C:\Users\<me>\.vscode\extensions and deleting both *.vscode-icons folders
Re-Installing
Reloading
Closing and Re-Opening VsCode
Commenting out this extension from my workspace recommendations `extensions.json` file

That last one only stopped the endless prompting to install recommended extensions but as of now the extension still fails to work. It's neither enabled or disabled but it's detected as installed and says a reload is required. However no matter how many times I reload it still says a reload is required.

- More info:
VsCode Version:
```
Version: 1.32.1 (user setup)
Commit: 05f146c7a8f7f78e80261aa3b2a2e642586f9eb3
Date: 2019-03-08T00:51:49.278Z
Electron: 3.1.3
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by StJohn3D** [comment]
**Update:**
After reading the README I tried doing this:
File > Preferences > File Icon Theme > VSCode Icons.

The extension is working (I see the icons now), however it still says that it requires a reload. Because of this I have to remove it from my recommended workspace `extensions.json` file, or else I'll be prompted to install it every time I boot up VsCode.

**Comment by robertohuertasm** [comment]
Today we changed our publisher so this certainly is a side-effect. I'm looking into it. Thanks for reporting it.

**Comment by robertohuertasm** [comment]
I think we'll have to republish the extension. I've tested it, followed all your steps and finally the only solution is to change the publisher name. For that, the only solution is to republish again from our side, so everyone will get a new version with the new publisher. I'm going to do the publishing. It may take up to an hour.

**Comment by robertohuertasm** [comment]
The publication process is ongoing. We'll close the issue once we check that everything is solved.

**Comment by robertohuertasm** [comment]
Done! @StJohn3D could you try and let us know if it works now? It seems to be working for me.

**Comment by StJohn3D** [comment]
@robertohuertasm It works!
Thanks! I love this extension, didn't realize how blind I felt without it until I lost it today.
Thanks for fixing this so quickly!
