### ISSUE TITLE
VSCode Extension Question: Can I Create a Folder Icon "Alias"?

### ISSUE THREAD

**Issue by homestar9** [vscode-icons/vscode-icons#1926]
First of all, I love this project! It has really changed the way I interact with VS Code and it is fantastic!

I'm curious if there is a way to edit my VS Code user settings so that I can have specific folders which are not currently supported use icons of already supported by vscode-icons.

For example, lets say I have a folder called `designs/` (not currently supported) but I want it to use the existing folder icon for `layouts/` (currently supported).  Can I edit my config file to make this so?

**Comment by robertohuertasm** [comment]
Hi @homestar9, you may want to take a look at the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning). You should find all the information that you need in there. 😉

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by JimiC** [comment]
Closing as answered

**Comment by homestar9** [comment]
Thank you @robertohuertasm for pointing me in the right direction.  I must have missed that section when skimming the Wiki previously.
