### ISSUE TITLE
vscode-icons causes restart loop with NxWorkspace projects

### ISSUE THREAD

**Issue by eduardoRoth** [vscode-icons/vscode-icons#1939]
- [X] I'm sure this issue is not a _duplicate_.

vscode-icons causes NxWorkspace projects to keep reloading.

1. Create a new Nx Workspace (`create-nx-workspace app-name`)
2. Choose "fullstack application"
3. Open it
4. VS Code will keep refreshing itself

Remove `package.json` (or just change it's extension) and issue will disappear.

**Comment by eduardoRoth** [comment]
Only happens if you have `vsicons.projectDetection.autoReload` enabled.

**Comment by JimiC** [comment]
Duplicate of #1925
