### ISSUE TITLE
My custom icon is not shown

### ISSUE THREAD

**Issue by mbaas2** [vscode-icons/vscode-icons#1942]
- [X] I'm sure this issue is not a _duplicate_.

- More info:

I'm using the best unknown programming-language: "[APL](http://www.dyalog.com)". There is work on the way to get extensions etc. for it - but meanwhile I was hoping I could use vscode-icons to at least have custom icons for some files.

So I read the wiki and added to my settings.json the following:
```
"vsicons.associations.files": [
    { "icon": "dyalog", "extensions": ["dyalog", "mipage"], "format": "png" }
]
```

The I created a folder `vscode-custom-icons`

and placed file `file_type_dyalog-icon.png` it.

I also ran `Icons: Apply Icons Customization`. The icon is not shown - the file gets no icons next to it (so my customization has _some_ effect at least.
I also tried `svg`and ìco`-files - which all display fine in XNView. Are there any specific requirements that I might have missed or can someone see what I've donw wrong?

**Comment by JimiC** [comment]
Please read https://github.com/vscode-icons/vscode-icons/wiki/Custom. Especially where it mentions the icon filename naming convention.

**Comment by mbaas2** [comment]
Sorry - that was a mistake in the question. I had read that page as well and called the file `file_type_dyalog-icon.png` - have update the q to avoid confusion.

**Comment by JimiC** [comment]
OK next question. Where is the folder that contains the custom placed?

**Comment by mbaas2** [comment]
The absolute path is C:\Users\mbaas\AppData\Roaming\Code\User\vsicons-custom-icons

**Comment by JimiC** [comment]
The correct naming is `file_type_dyalog.png`.

**Comment by mbaas2** [comment]
Thanks - that `-icon` messed me up. I renamed the file and even applied the customization, just to be 100% sure - but still no joy :(

**Comment by JimiC** [comment]
Are you using `Code` or `Code-Insiders`?

**Comment by JimiC** [comment]
Another thing I noticed is that you `array` for `"vsicons.associations.files"` is not closing, Could you have syntax errors?

**Comment by mbaas2** [comment]
Sorry about the missing `]` - that was only visible in the post here, my settings have it. (I have update the q). And I'm using ´Code`.

**Comment by JimiC** [comment]
Well, you have fallen in the same pit me and others have fallen into many many many many times.

The correct name for the folder is `vsicons-custom-icons` NOT `vscode-custom-icons`.

**Comment by mbaas2** [comment]
Nope, [I'm using that path](#issuecomment-480570989) already...

**Comment by JimiC** [comment]
Looks like a bug. I'm investigating...

**Comment by JimiC** [comment]
It's a bug alright. Thanks for sticking to it. I'll get a fix out soon and hopefully, I'll submit it in time for the upcoming release.

**Comment by mbaas2** [comment]
Ok, great! Thank you for putting up with my many typos! ;-)

**Comment by mbaas2** [comment]
@JimiC : got 8.5.0 - but it still doesn't show the icon. Situation has somewhat changed: previously there was no icon for the .dyalog-files, now it shows vscode's default-icon. What am I missing? (Somehow the settings were wiped out after the upgrade, so I've put them back, regenrated the manifest and also re-applied customizations.)  (Icons like .js and .xml are shown fine, so I can confirm it's working in general - just doesn't like my customization)
What am I missing?

**Comment by JimiC** [comment]
It tested it with your settings and custom icons folder path and I got it working. Will check again.

**Comment by JimiC** [comment]
Do you by any chance have `Code` installed on `C:` and your project is in another drive?

**Comment by mbaas2** [comment]
Nope, it's all on C:

**Comment by JimiC** [comment]
CAn you provide some screenshots? It's really hard to troubleshoot this way,

**Comment by mbaas2** [comment]
Sure. I have also attached a .PNG, in case there is anything wrong with the file I'm using.
![file_type_dyalog](https://user-images.githubusercontent.com/5645494/55738635-c82b0e00-5a27-11e9-956b-a4531d5c3fef.png)

Screenshot of VSCode's Explorer:
![image](https://user-images.githubusercontent.com/5645494/55738737-00325100-5a28-11e9-8e70-36ef1564d25b.png)

Any other screenies you'd like to see?

**Comment by mbaas2** [comment]
It's unfortunate that this PNG is so large - I hope that wouldn't a problem. I have a SVG which is much smaller, but I'm not sure I could share that. (If you have access to FontAwesome Pro, it's `brands/dyalog`.)

**Comment by JimiC** [comment]
That's not our icons.

**Comment by mbaas2** [comment]
Oh no...SORRY - someone must have picked a different icon-them :((((  (blush, cry etc.)

**Comment by sexling** [comment]
I'm trying to change the color of the default folder
Here's what I placed in `settings.json`
```
  "vsicons.customIconFolderPath": "C:\\Users\\aquad\\AppData\\Roaming\\Code\\User\\vsicons-custom-icons",
  "vsicons.associations.folderDefault.folder": {
    "icon": "myFolder",
    "format": "svg"
  }
```
How I set up the files
![alt text](https://i.imgur.com/3deKuYn.png "")

The result is an empty space
![alt text](https://i.imgur.com/QnINc1k.png "")
