### ISSUE TITLE
[Icon Request] Support for APL

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1963]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `apl`
  - Sample original Icon: N/A
  - Language ids: `apl`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=OptimaSystems.vscode-apl-language
- More info: https://en.wikipedia.org/wiki/APL_(programming_language)

**Comment by Alhadis** [comment]
It might help to differentiate between "traditional" APL and Dyalog APL. The latter is heavily modernised and supports many concepts which never existed in the original language: classes, control-flow (`:If`, `:Else`), and object-oriented programming.

For ordinary APL, no "official" logo exists, but the "grade up" symbol (⍋) is probably one of the more distinctive shapes of the language's alphabet:

<img src="https://raw.githubusercontent.com/file-icons/source/master/svg/APL.svg?sanitize=true" width="256" />

(Also, the author of that language extension [ported my work](https://github.com/Alhadis/language-apl). Good to see it's going places. 😀)

**Comment by JimiC** [comment]
@Alhadis It's well known, you are a pioneer, Sir. 😄

**Comment by sloorush** [comment]
APL now has a new logo and dyalog is also a version of APL massively used.

Information about new apl logo: https://aplwiki.com/wiki/APL_logo

Is it possible to reopen this issue?
