### ISSUE TITLE
Entity/repository icons

### ISSUE THREAD

**Issue by chriskuech** [vscode-icons/vscode-icons#1968]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

I propose extending the following existing folder icons for projects that follow the entity/repository design pattern:
* existing [db](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#db) icon for `repository` and `repositories` folders
* existing [model](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#model) icon for `entity` and `entities` folders

**Comment by JimiC** [comment]
Please #650
