### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rodpater** [vscode-icons/vscode-icons#1970]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.5.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\devpater\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
No `C:\Users\devpater\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt` attached
