### ISSUE TITLE
Changing Default Folder Icon

### ISSUE THREAD

**Issue by sexling** [vscode-icons/vscode-icons#1972]
I'm trying to change the color of the default folder
Here's what I placed in `settings.json`
```
  "vsicons.customIconFolderPath": "C:/Users/aquad/AppData/Roaming/Code/User",
  "vsicons.associations.folderDefault.folder": {
    "icon": "myFolder",
    "format": "svg"
  }
```
How I set up the files
![alt text](https://i.imgur.com/3deKuYn.png "")

The result is an empty space
![alt text](https://i.imgur.com/QnINc1k.png "")

**Comment by JimiC** [comment]
1. You don't need to set `vsicons.customIconFolderPath` anymore for the default location.
2. See [wiki](https://github.com/vscode-icons/vscode-icons/wiki/Custom) for the correct icon filename naming convention (specifically where it says `and for folder icons`...)

**Comment by sexling** [comment]
It works, thanks buddy and have an awesome day!
