### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jcpjstartups** [vscode-icons/vscode-icons#1973]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.5.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Volumes/Files/Users/jc/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
No /Volumes/Files/Users/jc/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt
