### ISSUE TITLE
Folder icons in explorer/workspace not showing

### ISSUE THREAD

**Issue by chris-c-thomas** [vscode-icons/vscode-icons#1974]
I'm actually not sure if this is an issue, so please feel free to close if it is, but since the last update I've noticed I no longer have icons for folders in my workspace. Just the expand arrows. 

The only related PR in the changelog I could find is this: https://github.com/vscode-icons/vscode-icons/pull/1954 though I've not using any custom icons, just the defaults. 

macOS 10.14.4
VSCode 1.33.0
VSCode-Icons 8.5.0

**Comment by chris-c-thomas** [comment]
Closing. I'm an idiot. For whatever reason a different icon theme was enabled after the update. That in itself might be an issue but all is well regarding my folder icons. 

It's amazing how much I've come to rely on folder/file icons. I just spent 10 minutes lost in my projects.

**Comment by jamesdixon** [comment]
@chris-c-thomas FWIW, I had this happen as well and no other icon themes installed. Turns out I had to go back in and hit the "Set File Icon" option in the plugin in order for folder icons to show up again. Hopefully, this is helpful for others.

**Comment by robertohuertasm** [comment]
Thanks for reporting it. We're aware of this and working on it.
