### ISSUE TITLE
Go icons

### ISSUE THREAD

**Issue by jbrodriguez** [vscode-icons/vscode-icons#1975]
- [x] I'm sure this issue is not a _duplicate_.

The Go icon is now a blue gopher, that looks more like a ghost.

![Screen Shot 2019-04-11 at 16 49 25](https://user-images.githubusercontent.com/1305422/55995406-fe5fcc00-5c79-11e9-95f3-b43923553be3.png)

I liked the previous icon (Go text, also in line with official branding).

Any chance to get back the previous one ?

**Comment by robertohuertasm** [comment]
As far as I know the current icon is the official one, not the gopher. I use go every day and the icons I see are not these ones. What version of the extension are you using? Are you sure is our extension? It's not the first time that happens that people change the icons without noticing.

**Comment by jbrodriguez** [comment]
Thanks for the reply !

Using vscode-icons v8.5.0

The only other go-related extension I'm using is ms-vscode.go, which I don't believe is touching icons (v0.9.2)

So ... I uninstalled/reinstalled and it prompted for a File/Icon theme ? (can't quite remember).

Options were Seti and VSCode ... choosing VSCode fixed it.
