### ISSUE TITLE
[Icon Request] Support for Jest __mock__ folders

### ISSUE THREAD

**Issue by Abuntxa** [vscode-icons/vscode-icons#1977]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension, filename, language id`
  - Icon Name: `jest mocks`
  - Sample original Icon: `N/A`
  - Extensions: `none(folder)`
  - Filenames: `**/__mocks__`
  - Language ids: `typescript, javascript`

- Language Extensions:
- More info:
The javascript and typescript unit testing framework [Jest](https://jestjs.io/en/), allows defining mocks of your own modules by creating a subfolder __mocks__ as explained [here](https://jestjs.io/docs/en/manual-mocks#mocking-node-modules).

vscode-icons already has a rule to identify the jest test folders that allows to easily identify what part of the folder structure belongs to the unit testing and what to the production code.
The mocks folder belongs to the unit testing part but it cannot be easily identified because of the lack of specific icon. 

The basic need would be to have an icon for the "__mocks__" folder.

The full solution would be to have a new mock icon for the folder and variants of it for the subfiles describing the type of the file (ts for typescript, js for javascript)

I have attached an image with an example of how it is seen right now.

![vsCodeIcons](https://user-images.githubusercontent.com/8349465/56296247-63aa3600-612e-11e9-9176-c4255deef906.PNG)

**Comment by JimiC** [comment]
Please see #650
