### ISSUE TITLE
Two different Typescript files have different colored icons?

### ISSUE THREAD

**Issue by joshball** [vscode-icons/vscode-icons#1987]
- [x] I'm sure this issue is not a _duplicate_.

```
vscode ver 1.33.1 (Windows)
vscode-icons ver: 8.5.0
```
Two different typescript files have two different colored icons. Any thoughts on why or this a bug? 

![image](https://user-images.githubusercontent.com/127526/56461160-75c4e800-636b-11e9-89fe-bfd1f9420b36.png)

If for some reason colors change based on state, feel free to point me to the documentation (I did searches, but haven't seen anything yet).

Thanks!

**Comment by joshball** [comment]
OK, I just figured out why. ;-) Test file. `*.spec.ts*`
Fair enough. With this knowledge, I still can't find documentation on that. Maybe a wiki page on these kind of differences?

**Comment by KingDarBoja** [comment]
@joshball There is a [wiki](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles) listing all files and folders supported by this extension.

**Comment by JimiC** [comment]
These are not our icons.

**Comment by robertohuertasm** [comment]
Closing this as it's clear that @joshball is not using our icon set. 

@joshball check your settings, I'm sure you're using Seti. 😉

**Comment by joshball** [comment]
@JimiC and @robertohuertasm you are correct. I think in my effort to debug the plugin got disabled. I apologize for the incorrect report. Thanks for your efforts.
