### ISSUE TITLE
[BUG] vscode-icons needs re-activation after new version installation and editor restart

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#2017]
- [x] I'm sure this issue is not a _duplicate_.

It came to my attention that `vscode-icons` requires re-activation when a new version is released and after closing and re-opening `vscode` (not after reload).

This is caused because `vscode`, on the restart, executes the `uninstall` script to remove the previous version and in that script, we do a clean-up that includes the removal of the `workbench.iconTheme` setting.

**Comment by drweb86-work** [comment]
Please consider fixing this.
