### ISSUE TITLE
How to indent the code outline of the workspace

### ISSUE THREAD

**Issue by Rain120** [vscode-icons/vscode-icons#2020]
OS Version: Windows 10 1809

Vscode version:

![Vscode version](https://user-images.githubusercontent.com/20939839/56375310-b7547680-6237-11e9-821e-71404a33c3f4.png)

VScode-icons Version:

![image](https://user-images.githubusercontent.com/20939839/56574140-1974f900-65f5-11e9-851f-19778da3b633.png)

Current situation：
![Current situation](https://user-images.githubusercontent.com/20939839/56375121-47de8700-6237-11e9-9ef2-14b70acb4575.png)

Expect:
![Expect](https://user-images.githubusercontent.com/20939839/56375319-c0454800-6237-11e9-9187-07781ee73581.png)

vscode-icon theme: vsocde-icons

[More Details in VSCode issue](https://github.com/Microsoft/vscode/issues/72568)

**Comment by JimiC** [comment]
Please see https://github.com/Microsoft/vscode/issues/72568#issuecomment-485749843
