### ISSUE TITLE
Support .cjs as a JavaScript file

### ISSUE THREAD

**Issue by bnb** [vscode-icons/vscode-icons#2027]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `javascript`
  - Sample original Icon: ![logo](https://github.com/vscode-icons/vscode-icons/raw/master/icons/file_type_js.svg?sanitize=true)
  - Extensions: `.cjs`

- More info:
Since Node.js shipped v12.0.0, the `.cjs` extension is now supported as a JavaScript file that will be explicitly parsed as a CommonJS module (as opposed to a ES Module with `.mjs`).

This file extension was added with the explicit intention to lower the barrier for supporting both ESM and CommonJS. For more context, you can read the [official post](https://medium.com/@nodejs/announcing-a-new-experimental-modules-1be8d2d6c2ff) from the Node.js Modules Team on Medium ❤️

**Comment by JimiC** [comment]
We are going to leave this to be supported by `vscode` directly.
