### ISSUE TITLE
[Icon Request] Support for Kubernetes files

### ISSUE THREAD

**Issue by sircrapsalot** [vscode-icons/vscode-icons#2032]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `kubernetes`
  - Sample original Icon: ![logo](https://github.com/kubernetes/community/blob/master/icons/svg/resources/unlabeled/deploy.svg)
  - Filenames: `kubernetes-deployment.yml`, `kubernetes-deployment.yaml`, `kubernetes-service.yml`, `kubernetes-service.yaml`

**Comment by JimiC** [comment]
Any documentation?

**Comment by sircrapsalot** [comment]
What kind of documentation are you looking for? On the naming convention or on Kubernetes in general?

**Comment by JimiC** [comment]
The naming.

**Comment by sircrapsalot** [comment]
Here is an example of a deployment file.  https://kubernetes.io/docs/concepts/workloads/controllers/deployment/.

**Comment by JimiC** [comment]
From what I'm seeing the pattern is `*-deployment.yaml`. Unfortunately, we can't support glob patterns simply because `vscode` does not support that either.

So I have to decline your request. But you can use our customization feature to assign the icon to the namings your use in your projects.

**Comment by sircrapsalot** [comment]
That's too bad! Thanks for checking!
