### ISSUE TITLE
Latest Updates Corrupts User Settings File

### ISSUE THREAD

**Issue by atom0s** [vscode-icons/vscode-icons#2034]
- [x] I'm sure this issue is not a _duplicate_.

While I don't think this is considered a duplicate, it does tie into this issue about reactivation partially: https://github.com/vscode-icons/vscode-icons/issues/2017

If you have custom overrides for files to display icons via the following user configuration key:

```
"vsicons.associations.files":
```

When you update, you are forced to reactivate the extension due to some bug. However, upon doing so, the users setting file will corrupt, as vs-icons will delete this key partially. It only deletes the actual key and not the values leaving a half-broken file behind.

By this, I mean that my custom configuration for this looked like:

```
    "vsicons.associations.files": [{
            "icon": "css",
            "extensions": ["scs"],
            "format": "svg"
        },
        {
            "icon": "html",
            "extensions": ["shtm", "shtml"],
            "format": "svg"
        },
        {
            "icon": "js",
            "extensions": ["tis"],
            "format": "svg"
        }
    ],
```

After updating, then attempting to force-reactivate the extension as required due to this issue, the following is what is seen in the file:

```
        {
            "icon": "html",
            "extensions": ["shtm", "shtml"],
            "format": "svg"
        },
        {
            "icon": "js",
            "extensions": ["tis"],
            "format": "svg"
        }
    ],
```

The entire key and first entry were gone. Mainly the key itself is the biggest problem as it causes the settings file to be 'corrupt'.

I had this happen on both my desktop and laptop today while updating, same setup with same outcome.

**Comment by JimiC** [comment]
This is related to #2017.
