### ISSUE TITLE
[Icon Request] Support for Remark

### ISSUE THREAD

**Issue by remcohaszing** [vscode-icons/vscode-icons#2036]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `remark`
  - Sample original Icon: ![logo](https://avatars2.githubusercontent.com/u/16309564)
  - Filenames: `.remarkrc.js`

- More info: Remark is a tool that works with Markdown. It includes a [parser](https://github.com/remarkjs/remark/tree/master/packages/remark-parse), [linter](https://github.com/remarkjs/remark-lint), and [CLI](https://github.com/remarkjs/remark/tree/master/packages/remark-cli), and itegrates with other tools. The CLI uses a file named _.remarkrc.js_ for its configuration.

**Comment by KingDarBoja** [comment]
The official icon as you can see at [RemarkJS GitHub](https://github.com/remarkjs/remark#) is the entire `remark` work. So not  very excited to make a text-only icon.

**Comment by JimiC** [comment]
My suggestion is to use the red `r` and the black `m` (but not in black for dark themes).

**Comment by KingDarBoja** [comment]
@JimiC We should take into account these ones too: [UnifiedJS](https://unified.js.org/)

**Comment by JimiC** [comment]
Do we have a request for `UnifiedJS`?

**Comment by KingDarBoja** [comment]
Not what I mean, just scroll down and check the other 2 syntax along with remark: Rehype and Retext 🤔

**Comment by JimiC** [comment]
I see. Same principal. `rm` for `remark` (red-ish), `rh` for `rehype` (yellow-ish), `rt` for `retext` (green-ish).
