### ISSUE TITLE
[Icon Request] Laravel's `artisan` file

### ISSUE THREAD

**Issue by g-plane** [vscode-icons/vscode-icons#2042]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `laravel`
  - Sample original Icon: There is an existing Laravel logo in this repo.
  - Extensions: (No)
  - Filenames: `artisan`
  - Language ids: (No)

- Language Extensions: No.

**Comment by JimiC** [comment]
Please provide a link to any documentation that can help us better understand your request.

**Comment by g-plane** [comment]
It seems that there is a similar issue: https://github.com/vscode-icons/vscode-icons/issues/870 .

**Comment by JimiC** [comment]
Still. We don't all use `Laravel` so don't assume we know all about it.

**Comment by g-plane** [comment]
We can use an existing icon, e.g. the icon for `.blade.php`.

**Comment by JimiC** [comment]
Beside that, I would like to know what `Artisan` is and whether it should be supported.

**Comment by g-plane** [comment]
It's just a executable PHP script. You can imagine that it's a file like `node_modules/.bin/blah.js`.

**Comment by JimiC** [comment]
So. Is `artisan` just a filename? Is it a file extension? Is it something else?
If you don't want me to get on your nerves please read https://github.com/vscode-icons/vscode-icons/wiki/Issue and adjust the OP accordingly.

**Comment by g-plane** [comment]
It's just a filename without extension. Sorry for confusing.

**Comment by KingDarBoja** [comment]
From the [Laravel Docs](https://laravel.com/docs/5.0/artisan)

> Artisan is the name of the command-line interface included with Laravel. It provides a number of helpful commands for your use while developing your application. It is driven by the powerful Symfony Console component.

So I don't think it is a filename neither a script...

**Comment by JimiC** [comment]
https://laravel.com/docs/5.8/artisan#writing-commands

**Comment by KingDarBoja** [comment]
I do think it is better to close this issue @JimiC, I have been looking at the docs and also googling some examples and seem like those generated command files are php files.

There isn't nothing related to a `artisan` filename as stated by the author.
