### ISSUE TITLE
Improve/configure support of NX Workspace

### ISSUE THREAD

**Issue by gperdomor** [vscode-icons/vscode-icons#2048]
- [x] I'm sure this issue is not a _duplicate_.

Hi.... I'm working with a Nx Project with some Angular and some NestJS apps, at least for now, i don't have React apps...

I'm getting this message...

<img width="456" alt="Screen Shot 2019-05-03 at 8 49 24 AM" src="https://user-images.githubusercontent.com/371939/57138338-6c327b80-6d80-11e9-84ac-eebff078cf96.png">

Is possible to setup which folders are Angular apps, and which one are NestJS to get the proper icons in each of them?

**Comment by JimiC** [comment]
See https://github.com/vscode-icons/vscode-icons/issues/1925#issuecomment-476273935

**Comment by JimiC** [comment]
Also, duplicate of #1939 but who cares.

**Comment by gperdomor** [comment]
@JimiC well... is not a duplicated of #1939, I'm just asking about the possibility of configure the icon preset in a folder scope level instead a global workspace, not about a restart loop 😄...

I think this issue should be open again

**Comment by JimiC** [comment]
I corrected my comment about the duplicate. The reference to the comment I made in #1925 is your answer.

**Comment by JimiC** [comment]
@gperdomor I like to apologize for my bluntness yesterday. I had an issue that got on my nerves at the time but this is not an excuse to be blunt to others.
To the point, `vscode` has tech limitations when it comes to icons themes. You see, it does not have any mechanism to determine the icon to use other than the file extension or the filename itself (and the `languageid` when it comes to 3rd party `vscode` extensions).
In NX Workspace projects, `Angular` and `Nest` file extensions, for some files, are the same and therefore we can enable only one or the other icon set. Never both. The only trick I could find was explained in https://github.com/vscode-icons/vscode-icons/issues/1925#issuecomment-478358795.

I hope you got the explanation you were seeking and forgive me.
