### ISSUE TITLE
Elixir's .html.eex files are now shown

### ISSUE THREAD

**Issue by ahmetcetin** [vscode-icons/vscode-icons#2052]
- [x] I'm sure this issue is not a _duplicate_.
Related with closed #1414 

- Language Extensions: .html.eex
- More info:

.html.eex files are not showing the icon, I see it was closed by #1414 but now it's not working again, either I don't know how to set it up to enable it, or it became broken again by new releases since then.

<img width="431" alt="Untitled" src="https://user-images.githubusercontent.com/5046786/57441215-c41e2600-7249-11e9-9fa2-cc9cdd17dead.png">

**Comment by JimiC** [comment]
See https://github.com/vscode-icons/vscode-icons/issues/1414#issuecomment-490820667
