### ISSUE TITLE
[Icon Request] Support for Hunspell

### ISSUE THREAD

**Issue by remcohaszing** [vscode-icons/vscode-icons#2057]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId`
  - Icon Name: `hunspell`
  - Sample original Icon: ![logo](https://github.com/Jason3S/vscode-hunspell-ext/blob/master/images/hunspell.png?raw=true)
  - Extensions: `.aff`, `.dic`
  - Language ids: `hunspell.aff`, `hunspell.dic`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.hunspell
- More info:

Hunspell doesn’t appear to have an official icon. However, the linked VSCode extension does have an icon. This icon could be used.

**Comment by KingDarBoja** [comment]
I have a icon idea for this one: A wizard making a spell using some kind of dictionary or book on a paper.

It could use the Hungary Flag colors since it is being developed by a hungary team (and sponsors).

**Comment by remcohaszing** [comment]
@KingDarBoja Your idea sound really cool! Perhaps the book could have different colors for `.aff` and `.dic` files.

**Comment by JimiC** [comment]
The simplest the icon the better. Too much details and the icon will not be visible.

**Comment by KingDarBoja** [comment]
After thinking a bit about my first idea, I decided to scrap the wizard face and just put a hat instead.

![hunspell](https://user-images.githubusercontent.com/30560560/60760544-96145280-9ffc-11e9-8bb0-cc6d01972af5.PNG)

**File size: 3.44 kB.**

**Comment by JimiC** [comment]
Lose the stars and the stick. It will reduce the file size further.
