### ISSUE TITLE
vscode-icons install on remote SSH

### ISSUE THREAD

**Issue by PatrLind** [vscode-icons/vscode-icons#2058]
- [ ] I'm sure this issue is not a _duplicate_.

So I tried the new Remote SSH feature in the VS Code Insiders today. Logged in to a Linux machine from my Windows developer machine.
However, it seems like the vscode-icons extension doesn't work with this mode. The icons in the remote session is not from vscode-icons and it seems there is no way to install the extension remotely either. I assume this is by design because the icons should probably only be on my Windows machine (in this case). But still, I assume the icons would be shown in the file browser.

I am not sure if this is this a bug in vscode-icons or some configuration error on my part.

**Comment by JimiC** [comment]
Please see https://github.com/vscode-icons/vscode-icons/issues/2045
