### ISSUE TITLE
[Icon Request] Support for Inno Setup

### ISSUE THREAD

**Issue by huiyifyj** [vscode-icons/vscode-icons#2059]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Inno Setup`
  - Extensions: `.iss`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=idleberg.innosetup
- More info:
  HomePage: http://www.jrsoftware.org/
![innoSetup](https://user-images.githubusercontent.com/32027253/57967471-e9214000-7991-11e9-8553-e3dffb316e47.png)

**Comment by huiyifyj** [comment]
[file-icon](https://github.com/file-icons/vscode) support `.iss` extension file, but its format supported is `ttf`, not `svg`.

**Comment by KingDarBoja** [comment]
This one is a hard to make due to the gradient pattern on the official logo.

The good thing is that file-icon has an svg (black and white) version of the [icon](https://raw.githubusercontent.com/file-icons/source/master/svg/InnoSetup.svg?sanitize=true) so probably gonna base my work on it.

**Comment by huiyifyj** [comment]
Thanks.
