### ISSUE TITLE
[Icon Request] Support for tox file

### ISSUE THREAD

**Issue by jadchaar** [vscode-icons/vscode-icons#2065]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `tox`
  - Sample original Icon: ![tox](https://tox.readthedocs.io/en/latest/_static/img/tox.png)
  - Filenames: `tox.ini`

- More info: https://tox.readthedocs.io/en/latest/

**Comment by JimiC** [comment]
Any documentation link would be highly appreciated.

**Comment by jadchaar** [comment]
Hi @JimiC, here it is: https://tox.readthedocs.io/en/latest/
