### ISSUE TITLE
[Icon Request] Support for .cfg file

### ISSUE THREAD

**Issue by yousef157** [vscode-icons/vscode-icons#2075]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `cfg`
  - Sample original Icon: 
![image](https://user-images.githubusercontent.com/48018938/59051301-95718a80-889d-11e9-94b6-266d2a09e084.png)

  - Filenames: `example.cfg`

- More info: It's the same as an .config file, but shortened. _**c**_on_**f**_i_**g**_

**Comment by JimiC** [comment]
What language are you using?

**Comment by yousef157** [comment]
Not really a programming language, but Valve's Source engine.

**Comment by JimiC** [comment]
This file extension is natively supported by `vscode`. https://github.com/microsoft/vscode/blob/master/extensions/ini/package.json#L21

You should see the icon. If not check what is messing with it.

**Comment by yousef157** [comment]
https://www.streamable.com/7iwrh

Video that shows the problem. I think nothing's messing with it.
I tried uninstalling and installing, but it's still broken.

**Comment by JimiC** [comment]
Try `F1 > Icons > Activate VSCode Icons`

**Comment by yousef157** [comment]
https://www.streamable.com/vi74n

**Comment by JimiC** [comment]
I don't and I can't know what's going on with your installation but as I have proved, `cfg` is already supported natively by `vscode`.

Some more advice I can give is:
- disable all extensions except `vscode-icons`
- check your user and workspace settings for any file association highjacking
