### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by marrik96** [vscode-icons/vscode-icons#2078]
- [x ] I'm sure this issue is not a _duplicate_.
- [x ] I'm submitting an icon request:
  - Type: Folder Icon
  - Icon Name: Azure
  - Sample original Icon: ![logo]()
  - Extensions: No extension, folder icon
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info: Similar to folder icons for GCP, and AWS.
![Azure-Icon-Folder-request](https://user-images.githubusercontent.com/22241571/59148173-efbc3980-89ca-11e9-97aa-73705c6aa393.png)

**Comment by JimiC** [comment]
#650
