### ISSUE TITLE
[Icon Request] Support for Nearley Grammar File.

### ISSUE THREAD

**Issue by Floffah** [vscode-icons/vscode-icons#2079]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `nearley grammer`
  - Sample original Icon: `no icons on the internet`
  - Filenames: `grammar.ne` (most commonly used)
  - Extension: `.ne`
  - Language Extensions: [click here](https://marketplace.visualstudio.com/items?itemName=karyfoundation.nearley)

- More info:[Nearley docs](https://nearley.js.org/docs/) [Nearley github](https://github.com/kach/nearley)

**Comment by KingDarBoja** [comment]
Closed via #2077
