### ISSUE TITLE
[Icon Request] Support for Dojo

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/vscode-icons#2084]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `dojo`
  - Sample original Icon: ![logo](https://dojo.io/images/logos/dojo2-logo-white.svg)
  - Filenames: `.dojorc`

- Language Extensions: None, it uses Typescript.
- More info: [Dojo](https://dojo.io/) [Dojo/cli](https://github.com/dojo/cli) [Dojo2 Example App](https://github.com/gothinkster/dojo2-realworld-example-app)

From the Dojo/cli docs:

> Dojo CLI commands support a JSON configuration file at the root of the project called .dojorc . Each command has a dedicated section in the .dojorc keyed by the command name minus the cli- prefix.

**Comment by JimiC** [comment]
Nice colorful icon. Me likey.
