### ISSUE TITLE
[Icon Request] Support for Jest Snapshot

### ISSUE THREAD

**Issue by remcohaszing** [vscode-icons/vscode-icons#2091]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId`
  - Icon Name: `Jest Snapshot`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_jest.svg?sanitize=true)
  - Extensions: `.js.snap`, `.jsx.snap`, `.ts.snap`, `.tsx.snap`
  - Language ids: `jest-snapshot`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest
- Language Definition: https://github.com/jest-community/vscode-jest/blob/master/package.json#L34-L46

**Comment by KingDarBoja** [comment]
@JimiC  Just curious, why the `Jest` icon color is different from the [official](https://github.com/facebook/jest/blob/04e6a66d2ba8b18bee080bb28547db74a255d2c7/website/static/img/jest.png) one?.

**Comment by JimiC** [comment]
I believe it had that color then.
