### ISSUE TITLE
[Icon Change] Bash Official Icon

### ISSUE THREAD

**Issue by KingDarBoja** [vscode-icons/vscode-icons#2096]
- [x] I'm sure this issue is not a _duplicate_.

The GNU Bash has an official logo as you can check at the [official site](https://www.gnu.org/software/bash/) under the maintainer bash link. Currently the `vscode-icons` extensions uses a different icon (a shell window) so would be great if it gets updated with the official one (which looks awesome).

The source icon is available at: [official bash logo github](https://github.com/odb/official-bash-logo)

**Comment by JimiC** [comment]
Our icon attempts to support all flavors of `shell` (ie. `sh`, `bash`, `zsh`, `csh`, etc).
I don't see any reason to change it, especially to `bash` icon which does not represent the other flavors.

**Comment by robertohuertasm** [comment]
The logo is super cool but I think the same as @JimiC  in this regard.

**Comment by KingDarBoja** [comment]
Argghhh, my bad! Didn't know that the official vscode extension included those flavors of `shell`. I thought it was different for each OS.
