### ISSUE TITLE
[Icon Request] - Ngrx folder icon

### ISSUE THREAD

**Issue by GabriMagic** [vscode-icons/vscode-icons#2108]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `Icon Request`
  - Icon Name: `ngrx_folder`
  - Sample original Icon: ![logo](https://ngrx.io/assets/images/badge.svg)
  - Extensions: `none`
  - Filenames: `folders` (no files)
  - Language ids: `none`

- Language Extensions: none
- More info: 

As Redux have an icon folder for a folder named "redux" I would ask for a similar icon for the "ngrx" folder with his icon.

**Comment by JimiC** [comment]
See #650
