### ISSUE TITLE
[Icon Request] A folder name inc should have the same icon as the folder include

### ISSUE THREAD

**Issue by isaumya** [vscode-icons/vscode-icons#2114]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:

- More info: Currently if I create a folder name `include` it gets a separate ash colour icon. But when I create a folder called `inc` which is basically the short form of the above, it got no special icons. I think it should be fixed and they both should have the same icon.

**Comment by JimiC** [comment]
#650
