### ISSUE TITLE
[Icon Request] Support for Confluence and Jira [Atlassian]

### ISSUE THREAD

**Issue by ougarte** [vscode-icons/vscode-icons#2118]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension `
  - Icon Name: `atlassian`
  - Sample original Icon: ![logo](https://atlassian.gallerycdn.vsassets.io/extensions/atlassian/atlascode/1.4.0/1558123121475/Microsoft.VisualStudio.Services.Icons.Default)
  - Extensions: `.confluence .jira .wiki .markup` 
- More info: [VSCode Confluence Markup plugin](https://marketplace.visualstudio.com/items?itemName=denco.confluence-markup)

**Comment by JimiC** [comment]
This can be supported via `language id`.

**Comment by KingDarBoja** [comment]
I do rather use the [official confluence logo](https://es.atlassian.com/company/news/press-kit) instead of the Atlassian Company due to being used as `language id`.
