### ISSUE TITLE
[Icon Request] Support for extension pages

### ISSUE THREAD

**Issue by SimonSiefke** [vscode-icons/vscode-icons#2130]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request for extension pages. Currently vscode-icons uses the same icon as for a new file: 
![vscode-icons](https://user-images.githubusercontent.com/23744935/60900166-0d035280-a26c-11e9-8957-0c1de765d7e6.png)

**Comment by jens1o** [comment]
I'm not sure whether this is possible, yet. However, I couldn't find a vscode issue for this.

**Comment by SimonSiefke** [comment]
Closing as this is now supported by VSCode :)
