### ISSUE TITLE
[Icon Request] Support for memcached

### ISSUE THREAD

**Issue by muuvmuuv** [vscode-icons/vscode-icons#2131]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `memcached`
  - Sample original Icon: ![logo](https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Memcached.svg/480px-Memcached.svg.png)
  - Website: https://memcached.org/

There is not really a norm for memcached folders but it would look kind of good to have an icon on a folder named memcached. In my case e.g. I have a nginx, php and mariadb folder inside my docker folder with a custom icon but the memcached is just default which looks kind of weird. Would be great to have a memcached folder icon with one little creepy demon on it with their color (#524745).

I have made two quick samples:

![memcached-closed](https://user-images.githubusercontent.com/11534760/60946699-26011780-a2ef-11e9-8209-b0b645d4caca.png)
![memcached-opened](https://user-images.githubusercontent.com/11534760/60946700-26011780-a2ef-11e9-9875-5076d047b86a.png)

**Comment by JimiC** [comment]
#650
