### ISSUE TITLE
[Icon Request] Support ".k8s" folders to use the existing "k8s" folder icon

### ISSUE THREAD

**Issue by mmisztal1980** [vscode-icons/vscode-icons#2134]
- [ x] I'm sure this issue is not a _duplicate_.
- [x ] I'm submitting an icon request
  
The "k8s" folders use a nice kubernetes icon. Recently we have renamed all of our "k8s" folders into ".k8s". This has moved all the ".k8s" folders to the top of their parent containers, however we appear to have lost the icon associated with the "k8s" folder.

It would be great to get the icon back for improved visibility.

**Comment by JimiC** [comment]
#650
