### ISSUE TITLE
[Icon Request] For ReStructedText

### ISSUE THREAD

**Issue by pynickle** [vscode-icons/vscode-icons#2136]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `icon requests`
  - Icon Name: `ReST`
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: `xxx.rst/xxx.rest`
  - Language ids: `rst`

- Language Extensions:
- More info:
reStructedText document(a text markup language like markdown) : http://docutils.sourceforge.net/rst.html

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

**Comment by JimiC** [comment]
https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext
