### ISSUE TITLE
[Icon Request] Support for Riot JS v4+ (.riot files)

### ISSUE THREAD

**Issue by adrianvoica** [vscode-icons/vscode-icons#2137]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `riot`
  - Sample original Icon: ![logo](https://riot.js.org/img/logo/square.svg)
  - Extensions: ``
  - Filenames: `riot`
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by JimiC** [comment]
Already [supported](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#riot) via https://marketplace.visualstudio.com/items?itemName=nesterow.riot-vsc

If you want to request an icon update modify the issue accordingly and reopen it.

**Comment by adrianvoica** [comment]
@JimiC thanks for pointing that out. Actually, that (old) logo is from the old format (v3 and below) that had a default filename extension of '.tag'. The '.riot' extension is the default for the newer versions of the framework (v4+). I will reopen this as an Update Icon Request. Cheers!
