### ISSUE TITLE
[Icon Request] Support for Biml (Business Intelligence Markup Language)

### ISSUE THREAD

**Issue by zbecknell** [vscode-icons/vscode-icons#2142]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `Biml`
  - Sample original Icon: ![logo](https://github.com/zbecknell/biml-support/blob/master/assets/icon.png)
  - Language ids: `biml`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=zbecknell.biml-support
- More info: https://www.varigence.com/Biml

I received a request to add `biml` support, which is very similar to my existing T4 template syntax extension.

**Comment by KingDarBoja** [comment]
@zbecknell You own extension at marketplace? Nice! 👍

**Comment by zbecknell** [comment]
Yes, I added the extension for Biml support.  Thanks so much for the great work on vscode icons!
