### ISSUE TITLE
[Icon Request] Support for Renovate Bot.

### ISSUE THREAD

**Issue by dantehemerson** [vscode-icons/vscode-icons#2143]
Add icon for [renovate bot](https://github.com/apps/renovate) config file.

- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename, extension`
  - Icon Name: `renovatebot`
  - Sample original Icon: ![logo](https://avatars3.githubusercontent.com/u/38656520?s=400&v=4)
  - Extensions: `.json`
  - Filenames: `renovate.json`
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
More info: [Renovate Config](https://renovatebot.com/docs/configure-renovate/)

Be sure to provide such information when opening a new issue.

Cheers!

**Comment by dantehemerson** [comment]
@KingDarBoja  Thanks!!! 🤗
