### ISSUE TITLE
[Icon Request] Support for .prisma

### ISSUE THREAD

**Issue by SamuelColacchia** [vscode-icons/vscode-icons#2144]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `prisma`
  - Sample original Icon: 
![logo_dark](https://raw.githubusercontent.com/prisma/presskit/master/Logo%20Symbol%20Dark.svg?sanitize=true)
  - Extensions: `.prisma`

- More info:
Here is a link to [Prisma's presskit](https://github.com/prisma/presskit)

**Comment by KingDarBoja** [comment]
Just as extra info: [VSCode Marketplace Prisma](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)
