### ISSUE TITLE
[Icon Request] Befunge93 and Befunge98 languages

### ISSUE THREAD

**Issue by kagof** [vscode-icons/vscode-icons#2151]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `Language`
  - Icon Name: `Befunge`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/kagof/VSCode-Befunge/master/assets/icon.png)
  - Extensions: `.bf`, `.befunge`, `.b93`, `.b98`
  - Filenames: ``
  - Language ids: `befunge`, `befunge98`

- Language Extensions: Befunge: [repo](https://github.com/kagof/VSCode-Befunge), [marketplace](https://marketplace.visualstudio.com/items?itemName=kagof.befunge)
- More info:

Befunge is an Esoteric programming language.

I've searched far and wide for an "official" icon for Befunge, but haven't found one. I created the one above for the Befunge VSCode extension, but I am *definitely* not a graphic designer, and acknowledge that it likely leaves much to be desired. I'd be thrilled if someone designed their own or improved on (or gave me some pointer on how to improve on) this one.

**Comment by KingDarBoja** [comment]
I will see what I can do, pretty crazy language we got here 😨
