### ISSUE TITLE
Calling to all our fellow translators

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#2158]
Hi friends, 

Before we release `v9.0.0` we would like to have all translations finished.

We're calling for help to:

- [ ] :fr: @MonsieurMan
- [x] :de: @jens1o
- [x] :it: @mariotsi @sabinrimni
- [ ] :jp: @kimushu
- [x] :brazil: @cgarbin
- [ ] :ru: @ksvitkovsky
- [x] :cn: @iFun @g-plane
- [x] :es: @robertohuertasm
- [ ] :tr: @kendinikertenkelebek

Btw, if you happen to be `Korean` or `Taiwanese` and want to support this project by providing proper translations for your language, get in touch with us by answering to this thread. We'll be very glad to talk to you! 😉

**Comment by mariotsi** [comment]
Italian 👍🏻

**Comment by g-plane** [comment]
It seems that the translation progress has been moved to Crowdin, right?

**Comment by JimiC** [comment]
Yes. you can login with `GitHub` credentials.

**Comment by cgarbin** [comment]
Hi Jimi,

https://crowdin.com/project/vscode-icons-i18n doesn't show any pending
string for Portuguese.

Looks like you approved several suggestions earlier today. Seems like it's
all in sync now.

Christian

**Comment by JimiC** [comment]
Yes. Those translators that have the checkbox checked means that they are OK.

**Comment by iFun** [comment]
updated

**Comment by kendinikertenkelebek** [comment]
Turkish translations are updated.

**Comment by robertohuertasm** [comment]
Thanks @kendinikertenkelebek!
