### ISSUE TITLE
[Icon Request] Support for PlatformIO

### ISSUE THREAD

**Issue by ivankravets** [vscode-icons/vscode-icons#2159]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`, `language id`
  - Icon Name: `platformio`
  - Sample original Icon: https://raw.githubusercontent.com/platformio/platformio-vscode-ide/develop/resources/platformio-mini-logo.svg
  - Filenames: `platformio.ini`
  - Language Ids: see https://github.com/platformio/platformio-vscode-ide/blob/develop/package.json#L40

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=platformio.platformio-ide
- More info: https://github.com/platformio

**Comment by KingDarBoja** [comment]
How could I miss such wonderful extension for Atom and VSCode? 😍

**Comment by ivankravets** [comment]
Thanks 🙏 👍😊🎊
