### ISSUE TITLE
插件完整性受到了破坏不能启用

### ISSUE THREAD

**Issue by 734204679** [vscode-icons/vscode-icons#2167]
Issue Type: <b>Feature Request</b>

插件完整性受到了破坏不能启用，重新安装也一样

Extension version: 9.0.0
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

**Comment by JimiC** [comment]
English please
