### ISSUE TITLE
The integrity of the extension is compromised. There is NO guarantee that the extension will work as designed.

### ISSUE THREAD

**Issue by xiaolu0018** [vscode-icons/vscode-icons#2169]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by xiaolu0018** [comment]
![image](https://user-images.githubusercontent.com/24520667/62042945-d6e53d00-b231-11e9-8e10-031eea480ddf.png)

**Comment by tavrez** [comment]
#2165
