### ISSUE TITLE
Angular icons not show in v9.1.0

### ISSUE THREAD

**Issue by brunosotto** [vscode-icons/vscode-icons#2176]
I upgraded today to version 9.1.0 and all angular icons disappeared.
HTML, SCSS, Folders, .spec.ts icons are appearing normally.
vscode 1.36.1
MacOS Mojave 10.14.5

**Comment by JimiC** [comment]
Screenshot please

**Comment by rbrewington** [comment]
Seconded @JimiC 
![Screen Shot 2019-07-29 at 3 28 19 PM](https://user-images.githubusercontent.com/25082725/62080078-8bbd3100-b215-11e9-92cb-f91c68715b8c.png)

Module file action-button-list.module.ts used to have a purple angular icon. 
Component file action-button-list.component.ts used to have a red angular icon.

**Comment by robertohuertasm** [comment]
@rbrewington have you tried `Apply icons customizations`? I just tested it and worked. If it doesn't work. Try again this sequence:
- Toggle Angular preset
- Apply icons customizations

**Comment by rbrewington** [comment]
Does not seem to have worked for me, unfortunately :(

**Comment by rbrewington** [comment]
If I install version 8.8.0, I get prompted to restart because an angular project was detected. And then the icons work.

If I install version 9.0.0 or higher, I get no prompt, and no combination of settings seems to get it to show the angular icons.

**Comment by robertohuertasm** [comment]
Just to confirm, you used `Apply icons customizations` option, didn't you?

**Comment by rbrewington** [comment]
@robertohuertasm Yes. several times.

**Comment by robertohuertasm** [comment]
Which operating system are you using?

**Comment by rbrewington** [comment]
MacOS Mojave v10.14.5

**Comment by robertohuertasm** [comment]
Is your Angular repo a monorepo? Do you have several `package.json` files? I know it used to work for you in previous versions but just to see what would make the difference since I cannot reproduce it for the moment on my side.

**Comment by rbrewington** [comment]
No, there's only one package.json

**Comment by robertohuertasm** [comment]
So, no `workspace` project either I guess...

**Comment by rbrewington** [comment]
Hmm, I'm not sure what you mean by workspace project, so I'm going to say no.

**Comment by robertohuertasm** [comment]
[Here you can find an explanation](https://code.visualstudio.com/docs/editor/multi-root-workspaces) of workspaces. Sorry for not linking the resource before.

**Comment by JimiC** [comment]
Post your settings file content.

**Comment by rbrewington** [comment]
it's empty

**Comment by robertohuertasm** [comment]
Use `Toggle Angular Preset`, and check it out again after that.

**Comment by JimiC** [comment]
Angular preset does not work in user settings

**Comment by rbrewington** [comment]
hmm. When I check the option in vsCodes settings ui, it sets the value in user settings

**Comment by JimiC** [comment]
Yes because the default settings file is user but still our extension requires angular preset to be on workspace settings.

**Comment by rbrewington** [comment]
Okay, I've set it to true in the workspace, but I still don't see the angular icons.
I've tried restarting vscode and running the apply icon customizations

**Comment by JimiC** [comment]
Open the developer tools and see if there is any error logging. The project auto detection should had picked up that it's an angular project.

**Comment by rbrewington** [comment]
fromDirPath not defined

**Comment by robertohuertasm** [comment]
@brunosotto can you verify that you're also getting the same error?

**Comment by brunosotto** [comment]
> Use `Toggle Angular Preset`, and check it out again after that.

this way it worked
👍 
😃

**Comment by JimiC** [comment]
@brunosotto Turns out that there is a logic bug in `PAD` (project auto-detection) when the editor supports icons auto-reloading. I managed to identify the cause and working on a fix.

@rbrewington I will need your help to identify why `fromDirPath` is `undefined` in your case. Are you using `vscode` in portable mode or is it installed?

**Comment by rbrewington** [comment]
I'm pretty sure it's installed. I googled it, but I can't tell if there's a good way to know for sure.

**Comment by rbrewington** [comment]
Some extra details:

When I set vscode-icons as the file icon theme, I don't get any errors, but there's no prompt about project detection and angular icons are not visible.

I only get the fromDirPath error when I use "Apply icon customizations"

**Comment by JimiC** [comment]
I can't seem to reproduce your issue on `linux` or `windows`. I'll try it on a `macos` VM I have but it runs `high sierra`.

**Comment by JimiC** [comment]
@rbrewington I just tested `9.1.0` on `MacOS High Sierra v10.13.6`. I opened an `Angular` project and the icons didn't change (due to the known bug).

When I select `F1 > Icons > Apply Icons Customization` the log entry in 'Developer Tools' presents the massage `[vscode-icons] Icons manifest file successfully generated!`. This is an indication that everything went fine.

When I select `F1 > Icons > Toggle Angular Preset (Workspace Level)` the `Angular` icons showed up.

Looking at the code the only way you can get that error is related to #2178 , for which a fix is already submitted. I would suggest that do use `v8.8.0` until we fully stabilize `v9`.

**Comment by rbrewington** [comment]
Okay. Thank you for looking into it @JimiC . 🙂

**Comment by YogeshK887** [comment]
> Use `Toggle Angular Preset`, and check it out again after that.

This worked for me. Thanks! @robertohuertasm
