### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by rjj-work** [vscode-icons/vscode-icons#2185]
[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/3452613/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `8.8.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/rjj/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
`8.8.0` is not supported anymore.
