### ISSUE TITLE
Add support for `.<extension>.js` files

### ISSUE THREAD

**Issue by ImedAdel** [vscode-icons/vscode-icons#2194]
- [X] I'm sure this issue is not a _duplicate_.

- Language Extensions: `*.gql.js`, `*.sql.js`, `*.style.js`, `*.config.js`, etc.
- More info: For one reason or another, you might want to use `.js` extension with your styling, database queries, etc. It would be "cleaner" to have the extension _before_ `.js` affect the displayed icon.

**Comment by JimiC** [comment]
Not technical possible. Sorry.

**Comment by ImedAdel** [comment]
Through Regex matching?
