### ISSUE TITLE
[Icon Request] Support for Styled Components

### ISSUE THREAD

**Issue by i2xzy** [vscode-icons/vscode-icons#2201]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension, filename`
  - Icon Name: `styled components`
  - Sample original Icon: 💅
![logo](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/160/apple/198/nail-polish_1f485.png)
  - Extensions: `.styled.js, .sc.js`
  - Filenames: `styled.js`

- More info: https://www.styled-components.com/

**Comment by KingDarBoja** [comment]
Just as information, there is a [vscode extension](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) for these files.
