### ISSUE TITLE
[Icon Request] Support for vue.config.js

### ISSUE THREAD

**Issue by igorer88** [vscode-icons/vscode-icons#2205]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageid`, `filename`
  - Icon Name: `vueconfig`
  - Sample original Icon: 
![logo](https://user-images.githubusercontent.com/6375299/63284667-0c55d700-c282-11e9-987f-1d17937b2cd1.png)

  - Extensions: `.config.js`
  - Filenames: `vue.config.js`
  - Language ids: `vue`, `vueconfig`

- Language Extensions: ??
- More info: https://vuejs.org/

**Comment by igorer88** [comment]
Just like the existent one with the addition of the config wheel.

**Comment by KingDarBoja** [comment]
I believe this would be the next candidate for the **PAD** system in order to support `vue.config.js` but not sure what are the file extensions being related to vue projects.

Any thoughts @vscode-icons/development team?

**Comment by JimiC** [comment]
The correct doc for this is at https://cli.vuejs.org/config/.
@KingDarBoja Nope. This isn't a candidate for PAD. This should be supported like any other similar icon.
i.e.
```
{
      icon: 'vue',
      extensions: ['vue.config.js'],
      languages: [languages.vue],
      format: FileFormat.svg,
    },
```

**Comment by JimiC** [comment]
On second thought, scratch the above comment. Since `vue` has also file extensions this can be implemented as a new icon with the cog, as suggested.

```
    {
      icon: 'vueconfig',
      extensions: ['.vuerc', 'vue.config.js'],
      filename: true,
      format: FileFormat.svg,
    },
```

**Comment by JimiC** [comment]
@igorer88
1. https://github.com/vscode-icons/vscode-icons/wiki/Pad
2. >  this can be implemented as a new icon with the cog, as suggested.

**Comment by JimiC** [comment]
It needs an icon too so let @KingDarBoja do it.
