### ISSUE TITLE
Recognizing only by extension

### ISSUE THREAD

**Issue by kanlukasz** [vscode-icons/vscode-icons#2207]
Hey,

Is it possible to recognize icons only by files extension?

Now, if I saved file with extension `.txt` but I set language ` yaml`, the icon I see is the `yaml` icon, but it should be a `.txt`, because the file extension is `.txt`

This is how a similar `Material Icon Theme` plugin works, but I like yours better :)

**Comment by robertohuertasm** [comment]
Our plugin relies on `language id` so we change the icon according to the language if available. Regarding the behavior of the other icon theme you refer it seems that they're just using the extension as a link.

Our decision was to leverage the language id when possible (there are icons that are still depending only on the extension) so it's a design decision that we deliberately chose.

You can override this though using our [customization capabilities](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning#some-examples): 

```json
// put this in your settings:
"vsicons.associations.files": [
    {
      "icon": "text",
      "extensions": [
        "txt",
      ],
      "format": "svg"
    }
  ]
```
