### ISSUE TITLE
[Icon Request] Support for 'GenStat' [.gen, .gpi]

### ISSUE THREAD

**Issue by PaulGoedhart** [vscode-icons/vscode-icons#2210]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by PaulGoedhart** [comment]
[GenStat.zip](https://github.com/vscode-icons/vscode-icons/files/3535191/GenStat.zip)

**Comment by KingDarBoja** [comment]
Hello @PaulGoedhart 

Please fill the missing fields according to the issues guidelines.

Cheers!

**Comment by KingDarBoja** [comment]
Related to this issue: [vscode-genstat-extension](https://github.com/jwkruisselbrink/vscode-genstat-extension)
