### ISSUE TITLE
The second image folder will not display icon

### ISSUE THREAD

**Issue by zhuohoudeputao** [vscode-icons/vscode-icons#2212]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
![image](https://user-images.githubusercontent.com/35682614/63633392-98993d00-c67a-11e9-8ef3-a98bf143cfb6.png)

**Comment by JimiC** [comment]
You will have to use the customization feature for that (https://github.com/vscode-icons/vscode-icons/wiki/FineTuning#some-examples). `vscode` does not support `glob` expressions.
