### ISSUE TITLE
[Icon Request] INC file

### ISSUE THREAD

**Issue by Rombecchi** [vscode-icons/vscode-icons#2216]
- [ X] I'm sure this issue is not a _duplicate_.
- [ X] I'm submitting an icon request:
  - Type: `INC`
  - Icon Name: `file_type_inc.svg`
  - Sample original Icon: "INC" (like ASP in dark color?)
![file_type_inc](https://user-images.githubusercontent.com/1488340/63845003-80cafd00-c989-11e9-8089-a47b5c39dfd9.png)
  - Extensions: `.inc`
  - Filenames: `*`
  - Language ids: interpreted as ASP/ text-file

- Language Extensions: .inc
- More info: this kind of files are used in Classic ASP for including external resource

**Comment by KingDarBoja** [comment]
If I am not mistaken, the `.inc` extension is not language specific.

**Comment by Rombecchi** [comment]
You're right. However can you add a not-specific text icon, please? Thank you

**Comment by JimiC** [comment]
`inc` is short for `include`. Build on that @KingDarBoja

**Comment by Rombecchi** [comment]
No matter. Should be ok also for generic text file

**Comment by KingDarBoja** [comment]
We do have already a include icon being used for the `include` folder definition as seen on the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#include).

Gonna use that instead of coming with a new one to keep uniformity.
