### ISSUE TITLE
[Icon Request] TOTVS File

### ISSUE THREAD

**Issue by efdeiasoliveira** [vscode-icons/vscode-icons#2224]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: PRG
  - Icon Name: file_type_prg.svg
  - Sample original Icon: ![logo]()
  - Extensions: .prg
  - Filenames: *
  - Language ids: ADVPL TOTVS

- Language Extensions: .prg
- More info: this kind of files are used in ADVPL TOTVS

  - Type: PRX
  - Icon Name: file_type_prx.svg
  - Sample original Icon: ![logo]()
  - Extensions: .prx
  - Filenames: *
  - Language ids: ADVPL TOTVS

- Language Extensions: .prx
- More info: this kind of files are used in ADVPL TOTVS

  - Type: PRW
  - Icon Name: file_type_prw.svg
  - Sample original Icon: ![logo]()
  - Extensions: .prw
  - Filenames: *
  - Language ids: ADVPL TOTVS

- Language Extensions: .prw
- More info: this kind of files are used in ADVPL TOTVS

  - Type: TLPP
  - Icon Name: file_type_tlpp.svg
  - Sample original Icon: ![logo]()
  - Extensions: .tlpp
  - Filenames: *
  - Language ids: ADVPL TOTVS

- Language Extensions: .tlpp
- More info: this kind of files are used in ADVPL TOTVS

[ICONS TOTVS.zip](https://github.com/vscode-icons/vscode-icons/files/3570690/ICONS.TOTVS.zip)

**Comment by KingDarBoja** [comment]
Hello @efdeiasoliveira,

Please provide the vscode syntax extension in order to check out if there is TOTVS support.

Cheers!

**Comment by efdeiasoliveira** [comment]
[X] I'm sure this issue is not a duplicate.

 [X] I'm submitting an icon request:

Type: PRG
Icon Name: file_type_prg.svg
Sample original Icon: logo
Extensions: .prg
Filenames: *.prg
Language ids: ADVPL TOTVS
Language Extensions: .prg

More info: this kind of files are used in ADVPL TOTVS

Type: PRX
Icon Name: file_type_prx.svg
Sample original Icon: logo
Extensions: .prx
Filenames: *.prx
Language ids: ADVPL TOTVS
Language Extensions: .prx

More info: this kind of files are used in ADVPL TOTVS

Type: PRW
Icon Name: file_type_prw.svg
Sample original Icon: logo
Extensions: .prw
Filenames: *.prw
Language ids: ADVPL TOTVS
Language Extensions: .prw

More info: this kind of files are used in ADVPL TOTVS

Type: TLPP
Icon Name: file_type_tlpp.svg
Sample original Icon: logo
Extensions: .tlpp
Filenames: *.tlpp
Language ids: ADVPL TOTVS
Language Extensions: .tlpp

More info: this kind of files are used in ADVPL TOTVS

[ICONS TOTVS.zip](https://github.com/vscode-icons/vscode-icons/files/3579803/ICONS.TOTVS.zip)

**Comment by JimiC** [comment]
I'm really tempted to close this issue as unacceptable.

**Comment by jens1o** [comment]
I'd opt for the same, Jimi. :)

**Comment by JimiC** [comment]
@KingDarBoja Here are some useful info about this issue:

- https://en.wikipedia.org/wiki/AdvPL
- https://github.com/totvs
- https://marketplace.visualstudio.com/items?itemName=KillerAll.advpl-vscode
    - https://github.com/totvs/advpl-vscode/blob/master/package.json#L388

Possible icon to use: https://avatars3.githubusercontent.com/u/20243897?s=200&v=4

**Comment by efdeiasoliveira** [comment]
Good Afternoon! I have verified that the .PRW extension has been added.

Missing extensions .PRG, .PRX and .TLPP, which are also in this Issue. 

All of these extensions have the same icon.


Thank you very much...

**Comment by JimiC** [comment]
Yes all file extensions will have the same icon because that's how the marketplace extension is defining them (they are all under the same `language id`).

**Comment by efdeiasoliveira** [comment]
In the merge of issue #2231, only the extension .PRW has been added

Missing extensions .prg, prx and .tlpp

**Comment by robertohuertasm** [comment]
@efdeiasoliveira the PR #2231 uses `language id`. This means that it will depend on an extension that the user has to install. For instance, you can use [this one](https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode). As you can see [here](https://github.com/totvs/tds-vscode/blob/master/package.json#L187) it supports lots of different extensions.

**Comment by efdeiasoliveira** [comment]
Understand!. It had confused me because of the google translator.

Thank you very much and congratulations for your commitment to resolve my request.
