### ISSUE TITLE
[Icon Request] Folder named "builds"

### ISSUE THREAD

**Issue by 3GOMESz** [vscode-icons/vscode-icons#2226]
- [x]  I'm sure this issue is not a _duplicate_.

- More info:
I noticed that there is a folder icon called "build" and I think it would also be interesting to have one for "builds". I find it valid in a situation where the developer has a builds folder with several builds of something that is developing in their respective versions.

   EXAMPLE:
   
   • Builds [Folder]
       »  projectBuild-Version-0001.rar [INSIDE THE FOLDER]
       »  projectBuild-Version-0002.rar [INSIDE THE FOLDER]
       »  projectBuild-Version-0003.rar [INSIDE THE FOLDER]
       »  projectBuild-Version-0004.rar [INSIDE THE FOLDER]
       »  projectBuild-Version-0005.rar [INSIDE THE FOLDER]

**Comment by JimiC** [comment]
#650
