### ISSUE TITLE
.tpl uses template folder icon instead of the smarty bulb icon?

### ISSUE THREAD

**Issue by sudoranger** [vscode-icons/vscode-icons#2228]
How can I add ".tpl" to the list of extensions that are using the "template" folder icon instead of the yellow-colored bulb icon?

Edit: Sorry, that didn't come out as intended. The topic is also wrong. I was actually looking to make "tpl" folder to use the same icon as "template/templates"...

**Comment by JimiC** [comment]
Add this in your `settings.json` file:
```
"vsicons.associations.folders": [
  { "icon": "template", "extensions": ["tpl"], "format": "svg" }
]
```
If the icon doesn't show up in a few seconds then try: `F1 > Icons > Apply Icons Customization`

**Comment by sudoranger** [comment]
I keep on getting this notification upon restart and it won't turn off/go away.

`The icons manifest will be regenerated. Select 'Restart' for changes to take effect.`

**Comment by sudoranger** [comment]
Sorry, that notification I mentioned above was not actually from vscode-icons but rather vscode-icons-mac. I've uninstalled the later extension and the notification didn't show up again. Seems like a conflict since it was a fork from this I think.

You may close this issue, using the above settings.json workaround did the trick. I managed to make the `tpl` folder to have the same icon as `template` or `templates`... I normally use short names for my folders for example `img` instead of `images` so if you could add `tpl` as a default folder name for the template icon in the next release would be nice.

Thank you @JimiC
