### ISSUE TITLE
Feature request: support for changing all file icons based on file path

### ISSUE THREAD

**Issue by iamkenos** [vscode-icons/vscode-icons#2229]
- [x] I'm sure this issue is not a _duplicate_.

Is it possible to support changing the icons of all files, regardless of the extension, given a glob?

I like the minimalistic feel of having the folder icons hidden and use the file icons as a visual cue instead.

Something like:
![image](https://user-images.githubusercontent.com/21245218/64483145-3d497c00-d230-11e9-9f34-21a001e4bf36.png)

As it is, I dont have a way of keeping the `index.js` icon similar to that of the rest of the files inside the same glob.

I was hoping of being able to do something like:

```
  "vsicons.associations.files": [
    {
      "icon": "my-icon",
      "glob": [
        "./**/pages/meta/**.*",
      ],
    },
    {
      "icon": "my-other-icon",
      "glob": [
        "./**/pages/objects/**.*",
      ],
    },
  ],
``` 

I do feel this will raise some complexities like...

- which setting should take precedence if we have a definition for a specific extension under a glob?
- how will the glob work for user vs workspace `settings.json`?

...to list a few.

**Comment by JimiC** [comment]
`vscode` does not support `glob` expressions for icon themes. Supporting it from our side is too much work for us for the time we have available. If anyone feels like giving it a try we are more then willing to accept a PR.
