### ISSUE TITLE
[Icon Request] Support for .format.ps1xml & .types.ps1xml

### ISSUE THREAD

**Issue by TylerLeonhardt** [vscode-icons/vscode-icons#2238]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `file_type_powershell_format.svg` & `file_type_powershell_types.svg`
  - Sample original Icon: ![powershell](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_powershell.svg) but a different color
  - Extensions: `.format.ps1xml` & `.types.ps1xml`
  - Language ids: `powershell`

- Language Extensions: inbox highlighting and also the PowerShell extension
- More info:

It would be nice to have another color for `.format.ps1xml` & `.types.ps1xml` 
![image](https://user-images.githubusercontent.com/2644648/64741583-f10b6f80-d4ad-11e9-8935-176f51e7df05.png)

A whole rainbow 🌈

**Comment by KingDarBoja** [comment]
Just to complete your issue:
- [Microsoft - About format.ps1xml](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6)
- [Microsoft - About types.ps1xml](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_types.ps1xml?view=powershell-6)

As side point, the Powershell official icon got changed on the latest release (Core 6) as seen on . This is the current [official](https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/PowerShell_Core_6.0_icon.png/64px-PowerShell_Core_6.0_icon.png) icon.

**Comment by KingDarBoja** [comment]
Don't worry about this, I got it covered. :cake: I will post the design very soon (this weekend hopefully).
