### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by luckfu** [vscode-icons/vscode-icons#2241]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `9.3.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/fupengcheng/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
No `cpuprofile` file submitted.
