### ISSUE TITLE
[Icon Update] Update icon for Gradle

### ISSUE THREAD

**Issue by dialex** [vscode-icons/vscode-icons#2250]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an **update** icon request:
  - Type: Gradle
  - Icon Name: `?`
  - Sample original Icon: ![logo](https://gradle.com/wp-content/themes/fuel/assets/img/branding/gradle-elephant-icon-dark-green.svg)
  - Extensions: `.gradle`
  - Filenames: `?`

- More info: Gradle recently updated their logo, see https://gradle.com/brand/

**Comment by KingDarBoja** [comment]
The elephant became happier this time 😆

**Comment by dialex** [comment]
YES! It finally started doing anger management therapy 😅

**Comment by KingDarBoja** [comment]
Should I include the gradle folder in another PR? @JimiC 

Reference: [Android Project Structure](https://medium.com/@mikelimantara/overview-of-android-project-structure-and-naming-conventions-b08f6d0b7291).

**Comment by JimiC** [comment]
Yes
