### ISSUE TITLE
Icon Size

### ISSUE THREAD

**Issue by SheepDomination** [vscode-icons/vscode-icons#2257]
The correct size for all icons must be `16x22`px ?

**Comment by JimiC** [comment]
`30x30` on a `32x32` canvas. But we always wanted to change that since we switched to `SVG`.

**Comment by SheepDomination** [comment]
By canvas size you mean pixel size ?

**Comment by KingDarBoja** [comment]
Actually, it is `32x32` pixels on the artboard while the icons must be `28x28` as maximum size. I attached an image of the guides being used on Adobe Illustrator so I always get insight of the icon limits on the artboard.

![Icon Size Layout](https://user-images.githubusercontent.com/30560560/66259126-ef625e00-e772-11e9-958b-5bb0177a1cd2.png)

**Comment by SheepDomination** [comment]
There is a huge problem when creating SVG icons, as mentioned [here.](https://github.com/vscode-icons/vscode-icons/issues/2252#issuecomment-593584334)

**Comment by KingDarBoja** [comment]
Closing as resolved.
