### ISSUE TITLE
[Icon Request] Support for Razzle Config

### ISSUE THREAD

**Issue by anthony0030** [vscode-icons/vscode-icons#2259]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `Config File`
  - Icon Name: `Razzle`
  - Sample Original Icon: ![logo](https://user-images.githubusercontent.com/4060187/28923990-050a32d4-782e-11e7-9da7-574ce5a8b455.png) (Just the Letter R)
  - Filenames: `razzle.config.js`

**Comment by KingDarBoja** [comment]
Just to complete the issue with the proper documentation, it can be found at [GitHub](https://github.com/jaredpalmer/razzle).

**Comment by anthony0030** [comment]
Thank you! I saw the icon pop-up today, looks great.
