### ISSUE TITLE
[Icon Request] Support for lex/flex file format (.l/.flex)

### ISSUE THREAD

**Issue by devansh1305** [vscode-icons/vscode-icons#2265]
- [true ] I'm sure this issue is not a _duplicate_.
- [true] I'm submitting an icon request:
  - Type: `file` `language`
  - Icon Name: `lex/flex icon`
  - Sample original Icon:     ![file_type_lex-file-icon](https://user-images.githubusercontent.com/30989930/66719492-9cb22300-edbe-11e9-96c8-289d2c924f85.png)

  - Extensions: `.l` `.flex`

- Language Extensions: `.l` `.flex`
- More info: 
https://marketplace.visualstudio.com/items?itemName=faustinoaq.lex-flex-yacc-bison
https://github.com/westes/flex

**Comment by KingDarBoja** [comment]
I was searching on Google and didn't find any icon/logo for such files. However, I came up with the official website (or that's what I think) for [Lex & Yacc](http://dinosaur.compilertools.net/).

Based on the explanation provided at this website, I do think I can make some design for the sake of not using letter-only icons.

**Comment by devansh1305** [comment]
Do you want me to design icons for lex/yacc ?

**Comment by KingDarBoja** [comment]
> Do you want me to design icons for lex/yacc ?

it is not necessary but if you want to do it, no problem with that.

**Comment by devansh1305** [comment]
Honestly, I would really like letters icons because they easily convey the type of file. Also when it comes to conversations most devs usually call it ".l" or ".y" file.
