### ISSUE TITLE
[Icon Request] Support for yacc/bison file format (.y/.yacc)

### ISSUE THREAD

**Issue by devansh1305** [vscode-icons/vscode-icons#2266]
- [true ] I'm sure this issue is not a _duplicate_.
- [true] I'm submitting an icon request:
  - Type: `file` `language`
  - Icon Name: `yacc/bison icon`
  - Sample original Icon:     ![file_type_yacc-file-icon](https://user-images.githubusercontent.com/30989930/66719519-0b8f7c00-edbf-11e9-973f-93ed8213d0b1.png)

  - Extensions: `.y` `.bison`

- Language Extensions: `.y` `.bison`
- More info: 
https://marketplace.visualstudio.com/items?itemName=faustinoaq.lex-flex-yacc-bison
https://www.gnu.org/software/bison/

**Comment by KingDarBoja** [comment]
Related to #2265, check out comment for more info.
