### ISSUE TITLE
[Icon Request] Support for BabelEdit

### ISSUE THREAD

**Issue by jhiben** [vscode-icons/vscode-icons#2272]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `BabelEdit`
  - Icon Name: `BabelEdit`
  - Sample original Icon: ![logo](https://www.codeandweb.com/img/product-icons3.png)
  - Extensions: `.babel`

- More info: [BabelEdit](https://www.codeandweb.com/babeledit)

**Comment by KingDarBoja** [comment]
The Babel extension is already supported as you can check at [List of Files Wiki](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles).

The BabelEdit is just a dev tool and hence isn't related to syntax highlighting.
