### ISSUE TITLE
[Icon Request] Support for Create React App

### ISSUE THREAD

**Issue by jhiben** [vscode-icons/vscode-icons#2273]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `CreateReactApp-env`
  - Sample original Icon: ![logo](https://create-react-app.dev/img/logo.svg)
  - Filenames: `.env`

- More info: [Create React App](https://create-react-app.dev/) [.env file](https://create-react-app.dev/docs/adding-custom-environment-variables/#what-other-env-files-can-be-used)

**Comment by xiaoxiangmoe** [comment]
@jhiben see https://github.com/vscode-icons/vscode-icons/pull/1590/files

**Comment by JimiC** [comment]
Already supported.
