### ISSUE TITLE
[Icon Request] Support for 'stan' 

### ISSUE THREAD

**Issue by AntoineChn** [vscode-icons/vscode-icons#2277]
- [ x] I'm sure this issue is not a _duplicate_.
- [ x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `stan`
  - Sample original Icon: ![logo](https://mc-stan.org/images/stan_logo.png)
  - Extensions: `.stan`

- More info: 
    - official site : https://mc-stan.org/ 
    - official collection of logos : https://github.com/stan-dev/logos

**Comment by JimiC** [comment]
Support via https://marketplace.visualstudio.com/items?itemName=ivan-bocharov.stan-vscode
