### ISSUE TITLE
[Icon Request] support for .env* files

### ISSUE THREAD

**Issue by HitLuca** [vscode-icons/vscode-icons#2278]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `env`
  - Sample original Icon: ![logo]()
  - Filenames: `.env*`

- Language Extensions:
- More info: should be applied to any .env* file, including .env.test, .env.prod, .env etc.

**Comment by KingDarBoja** [comment]
Hi @HitLuca,

You have to install an vscode extension to detect the `.env` files like as https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv since we relly on the language id for detecting such files.

Cheers!

**Comment by HitLuca** [comment]
Thanks @KingDarBoja, It works perfectly now. Closing this issue!

**Comment by kid1412621** [comment]
> Hi @HitLuca,
> 
> You have to install an vscode extension to detect the `.env` files like as https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv since we relly on the language id for detecting such files.
> 
> Cheers!

I'm using [this extension](https://marketplace.visualstudio.com/items?itemName=IronGeek.vscode-env) for .env file, but its languageId is env instead of dotenv. could u sopport that too?

**Comment by robertohuertasm** [comment]
Hi @kid1412621 would you create a PR for that? It would be awesome! It's basically adding the new id. We can guide you through.

**Comment by robertohuertasm** [comment]
You can go [here](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts#L76) and substitute `ids` with this: `['dotenv', 'env']`.

**Comment by paul-uz** [comment]
@HitLuca We use the convention `.env.client-name.environment-type` eg `.env.google.live` - which is not covered by this. Could that be done?

**Comment by HitLuca** [comment]
@paul-uz I made any `.env*` file be associated with the `dotenv` type, and it works when trying your sample filename. Add this to your `settings.json`

```json
"files.associations": {
        ".env*": "dotenv",
    }
``` 

lemme know if it works!

**Comment by paul-uz** [comment]
It works using the settings, was just wondering if it would work out of the box without additional settings :)

**Comment by HitLuca** [comment]
I guess no, since technically the filename you are using is not standard

**Comment by voidei** [comment]
This has been stale for a while now, but I wanted to add in my 2 cents to this as I'd love to see a .env files receive and official logo. While it would be "easier", per say, to simply associate the icon with a language - as has been said, that would require extra work on the user's part; I've currently got a (very unoptimised) icon for .env files based on the following `vsicons.associations.files` setting, which could be applied to the icon type in the manifest.

```json
"icon": "dotenv",
"extensions": [
  ".envinfo",
  ".env-sample",
  ".env",
  ".fart",
  ".flaskenv",
  ".me",
  ".project",
  ".secret",
  ".sync",
  ".vault",
],
"filenamesGlob": [".env"],
"extensionsGlob": [
  "build.local",
  "build",
  "ci.local",
  "ci",
  "deploy",
  "deployment",
  "dev.local",
  "dev",
  "development.local",
  "development",
  "example",
  "fart",
  "live.local",
  "live",
  "local",
  "me",
  "previous",
  "prod.local",
  "prod",
  "production.local",
  "production.previous",
  "production",
  "qa.local",
  "qa",
  "sample",
  "secret",
  "secrets",
  "stag.local",
  "stag",
  "stage.local",
  "stage",
  "staging.local",
  "staging.previous",
  "staging",
  "sync",
  "test.local",
  "test",
  "testing",
  "uat.local",
  "uat",
  "vault",
],
"filename": true,
"format": "svg",
```

I don't see this as being any more difficult to do as there's many icons with only a file association and not a language association.
