### ISSUE TITLE
[Icon Request] Support for dependabot

### ISSUE THREAD

**Issue by jurijzahn8019** [vscode-icons/vscode-icons#2287]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `dependabot`
  - Sample original Icon: ![logo](https://avatars3.githubusercontent.com/u/27347476?s=200&v=4)
  - Extensions: `.dependabot`
  - Filenames: ``
  - Language ids: ``

- Language Extensions: .yml, .yaml
- More info: https://github.com/dependabot

**Comment by JimiC** [comment]
#650
