### ISSUE TITLE
Angular module conflict with routing module

### ISSUE THREAD

**Issue by msqaddura** [vscode-icons/vscode-icons#2288]
I think the image below explains everything about the issue :D 
![image](https://user-images.githubusercontent.com/11808840/68581920-2ae2fd00-0482-11ea-9d62-a8a43ede6ddd.png)

I dont know if it is possible to change the extension from `app-routing.module.ts` to `-routing.module.ts`

from:
`
icon: 'ng_routing_ts',
extensions: ['app-routing.module.ts'],
filename: true,
`
to:
`
icon: 'ng_routing_ts',
extensions: ['-routing.module.ts'],
filename: true,
`

Would be great if VSCode allows that!

**Comment by JimiC** [comment]
Unfortunately `glob` expressions are not supported but you could config `vscode-icons` and add your filenames to it. Check out the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning).

**Comment by msqaddura** [comment]
Yeah, I recall that thing that is why I wondered if possible. but no worries at all and thank you! I will do  the config one

**Comment by KingDarBoja** [comment]
@msqaddura I do tend to call my routing files as `name.routing.ts` instead of using the `.module` extension because it will default to the module icon (purple) instead of the routing one (yellow).

**Comment by robertohuertasm** [comment]
Closing this as it's not feasible at the moment. Thanks everyone involved!
