### ISSUE TITLE
Widgets Folder Icon

### ISSUE THREAD

**Issue by mrgnhnt96** [vscode-icons/vscode-icons#2289]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `Folder`
  - Icon Name: `Widgets`
  - Language ids: `Dart\Flutter`

- More info: I noticed that there is not an icon for a "Widgets" folder. I think that it would be cool to have that included.

**Comment by JimiC** [comment]
#650
