### ISSUE TITLE
[Feature Request] Special icon switch

### ISSUE THREAD

**Issue by lazyyx** [vscode-icons/vscode-icons#2294]
It might be a good idea to provide a special icon based on the folder/file name, but sometimes people might want to display just a normal folder/file icon.

For example, under a Go project, there is an `interfaces` folder, and the folder displays a C++-related icon.

Adding a switch to configure the display of a special folder/file icon might be a better choice.

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#interfaces is not a `C++` related icon. You can always use your own icon by using the customization feature (https://github.com/vscode-icons/vscode-icons/wiki/Customization).

**Comment by lazyyx** [comment]
The point is: this folder should be a normal folder in my project.
Although each icon can be customized, wouldn't it be more convenient to provide a switch to control the display of these special icons?

**Comment by JimiC** [comment]
There is. You can disable all special folder icons. Check configuration.

**Comment by lazyyx** [comment]
What should I do?

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/Presets

**Comment by lazyyx** [comment]
Set `vsicons.presets.foldersAllDefaultIcon` to `true`, the folder has restored its default icons.

Thanks.
