### ISSUE TITLE
[Icon Request] Support for ::rexx::

### ISSUE THREAD

**Issue by johnboard** [vscode-icons/vscode-icons#2296]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `languageid`
  - Icon Name: `rexx`
  - Sample original Icon: ![reginaw32](https://user-images.githubusercontent.com/48809174/69751496-1f145d80-1147-11ea-921e-5c9a775a9ffa.jpg)
- Language ids: `rexx`

- Language Extensions: [rexx-syntax-highlighting](https://marketplace.visualstudio.com/items?itemName=websi96.rexx-syntax-highlighting)

**Comment by KingDarBoja** [comment]
Hello @johnboard,

Is this the [rexx language](https://www.rexxla.org/rexxlang/) you talking about?

**Comment by johnboard** [comment]
That's the one. There are a couple of good interpreters (and a good number of commercial ones) - the best known is https://regina-rexx.sourceforge.io (updated last month)

**Comment by johnboard** [comment]
Thanks for looking at this - much appreciated.
