### ISSUE TITLE
Icon for perl is too dark for a dark theme.

### ISSUE THREAD

**Issue by carlosfrodriguez** [vscode-icons/vscode-icons#2300]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:

- Language Extensions: pl, pm, t
- More info: The icon is too dark for for a dark theme 
<img width="207" alt="Screen Shot 2019-11-28 at 12 30 01 PM" src="https://user-images.githubusercontent.com/223980/69826944-e58d3200-11da-11ea-8dd8-53713d434313.png">

**Comment by KingDarBoja** [comment]
@JimiC Maybe we could provide a light version for the Perl Camel but use some kind of light colour and not just a slight white gray.

**Comment by JimiC** [comment]
That's the official color. Does it have also a light version?

**Comment by KingDarBoja** [comment]
@JimiC Not sure as the Camel is a trademark of O'Reilly in association with Perl.

Source: [The Perl Camel](https://www.perl.org/camel.html)

I don't see anything that block us to provide a light version as long as we respect the trademark [guidelines](https://www.oreilly.com/retail/2014_Trademark_guidelines.pdf):

> _"Color guidelines: The details and outlines of the animals always appear darker than
the background color, i.e., they may not be reversed. If they are to appear on a dark
color, they may be masked precisely with white, with the animal graphic overlaid in a
darker color. Any use of the animals in colors other than their appearance on the
book covers must be approved in advance by O’Reilly Media, Inc."_

**Comment by carlosfrodriguez** [comment]
@KingDarBoja That are good news, I will be looking forward for the new icon :-)

**Comment by JimiC** [comment]
Read the guidelines again. The animal color has to be _always_ dark even in dark themes.
>If they are to appear on a dark color, they may be masked precisely with white, with the animal graphic overlaid in a darker color.

**Comment by JimiC** [comment]
Maybe it's best to get away from the camel icon and use a literal perl icon.

**Comment by carlosfrodriguez** [comment]
@JimiC That would be also acceptable, to have the onion icon instead of the camel

**Comment by JimiC** [comment]
Onion icon is already supported.

**Comment by carlosfrodriguez** [comment]
@JimiC I will try, let me read how to do it, but from https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles , it also looks very dark.

**Comment by carlosfrodriguez** [comment]
@JimiC I was able to test it and yes it look better, but sill too dark, if a lighter version could be added it will be great

**Comment by JimiC** [comment]
As I said we can't deviate from official guidelines. Your only option is to use the customization feature and use your own icon.

**Comment by KingDarBoja** [comment]
> Read the guidelines again. The animal color has to be _always_ dark even in dark themes.
> 
> > If they are to appear on a dark color, they may be masked precisely with white, with the animal graphic overlaid in a darker color.

With mask they refer to add a outline to the logo or what? Because that's what I have on mind
