### ISSUE TITLE
[Icon Request] Support for Modernizr config file

### ISSUE THREAD

**Issue by pierredarrieutort** [vscode-icons/vscode-icons#2301]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `modernizr`
  - Sample original Icon: ![logo](https://ptb2.me/img/modernizr-fa4d36ef.png)
  - Filenames: `modernizr.js, modernizrrc.js, .modernizr.js, .modernizrrc.js`
  - Language ids: `modernizr`

- Language Extensions: `js`
- More info: [Official modernizr website](https://modernizr.com/)

**Comment by KingDarBoja** [comment]
The type actually should be `filename`. @JimiC Can we support it?

**Comment by JimiC** [comment]
It's an rc file just like any other we support.
