### ISSUE TITLE
[Icon Request] Support for rust-toolchain

### ISSUE THREAD

**Issue by deeprobin** [vscode-icons/vscode-icons#2304]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `Rust Toolchain Selector File`
  - Sample original Icon: Rust does not provide anything for this file but the current icon is just a default sheet of paper icon
  - Extensions: none
  - Filenames: `rust-toolchain`
  - Language ids: `rust`

- Language Extensions:
- More info:

**Comment by robertohuertasm** [comment]
See https://github.com/rust-lang/rustup#the-toolchain-file

**Comment by KingDarBoja** [comment]
@robertohuertasm Is this not a valid file? If not, we should close this issue.

**Comment by deeprobin** [comment]
I think it is valid. Because .nvmrc is also valid. @KingDarBoja

**Comment by robertohuertasm** [comment]
Yes, don't close it.

**Comment by JimiC** [comment]
@KingDarBoja it's valid.
