### ISSUE TITLE
Cannot add custom icons

### ISSUE THREAD

**Issue by DaveRainbowin** [vscode-icons/vscode-icons#2310]
Yes, I have read both the wiki pages. I have:
 - [x] a file named file_type_abc.svg in the proper folder for custom icons
- [x] `"vsicons.associations.files": [ {"icon": "abc", "extensions": ["abc", "music"], "format": "svg"} ]`
Using windows and standard vscode
Is there something I did wrong or does it just not work?
And also, this icon is supposed to appear on <name>.abc or <name>.music files.

**Comment by KingDarBoja** [comment]
Hello @DaveRainbowin,

Can you show us the folder path being used in this case?

**Comment by DaveRainbowin** [comment]
C:\Users\<me>\AppData\Roaming\Code\User\vsicons-custom-icons

**Comment by JimiC** [comment]
Usually, the extension picks up any change done in the `settings.json` file, but there are times when it doesn't. In that case, the proper action is to trigger an explicit regeneration of the icon's manifest file. `F1 > Icons > Apply Icons Customization`.

**Comment by JimiC** [comment]
Closing with reason: No follow-up.
