### ISSUE TITLE
How can I add "webpack.config.src.js" to the list of filenames that use the webpack icon

### ISSUE THREAD

**Issue by plastikfan** [vscode-icons/vscode-icons#2312]
I have taken a look at https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles to see which filenames trigger the use of the webpack icon. In this list, there are no entries that represent 'source code config' as opposed to 'test code config'. I would have been willing to change my 'source code confg' file name to an existing one in that list, but none of them are applicable. So I would like to add 'webpack.config.test.js' to the list of files that use the webpack icon. How can I do this? Thanks.

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by plastikfan** [comment]
Thanks @JimiC. To associate the webpack icon with my custom webpack filename: 'webpack.config.src.js', I added the following to my settings file:

>     "vsicons.associations.files": [{
>         "icon": "webpack",
>         "extensions": [
>             "webpack.config.src.js"
>         ],
>         "filename": true,
>         "format": "svg"
>     }]

This suits my needs perfectly, so I'll close this issue.
