### ISSUE TITLE
[Icon Request] Support for 'LilyPond'

### ISSUE THREAD

**Issue by Guyutongxue** [vscode-icons/vscode-icons#2324]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId`
  - Icon Name: `lilypond`
  - Sample original Icon: ![logo](http://lilypond.org/pictures/lily-home-32x32.png)
  - Extensions: `.ly`, `.ily`
  - Language ids: `lilypond`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=truefire.lilypond
- More info: [LilyPond offical website](http://lilypond.org/index.html). LilyPond is a music engraving program as part of GNU Project.

**Comment by SheepDomination** [comment]
I thought this extension can accept new extensions, as long as the extension name and language id is supplied ?
