### ISSUE TITLE
单数和复数的文件夹名称可不可以都有一个icon，例如services和service。

### ISSUE THREAD

**Issue by ifblooms** [vscode-icons/vscode-icons#2326]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: `service`
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
**Google translator:** 
> _Can both the singular and plural folder names have an icon, such as services and services._

Of course, but please use english language when opening a new issue or feature request.

Cheers!

**Comment by JimiC** [comment]
This is all Chinese to me.
