### ISSUE TITLE
.pem file displays wrong icon

### ISSUE THREAD

**Issue by nebbles** [vscode-icons/vscode-icons#2330]
- [x] I'm sure this issue is not a _duplicate_.

Despite `pem` being listed next to `key` as an extension that receives the `key` icon, it instead displays the text file icon.

**Comment by JimiC** [comment]
Check `settings.json` to see if anything overrides the association.

**Comment by nebbles** [comment]
The only vsicons entry in `settings.json` is `"vsicons.presets.foldersAllDefaultIcon": true`

**Comment by JimiC** [comment]
Disable momentarily all extensions but vscode-icons and check again.

**Comment by nebbles** [comment]
It seems the issue was that I had never 'set file icon theme' on any VSCode instance. As such I have never actually been using VSCode-Icons set (and never realised I wasn't) despite the extension being installed.
