### ISSUE TITLE
[Icon Request] Associate secondary actionscript icon with "AS2 Language Support" extension

### ISSUE THREAD

**Issue by admvx** [vscode-icons/vscode-icons#2331]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `language-id`
  - Icon Name: `actionscript2`
  - Sample original Icon: [please use existing `actionscript2` icon]
  - Filenames: `*.as`
  - Language ids: `actionscript`

- Language Extensions: [AS2 Language Support](https://marketplace.visualstudio.com/items?itemName=admvx.as2-language-support)
- More info: as initially discussed in #2329 the [ActionScript and MXML](https://marketplace.visualstudio.com/items?itemName=bowlerhatllc.vscode-nextgenas) vscode extension is currently associated with the `actionscript` icon via language ID `nextgenas`. I'd like the more generic icon currently included in this project (`actionscript2`) to be associated with the language ID `actionscript`.

Thank you

**Comment by KingDarBoja** [comment]
@robertohuertasm Basically, add another id to the `ids` property in this line:
```ts
actionscript: { ids: 'nextgenas', defaultExtension: 'as' },
```

That should work, right?

**Comment by JimiC** [comment]
Yes. `ids: []` will do the trick.

**Comment by KingDarBoja** [comment]
@JimiC The author also stated (and I confirmed) that the original extension changed the language id from `nextgenas` to `actionscript` 8 months ago. Should be safe to remove it from the language ids array?

**Comment by JimiC** [comment]
Yes.
