### ISSUE TITLE
wiki: wrong custom icon path for portable mode

### ISSUE THREAD

**Issue by dehesselle** [vscode-icons/vscode-icons#2333]
- [x] I'm sure this issue is not a _duplicate_.

I believe the [wiki documentation for adding a custom icon](https://github.com/vscode-icons/vscode-icons/wiki/Custom) is wrong. The proposed default path for `vsicons-custom-icons` for a portable installation on Window is
`<path_to_the_application>\<Data Folder>\user-data\vsicons-custom-icons`
I only got it to work through experimentation and comparing it to a non-portable installation, using
`<path_to_the_application>\<Data Folder>\user-data\User\vsicons-custom-icons`

![folder_custom_icons](https://user-images.githubusercontent.com/11375494/72096198-ff617f00-3319-11ea-80e6-0b3ce4f06170.png)

I haven't checked the other platforms but it's likely that `...\user-data\User\...` is required everywhere.

**Comment by JimiC** [comment]
Actually the docs are correct but the code implementation is wrong, It's actually an inconsistency bug from our side.

According to [vscode portable mode docs](https://code.visualstudio.com/docs/editor/portable)  the `User` directory should be copied as `user-data` in portable mode.

**Comment by JimiC** [comment]
After checking it again turns out that you're correct. The wiki docs are wrong.

**Comment by JimiC** [comment]
Wiki docs corrected. Thanks for bringing this to our attention.

**Comment by dehesselle** [comment]
Glad to be of help!
