### ISSUE TITLE
RipGrep recursive globbing causing very large CPU and memory strain

### ISSUE THREAD

**Issue by h1nk** [vscode-icons/vscode-icons#2342]
I'll often edit some of my user configuration files (dotfiles) using `code -r ~/` to open up my entire home folder tree at once. While doing this I've noticed incredible amounts of resource strain (both CPU and memory). Often times when I'm doing this VSCode will use nearly 100% of my CPU along with multiple gigabytes of memory. It's to the point where my system freezes and I have to spam <kbd>SysRq</kbd> + <kbd>F</kbd> to unfreeze my system just I can close and reopen VSCode. I've identified the resource trashing issues to originate from a RipGrep subprocess (`/usr/share/code/resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/package.json -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/node_modules/** --no-ignore --follow --no-config --no-ignore-global`). When running VSCode with all extensions disabled (`code --disable-extensions -r ~/`) I have no problems with excessive resource usage. I've gone through the tedious process of disabling each extension and narrowing down the issue to this extension.

- [ ] I'm sure this issue is not a _duplicate_.
[It is a duplicate issue.](https://github.com/vscode-icons/vscode-icons/issues?utf8=%E2%9C%93&q=in%3Atitle+CPU)

- Language Extensions:
None

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/wiki/Pad

**Comment by h1nk** [comment]
I'm good to go now, thanks.
