### ISSUE TITLE
Change the default file extension icon on vscode-icons don´t works

### ISSUE THREAD

**Issue by emersondevtoo** [vscode-icons/vscode-icons#2358]
I am trying to change the icon from the extension **test.js**. I found this documentation [vscode-icons Fine tuning][1] on my settings file ```settings.json``` I put:

```json
{
  "vsicons.associations.files": [
    { "icon": "test", "extensions": ["test.js"], "format": "svg", "overrides": "test.js" }
  ]
}
```
But don't work, and when I change it to js, works:

```json
{
  "vsicons.associations.files": [
    { "icon": "test", "extensions": ["js"], "format": "svg", "overrides": "js" }
  ]
}
```

What am I missing?

  [1]: https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by JimiC** [comment]
The `id` of the icon is `testjs`.
```
{
  "vsicons.associations.files": [
    { "icon": "test", "format": "svg", "overrides": "testjs" }
  ]
}
```

**Comment by KingDarBoja** [comment]
Closing as resolved 💯
