### ISSUE TITLE
[Icon Request] Support for C++ ipp, tpp and inl files

### ISSUE THREAD

**Issue by lukechu10** [vscode-icons/vscode-icons#2361]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `Icon`
  - Icon Name: `C++`
  - Sample original Icon: C++ source file icon
  - Extensions: `.ipp .tpp .inl`
  - Filenames: ``
  - Language ids: `C++`

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
Can you provide some explanation and source info about these C++ extensions?

**Comment by lukechu10** [comment]
`.tpp`, `.ipp` and `.inl` are all C++ source files for template classes. This is because in C++, templates are generated during compile time and the compiler needs access to the function definitions. This means we cannot use the plain `.cpp` extension. Check out this: https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file/495056#495056. In VSCode, when I use these extensions, the file just appears as the default file icon and it doesn't seem to be in this list: https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles.

**Comment by lukechu10** [comment]
These extensions are for the definitions for functions in template classes. This is because when using template classes, the compiler needs access to the definitions to generate the corresponding function/class. This is why the `.cpp` extension is not used: https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file/495056#495056

**Comment by JimiC** [comment]
According to https://github.com/microsoft/vscode/blob/master/extensions/cpp/package.json#L30 only `tpp` is not supported. Better take this to the `vscode` team to add `tpp` to the list.

**Comment by KingDarBoja** [comment]
@JimiC Should we open a ticket at VSCode repo in order to request this?

**Comment by JimiC** [comment]
Closing with reason: resolved
