### ISSUE TITLE
[Icon Request] Support for folder "sdk", "sdks"

### ISSUE THREAD

**Issue by jurijzahn8019** [vscode-icons/vscode-icons#2362]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename `
  - Icon Name: `sdk`
  - Sample original Icon: ![Just an Example](https://www.dreamstime.com/sdk-icon-trendy-flat-vector-white-background-t-technology-collection-illustration-can-be-use-web-mobile-eps-image130326090)
  - Filenames: `sdk, sdks`

- More info:
  I would like to have a folder where i want store my sdk subfolders with sdk sources/binaries

**Comment by JimiC** [comment]
#650
