### ISSUE TITLE
Fix F# icon.

### ISSUE THREAD

**Issue by hangacs** [vscode-icons/vscode-icons#2364]
F# source file end with ".fs" in my vscode on Windows 10 shows glsl file icon.
Ocaml source file end with "ml" can't show proper icon.

**Comment by JimiC** [comment]
Please provide screenshots.

**Comment by hangacs** [comment]
> Please provide screenshots.

- This is vscode icons:

![vsicon_icon](https://user-images.githubusercontent.com/12413476/74245848-a15ff700-4d1e-11ea-9107-034f228ca7f1.png)

- This is material icon for comparison:

![material_icon](https://user-images.githubusercontent.com/12413476/74246061-e6842900-4d1e-11ea-8458-f18d89e5eada.png)

**Here is some references about file extensions:**

- [F#](https://ocaml.org/learn/tutorials/filenames.html)

- [Ocaml](https://stackoverflow.com/questions/23292701/what-are-the-differences-between-in-fsx-fsi-and-fs-file-in-f)

**Comment by KingDarBoja** [comment]
Not sure about this but do you have installed [ionide-vscode-fsharp](https://github.com/ionide/ionide-vscode-fsharp) extension?

**Comment by hangacs** [comment]
@KingDarBoja 
Yes I've installed ionide-fsharp and ionide-FAKE. Disabling or uninstalling them and reinstalling vscode-icon-theme does not do any change.

**Comment by KingDarBoja** [comment]
I wasn't able to reproduce the issue.

This is my vscode before installing OCaml and Reason IDE (`freebroccolo.reasonml`) or 

![vscode-fsharp-ocaml-step1](https://user-images.githubusercontent.com/30560560/74382980-57c5e980-4dbc-11ea-8a83-10b973c1eee1.png)

After installing OCaml extension:

![vscode-fsharp-ocaml-step2](https://user-images.githubusercontent.com/30560560/74383366-108c2880-4dbd-11ea-9a59-ddbc82c682d8.png)

After installing Ionide-fsharp (`ionide.ionide-fsharp`):

![image](https://user-images.githubusercontent.com/30560560/74383512-59dc7800-4dbd-11ea-94f0-5cd2da595db6.png)

```console
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by hangacs** [comment]
It turned out that this problem is caused by another extension called _Shader languages support for VS Code_ and I don't know I have to install Ocaml extension to show the icon. Thanks for you patient!

**Comment by KingDarBoja** [comment]
Glad you solved it! 🚀
