### ISSUE TITLE
Change the closed root folders to have the folder-root-open.svg icon and Open folder to have the folder-root.svg icon

### ISSUE THREAD

**Issue by chriswinslow** [vscode-icons/vscode-icons#2372]
- [x] I'm sure this issue is not a _duplicate_.

- More info: I have a fair amount of projects in my workspace and I often have multiple projects expanded at any given time. I find having the closed/collapsed project icons filled with the hollow grey circle (filename: folder-root.svg) and open/expanded project folders filed with the almost filled grey circle (filename: folder-root-open.svg) to be much easier on the eye when scrolling up or down looking for the opened project folders.

Plus it just seems to make more sense that an expanded folder me marked as a filled icon rather than a hollow one. I change the filenames around on every update of the icon package.

Would you consider the above and swapping the icons around?

**Comment by JimiC** [comment]
You can use the customization feature (https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) to have them swapped permanently on your projects.

**Comment by JimiC** [comment]
Closing with reason: resolved.
