### ISSUE TITLE
Update the blade icon to the latest Laravel logo

### ISSUE THREAD

**Issue by AndreasSchantl** [vscode-icons/vscode-icons#2379]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `Update of existing blade icon as Laravel has a new logo`
  - Icon Name: `Blade`
  - Sample original Icon: ![new logo](https://github.com/laravel/art/blob/master/logo-mark/5%20svg/3%20rgb/1%20Full%20Color/laravel-mark-rgb-red.svg)
  - Extensions: `.blade.php`
  - Filenames: `*`

**Comment by KingDarBoja** [comment]
Hi @AndreasSchantl , the blade icon already has the latest Laravel logo, you need to install a vscode extension like [Laravel-blade](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) to enable it.
