### ISSUE TITLE
.razor not being associated correctly

### ISSUE THREAD

**Issue by ndotb** [vscode-icons/vscode-icons#2390]
- [x] I'm sure this issue is not a _duplicate_.
- Language Extensions: razor
- More info:

Despite the existence of a razor icon (https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#razor), razor files aren't being associated correctly.

Actual behavior:
![image](https://user-images.githubusercontent.com/20463809/75279384-82ab3700-57d9-11ea-8164-29984250612d.png)

**Comment by JimiC** [comment]
I don't recall having that kind of icon. Are you really sure you have `vscode-icons` activated?

**Comment by ndotb** [comment]
It's there... what's weird is I went back to the extension page just to double check it was enabled (it was) and all of my icons came back.

VSCode has been busy breaking a lot of extensions with recent releases, so I don't even know how long it was disabled-but-not-really-disabled.

I don't have any other icon themes installed.

Actual (and expected) behavior now:
![image](https://user-images.githubusercontent.com/20463809/75293996-59000900-57f5-11ea-9413-a2a7a7aa8e74.png)

Self-closing
