### ISSUE TITLE
Please add a feature to give extension some icon themes from gnome-look.org

### ISSUE THREAD

**Issue by mhkarimi1383** [vscode-icons/vscode-icons#2391]
Please add a feature to give extension some icon themes from gnome-look.org it can help us to customize it better and easier.

**Comment by robertohuertasm** [comment]
I'm not really sure to understand your request. Can you elaborate a little bit more?

**Comment by mhkarimi1383** [comment]
Lots of users are coming from Linux so it coud be nice if your extension can load icon theme from gnome-look.org website I know it's so hard to do that but it is a good idea to have that option user imports compressed file and extension will do proper things on that file.

sorry about bad English

**Comment by robertohuertasm** [comment]
I guess this is out of the scope for this extension. Without knowing that much about [gnome-look.org](https://www.gnome-look.org) I'm not sure that this would be even feasible. 

For starters, we would have to map whatever convention they are using to our registered extensions which, if feasible, would require a lot of work and not sure the return of the investment would be worth it. 

Anyway, if you have the idea clear in your mind, we welcome all the PRs! So please, go for it!

All the best,
Roberto

**Comment by mhkarimi1383** [comment]
OK, but every GNU/Linux user know what is it

**Comment by robertohuertasm** [comment]
That's a broad generalization. I'm using Linux and didn't know about it. Anyway, if someone in the team wants to explore this request I'm more than happy. If not, I think we should close it.

**Comment by JimiC** [comment]
I didn't know it either. But for all purposes using any of those icons with our customization feature will provide the result the user is expecting. Furthermore providing the `associations` to add them to our wiki, would be ideal for use from another user.

**Comment by mhkarimi1383** [comment]
If you are a GNU/Linux user that uses gnome desktop and personalization is important for you. you probably know about gnome-look.org I recommend to check it out.

**Comment by JimiC** [comment]
We are going to close this issue if it doesn't get traction within 30 days.

**Comment by SheepDomination** [comment]
Are those SVG icons ?

**Comment by mhkarimi1383** [comment]
they have SVG and PNG files in different sizes in the special directory structure.

**Comment by SheepDomination** [comment]
There seems to be a few things no working with this extension; either that or the documentation is not setup correctly.

**Comment by KingDarBoja** [comment]
Closing as this issue never got traction.
