### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hoiwa** [vscode-icons/vscode-icons#2392]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.0.0`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/hwwong/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
Please read: https://github.com/vscode-icons/vscode-icons/wiki/Pad

**Comment by hexboy** [comment]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.0.0`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.43.1`

[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://paste.ubuntu.com/p/Jg5F3wKmWW/)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load
