### ISSUE TITLE
Requesting that not all all text files be represented as docker files

### ISSUE THREAD

**Issue by mpusch88** [vscode-icons/vscode-icons#2394]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:

- Language Extensions: txt
- More info: When loading text files, vscode-icons always chooses to display them as docker files. As I use vscode as my main text editor, this bug is occasionally confusing.

**Comment by JimiC** [comment]
Check your settings. Some other extension may be interfering.

**Comment by JimiC** [comment]
Closing with reason: no follow up.
