### ISSUE TITLE
[Icon Request] Support for lnk icons

### ISSUE THREAD

**Issue by NewUserHa** [vscode-icons/vscode-icons#2400]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `lnk`
  - Sample original Icon: ![logo](https://image.flaticon.com/icons/svg/29/29615.svg)
  - Extensions: `lnk`
  - Filenames: `lnk`
  - Language ids: `lnk`

- Language Extensions:
- More info:

**Comment by JimiC** [comment]
@KingDarBoja Is this the official logo?

**Comment by JimiC** [comment]
Personally I would simply use the chain icon

**Comment by KingDarBoja** [comment]
> @KingDarBoja Is this the official logo?

Harder to tell as most images on a google search are similar to this.

**Comment by JimiC** [comment]
I don't have the same experience. I would definitely go with the simpler chain icon.

**Comment by NewUserHa** [comment]
better to use Windows default arrow icon.
