### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ahmdtalat** [vscode-icons/vscode-icons#2407]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.0.0`
- OS Version: `Linux x64 4.19.107-1-MANJARO`
- VSCode version: `1.43.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/death/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertohuertasm** [comment]
Refer to #2392
