### ISSUE TITLE
[Icon Request] Support for awk icons

### ISSUE THREAD

**Issue by volker-raschek** [vscode-icons/vscode-icons#2411]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `awk`
  - Sample original Icon: Same as shell icon? Can't find original icon
  - Extensions: `awk`
  - Filenames: `awk`

**Comment by KingDarBoja** [comment]
Maybe we could provide one like the penguin on this [image](https://nextjournal.com/data/QmZwtpT9ko15h26Fn2VH2HratvDncLVRS3yUcVBiuMyJ94?content-type=image%2Fpng&filename=awk.png).
