### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Agos88** [vscode-icons/vscode-icons#2413]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.43.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Agostino Padula\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/issues/2392
