### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by majbootred** [vscode-icons/vscode-icons#2414]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.0.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`[C:\Users\mjacob\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt
[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/4353544/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)
](url)`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2,
                41,
                44
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "s",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 142320
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 142818
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 142837
            },
            "hitCount": 0,
            "children": [
                5
            ]
        },
        {
            "id": 5,
            "callFrame": {
                "functionName": "",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 149897
            },
            "hitCount": 0,
            "children": [
                6
            ]
        },
        {
            "id": 6,
            "callFrame": {
                "functionName": "e._validate",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 158306
            },
            "hitCount": 0,
            "children": [
                7
            ]
        },
        {
            "id": 7,
            "callFrame": {
                "functionName": "v.validate",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 158903
            },
            "hitCount": 0,
            "children": [
                8
            ]
        },
        {
            "id": 8,
            "callFrame": {
                "functionName": "v._addSchema",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 161510
            },
            "hitCount": 0,
            "children": [
                9
            ]
        },
        {
            "id": 9,
            "callFrame": {
                "functionName": "v.validateSchema",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 159674
            },
            "hitCount": 0,
            "children": [
                10
            ]
        },
        {
            "id": 10,
            "callFrame": {
                "functionName": "v.validate",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 158903
            },
            "hitCount": 0,
            "children": [
                11
            ]
        },
        {
            "id": 11,
            "callFrame": {
                "functionName": "v.getSchema",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 160222
            },
            "hitCount": 0,
            "children": [
                12
            ]
        },
        {
            "id": 12,
            "callFrame": {
                "functionName": "v._compile",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 162090
            },
            "hitCount": 0,
            "children": [
                13
            ]
        },
        {
            "id": 13,
            "callFrame": {
                "functionName": "e",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 165847
            },
            "hitCount": 0,
            "children": [
                14
            ]
        },
        {
            "id": 14,
            "callFrame": {
                "functionName": "M",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 23,
                "columnNumber": 166399
            },
            "hitCount": 0,
            "children": [
                15
            ]
        },
        {
            "id": 15,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 0,
            "children": [
                16
            ]
        },
        {
            "id": 16,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 56158
            },
            "hitCount": 0,
            "children": [
                17,
                38,
                39
            ]
        },
        {
            "id": 17,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 2,
            "children": [
                18,
                37,
                42
            ],
            "positionTicks": [
                {
                    "line": 9,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 18,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 56158
            },
            "hitCount": 0,
            "children": [
                19,
                36
            ]
        },
        {
            "id": 19,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 0,
            "children": [
                20
            ]
        },
        {
            "id": 20,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 31970
            },
            "hitCount": 0,
            "children": [
                21,
                35
            ]
        },
        {
            "id": 21,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 0,
            "children": [
                22
            ]
        },
        {
            "id": 22,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 28988
            },
            "hitCount": 0,
            "children": [
                23,
                24
            ]
        },
        {
            "id": 23,
            "callFrame": {
                "functionName": "copy",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42029
            },
            "hitCount": 0
        },
        {
            "id": 24,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 0,
            "children": [
                25,
                34
            ]
        },
        {
            "id": 25,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 46821
            },
            "hitCount": 6,
            "children": [
                26,
                28,
                31,
                32,
                33
            ],
            "positionTicks": [
                {
                    "line": 26,
                    "ticks": 6
                }
            ]
        },
        {
            "id": 26,
            "callFrame": {
                "functionName": "getPathExpr",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 43598
            },
            "hitCount": 0,
            "children": [
                27
            ]
        },
        {
            "id": 27,
            "callFrame": {
                "functionName": "x",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 45416
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 28,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 122588
            },
            "hitCount": 0,
            "children": [
                29
            ]
        },
        {
            "id": 29,
            "callFrame": {
                "functionName": "X",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 130876
            },
            "hitCount": 0,
            "children": [
                30
            ]
        },
        {
            "id": 30,
            "callFrame": {
                "functionName": "Z",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 8,
                "columnNumber": 130947
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 9,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 31,
            "callFrame": {
                "functionName": "varOccurences",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42730
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 32,
            "callFrame": {
                "functionName": "varReplace",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42821
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 33,
            "callFrame": {
                "functionName": "cleanUpCode",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42933
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 34,
            "callFrame": {
                "functionName": "cleanUpCode",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42933
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 35,
            "callFrame": {
                "functionName": "cleanUpCode",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42933
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 36,
            "callFrame": {
                "functionName": "varOccurences",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42730
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 37,
            "callFrame": {
                "functionName": "cleanUpCode",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42933
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 42,
            "callFrame": {
                "functionName": "e.exports",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 25,
                "columnNumber": 46821
            },
            "hitCount": 0,
            "children": [
                43
            ]
        },
        {
            "id": 43,
            "callFrame": {
                "functionName": "copy",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42029
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 38,
            "callFrame": {
                "functionName": "varOccurences",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 42730
            },
            "hitCount": 5,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 5
                }
            ]
        },
        {
            "id": 39,
            "callFrame": {
                "functionName": "escapeFragment",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 44470
            },
            "hitCount": 0,
            "children": [
                40
            ]
        },
        {
            "id": 40,
            "callFrame": {
                "functionName": "D",
                "scriptId": "564",
                "url": "file:///c:/Users/mjacob/.vscode/extensions/vscode-icons-team.vscode-icons-10.0.0/dist/src/vscode-icons.bundle.js",
                "lineNumber": 0,
                "columnNumber": 45482
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 41,
            "callFrame": {
                "functionName": "(garbage collector)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 1
        },
        {
            "id": 44,
            "callFrame": {
                "functionName": "(program)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 6
        }
    ],
    "startTime": 3850628895,
    "endTime": 3858800642,
    "samples": [
        23,
        25,
        25,
        25,
        25,
        25,
        25,
        27,
        30,
        31,
        31,
        32,
        33,
        34,
        35,
        36,
        36,
        37,
        38,
        40,
        38,
        38,
        41,
        17,
        43,
        17,
        38,
        38,
        44,
        44,
        44,
        44,
        44,
        44
    ],
    "timeDeltas": [
        8166100,
        449,
        136,
        309,
        142,
        143,
        134,
        133,
        132,
        137,
        136,
        158,
        136,
        131,
        133,
        122,
        157,
        135,
        149,
        131,
        132,
        137,
        156,
        161,
        135,
        140,
        180,
        134,
        125,
        121,
        119,
        127,
        126,
        122
    ]
}

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/issues/2392
