### ISSUE TITLE
[Icon Request] Support for Remote Development extension

### ISSUE THREAD

**Issue by myermian** [vscode-icons/vscode-icons#2422]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `devcontainer`
  - Sample original Icon: N/A
  - Filename: `devcontainer.json`

- More info: This may have to be delayed as the Remote Development extension is still under preview, so things can change.
- https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack
- https://github.com/microsoft/vscode-dev-containers

**Comment by JimiC** [comment]
There is no filename or file extension to be associated with.

**Comment by myermian** [comment]
Currently, the extension authors (Microsoft) have chosen to use:

- `.devcontainer` (folder)
- `devcontainer.json` (file)

So, I'm not sure what you mean that there is no filename or file extension to be associated with?

**Comment by JimiC** [comment]
In your request you have used `language id` as `Type`. The extension does not declare any. When we request more info from you we expect from you to be as specific as possible and not just drop a link for us to read a wall of text and figure out what you mean. Sorry for being blunt but we are facing difficult times and personally my free time is more precious than anything else nowadays. As I'm constantly saying, help us so we can help you.

**Comment by myermian** [comment]
> `Language Extensions`: <- if `Type` includes `languageId`, provide links to the`vscode` extensions, found in the [marketplace](https://marketplace.visualstudio.com/vscode), that support language highlighting, otherwise remove the entire line.

> `language id`, when the request refers to a, `vscode` or a 3rd party extension, `language id` (if you are not sure use any of the above).

I misunderstood how to appropriately file the request. I read this as "use `languageId` if you are referencing vscode extensions that exist in the marketplace -- that is, I thought that if you specified the vscode extension, then all of the folder/files related to that extension would be accounted for?

**Comment by JimiC** [comment]
There are `vscode` extensions that declare `language: id` in `package.json`. We use that to associate an icon to the filenames or/and file extensions they declare. The extension you mention doesn't do that. Not all `vscode` extensions are language support extensions. Unfortunately, it's impossible to explain that to each and everyone of you. Of course, I realize and accept that not all of you know the technical details and that's why reading the wiki *carefully* is key.
