### ISSUE TITLE
[Icon Request] rpm and archlinux folder

### ISSUE THREAD

**Issue by huiyifyj** [vscode-icons/vscode-icons#2423]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `folder`
  - Icon Name: `rpm`, `archlinux`
  - Sample original Icon:
    - rpm: https://simpleicons.org/?q=redhat or https://simpleicons.org/icons/redhat.svg
    - archlinux: https://simpleicons.org/?q=archlinux or https://simpleicons.org/icons/archlinux.svg

- More info:
  This folder is used to store packaging resources or scripts, like `deb` folder. #2418

**Comment by JimiC** [comment]
see #650
