### ISSUE TITLE
[Icon request] Light and Dark folders.

### ISSUE THREAD

**Issue by RubenVerg** [vscode-icons/vscode-icons#2431]
- [x] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `light`/`dark`
  - Sample original Icon: ![logo](https://github.com/RubenVerg/Storage/blob/master/default_folder.svg)
  - Filenames: `light, .light / dark, .dark (folders)`
- More info:
Not actual languages (there should be a setting for that :}), but instead containers for styles of light- and dark-mode sites.

**Comment by JimiC** [comment]
see #650
