### ISSUE TITLE
[Icon Request] Support for .Kusto/.CSL icon

### ISSUE THREAD

**Issue by BillzGitHub** [vscode-icons/vscode-icons#2432]
- [X ] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Kusto`
  - Sample original Icon: ![logo](https://microsoft.sharepoint.com/teams/ceip/SharedDocuments/Tools/Kusto Explorer.zip)
  - Extensions: `.csl .kusto`
- More info: There was no easy URL that points to this. I found the zip that contains the installer for Kusto Explorer. Within the zip you will find the kusto.logo.ico Icon File

**Comment by KingDarBoja** [comment]
Seems like this is related to Kusto, a service for storing and running interactive analytics over Big Data owned by Microsoft.

VSCode extension -> [kusto-syntax-highlighting](https://github.com/josin/kusto-syntax-highlighting/blob/master/package.json)

**Comment by BillzGitHub** [comment]
I have a vendor account with Microsoft and that is how I was able to get access to the URL above with the zip folder containing the icon.

I redownloaded the zip folder and deleted all contents from it, except for the Kusto Logo (kusto.logo.ico)

[Kusto Explorer (1).zip](https://github.com/vscode-icons/vscode-icons/files/4537596/Kusto.Explorer.1.zip)

Let me know if there is anything else I can provide that would help.

Thanks

**Comment by KingDarBoja** [comment]
Hi @BillzGitHub 

Can you provide a svg file? I have issues trying to open `ico` files and using converters does not yield a good svg.

Also, by looking at the docs, the icon is pretty different to the one you posted. https://docs.microsoft.com/en-us/connectors/kusto/

**Comment by KingDarBoja** [comment]
@BillzGitHub I will dig on google for that Kusto icon svg as all pngs are too small to work on. Also, no access for me with that url :D

**Comment by BillzGitHub** [comment]
@KingDarBoja , I owe you an apology. I had an email chat with the Group Program Manager for Azure Data Explorer and they suggested that we should, in fact, be using the SVG you had presented.

Sorry for the confusion.

Thanks for your help on this, 
Bill
[azure_data_explorer.zip](https://github.com/vscode-icons/vscode-icons/files/4565399/azure_data_explorer.zip)

**Comment by KingDarBoja** [comment]
No problem mate, just wanted to be sure to have a svg so I can do this quickly 😄
