### ISSUE TITLE
Custom file icon not work for ".csv" files

### ISSUE THREAD

**Issue by onlyzdd** [vscode-icons/vscode-icons#2433]
Hi, I'm trying to customize file icon for ".csv" files. However, it does not work but works for other file extensions (e.g., ".py"). You can see from the screenshot, icon for ".py" files has been changed to "javascript" icons but it's not working for ".csv" files.

![example](https://imgur.com/vaYqcw4.png)

BTW, inline style for ".csv" files:

![style](https://imgur.com/CMIuI5H.png)

I'm using mac code v1.43.2, vsicons v10.0.0.

**Comment by KingDarBoja** [comment]
You should provide the extensions in one single array instead of different icon objects as the extension is loading the first icon definition. Subsequent overrides doesn't work it seems.

```json
{ "icon": "js", "extensions": [".py", ".csv"], format: "svg" }

**Comment by onlyzdd** [comment]
Hi, @KingDarBoja. I tried your solution and reload window, but it's still not working. I'm wondering whether your can replicate this problem?

![](https://imgur.com/ixub2E6.png)

**Comment by KingDarBoja** [comment]
@onlyzdd Sorry for the late response but I gave you the wrong setup, it should be indeed an extensions array but the string must not have dots.

**Proof**
![image](https://user-images.githubusercontent.com/30560560/78728772-dabb7a00-78fd-11ea-9ec5-40f2dd2b8553.png)

**Comment by onlyzdd** [comment]
> @onlyzdd Sorry for the late response but I gave you the wrong setup, it should be indeed an extensions array but the string must not have dots.
> 
> **Proof**
> ![image](https://user-images.githubusercontent.com/30560560/78728772-dabb7a00-78fd-11ea-9ec5-40f2dd2b8553.png)

**Comment by onlyzdd** [comment]
@KingDarBoja Thank you.

**Comment by JimiC** [comment]
As shown in https://github.com/vscode-icons/vscode-icons/wiki/FineTuning#some-examples
