### ISSUE TITLE
[Icon Request] Support for .issuetracker

### ISSUE THREAD

**Issue by jerone** [vscode-icons/vscode-icons#2434]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `issuetracker`
  - Sample original Icon: -
  - Filenames: `.issuetracker` (full file name)
  - Language ids: unknown

- Language Extensions: not (yet) available.
- More info:

`.issuetracker` is used by [Fork](https://fork.dev/) (_"a fast and friendly git client for Mac and Windows"_) to link issues to the bug-tracker.

See https://github.com/ForkIssues/TrackerWin/issues/265#issuecomment-492285012

Also implemented in Visual Studio extension [File Icons](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.FileIcons) by Mads Kristensen: https://github.com/madskristensen/FileIcons/issues/221

**Comment by KingDarBoja** [comment]
Hi @jerone 

Does this `issuetracker` filename has an official icon? If so, would be great if you can share it.

**Comment by jerone** [comment]
@KingDarBoja No, not that I know of.

This is what Visual Studio extension File Icons is using:
![image](https://user-images.githubusercontent.com/55841/80302749-3ade6700-87ac-11ea-90fe-9497e553f05d.png)

@DanPristupov Maybe you have a suggestion...

**Comment by DanPristupov** [comment]
I think it should have same icon as other dot-files (`.gitignore`, `.gitattributes`, `.gitmodules`, `.editorconfig`, etc)
