### ISSUE TITLE
[Icon Request] Support for API-Extractor

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#2439]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `api_extractor`
  - Sample original Icon: ![logo](https://api-extractor.com/images/api-extractor.svg)
  - Filenames: `api-extractor.json`, `api-extractor-base.json`

- More info: https://api-extractor.com/
https://github.com/microsoft/api-extractor.com-website/blob/master/images/api-extractor.svg

**Comment by KingDarBoja** [comment]
Beautiful icon if you ask me. The only issue would be the background that should make it have a light version too.

**Comment by JimiC** [comment]
We could use it without the circular background. Experiment on it.
