### ISSUE TITLE
[Icon Request] Support for Zig

### ISSUE THREAD

**Issue by LiteUnder** [vscode-icons/vscode-icons#2449]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `zig`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/ziglang/logo/master/zig-icon.svg?sanitize=true)
  - Extensions: `zig`

- More info: [official website](https://ziglang.org)

**Comment by KingDarBoja** [comment]
More info: [vscode-zig](https://github.com/ziglang/vscode-zig)
