### ISSUE TITLE
How to associate `_test.go` with `Golang` icon 

### ISSUE THREAD

**Issue by ioanb7** [vscode-icons/vscode-icons#2459]
I've changed the icons for javascript test files like so:
![image](https://user-images.githubusercontent.com/9282777/79080070-daaae800-7d0a-11ea-8126-354b573d452c.png)
I would like to do the same for golang. However, the extension gets confused because `_test.go` is not really a file extension.

Following code shows what my settings.json config looks like now:
```
    "vsicons.associations.files": [
        { "icon": "asciidoc", "extensions": ["test.js"], "format": "svg", "extends":"testjs" },
        { "icon": "asciidoc", "extensions": ["_test.go"], "format": "svg", "extends":"go" },
    ],
```
![image](https://user-images.githubusercontent.com/9282777/79080093-05953c00-7d0b-11ea-822e-d134ee70f21f.png)

Thanks,
Ioan

**Comment by JimiC** [comment]
`vscode` can't handle `glob` file associations for icon themes. This is ancient history. Better try `server.test.go` as filename.

**Comment by ioanb7** [comment]
That's a shame as go tests have to follow this format. Its own standard libraries follow the same convention: https://github.com/golang/go/tree/master/src/strings

**Comment by JimiC** [comment]
Why do ppl feel the urge to do things outside a standard?!?

**Comment by ioanb7** [comment]
One reason for this is the tool support. For example the command `go test` only runs the `_test.go` files.
```
> go help test
usage: go test [build/test flags] [packages] [build/test flags & test binary flags]

'Go test' automates testing the packages named by the import paths.
It prints a summary of the test results in the format:

        ok   archive/tar   0.011s
        FAIL archive/zip   0.022s
        ok   compress/gzip 0.033s
        ...

followed by detailed output for each failed package.

'Go test' recompiles each package along with any files with names matching
the file pattern "*_test.go".
These additional files can contain test functions, benchmark functions, and
example functions. See 'go help testfunc' for more.
```

I'm sure there is a hack somewhere to run .test.go files, but it's undesirable.

**Comment by JimiC** [comment]
There is literally nothing we can do about it. Sorry.

**Comment by bradzacher** [comment]
shouldn't this be achievable via:

```json
{
    "icon": "asciidoc",
    "filenamesGlob": [
        "_test"
    ],
    "extensions": [
        ".go"
    ],
    "extends": "asciidoc"
}
```

This is what I'm using to match `foo-e2e.js` and `bar-test.js`:
```json
{
    "icon": "testjs",
    "filenamesGlob": [
        "-e2e",
        "-test"
    ],
    "extensions": [
        ".js"
    ],
    "extends": "testjs"
}
```

Ordering is important - the vscode-icons will apply the last matching association in the array.

**Comment by JimiC** [comment]
No! This is not the `glob` you think it is.

**Comment by bradzacher** [comment]
Curious. Why does the extension define config like this if it won't work?

https://github.com/vscode-icons/vscode-icons/blob/d2b76ec8b90d4cde05f6ed3078c5c2d93df9f8a8/src/iconsManifest/supportedExtensions.ts#L3583-L3590

Or am I misunderstanding - will this config only match `foo.test.js` and never `foo-test.js`?

**Comment by JimiC** [comment]
Those two attributes are used in combination to produce multiple file extensions. Again, it's not the `glob` you think it is.

**Comment by KingDarBoja** [comment]
Closing as resolved.

**Comment by Southclaws** [comment]
As this was resolved, how can you achieve different icons for Go test files?
