### ISSUE TITLE
.html.erb files not recognized

### ISSUE THREAD

**Issue by simonpeterdebbarma** [vscode-icons/vscode-icons#2463]
**My VSCode**
Version: 1.44.1 (user setup)
Commit: a9f8623ec050e5f0b44cc8ce8204a1455884749f
Date: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

![image](https://user-images.githubusercontent.com/31207418/79285209-20d28980-7e7a-11ea-9ef7-82766bec893b.png)

I found https://github.com/vscode-icons/vscode-icons/pull/160 where it seems to have been fixed, but it does not work on my system. Thank you for any help, in advance!

**Comment by JimiC** [comment]
Use an `erb` syntax highlighting extension from the marketplace to make the icon show up.

**Comment by simonpeterdebbarma** [comment]
@JimiC I have `erb` syntax highlighting extensions. I tried installing various ones but it still doesn't work.

Do you have any you suggest in particular?

**Comment by JimiC** [comment]
Checking again the icon should show up as `ruby` syntax highlighting is natively supported. (proof: https://github.com/microsoft/vscode/blob/master/extensions/ruby/package.json)

Disable all extensions except `vscode-icons`. Check the icon shows. If it does then enable your extensions one by one. See what's causing the icon not to show.

**Comment by tnvr000** [comment]
Is this issue solved? Because I'm facing the same issue in Ubuntu 18.04. It is Rails (https://marketplace.visualstudio.com/items?itemName=bung87.rails) extension that is causing the issue.

**Comment by KingDarBoja** [comment]
Hi @tnvr000,

Please avoid commenting old issues and instead open a new one explaining the bug/feature you would like to be looked at.

Thank you!
