### ISSUE TITLE
Folder icons clickable like arrows?

### ISSUE THREAD

**Issue by kanlukasz** [vscode-icons/vscode-icons#2466]
- [x] I'm sure this issue is not a _duplicate_.

### More info:

Hello,

I have the `"workbench.list.openMode"` option set to `"doubleClick"`, so the folders are opened after double-clicking.

But if you click the arrow:
![image](https://user-images.githubusercontent.com/30685349/80068635-3f064c80-8540-11ea-9aa8-16d006bbbde3.png)
then the folder is expanded with one click (this demarcation is very helpful)

Can you add an option that will make the folder icons behave like the default arrows?
I would like to hide the arrows, keeping the one-click function on the folder icons

**Comment by robertohuertasm** [comment]
This is something you'll have to discuss with the vscode team as it is out of our control. I suggest you open this very same issue in their repo. Thanks!

**Comment by kanlukasz** [comment]
Ok thanks
