### ISSUE TITLE
[Icon Request] Support for dvc

### ISSUE THREAD

**Issue by iakremnev** [vscode-icons/vscode-icons#2467]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `dvc`
  - Sample original Icon: ![logo](https://i.imgur.com/YGWWPii.png?1)
  - Extensions: `None` 
  - Filenames: `.dvc`
  - Language ids: None

- Language Extensions: None
- More info: original logo can be obtained from *dvc-public* aws s3 bucket following command `dvc get https://github.com/iterative/dataset-registry images/dvc-logo-outlines.png` (see https://github.com/iterative/dataset-registry)

**Comment by iakremnev** [comment]
I extracted an svg image from dvc.org: https://gist.github.com/iakremnev/db3f9d5d580d53f4cf34f38773682b4a

**Comment by KingDarBoja** [comment]
Hi @iakremnev 

Can you please bring more information about this filename like a vscode extension or something else to look at?

**Comment by iakremnev** [comment]
Unfortunately, there's no extension up to this time but here's the official site of the project: https://dvc.org/
In short, it's a git-like tool for versioning and reproducing data-based experiments useful in data science projects.
