### ISSUE TITLE
[Icon request] support hook hooks folder

### ISSUE THREAD

**Issue by hackers267** [vscode-icons/vscode-icons#2468]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `icon request`
  - Icon Name: `hooks`
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: `folder hook`
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
Hi @hackers267 

Please provide more information about your icon request as we have no idea what you are referring to.

**Comment by hackers267** [comment]
for eample,I hava a folder named hooks or hook, then the folder icon can indicate it

**Comment by KingDarBoja** [comment]
Hi @hackers267 

What I meant was some info regarding any vscode extension or language that makes use of the `hook` folder in order to get some idea of what it means. Take a look at the list of [supported folder ](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders) icons.

Most of them are very specific to what kind of files those store or related to naming convetions in some languages/frameworks/etc.

**Comment by JimiC** [comment]
If this is not a folder name used by a tool, library, framework or  commonly used, it will not be supported. So unless you can provide information about it I'll be closing this issue.

**Comment by robertohuertasm** [comment]
I guess this is related to react hooks in case someone creates custom hooks: https://reactjs.org/docs/hooks-overview.html

See this example of how to structure a react project with custom hooks: https://www.relevantprogrammer.com/posts/todo-with-react-hooks/

Am I right @hackers267?

**Comment by hackers267** [comment]
> I guess this is related to react hooks in case someone creates custom hooks: https://reactjs.org/docs/hooks-overview.html
> 
> See this example of how to structure a react project with custom hooks: https://www.relevantprogrammer.com/posts/todo-with-react-hooks/
> 
> Am I right @hackers267?

Yes，that's what I mean.

**Comment by JimiC** [comment]
@hackers267 Could have said so in your OP. We aren't obligated to figure out what you mean or have in mind.

**Comment by hackers267** [comment]
I'm sorry about this. What I mean is, when I use the react and I create a folder named hook or hooks, the folder can has a icon to indicate the folder is a hook.

**Comment by chancegraff** [comment]
Drama aside, I came here looking for a [React Hooks](https://reactjs.org/docs/hooks-reference.html) icon and would love to have this implemented. I'm going to see if I can't get this working in a custom config and I'll see about opening a PR for it.

I'll update this comment with my results!

**Comment by robertohuertasm** [comment]
Thanks @chancegraff. Let me know if you need some guidance.
