### ISSUE TITLE
strange, why render icon to a Non-special folder

### ISSUE THREAD

**Issue by tjx666** [vscode-icons/vscode-icons#2470]
![screenshot_2020-04-25_18-18-55](https://user-images.githubusercontent.com/41773861/80277914-f2c83180-8724-11ea-96e0-dd82005c2d3c.png)

**Comment by tjx666** [comment]
Just make a folder named `0199-Binary Tree Right Side View` to reproduce

**Comment by ultram4rine** [comment]
That folder has special icon because folder name has View at the end. I think it's VSCode problem, because it happens other icon themes too.

**Comment by robertohuertasm** [comment]
I guess this is fixed. Can't reproduce it anymore. @tjx666 ping us if you're still experiencing this.
