### ISSUE TITLE
node folder not showing

### ISSUE THREAD

**Issue by matheusssilva** [vscode-icons/vscode-icons#2472]
As the title suggests, the node folder icon is not being shown.

VSCode 1.44.2
vscode-icons 10.1.1

![Captura de tela de 2020-04-28 17-58-06](https://user-images.githubusercontent.com/7414956/80537108-dc66e380-8979-11ea-94a4-3590437d6b10.png)

**Comment by KingDarBoja** [comment]
The **node** icon only works for `node_modules` folder name. You can enable that by using the [customisation feature](https://github.com/vscode-icons/vscode-icons/wiki/Custom).

**Comment by matheusssilva** [comment]
> The **node** icon only works for `node_modules` folder name. You can enable that by using the [customisation feature](https://github.com/vscode-icons/vscode-icons/wiki/Custom).

So I leave it as a suggestion. A folder icon for folders called "node" or "nodejs". It could be the image of a green folder with the nodejs emerald on it.
![nodeicon](https://user-images.githubusercontent.com/7414956/80596482-d0703580-89fc-11ea-9979-dbeebf90f5c5.png)

**Comment by JimiC** [comment]
`node` could also mean a node in a cluster of server 
- https://docs.microsoft.com/en-us/mem/configmgr/core/servers/deploy/configure/use-a-sql-server-cluster-for-the-site-database
- https://kubernetes.io/docs/concepts/architecture/nodes/

If it is to be then `nodejs` should be the name of the folder.

This issue should be closed by October 2020 if it doesn't have any traction.

**Comment by KingDarBoja** [comment]
The day has come and this issue shall be closed 🤖
