### ISSUE TITLE
[Icon Request] Support for ftHTML

### ISSUE THREAD

**Issue by soulshined** [vscode-icons/vscode-icons#2478]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `icon request`
  - Icon Name: `fthtml`
  - Sample original Icon: ![fthtml_file_icon.zip](https://github.com/vscode-icons/vscode-icons/files/4566856/fthtml_file_icon.zip)
  - Extensions: `ftHTML Language Support`
  - Filenames: `fthtml, ftHTML`
  - Language ids: `fthtml`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=davidfreer.fthtml-language-support
- More info:
Unfortunately, I don't have Adobe Suite or Illustrator but have linked sample icon above

**Comment by KingDarBoja** [comment]
@soulshined sorry for the delay, this is indeed a good request.
