### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jackyan** [vscode-icons/vscode-icons#2481]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.1.1`
- OS Version: `Darwin x64 19.4.0`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/jack.yan/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jackyan** [comment]
[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/4590389/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)

**Comment by Kvek** [comment]
Same here.
