### ISSUE TITLE
The default icon for Java files is too dim, it is recommended to change to a more modern Java file icon, for example: Red Hat icon or Oracle icon , open jdk icon

### ISSUE THREAD

**Issue by 395053994** [vscode-icons/vscode-icons#2483]
Issue Type: <b>Bug</b>

The default icon for Java files is too dim, it is recommended to change to a more modern Java file icon, for example: Red Hat icon or Oracle icon , open jdk icon

![image](https://user-images.githubusercontent.com/27546390/81299006-2fdadf00-90a8-11ea-9dd6-7b4749e6da48.png)
![image](https://user-images.githubusercontent.com/27546390/81299182-67498b80-90a8-11ea-820c-2f6167119e45.png)
![image](https://user-images.githubusercontent.com/27546390/81299341-a5df4600-90a8-11ea-9aa5-c676381eafe4.png)

Extension version: 10.1.1
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|9.59GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by JimiC** [comment]
Our principal is to use official icons. You can choose your own via the [icons customization feature](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning).

**Comment by 395053994** [comment]
Hello! vscode-icons How to customize icons
The document is very abstract and unreadable: https://github.com/vscode-icons/vscode-icons/wiki/Custom, request specific steps to replace the icon?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jimi (Dimitris) Charalampidis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 凌晨1:49
收件人： &nbsp;“ vscode-icons / vscode-icons” <vscode-icons@noreply.github.com&gt;;
抄送： &nbsp;“青春！” <395053994@qq.com&gt;;“作者” <author@noreply.github.com&gt;;
主题： &nbsp;Re：[vscode-icons / vscode-icons] Java文件的默认图标太暗，建议更改为更现代的Java文件图标，例如：Red Hat图标或Oracle图标，打开jdk图标（ ＃2483）





 
我们的原则是使用官方图标。您可以通过图标自定义功能选择自己的。
  
— 
您收到此消息是因为您创建了线程。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by 395053994** [comment]
Hello! vscode-icons How to customize icons
The document is very abstract and unreadable: https://github.com/vscode-icons/vscode-icons/wiki/Custom, request specific steps to replace the icon?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jimi (Dimitris) Charalampidis"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 凌晨1:49
收件人:&nbsp;"vscode-icons/vscode-icons"<vscode-icons@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vscode-icons/vscode-icons] The default icon for Java files is too dim, it is recommended to change to a more modern Java file icon, for example: Red Hat icon or Oracle icon , open jdk icon (#2483)





 
Our principal is to use official icons. You can choose your own via the icons customization feature.
