### ISSUE TITLE
Extend zeit icon to support Vercel files

### ISSUE THREAD

**Issue by nvignola** [vscode-icons/vscode-icons#2486]
- [x] I'm sure this issue is not a _duplicate_.

- More info: 

Vercel (formerly Zeit) in the [19.0.0 version](https://github.com/zeit/now/releases/tag/vercel%4019.0.0) has added support for new files:
  - `vercel.json`
  - `.vercelignore`

Vercel has performed a logo restyle [bringing minor changes](https://vercel.com/blog/zeit-is-now-vercel). I propose for those new files to reuse the [already present Zeit icon](https://github.com/vscode-icons/vscode-icons/blob/3f3cab73bf81b22d391c92b98a389f24655b85a7/src/iconsManifest/supportedExtensions.ts#L4069). 

The support for the current `now.json` and `.nowignore` should be still present until Vercel deprecate them.

**Comment by KingDarBoja** [comment]
Hi @nvignola 

Thanks for letting us know the logo rebranding, it shouldn't be too hard to change the current icon 😄
