### ISSUE TITLE
[Icon Request] Support for CDDL

### ISSUE THREAD

**Issue by anweiss** [vscode-icons/vscode-icons#2490]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `cddl`
  - Sample original Icon: TBD. There don't seem to be many grammar-based icons from which to base this, except for maybe the ANTLR icon? Could maybe re-use the JSON icon?
  - Extensions: `.cddl`
  - Filenames: `byron.cddl`
  - Language ids: `cddl`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=anweiss.cddl-languageserver
- More info:
  - The Concise Data Definition Language (CDDL) is a notational convention to express concise binary object representation (CBOR) and JSON data structures
  - [RFC 8610](https://tools.ietf.org/html/rfc8610)
  - CDDL's syntax closely resembles PEG and ABNF grammars
  - [Here](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/byron/cddl-spec/byron.cddl) is an example CDDL document

**Comment by KingDarBoja** [comment]
Hi @anweiss 

Can you point out where this extension (which I noticed is owned by yourself) declares the language id in order to support the file icon detection?

**Comment by anweiss** [comment]
Hey @KingDarBoja. Sure thing. See https://github.com/anweiss/cddl/blob/master/cddl-lsp/package.json#L38.
