### ISSUE TITLE
Add support for Bosque

### ISSUE THREAD

**Issue by carlos-menezes** [vscode-icons/vscode-icons#2494]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `bsq`
  - Sample original Icon: ![logo](https://github.com/microsoft/BosqueLanguage/blob/master/resources/brand/icon/fabric_fluent/Fabric_Bosque_Logo_32x32.png?raw=true)
  - Extensions: `.bsq`
  - Language ids: `bosque`

- Language Extensions: `.bsq`
- More info: branding resources can be found [here](https://github.com/microsoft/BosqueLanguage/tree/master/resources/brand).

**Comment by KingDarBoja** [comment]
Refer to this [package.json](https://github.com/microsoft/BosqueLanguage/blob/master/bosque-language-tools/package.json) and also [this issue](https://github.com/Microsoft/BosqueLanguage/issues/19).
