### ISSUE TITLE
Add support for Jython

### ISSUE THREAD

**Issue by reedand** [vscode-icons/vscode-icons#2497]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `jy`
  - Sample original Icon: ![Jython-icon](https://user-images.githubusercontent.com/10062760/82426787-31c97880-9a80-11ea-807d-690c54bc68d3.png)
  - Extensions: `.jy`
  - Filenames: `.jy`
  - Language ids: `jython`

- Language Extensions:
- More info:

**Comment by KingDarBoja** [comment]
I think there isn't any extension that supports Jython, even the current vscode-python doesn't support it as seen at this [issue](https://github.com/Microsoft/vscode-python/issues/4762).

**Comment by KingDarBoja** [comment]
Closing as not possible atm.
