### ISSUE TITLE
[Icon Request] Support for Hygen

### ISSUE THREAD

**Issue by ddialar** [vscode-icons/vscode-icons#2501]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `hygen`
  - Sample original Icon: Attached as SVG into the ZIP file.

[hygen-logo.zip](https://github.com/vscode-icons/vscode-icons/files/4664360/hygen-logo.zip)
  - Extensions: `ejs.t`

- Language Extensions: None
- More info: This kind of extension belongs to the templating files for [Hygen](https://www.hygen.io/), the automated code generator. Currently, this kind of files are been represented by the Perl camel logo.

**Comment by KingDarBoja** [comment]
After trying out providing such icon with the associated extension, it is impossible (AFAIK) to enable this as Perl extensions include `.t` and we can't discriminate it right now.

@JimiC any idea to solve this one?

**Comment by JimiC** [comment]
The file extension is `ejs.t`.It should not interfere with `.t`.
