### ISSUE TITLE
[Icon Request] Support for Bats

### ISSUE THREAD

**Issue by douglasduteil** [vscode-icons/vscode-icons#2505]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `bats` 
  - Sample original Icon: :bat:
  - Extensions: `.bats`
  - Shebang: `#!/usr/bin/env bats`
- Language Extensions: [`jetmartin.bats`](https://marketplace.visualstudio.com/items?itemName=jetmartin.bats)
- More info: https://github.com/bats-core/bats-core

**Comment by KingDarBoja** [comment]
I am Batman! 🦇
