### ISSUE TITLE
[Icon Request] Support for 'drawio'

### ISSUE THREAD

**Issue by techo207** [vscode-icons/vscode-icons#2512]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file icons`
  - Icon Name: `drawio`
  - Sample original Icon:  https://drawio-app.com/wp-content/uploads/2020/04/draw.io_logo_symbol_250x250.png
  - Extensions: `.drawio`

**Comment by KingDarBoja** [comment]
It seems this is a file extension as the current vscode extensions doesn't provide any language id.
