### ISSUE TITLE
Add support for Informix-4gl files

### ISSUE THREAD

**Issue by ecus** [vscode-icons/vscode-icons#2514]
- [X] I'm sure this issue is not a _duplicate_.
- [X I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `4gl`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `4gl`
  - Filenames: `.4gl`
  - Language ids: `4gl`

- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `4go`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `4go`
  - Filenames: `.4go`
  - Language ids: `4go`

- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `4gi`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `4gi`
  - Filenames: `.4gi`
  - Language ids: `4gi`

- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `per`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `per`
  - Filenames: `.per`
  - Language ids: `per`

- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `frm`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `frm`
  - Filenames: `.frm`
  - Language ids: `frm`

- [X] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `err`
  - Sample original Icon: zip attached ( [vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip) )
  - Extensions: `err`
  - Filenames: `.err`
  - Language ids: `err`

- Language Extensions:
- More info:
[vsicons-custom-icons.zip](https://github.com/vscode-icons/vscode-icons/files/4788362/vsicons-custom-icons.zip)

**Comment by JimiC** [comment]
Already supported https://github.com/vscode-icons/vscode-icons/pull/2190

**Comment by ecus** [comment]
> Already supported #2190

Not for all filetypes

**Comment by JimiC** [comment]
Take it up to the extension owner that supports it.
