### ISSUE TITLE
[Icon Request] Support for TeX auxiliary files

### ISSUE THREAD

**Issue by BambOoxX** [vscode-icons/vscode-icons#2521]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `tex_temp`
  - Sample original Icon: ![logo](https://github.com/vscode-icons/vscode-icons/files/4837603/file_type_light_tex_temp.pdf), basically just the original TeX logo print in orange, the color is open for discussion.

  - Extensions: `"aux","atfi","bbl","blg","hst","lof","lot","out","ver"` (I don't know if there is a record of all possible auxiliary LaTeX files)
  - Language ids: `tex`

- More info: The goal here is essentially to show the auxiliary TeX files with a specific icon, but different from the default one. Otherwise, the .tex is hidden in the middle of potentially numerous files. 
- An addition could be to have different colors for `.cls` (class), `.sty` (package), or `.bib` (bibliography) files.
- Here is a list of interesting TeX file extensions https://github.com/github/gitignore/blob/master/TeX.gitignore

The overall behavior would be quite equivalent to what happens in atom with the `file-icons` extension

**Comment by KingDarBoja** [comment]
The current behaviour is displaying the following language ids as the same Tex Icon:

```
{
      icon: 'tex',
      extensions: ['texi', 'tikz'],
      languages: [
        languages.tex,
        languages.latex,
        languages.bibtex,
        languages.doctex,
      ],
      light: true,
      format: FileFormat.svg,
},
```

Those were based on [LaTeX-Workshop extension](https://github.com/James-Yu/LaTeX-Workshop/blob/master/package.json).
Based on that, we could provide a colour variant per languageId related to this Tex extension but not sure what other members think about it. @JimiC @robertohuertasm

**Comment by BambOoxX** [comment]
@KingDarBoja I am currently using LaTeX-Workshop myself. To make my proposal more precise, my idea is only to add some icon for not already supported extensions. Basically, one color could go to temporary files, and another for configuration files (class, packages).
