### ISSUE TITLE
[Icon Bug] PineScript icon not working

### ISSUE THREAD

**Issue by AruXc** [vscode-icons/vscode-icons#2523]
- [x] I'm sure this issue is not a _duplicate_.

- Issue Type: Bug
- Extension Name: vscode-icons
- Extension Version: 10.1.1
- OS Version: macos catalina 10.15.4
- VSCode version: 1.45

filename .pine not show anything.

**Comment by KingDarBoja** [comment]
Did you installed this [extension](https://marketplace.visualstudio.com/items?itemName=leifcr.pine-script-syntax-highlighting)?

**Comment by AruXc** [comment]
> Did you installed this [extension](https://marketplace.visualstudio.com/items?itemName=leifcr.pine-script-syntax-highlighting)?

Yes, I already install extension and active it.

**Comment by KingDarBoja** [comment]
Just confirmed the issue on my local setup, I will check out what's going on, thank you for the report!

**Comment by KingDarBoja** [comment]
I just noticed now that there are two vscode extensions for Pinescript, but the first one uses `pine` as language Id whereas the second one uses `pinescript`.

I accidentally installed the wrong one, so the linked one **does work** on my local setup. 

Anyway, I will add the other language id just in case, but regarding your issue @AruXc , not sure what's going on.

**Comment by AruXc** [comment]
I tried the two extensions before I post the issue, but still not working. 

How did you do that? 

@KingDarBoja  Thanks for your help.

**Comment by KingDarBoja** [comment]
@AruXc I just installed the first extension and checked if the file with `.pine` showed the right icon.

![pine_working](https://user-images.githubusercontent.com/30560560/85966211-aac3c600-b984-11ea-8387-ba94e14d5636.png)

Maybe you need to check if you have the correct icon theme and reload VSCode.

**Comment by AruXc** [comment]
@KingDarBoja It's working...

But I still don't know why haha 

Thank you again for your time.
