### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by tqoliver** [vscode-icons/vscode-icons#2525]
[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/4846129/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)
[vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt](https://github.com/vscode-icons/vscode-icons/files/4846133/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.1.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/timothyoliver/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
See pinned issue.
