### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ludo57** [vscode-icons/vscode-icons#2526]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.1.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.46.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Ludovic\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
See piined issue
