### ISSUE TITLE
[Icon Request] Support for xmake

### ISSUE THREAD

**Issue by u3IFw2wfJ** [vscode-icons/vscode-icons#2530]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `xmake`
  - Sample original Icon: ![logo](https://xmake.io/assets/img/logo.svg)
  - Extensions: `tboox.xmake-vscode`
  - Filenames: `xmake.lua`
  - Language ids: ``

- Language Extensions: 
- More info:https://github.com/xmake-io/xmake

**Comment by KingDarBoja** [comment]
The vscode extension has `languageId` as seen at [package.json](https://github.com/xmake-io/xmake-vscode/blob/master/package.json#L56) of **xmake-vscode**.
