### ISSUE TITLE
Support for jest.config.js

### ISSUE THREAD

**Issue by redshoga** [vscode-icons/vscode-icons#2531]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `Jest Config`
  - Sample original Icon: https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_jest.svg
  - Filenames: `jest.config.js`

- More info:

https://jestjs.io/docs/en/configuration

**Comment by JimiC** [comment]
Already supported
