### ISSUE TITLE
How to 'disable' a folder ? 

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [vscode-icons/vscode-icons#2534]
Hello ! 

Sorry to ask, I had a look in the wiki and into the code but I can't quickly find out how is managed the kind of greyed out aspect of a folder icon like the `.settings` or the `webapp` ones.
![image](https://user-images.githubusercontent.com/26161416/87152742-8934d980-c2b6-11ea-959a-a516d9d9cfdf.png)

I have custom folder that I would like to make less visible, so use the same pattern, and I guess there is a configuration to set into vsicons.associations.folders, I already changed some things there, like icons, but I can't find how to do it for making that folder less visible.

Any idea ? Is it configurable ? I can't see it in the configuration section for folders.
Thanks !

**Comment by robertohuertasm** [comment]
This is not supported by the extension. I'm not even sure we have access to this functionality in the vscode api. Anyway, usually folders are greyed out because they're ignored in your gitignore file and this is automatically managed by vscode.

**Comment by GuillaumedesPommareSAP** [comment]
Ohhh ... I see 😊
As these folders where not greyed out with this plugin disabled and are when activated, I thought it has something to do with it.
I wanted to make some folders less visible, and some other more, but, you are right, currently this has nothing to do with the vscode-icons plugin.

It remains maybe an interesting feature IF there is any way to customize the folder from vscode api

**Comment by robertohuertasm** [comment]
I'm closing this as it seems to be solved! We take note of this use case in case it becomes available to us via the vscode api in the future.
