### ISSUE TITLE
Cannot fine tune root_folder icon

### ISSUE THREAD

**Issue by creage** [vscode-icons/vscode-icons#2541]
I'm using VSCode workspace, and I have custom layout of folders
```json
{
    "folders": [
        {
            "path": "e2e"
        }
    ]
}
```

I want some of these folders to have other icon than `root_folder`. So, I've tried 

```json
"vsicons.associations.folders": [
    {
        "icon": "e2e",
        "extensions": [
            "e2e"
        ],
        "format": "svg",
        "overrides": "root_folder"
    }
]
```
But the **e2e** folder icon still looks like `root_folder` icon.

How do I change it?

**Comment by JimiC** [comment]
You need to use `"vsicons.associations.folderDefault.root_folder"`. For some reason, this is not documented in our Wiki. We should add it asap.

**Comment by JimiC** [comment]
Docs updated.

**Comment by creage** [comment]
Well, what is the correct way of defining it?

```json
"vsicons.associations.folderDefault.root_folder": {
	"icon": "e2e",
	"extensions": [
		"e2e"
	],
	"format": "svg",
	"overrides": "root_folder"
}
```

This config does not change my icon.

And please note, that I don't want to change the default `root_folder` icon for all of folders, but for one particular folder only, if possible.

**Comment by JimiC** [comment]
If `e2e` if not the root folder then you should use `"vsicons.associations.folders"`.

**Comment by JimiC** [comment]
Furthermore, you can't change individual `roo_folder` icons. It's either all or none.

**Comment by creage** [comment]
Well, having a single root folder does not make much sense in our solution. I mean, our project has many folders - sources, tests, i18n etc. - these are all root folders in our Explorer view in VSCode. I was hoping to configure icons for these folders manually.

**Comment by JimiC** [comment]
It's not that we don't want to. It's the editor that's not supporting it.

**Comment by tjx666** [comment]
So why not just an icon for root_folder but using another name, for example: `vsicons_root_folder`?

**Comment by JimiC** [comment]
> > It's not that we don't want to. It's the editor that's not supporting it.
> 
> @JimiC When this feature is implemented, will custom individual root folder icons be possible? [microsoft/vscode#12493 (comment)](https://github.com/microsoft/vscode/issues/12493#issuecomment-249117649)

I'm not optimistic on that front.
