### ISSUE TITLE
[Icon Request] Support for .storybook folders

### ISSUE THREAD

**Issue by jun-sheaf** [vscode-icons/vscode-icons#2544]
- [X] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: folder
  - Icon Name: `storybook-folder`
  - Sample original Icon: The current storybook icon superimposed over the folder icon of similar color (like typings).
  - Extensions: None
  - Filenames: `.storybook`
  - Language ids: None
  - Language Extensions: None
  - More info: The `.storybook` folder is the primary method for configuring storybook.

**Comment by JimiC** [comment]
The icons already exist https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#story.

**Comment by jun-sheaf** [comment]
The filename .storybook should be built in. It's currently not listed as one of the filenames for the story folder icon

**Comment by JimiC** [comment]
Please link official documentation where the name is used.

**Comment by jun-sheaf** [comment]
See here: (List of Folder Icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders)
Check the `story` icon and its associated list of extensions. `.storybook` is not listed.

**Comment by JimiC** [comment]
I know. What I'm asking is for you to link official documentation where it says that `.storybook` is used. Can't make it clearer than that.

**Comment by robertohuertasm** [comment]
https://storybook.js.org/docs/basics/writing-stories/ This is from the official docs and they reference the aforementioned folder extension.

**Comment by robertohuertasm** [comment]
@jun-sheaf we usually thank having some official link to support your claiming. It help us to identify valid usages as we cannot keep up with the amount of different conventions in many different technologies.

**Comment by jun-sheaf** [comment]
> Please link official documentation where the name is used.

Misread this. Was working at 2AM, my apologies.

> @jun-sheaf we usually appreciate having some official link to support your claiming.

Yes, that's clear. Perhaps you should implement this into the issue template under `Reference:`.

**Comment by jun-sheaf** [comment]
> @jun-sheaf 
> 
> >Storybook has a few files it uses for configuration, and they are grouped together into a directory (default: .storybook).
> 
> 
> 
> That would suffice. You do understand that I personally don't have the time or the will to read the docs of any library, framework, tool, extension someone is requesting support to. I'm not even bothering. It's up to you, the user, to make it as easier as possible for us to justify your request and accept it.

As previous stated, it was a mistake on my part. What you said is obvious; I did not intend for you to look through the docs.

In any case, the PR you closed fixe/ this issue. Should I resubmit it? Or would you like a maintainer to deal with this?

**Comment by JimiC** [comment]
Your PR took the wrong approach. This issue is already assigned.
