### ISSUE TITLE
[Icon Request] Support for old Gradle Icon

### ISSUE THREAD

**Issue by koldou98** [vscode-icons/vscode-icons#2568]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `Extension`
  - Icon Name: `Gradle`
  - Sample original Icon: ![logo](https://res.cloudinary.com/dmgyattwm/image/upload/v1595934980/gradle_old_ab3v4k.svg)
  - Extensions: `gradle`

**Comment by KingDarBoja** [comment]
This can be supported as optional icon, so you need to enable it using the [customisation feature](https://github.com/vscode-icons/vscode-icons/wiki/Customization) after PR has been accepted and merged.
