### ISSUE TITLE
[Icon Request] Support for "webapp" Folder Icon

### ISSUE THREAD

**Issue by 3GOMESz** [vscode-icons/vscode-icons#2569]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `Folder`
  - Icon Name: `webapp`
  - Extensions: `webapp`

It would be interesting to have support for folders called "webapp" where, unlike common applications, web applications(webapp) indicates that your application runs on the web as an express.js server for example.

**Comment by 3GOMESz** [comment]
I have no idea how an icon would look like for that. For now I'm waiting for more people to discuss the idea...

**Comment by KingDarBoja** [comment]
Maybe the folder icon with the server one like this: 
![image](https://user-images.githubusercontent.com/30560560/89589923-62fa4f00-d80c-11ea-891f-55c814002063.png)

Of course, scrapping the DB icon in order to keep the icon simple.

Also any suggestion to folder icons should be commented at #650 😛
