### ISSUE TITLE
how to add flutter sdk path

### ISSUE THREAD

**Issue by michaelNabil316** [vscode-icons/vscode-icons#2570]
![Capdddture](https://user-images.githubusercontent.com/66490732/89063582-18428800-d371-11ea-868c-a8394af2e61f.PNG)

when do run issue appear about add --stracktrac or --debug
i tried too much solves but no way
when open project structure i found this, tried to add c:\src\flutter but it tell me not a valid path
<!-- Please first read how to submit an issue, if

**Comment by michaelNabil316** [comment]
@sandy081 please take a look

**Comment by JimiC** [comment]
@michaelNabil316 Wrong repo.

**Comment by michaelNabil316** [comment]
what wrong in this?

**Comment by JimiC** [comment]
This is not the correct repo to post your issue,

**Comment by michaelNabil316** [comment]
it's my second time to share issue so i just new here
