### ISSUE TITLE
no sdk path for flutter

### ISSUE THREAD

**Issue by michaelNabil316** [vscode-icons/vscode-icons#2575]
![Capdddture](https://user-images.githubusercontent.com/66490732/89122274-a3856000-d4ce-11ea-9e58-49f9ef578dda.PNG)

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
@flutter
@dart
 -More
the app doesn't run and asked for put --stracktrac or --debug and also didn't work and when open project structure i found this and when choose src/flutter as flutter sdk path it tell me not valid

**Comment by michaelNabil316** [comment]
@sandy081
please take a look here

**Comment by JimiC** [comment]
Please stop opening issue about this here. This is not the correct repo for your issue,
