### ISSUE TITLE
[Icon Request] Support for ReasonML BuckleScript 8 files

### ISSUE THREAD

**Issue by wpwood** [vscode-icons/vscode-icons#2576]
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `.res, .resi`
  - Icon Name: `reason`
  - Sample original Icon: ![logo]()
  - Extensions: `.res, .resi`
  - Filenames: `example.res, example.resi`
  - Language ids: `reason`

- Language Extensions:
- More info:

There's a new syntax for ReasonML that uses files ending in .res and .resi instead of .re and .rei. The existing ReasonML icon is fine, it just needs to be used for '.res and '.resi files as well as .re and .rei (at least for now, all four file extensions are supported in ReasonML).

Details at https://reasonml.org/docs/reason-compiler/latest/new-bucklescript-syntax

**Comment by KingDarBoja** [comment]
> How to Use the New Syntax
Install bs-platform@8.1 and create a file with the .res or .resi file extension to enable the new syntax parser (no further configuration required).

Just to save us some time 😋

**Comment by KingDarBoja** [comment]
Closing as there has been a new ReScript support which handles BuckleScript files: #2600
