### ISSUE TITLE
Add support for `tool` within the `tools` folder

### ISSUE THREAD

**Issue by jorgecoca** [vscode-icons/vscode-icons#2583]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

The existing `tools` folder supports `tools`, `.tools`, `util` and `utils`; however, in Dart it is a convention to have a `tool` folder, so I think it'd make sense to see `tool` included in this category as well

**Comment by KingDarBoja** [comment]
Just in case someone need to check: https://dart.dev/tools/pub/package-layout
