### ISSUE TITLE
[Icon Request] Support for Power Query (new extension)

### ISSUE THREAD

**Issue by zahra-travail** [vscode-icons/vscode-icons#2586]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `mlang`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_mlang.svg?_sm_au_=iVVjBrrHH6J2B1ZJLVN2jKsTtN4QF) 

![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_light_mlang.svg?_sm_au_=iVVjBrrHH6J2B1ZJLVN2jKsTtN4QF)
  - Extensions: `PowerQuery.vscode-powerquery`
  - Filenames: `.pq, .pqm, .m, .mout`
  - Language ids: `powerquery`

- Language Extensions:
- More info:
Was used for the old extension sea1jxr.powerquerymlanguage which is now unpublished and replaced by PowerQuery.vscode-powerquery. The original request for powerquerymlanguage was made in issue #1254

Existing icon file_type_light_mlang.svg and file_type_mlang.svg in the code can be reused.
--

**Comment by KingDarBoja** [comment]
Just in case, the new extension is owned by Microsoft and available at https://marketplace.visualstudio.com/items?itemName=PowerQuery.vscode-powerquery
