### ISSUE TITLE
[Icon Request] Support for benchmark/benches folders

### ISSUE THREAD

**Issue by aspenluxxxy** [vscode-icons/vscode-icons#2588]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - **Type**: `dirname`
  - **Icon Name**: `benchmark`
  - **Sample original Icon**: Couldn't really find a good icon to represent "benchmarks", but it'd probably be a graph or something? Maybe something representing speed? Like a speedometer?
  - **Extensions**: None
  - **Filenames**: Folders named `benches`, `bench`, `benchmarks`, `benchmark`, etc
  - **Language ids**: None

**Comment by aspenluxxxy** [comment]
Example for where this would be used: the `benches` folder [is standard in Cargo's project layout](https://doc.rust-lang.org/cargo/guide/project-layout.html)

**Comment by KingDarBoja** [comment]
Please suggest the folder icon at #650, thanks!
