### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GiuseppeMobijay** [vscode-icons/vscode-icons#2591]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `10.2.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.48.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/mediabilling/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by JimiC** [comment]
See pinned issue,
