### ISSUE TITLE
[Icon Request] Support for ReScript

### ISSUE THREAD

**Issue by fa7ad** [vscode-icons/vscode-icons#2599]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension, languageId`
  - Icon Name: `rescript`
  - Sample original Icon: ![logo](https://rescript-lang.org/static/rescript-logo.svg)
  - Extensions: `.res, .resi`
  - Language ids: `rescript`

- Language Extensions: [rescript-vscode](https://marketplace.visualstudio.com/items?itemName=chenglou92.rescript-vscode)
- More info: This should work very similar to reasonml, since these are essentially the same language (right now)

**Comment by KingDarBoja** [comment]
Looks like [ReasonML](https://reasonml.org/) is deprecated, now it is [ReScript](https://rescript-lang.org/) D:

**Comment by rafaelfesi** [comment]
AFAIK, ReasonML (`.re` and `.rei`) will continue to be an alternative syntax for OCaml and focus on native / cross compilation for all platforms. And ReScript will focus on web, transpiling to JS.

Also stated [here](https://reasonml.org) in "What about ReasonML?" section.
