### ISSUE TITLE
icon for .hh suffix is confused with .cc

### ISSUE THREAD

**Issue by Xiangpeng-Sun** [vscode-icons/vscode-icons#2602]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `file_type_cppheader`
  - Sample original Icon: ![logo](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_cppheader.svg)
  - Extensions: `.cc`

- More info:
   icon for .hh suffix shall be the same with .hpp header file instead of using .cc/.cpp 's icon
   
<img width="541" alt="image" src="https://user-images.githubusercontent.com/34417280/91651069-6e166700-eaba-11ea-940a-ee1b86d53d15.png">

**Comment by JimiC** [comment]
Looking at the [extensions](https://github.com/microsoft/vscode/blob/cca934db91ff8a4fa660710b5892c4014577fba9/extensions/cpp/package.json#L30) of the native supported `vscode` extension for CPP, we need to associate more than `hh` to the `cppheader` icon.
Added extensions should be: `hh`, `hxx`, `h++`.
`h` is already supported via the `cheader` icon.
