### ISSUE TITLE
getaddrinfo ENOTFOUND connct

### ISSUE THREAD

**Issue by URDEY** [vscode-icons/vscode-icons#2607]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by URDEY** [comment]
Error while starting Sync: request to https://vscode-auth.github.com/token?code=1bc6e71be94697ff138b&state=6672313d-1bfb-4575-b5a7-99ba51e93c65 failed, reason: getaddrinfo ENOTFOUND connect

**Comment by jens1o** [comment]
The error message doesn't really help us troubleshooting, it even seems unrelated to this extension?

**Comment by URDEY** [comment]
when check for VS updates net::ERR_PROXY_CONNECTION_FAILED it problem started from npm
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/gatsby-cli failed, reason: getaddrinfo ENOTFOUND proxyhostname
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

**Comment by jens1o** [comment]
> npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly. See: 'npm help config'

npm clearly indicates what your problem is, a misconfiguration of your HTTP(S) proxy

**Comment by JimiC** [comment]
Another thing I like to add is: This is **NOT** the repository for the `vscode` editor.
