### ISSUE TITLE
Prefix Support for filename match

### ISSUE THREAD

**Issue by debugger24** [vscode-icons/vscode-icons#2617]
As per python unit test practice, the test file name should start with `test_` prefix. If we add support for using prefix or use of regex like `test_*` for file selection for icon it will be nice.

- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by JimiC** [comment]
`vscode` does NOT support `glob` naming for icon themes.
