### ISSUE TITLE
Virtual environment (Venv)

### ISSUE THREAD

**Issue by Adilmrqureshi** [vscode-icons/vscode-icons#2618]
- [ x] I'm sure this issue is not a _duplicate_.
- [x ] I'm submitting an icon request:
  - Type: `python, extension`
  - Icon Name: `venv`
  - Sample original Icon: ![logo]()
  - Language ids: `python`

- Language Extensions:
- More info: This is commonly used and can just be a folder with the python logo at the bottom, or whatever you guys can come up with

**Comment by JimiC** [comment]
`.venv` folder icon is already implemented
