### ISSUE TITLE
Angular Icons Replaced with Plain TS

### ISSUE THREAD

**Issue by rodrigodivino** [vscode-icons/vscode-icons#2619]
- [x] I'm sure this issue is not a _duplicate_.

- More info:

Some icons specific for Angular, such as .component.ts and .service.ts (full list here #437) appear to me as plain typescript since the latest release:

![image](https://user-images.githubusercontent.com/21156756/93597761-f12c2e00-f991-11ea-8fd1-bc353401e103.png)

**Comment by KingDarBoja** [comment]
I can confirm the same issue on my current setup after last update. The fix is to manually activate the angular icons at workspace level by opening the command toolbar and select "Icons: toggle angular preset (workspace level)"

**Comment by break7533** [comment]
There are people that use the same naming for other frameworks.

I usually work with React and still create .component.ts and .service.ts files.

With the latest updates now I have Angular icons all over a React project.

For these scenarios, I believe having the manual toggle/config makes more sense than having a such general rule

**Comment by robertohuertasm** [comment]
@break7533, we're aware of that, and that's why Angular icons should only activate if the angular dependency exists in your `package.json`. If that's not your case, that could mean that somehow you've got the toggle enabled at config level. Could you check your `vscode` settings?

As @KingDarBoja says, you have a manual toggle available: `Icons: toggle angular preset (workspace level)`

**Comment by break7533** [comment]
Hi @robertohuertasm, no dependencies on Angular, until now I was using all default settings on the extension.
Everything was working fine until the extension updated this morning.

I don't have changes on the workspace settings and on the user settings I have the following.

```json
    "vsicons.presets.angular": false,
```

Yeah, the toggle also worked fine, just strange that it turned on for some reason
