### ISSUE TITLE
[Icon Request] Add Ogone support

### ISSUE THREAD

**Issue by SRNV** [vscode-icons/vscode-icons#2622]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `File`
  - Icon Name: `Ogone`
  - Sample original Icon: ![logo](https://user-images.githubusercontent.com/37340675/93677900-31cc9a00-faad-11ea-9f04-e054dba0126c.png)

  - Extensions: `o3` `ogone`
  - Language ids: `ogone`

- Language Extensions: `o3`
- More info: Ogone is a Deno framework for building front-end applications

**Comment by KingDarBoja** [comment]
I assume the marketplace extension related to this request is https://github.com/SRNV/Otone, right?

**Comment by SRNV** [comment]
@KingDarBoja yeah that's right

**Comment by SRNV** [comment]
@KingDarBoja any update on this one please ?

**Comment by KingDarBoja** [comment]
No worries, I will add the icon this weekend, no need to rush 😉

**Comment by SRNV** [comment]
great thanks, and sorry for the ping!
