### ISSUE TITLE
Update TypeScript Icons for tsconfig.json

### ISSUE THREAD

**Issue by miZyind** [vscode-icons/vscode-icons#2626]
- [x] I'm sure this issue is not a _duplicate_.

Since we've got the cool changes from https://github.com/vscode-icons/vscode-icons/issues/2581
It would be better if we have the same changes for tsconfig.json while enabling TS Official Icons:

<img width="110" alt="Screen Shot 2020-09-22 at 16 49 09" src="https://user-images.githubusercontent.com/21041375/93867649-8b260a80-fcf3-11ea-932c-bea9a3836180.png">

**Comment by KingDarBoja** [comment]
I don't get the suggestion, can you explain it with some example? Thank you :)

**Comment by miZyind** [comment]
Sorry for my unclear explanation.
This is the screenshot of default icons for TypeScript:
![default](https://user-images.githubusercontent.com/21041375/94328935-e6e8e000-ffe0-11ea-98d5-b602e7b38041.jpg)

After we toggled the "Official TS Present" settings. The `tsconfig.json` still looks like the default one:
![official](https://user-images.githubusercontent.com/21041375/94328980-5d85dd80-ffe1-11ea-8250-16b68bce0957.jpg)

This is what I expect:
![tsconfig](https://user-images.githubusercontent.com/21041375/94329187-0aad2580-ffe3-11ea-9018-d2161f6a5532.jpg)

Thanks :D

**Comment by KingDarBoja** [comment]
Fair enough, consider it done this weekend 🚀

**Comment by JimiC** [comment]
I'm against any change to the icon. Our icon for `tsconfig` has not changed even during the various changes to the official icon.
There is no `official` icon for `tsconfig` so we are not "obligated" to follow the official icon changes.

**Comment by robertohuertasm** [comment]
I agree we have no "obligation" considering there's no official icon but the thing is that @KingDarBoja has already done the work and it makes sense to change it according to the TS icon. I mean, it's not a crazy idea. In the end, that's what we did when first designed this icon so let's say I'm not against proceeding with the related PR.

**Comment by JimiC** [comment]
@robertohuertasm There will be consequences if we change the icon. The proper way to do it is by providing "switching" ability. This change will fire back on us.

**Comment by robertohuertasm** [comment]
You think people using the official icon will complain? My guess is that they will be happy with it given that they like the official icon already. I would certainly refrain from introducing a new switch just for this icon. The decision is whether to go with this change or not... I would accept the risk tbh, but that's me. In my opinion, it makes total sense to have the whole set of icons using the same look and feel. It's just a matter of coherence.

**Comment by JimiC** [comment]
OK. It's your decision. Any support that will arise is on you guys.

**Comment by miZyind** [comment]
I agree with @JimiC. Actually, the purpose of my suggestion is that I found that there is a switching feature. But the tsconfig icon doesn't be changed correspondingly after switched. If people wanna use the default one then this change shouldn't impact them. Only the user who switches to the official preset will see the changes and they would understand.

**Comment by robertohuertasm** [comment]
@miZyind I'm confused by your message. @JimiC proposed to create yet another switch. What I'm saying is that if you change to the official TS icon, you should get the official TS icon also for the tsconfig file. No need for another switch for this. As you said: 

> Only the user who switches to the official preset will see the changes and they would understand.

**Comment by orta** [comment]
:wave: - I don't use this icons set, but I designed the TS logo and but I've explored a TSConfig file-type icon before and while I'm not committing to this right now as the "official tsconfig" icon - I think it's the direction I'd take it:

![Screen Shot 2020-09-27 at 10 06 02 AM](https://user-images.githubusercontent.com/49038/94366923-2f6bd080-00a9-11eb-988e-672da7e76d12.png)

That said, if this cog is positioned and colored there for consistency inside the iconset, then I can dig keeping it grey and in the same position

**Comment by JimiC** [comment]
I on the other hand would like to keep the default `tsconfig` icon even when I switch to the `official TS` icon. How are you going to satisfy my need?

**Comment by robertohuertasm** [comment]
Thanks @orta for your contribution and your insight. I really like that logo.

@JimiC to solve your case, I would point you to the custom icon section. You can always do what you want. Of course, you could argue that this is also valid for the current case, and you would be right, but I think iconset coherence comes first. That's why I advocate for this change.

**Comment by JimiC** [comment]
I rest my case

**Comment by robertohuertasm** [comment]
@JimiC, I'm not saying that this change is going to satisfy everyone, it certainly won't. But it's also true that it doesn't satisfy some others right now. So no matter what we do, there will always be someone who is not going to like it. Why change this icon then? Because it makes sense to keep the consistency in the iconset. That's just it. If someone wants to change this consistency, then the price she/he has to pay is using the customization. I think it's a fair solution. @KingDarBoja thoughts?

@miZyind I take your `like` to my comment as that you agree with my point. Is that right? Do you have any other opinion about this?

**Comment by miZyind** [comment]
@robertohuertasm Yes, you are right. I feel much the same way with you. I just misunderstood what Jimi said.

**Comment by KingDarBoja** [comment]
I understood what JimiC wanted with the independant toogle for both `TS` and `TSConfig` official icons but I was thinking like roberto already stated, as the switch should be as it is suggested on this PR as this is coherent with what user **should expect** when enabling these icons. So if anyone wants separate official icons, should go with the customisation feature.

Now that orta has gave a possible official tsconfig icon, I would either wait a bit for a final design and just update this PR.
