### ISSUE TITLE
Update Improve (FLUTTER/DART) Icons and make them a bit larger to see and use product sans font

### ISSUE THREAD

**Issue by fisforfaheem** [vscode-icons/vscode-icons#2627]
It would help us lot!

**Comment by robertohuertasm** [comment]
Can you elaborate a little bit? I'm not really sure to understand what you mean. I work with Flutter apps every day and I think the icon size is not precisely small.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/696981/94025016-58921580-fdb8-11ea-84e9-abec140db20c.png">

**Comment by fisforfaheem** [comment]
i mean (on a big screen the icons do look small!_ for me also they should
be easier to look(modern feel)

**Comment by JimiC** [comment]
The icon size is set by the `vscode` editor. The only way you can make them larger is by zooming in (Ctrl+=).

**Comment by fisforfaheem** [comment]
hope it works

**Comment by KingDarBoja** [comment]
Closing as this is not controlled by ths extension but vscode editor settings.
