### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sameh125** [vscode-icons/vscode-icons#2631]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.0.0`
- OS Version: `Windows_NT ia32 6.1.7601`
- VSCode version: `1.49.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\sameh\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KingDarBoja** [comment]
Please read: https://github.com/vscode-icons/vscode-icons/wiki/Pad

Cheers!
