### ISSUE TITLE
[Icon Request] Support for py.typed

### ISSUE THREAD

**Issue by tristan957** [vscode-icons/vscode-icons#2634]
https://www.python.org/dev/peps/pep-0561/

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `py.typed`
  - Sample original Icon: Could maybe use an off-color python icon like https://camo.githubusercontent.com/68c7827eeb796f3a664f48f5657c04e65e04ae6e/687474703a2f2f6d7970792d6c616e672e6f72672f7374617469632f6d7970795f6c696768742e737667
  - Extensions: ``
  - Filenames: `py.typed`
  - Language ids: ``

- Language Extensions:
- More info:

The py.typed file is used to notify language servers that the package provides its own stub files, so it could skip type analysis of the raw python. The py.typed file was introduced in the following PEP. https://www.python.org/dev/peps/pep-0561/

**Comment by KingDarBoja** [comment]
Umm would be great to use the mypy one since it is a type checker project as well.
