### ISSUE TITLE
Doesn't respond when performance drop

### ISSUE THREAD

**Issue by CodeMonkeyCoder75** [vscode-icons/vscode-icons#2637]
- Issue Type: `Bug`
- Extension Name: `vscode-icons`
- Extension Version: `11.0.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

**Comment by KingDarBoja** [comment]
Please take a look at https://github.com/vscode-icons/vscode-icons/wiki/Pad
