### ISSUE TITLE
vue icon is not working

### ISSUE THREAD

**Issue by kasanitej** [vscode-icons/vscode-icons#2639]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions: javascipt vue
- More info: I can see "vue" in the list of supported icons (https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles). But it is not working for me. "vscode-icons" is already set as my icon theme. 
![image](https://user-images.githubusercontent.com/40614174/97068629-f743a900-15e6-11eb-8a8e-f5af840573cc.png)

**Comment by robertohuertasm** [comment]
can you provide the link to the vue extension you're using?

**Comment by kasanitej** [comment]
I am not using any vue extensions.. Do I have to use one to make it work?

**Comment by robertohuertasm** [comment]
Yes, it's tied to the language ID provided by Vue extensions not file extensions. Try to install one and let us know if it works.

**Comment by kasanitej** [comment]
Installed a vue extension, it is working. Thanks .
