### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Gintoki-C** [vscode-icons/vscode-icons#2640]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.0.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.50.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\user\AppData\Local\Temp\vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by KingDarBoja** [comment]
Please take a look at  https://github.com/vscode-icons/vscode-icons/wiki/Pad
