### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DerrickGodia** [vscode-icons/vscode-icons#2646]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.0.0`
- OS Version: `Darwin x64 20.1.0`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/gb/nkzjcsh5729bhf62_d3x_s280000gn/T/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertohuertasm** [comment]
Hi @DerrickGodia, it's pretty clear that you didn't bother to look for similar issues in the repo. There are plenty and a pinned one! 😜 

Please read: https://github.com/vscode-icons/vscode-icons/wiki/Pad
