### ISSUE TITLE
Display distortion with .go file icons

### ISSUE THREAD

**Issue by dantswain** [vscode-icons/vscode-icons#2656]
See the screenshot below.  To reproduce this I just need a single .go file in the explorer pane.  It doesn't seem to happen with any other file types (haven't tested this exhaustively but did try a few), and it goes away if I switch to any other file icon theme.  It comes back if I restart vs code.

VS Code version 1.51.1
macOS 10.15.7
vscode-icons v11.0.0

![image](https://user-images.githubusercontent.com/463747/100751400-44b8f000-33b5-11eb-8ed2-5faec26e4d24.png)

**Comment by KingDarBoja** [comment]
Harder to reproduce, could be a issue with MacOS only as tried on my Windows machine and no issues with a single Golang file.

**Comment by dantswain** [comment]
Yeah I understand. It almost certainly is something specific to macOS. The fact that it only happens with this icon set suggests to me that it at least has something to do with the interplay of certain assets and/or electron and/or macOS. Whatever other information I can provide to help, let me know.

In the meantime, and in case anyone else is encountering similar problems, I can “work around” the problem by using another icon set (material works for me).

**Comment by Belibaste** [comment]
I have kind of the same. The distorsion appear when the panel show a .jbuilder file (rails gem to generate JSON object)

**Comment by dantswain** [comment]
I think that in my case it has to do with GPU acceleration.  This issue was just the first example of it happening for me - it's since happened in several different applications.  In every case, I'm able to get it to go away by turning off hardware acceleration.  Unfortunately I'm sort of stuck with this version of macOS due to corporate upgrade policies, so I can't try to upgrade and re-enable acceleration yet.

I'm going to close this issue for now.  A workaround for me was to set this in `~/.vscode/argv.json`:

```
{
   "disable-hardware-acceleration": true
}
```
