### ISSUE TITLE
Cannot change default icons

### ISSUE THREAD

**Issue by Bas950** [vscode-icons/vscode-icons#2660]
So I was just testing some things out but I cant seem to change the icons for fileDefault, folderDefault, and folderDefault.root_folder.

 Just to test I added this:
```
        "vsicons.associations.fileDefault.file": {
		"icon": "someRandomIcon",
		"format": "svg"
	},
	"vsicons.associations.files": [
		{
			"icon": "someRandomIcon",
			"format": "svg",
			"extensions": [".env"]
		}
	]
```

And for the .env it shows correctly:
![image](https://user-images.githubusercontent.com/34792838/101395421-35143c80-38ca-11eb-9b0d-f12a05fb59b4.png)

But the files are just empty like it shows nothing:
![image](https://user-images.githubusercontent.com/34792838/101395461-42c9c200-38ca-11eb-94af-0bab38a59772.png)

same issue for the default folder & root folder, it just shows no icon, but it does have empty space in between of where the icon should be:
![image](https://user-images.githubusercontent.com/34792838/101395515-5b39dc80-38ca-11eb-99aa-c84c10431dda.png)

**Comment by robertohuertasm** [comment]
Hi @Bas950, this was undocumented. I just added the details to the [Custom Icons section in our wiki](https://github.com/vscode-icons/vscode-icons/wiki/Custom).

Basically, for this to work you need to have a file named with the following pattern `default_someRandomIcon.svg`. In your example, if you use  `js` or `ts` it won't work as it will be looking for `default_js.svg` in our icons. Unfortunately, normal icons follow another pattern `file_type_someRandomIcon.svg`.

This means that the only way for this to work is to make use of [Custom Icons](https://github.com/vscode-icons/vscode-icons/wiki/Custom). Just add the icon you want to set to the specific folder (depending on your OS/installation type), name it accordingly and you're done. If it doesn't show, remember to `Apply Icons Customization` in the vscode pane.
