### ISSUE TITLE
[Icon Request] Support for .dhall

### ISSUE THREAD

**Issue by azat-io** [vscode-icons/vscode-icons#2664]
For Dhall configuration files: https://dhall-lang.org/

![image](https://user-images.githubusercontent.com/5698350/102017796-11de0700-3d7a-11eb-95e6-5d57f77463cd.png)

**Comment by KingDarBoja** [comment]
It is recommended to share a link to any existing vscode extension, in this case: https://github.com/dhall-lang/vscode-language-dhall
