### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Tho391** [vscode-icons/vscode-icons#2672]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.0.0`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/47/g0v6vg2j42v3nyd5mlddfr5r0000gq/T/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertohuertasm** [comment]
Hi @Tho391, please be sure next time you open an issue check if there's another like yours. We have pinned this one for exactly the case that you're reporting: see #2392
