### ISSUE TITLE
[Icon Request] Support for GNU Linker (ld) file support

### ISSUE THREAD

**Issue by qodroi** [vscode-icons/vscode-icons#2676]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `gnu_linker`
  - Sample original Icon: [Icon Example](https://cdn1.iconfinder.com/data/icons/management-business-line/25/pazel-512.png)
  - Extensions: **.ld** (Capital - **.LD**)

- More info: [GNU Linker](https://en.wikipedia.org/wiki/Linker_(computing)#GNU_linker). I chose that icon because I thought that three pieces of a puzzle that need to be put together (like linker does, takes object files and connect them together into a final executable file) is similar to the linker process. The Icon can be converted to _svg_ format.

- An LD file is a script written in the GNU "linker command language." It contains one or more commands that are used to configure how input files storing static object code are to be compiled into a single executable program or library for the GNU operating system.

[Makefile uses the GNU logo](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_makefile.svg) so maybe also use the GNU logo for the linker or create different for each one of them.

**Comment by r0ei** [comment]
My idea for an icon is three pieces of a puzzle that need to be put together (like linker does, takes object files and connect them together into a final executable file)

[Here is an example](https://cdn1.iconfinder.com/data/icons/management-business-line/25/pazel-512.png)

**Comment by TheRealJoe24** [comment]
I agree, as someone who uses this file type often, this would be quite useful.

**Comment by sasial-dev** [comment]
What would you rather?
As I could either impliment a new icon or the GNU logo just like makefiles.

**Comment by r0ei** [comment]
> What would you rather?
> As I could either impliment a new icon or the GNU logo just like makefiles.

Honestly, as long as there will be an icon, I don't care about of what it'll be.  (;

**Comment by sasial-dev** [comment]
Oops, forgot about this one! 😳 
I'll create a PR with the GNU logo for this.

**Comment by qodroi** [comment]
I close it as completed, even though the PR has not been merged yet.

**Comment by robertohuertasm** [comment]
Why are you closing this? There’s a PR in the pipeline already. Let’s wait for it to be merged and close it then.
