### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by bestbrain10** [vscode-icons/vscode-icons#2686]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.1.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/yf/qhn4vhrd6ql3jhkkrvrk8ctw0000gn/T/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertohuertasm** [comment]
Please see pinned issue: https://github.com/vscode-icons/vscode-icons/issues/2392
