### ISSUE TITLE
Java icons

### ISSUE THREAD

**Issue by espinoleandroo** [vscode-icons/vscode-icons#2690]
Hi!!

Your icons pack is my favorite and I always use it in my projects

How can I get a FOLDER_JAVA and FOLDER_C#??
Can you help me to get it? or how can i desing it?

**Comment by robertohuertasm** [comment]
@espinoleandroo thanks for your kind comments! See [here the instructions](https://github.com/vscode-icons/vscode-icons/wiki/Custom) to provide your own custom icons.

**Comment by espinoleandroo** [comment]
Thanks!! I'll try it, again great job @robertohuertasm 👍🏽
