### ISSUE TITLE
[Icon Request] Support for metals

### ISSUE THREAD

**Issue by ultram4rine** [vscode-icons/vscode-icons#2691]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `metals`
  - Sample original Icon: ![logo](https://scalameta.org/metals/img/scalameta-logo.png)
  - Filenames: `.metals` (folder)

- More info: https://scalameta.org/metals/

**Comment by KingDarBoja** [comment]
Looks like this is a folder request, please take a look at #650 to submit your request, thank you.

By the way, always share the specific section where the folder/file name is mentioned to make things easier and decide if this is a valid request. 

https://scalameta.org/metals/docs/editors/vscode.html#files-and-directories-to-include-in-your-gitignore
