### ISSUE TITLE
[Icon Request] Support for Vite

### ISSUE THREAD

**Issue by tmdh** [vscode-icons/vscode-icons#2707]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `vite`
  - Sample original Icon: ![logo](https://github.com/vitejs/vite/blob/main/docs/public/logo.svg?raw=true)
  - Filenames: `vite.config.js, vite.config.ts`

**Comment by KingDarBoja** [comment]
Thank you for your submissiong, it is always recommended to link some docs that explain the possible filenames and any vscode syntax extension that provides a language id if that's the case.

As example:

- [vscode-vite](https://github.com/antfu/vscode-vite) (_does not have a language id but this is not required for filenames_)
- [vite config](https://vitejs.dev/config/)

**Comment by tmdh** [comment]
As the Vite config documentation says,

> [When running vite from the command line, Vite will automatically try to resolve a config file named **vite.config.js** inside project root.](https://vitejs.dev/config/#:~:text=When%20running%20vite%20from%20the%20command%20line,%20Vite%20will%20automatically%20try%20to%20resolve%20a%20config%20file%20named%20vite.config.js%20inside%20project%20root.)

> [Vite also directly supports TS config files. You can use **vite.config.ts** with the defineConfig helper as well.](https://vitejs.dev/config/#:~:text=Vite%20also%20directly%20supports%20TS%20config%20files.%20You%20can%20use%20vite.config.ts%20with%20the%20defineConfig%20helper%20as%20well.)
