### ISSUE TITLE
Add existing icon to an unknown extension file 

### ISSUE THREAD

**Issue by rbestardpino** [vscode-icons/vscode-icons#2709]
- [x] I'm sure this issue is not a _duplicate_.

Hello.

I am trying to make a file-icon associaton. I tried a lot of different configurations that I found online but no one solves my issue.

What I am trying to accomplish is simple, I want that every log file, besides ending in ".n" (n is a number), to have the default log icon. As shows in:

![image](https://user-images.githubusercontent.com/49445152/109426534-ee1b7c00-79cc-11eb-9dec-89358b582f57.png)

I have already 
![image](https://user-images.githubusercontent.com/49445152/109426692-ac3f0580-79cd-11eb-82f5-1b2aac5ce501.png) in my settings.json.

Thank you!

**Comment by robertohuertasm** [comment]
@rbestardpino, once #2790 is merged and deployed you will be able to do it with file associations. We were missing the language id association that would allow you to do it like that.
