### ISSUE TITLE
can i turn off icon at mk file? 

### ISSUE THREAD

**Issue by jhnyang** [vscode-icons/vscode-icons#2711]
- [x ] I'm sure this issue is not a _duplicate_.

Hello,
i love most of icons of this extension,
but with 'mk' file icon, i prefer default img (MK icon) to changed one (goat icon). 

Is there any customizing function?
or, some functions so that i can keep default icon , without applying extension on some specific file extensions.

sorry for poor english 
thank you.

**Comment by robertohuertasm** [comment]
Hi @jhnyang, [check this out](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning)!
