### ISSUE TITLE
[Icon Request] Support For Bicep

### ISSUE THREAD

**Issue by JustinGrote** [vscode-icons/vscode-icons#2712]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `SVG`
  - Icon Name: `bicep`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/jesseweed/seti-ui/b6e2289830ea77271c76fb8e0d02319f16a1c0d7/icons/bicep.svg)
  - Extensions: `.bicep, .arm.bicep`
  - Filenames: `N/A`
  - Language ids: `bicep`

- Language Extensions: `ms-azuretools.vscode-bicep`
- More info: https://github.com/azure/bicep

**Comment by anthony-c-martin** [comment]
@JustinGrote FYI, this is the icon we're planning to use for VSCode file icons: https://github.com/jesseweed/seti-ui/blob/b6e2289830ea77271c76fb8e0d02319f16a1c0d7/icons/bicep.svg

**Comment by JustinGrote** [comment]
> @JustinGrote FYI, this is the icon we're planning to use for VSCode file icons: https://github.com/jesseweed/seti-ui/blob/b6e2289830ea77271c76fb8e0d02319f16a1c0d7/icons/bicep.svg

Updated!

**Comment by KingDarBoja** [comment]
This is a languageId kind of file icon, as seen at [vscode-bicep](https://github.com/Azure/bicep/blob/main/src/vscode-bicep/package.json).
