### ISSUE TITLE
[Icon Request] Yarn Berry configuration file

### ISSUE THREAD

**Issue by mumincelal** [vscode-icons/vscode-icons#2714]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `file_type_yarn`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_yarn.svg)
  - Filenames: `.yarnrc.yml`

- More info: Yarn Berry (v2) has a configuration folder that name is `.yarnrc.yml`. This file is identical `.yarnrc` file in Yarn Classic and icons should be same

**Comment by KingDarBoja** [comment]
Thank for submitting this issue, it is always a good idea to provide the official docs to support any request for icons.

In this case, the correct docs to look at: https://yarnpkg.com/configuration/yarnrc
