### ISSUE TITLE
Support license suffixes

### ISSUE THREAD

**Issue by mainrs** [vscode-icons/vscode-icons#2730]
- [x] I'm sure this issue is not a _duplicate_.

A lot of Rust projects are dual licensed under MIT and Apache-2.0. One of the most popular ones is probably [serde](https://github.com/serde-rs/serde). Projects like these often have two license files named `license-mit` and `license-apache`. Would it be possible to add support for these kind of files as well? Maybe matching `license-`,`LICENSE-` as well alongside the already existing variations.

Thanks!

**Comment by robertohuertasm** [comment]
Hi @SirWindfield, the problem for us is that we cannot support that kind of matchings due to a limitation in vscode api. We can add, though, some of the most common license file names as alias. That should do the trick. Happy to receive a PR with that change 😜 .
