### ISSUE TITLE
[Icon Request] Support for CodeQL

### ISSUE THREAD

**Issue by lrecknagel** [vscode-icons/vscode-icons#2734]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId `
  - Icon Name: `codeql`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/github/vscode-codeql/main/extensions/ql-vscode/media/logo.svg)
  - Extensions: `ql, qll`
  - Language ids: `ql`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql

**Comment by KingDarBoja** [comment]
The provided language extension does have a `languageId` definition: [ql-vscode](https://github.com/github/vscode-codeql/blob/main/extensions/ql-vscode/package.json#L65).

Thanks for submitting the ticket and the PR 🚀

**Comment by lrecknagel** [comment]
Should I adapt the languageId in the PR?
I am not sure right now if this action is needed.

Thanks for taking care 🙂

**Comment by robertohuertasm** [comment]
Yes @lrecknagel! You should change it to `ql`.

**Comment by lrecknagel** [comment]
Thanks to both of you to guiding through this requested change and the hint about the existing languageId.
