### ISSUE TITLE
[Icon Request] Support for gcloud

### ISSUE THREAD

**Issue by remcohaszing** [vscode-icons/vscode-icons#2737]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `gcloud`
  - Sample original Icon: ![logo](https://avatars.githubusercontent.com/u/2810941)
  - Filenames: `.gcloudignore` `app.yaml` `cron.yaml` `dispatch.yaml` `dos.yaml` `index.yaml` `queue.yaml`
https://www.pinpng.com/pngs/m/61-610992_gcp-logo-cloud-google-cloud-logo-svg-hd.png
- More info:

More info on configuration files can be found [here](https://cloud.google.com/appengine/docs/standard/python/configuration-files).

More info on `.gcloudignore` can be found [here](https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore).

The following logo is still used in various places, but it appears it’s being phased out. I may be wrong about this.
![old logo](https://upload.wikimedia.org/wikipedia/commons/c/c2/Google-cloud-platform-v2.svg)

**Comment by sasial-dev** [comment]
I'm not too sure about setting an icon with google cloud for `app.yaml`, `cron.yaml`, `dispatch.yaml`, `index.yaml`, `queue.yaml` as they could be used without google cloud.

@robertohuertasm - what are your thoughts?

**Comment by robertohuertasm** [comment]
@sasial-dev exactly the same as yours. Those files are too generic to associate them with this icon. I'd suggest @remcohaszing to use custom icons for those ones.
