### ISSUE TITLE
[Icon Request] Support for dapr (dapr.io)

### ISSUE THREAD

**Issue by mmisztal1980** [vscode-icons/vscode-icons#2748]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `dapr`
  - Icon Name: `dapr`
  - Sample original Icon: ![logo](https://cdn.discordapp.com/emojis/778683867804467253.png?v=1)
  - Extensions: `N/A`
  - Filenames: `N/A`
  - Language ids: `N.A`

This icon should be applied to folders only, there are no `*.dapr` files, as dapr relies on YAML custom resource definitions.
Please apply the icon to the following folders:
- `dapr`
- `.dapr`
It'd be great if the folder would look like the `.vs` / `.vscode` folders :)

**Comment by KingDarBoja** [comment]
Hello!

It is always recommended to share atleast where the icon came from: https://github.com/dapr/dapr
