### ISSUE TITLE
Latest version in the open vsx registry

### ISSUE THREAD

**Issue by mikenikles** [vscode-icons/vscode-icons#2749]
- [x] I'm sure this issue is not a _duplicate_.

Hi, thank you for your work on this project 🙏 !

I notice the Open VSX Registry contains [a slightly older version](https://open-vsx.org/extension/vscode-icons-team/vscode-icons) of this extension.

On the above link, I do see a warning "This version of the “vscode-icons” extension was published by open-vsx" which makes me wonder if this is the right place to report this.

Does anyone know who currently takes care of publishing this extension to the open vsx registry? There are instructions at https://github.com/open-vsx/publish-extensions and I'd gladly provide support.

Thanks

**Comment by robertohuertasm** [comment]
Hi @mikenikles, we're not publishing to open vsx registry. I guess their team is responsible now of updating the extension from time to time. To be honest, I didn't even now of such registry. 

For the moment, we're having issues with Travis, as they have disabled all our CI pipelines (hopefully they will come back by the end of April) so we wouldn't be able to support any automatic deployment for the time being.

**Comment by mikenikles** [comment]
That's alright, I opened a PR manually for now at https://github.com/open-vsx/publish-extensions/pull/326. Once merged, it'll get deployed automatically and 11.4.0 will be available in the Open VSX registry the next day.

**Comment by remcohaszing** [comment]
This is resolved upstream. The latest version of vscode-icons is available on https://open-vsx.org/extension/vscode-icons-team/vscode-icons

**Comment by robertohuertasm** [comment]
For the record, we introduced this almost 2 years ago: https://github.com/vscode-icons/vscode-icons/compare/v12.1.0...v12.2.0
