### ISSUE TITLE
Wrong indent with `"vsicons.presets.hideFolders": true`

### ISSUE THREAD

**Issue by crabvk** [vscode-icons/vscode-icons#2753]
- [x] I'm sure this issue is not a _duplicate_.

- More info: vscode-icons v11.4.0

With `"vsicons.presets.hideFolders": false` everything looks cool:
![20210410_151922-nD2zWrI7](https://user-images.githubusercontent.com/3273827/114274976-4321c780-9a3a-11eb-90a2-ff7d71268bac.png)
but when this option set to `false`:
![20210410_152134-GVLUeGHa](https://user-images.githubusercontent.com/3273827/114275025-63ea1d00-9a3a-11eb-8935-0aac3deae0ed.png)
the indent of files kept the same which looks like they're inside the folder above them.

**Comment by robertohuertasm** [comment]
@crabvk unfortunately, this is not something we can fix. It is like this by default. Please, consider opening the issue in the `vscode` repo.

**Comment by AllySummers** [comment]
Hi, I was looking at why this seems to be causing a bigger indent on folderless themes and according to this comment https://github.com/microsoft/vscode/issues/141428#issuecomment-1025559505 a folderless theme can set the `align-icons-and-twisties` class. 

Is it possible to apply this when `vsicons.presets.hideFolders` is true?

**Comment by robertohuertasm** [comment]
Hi @michaelschufi, I’ll take a look when I have a moment. Thanks for bringing this up.

**Comment by robertohuertasm** [comment]
for reference: https://github.com/microsoft/vscode/issues/141428

**Comment by robertohuertasm** [comment]
@michaelschufi, I looked at the current situation, but we don't have any api to apply that custom `CSS` that @AllySummers was referring to. This is all on the VS Code side.

**Comment by michaelschufi** [comment]
Thanks for checking @robertohuertasm. Would it be feasible to e.g. add a tranparent icon for all folders instead? Or some workaround like this?

**Comment by robertohuertasm** [comment]
@michaelschufi, that could work, indeed. But it would add a weird space. You can try it yourself by changing the default folder icon. Add this to your settings: 
```json
 "vsicons.associations.folderDefault.folder": {
    "icon": "myfile",
    "format": "svg",
    "disabled": false
  }
```

![image](https://github.com/vscode-icons/vscode-icons/assets/696981/061dccdf-fd0b-4447-993e-080b71de64b0)
