### ISSUE TITLE
[Icon Request] Support for OpenSCAD

### ISSUE THREAD

**Issue by HKalbasi** [vscode-icons/vscode-icons#2755]
- [ x ] I'm sure this issue is not a _duplicate_.
- [ x ] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `open scad`
  - Sample original Icon: ![logo](https://openscad.org/assets/img/logo.png)
  - Extensions: `.scad`
  - Language ids: `OpenSCAD`

- More info: https://openscad.org/

**Comment by KingDarBoja** [comment]
Since this icon is a bit too complex, I guess a minimalistic version would work: https://www2.openscad.org/openscad-release-2019-05/
