### ISSUE TITLE
Associate Docker to compose.yaml/yml and docker-compose.yaml

### ISSUE THREAD

**Issue by SebDanielsson** [vscode-icons/vscode-icons#2761]
- [x] I'm sure this issue is not a _duplicate_.

According to the [Compose Spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md) Docker compose files should preferably be named just compose.yaml. I found that I don't get a Docker icon when using docker-compose.yaml instead of .yml or when naming the compose file compose.yaml or compose.yml.

**Comment by KingDarBoja** [comment]
Based on that link, these should be the possible filenames:

> The Compose file is a YAML file defining version (DEPRECATED), services (REQUIRED), networks, volumes, configs and secrets. The default path for a Compose file is `compose.yaml` (preferred) or `compose.yml` in working directory. Compose implementations SHOULD also support `docker-compose.yaml` and `docker-compose.yml` for backward compatibility. If both files exist, Compose implementations MUST prefer canonical `compose.yaml` one.

Seems like the [vscode-docker extension](https://github.com/microsoft/vscode-docker/blob/main/package.json#L1388) does not include such filenames 🤔
