### ISSUE TITLE
[Bug] Icon detection affects other projects (workspace)

### ISSUE THREAD

**Issue by dreamerblue** [vscode-icons/vscode-icons#2775]
- [x] I'm sure this issue is not a _duplicate_.

### How to Reproduce

1. Create two projects. The first one is an empty project. It only contains ts config and files like `src/middlewares/demo.middleware.ts`. And the second one is a Nest.js project.
2. Only open the first project, the icon on `.middleware.ts` is a TS icon.
3. Then open the second project, due to the Nest.js detection, the `.middleware.ts` in first project changed to Nest.js icon.

- More info: version 11.4.0

**Comment by dreamerblue** [comment]
@KingDarBoja maybe related to #1897? The detection should be workspace scope.

**Comment by robertohuertasm** [comment]
Hi @dreamerblue, unfortunately, this is a limitation with vscode. We cannot configure the extension per project. So if you're opening two different projects, the latest will always "win" and impose its characteristics. It's not possible to make the extension work different for different vscode windows so we'll have to live with this for the time being.

You can always disable the auto detection feature and if you're constantly switching between nestjs and normal projects, you can do it manually or don't do it at all.
