### ISSUE TITLE
.html.erb file not recognized with rails extension

### ISSUE THREAD

**Issue by tnvr000** [vscode-icons/vscode-icons#2779]
![Screenshot from 2021-05-28 11-50-19](https://user-images.githubusercontent.com/43482649/119939073-e9a23780-bfaa-11eb-81b9-0636928e3afc.png)

- [ ] I'm sure this issue is not a _duplicate_.
.html.erb files are not recognized when Rails (https://marketplace.visualstudio.com/items?itemName=bung87.rails) extension is enabled.

OS: Ubuntu 18.04
vs code: code_1.56.2-1620838498_amd64.deb

**Comment by KingDarBoja** [comment]
Looks like the issue is caused by the extension not including / declaring the other file extensions compared to this one: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

**Comment by robertohuertasm** [comment]
As @KingDarBoja mentioned, [the second extension language supports erb language id](https://github.com/rubyide/vscode-ruby/blob/main/packages/vscode-ruby/package.json#L63). [This one supports html.erb language id](https://github.com/bung87/vscode-rails/blob/dev/package.json#L101). Maybe we can add that id so we can support this.

**Comment by robertohuertasm** [comment]
It seems it's not as easy as I thought. There's something going on with the `erb` extension.  This needs some more investigation.

**Comment by robertohuertasm** [comment]
@tnvr000 the issue is due to the kind of language id this extension is declaring. It used a combined extension (`html.erb`) which is not supported by the vscode api. The only solution is to manually set the icon association.

Go to your settings and add these lines:

```
"files.associations": {
    "*.html.erb": "erb"
  },
```

That should do the trick!

**Comment by robertohuertasm** [comment]
I might not have test it ok. I'll provide a fix for this. I'll add a new language id for erb.

**Comment by tnvr000** [comment]
Version 11.6.0 update fixed the issue. Thanks
