### ISSUE TITLE
[Icon Request] Support for ' .rpy'

### ISSUE THREAD

**Issue by Neyunse** [vscode-icons/vscode-icons#2786]
- [x]  I'm sure this issue is not a _duplicate_.

- [x] I'm submitting an icon request:
  - Type: `file_type`
  - Icon Name: ``
  - Sample original Icon: ![logo](https://upload.wikimedia.org/wikipedia/commons/7/7e/Ren%E2%80%99Py_Logo_6-13-6_200x307px.png)
  - Extensions: `.rpy`
  - Filenames: ``
  - Language ids: ``

- Language Extensions: Ren'Py Files
- More info:
[Ren'Py ](https://en.wikipedia.org/wiki/Ren%27Py) is a Python-based visual novel engine, using .rpy files for code and dialogs

**Comment by KingDarBoja** [comment]
Associated language extension: https://marketplace.visualstudio.com/items?itemName=LuqueDaniel.languague-renpy

**Comment by rohith-cmd** [comment]
Hello I would like to take up the issue

**Comment by robertohuertasm** [comment]
All yours then! 😁

**Comment by sasial-dev** [comment]
Looks like this issue hasn't had any activity since @rohith-cmd said they would take it up.

**Comment by sasial-dev** [comment]
@Neyunse, are you sure you want
 ![](https://camo.githubusercontent.com/dfd1362396831ba8c0d8b550ac39c4544a45778c36b2a16346749ab56610911c/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f372f37652f52656e25453225383025393950795f4c6f676f5f362d31332d365f3230307833303770782e706e67) 
as the icon?

**Comment by sasial-dev** [comment]
It might be worth simplifying it, it's a bit to detailed for vscode-icons!

**Comment by Neyunse** [comment]
> It might be worth simplifying it, it's a bit to detailed for vscode-icons!

Ren'Py has no other logo, this is the logo that occupies the engine. I don't know how it could be simplified. 🤔

**Comment by robertohuertasm** [comment]
Why did you close it?

**Comment by robertohuertasm** [comment]
I'll keep it open just in case we decide to implement it and someone else finds it useful.

**Comment by isanjit3** [comment]
Hi, I see this issue is still open, may I take up the issue?

**Comment by robertohuertasm** [comment]
Go for it!

**Comment by Hemant-Dua** [comment]
@isanjit3 Still at it...???
