### ISSUE TITLE
Document `light` field within custom icons docs

### ISSUE THREAD

**Issue by colinking** [vscode-icons/vscode-icons#2797]
- [x] I'm sure this issue is not a _duplicate_.

I just ran through the Fine Tuning docs to add a custom icon for a file format of mine. However, I had trouble figuring out how to provide an alternate light icon until I saw [an example PR](https://github.com/vscode-icons/vscode-icons/pull/1589/files#diff-bf78b49ad37b0fa8b286d0bfbd80b80c91f4d1b03112cefa63e98658f1f63542).

What do y'all think of adding an example of this to the [Fine Tuning docs](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning)? Something like:

```js
// Providing an alternate light-mode icon.
// If you want to render a different icon in dark-mode vs. light-mode, set `light` to `true`
// to instruct vscode-icons to check for a file matching `file_type_light_<icon>`.
"vsicons.associations.folders": [
  { "icon": "src", "extensions": ["src"], "format": "svg", "light": true }
]
```

**Comment by robertohuertasm** [comment]
Good idea @colinking!

**Comment by robertohuertasm** [comment]
Done! Thanks for the suggestion ❤️
