### ISSUE TITLE
Prettier icon is not good in dark mode

### ISSUE THREAD

**Issue by shivapoudel** [vscode-icons/vscode-icons#2798]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo](file_type_prettier.svg)
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

Current `.prettierignore` and `.prettierrc.js` supported icon in this extension is not so good in [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) with color scheme "GitHub Dark Dimmed".

![image](https://user-images.githubusercontent.com/3774827/122655215-8bfba800-d170-11eb-8ea9-0c4b0d129420.png)

**Comment by robertohuertasm** [comment]
As far as I can see it's pretty noticeable. I mean, there's plenty of color in that icon. Do you have any suggestion?

**Comment by shivapoudel** [comment]
Yeah that plenty of color is slightly making uneasy, my friend :)

**Comment by robertohuertasm** [comment]
That's an opinion, in any case, as valid as any other 😉. Let's see how many +1 gets this to start considering this.

**Comment by robertohuertasm** [comment]
Let me add that we normally use the official icons unless we see a very good reason not to.
