### ISSUE TITLE
[Icon Request] Support for Noc

### ISSUE THREAD

**Issue by mortim** [vscode-icons/vscode-icons#2799]
- [x] I'm sure this issue is not a duplicate.

- [x] I'm here to ask for adding a support for my own programming language Noc
   - Type: `extension, languageId`
   - Icon Name: `Noc`
   - Sample original Icon:
        ![noc-logo](https://raw.githubusercontent.com/noc-lang/home/8206097f337b7e5f8b46ace90c8691e344057bf7/assets/icon.svg)
   - Extensions: `noc`
   - Language ids: ``noc``
   - Language Extensions: [Noc extension in marketplace](https://marketplace.visualstudio.com/items?itemName=mortim.noc)

- Noc icon
   - Icon: [noc.woff](https://github.com/noc-lang/vscode-noc/blob/master/icon/noc.woff)
   - font-character: ``\E900``
   - font-color: ``#6fa0bb``
   - icon-theme: [noc-icon-theme.json](https://github.com/noc-lang/vscode-noc/blob/master/icon/noc-icon-theme.json)

- More info: [vscode-noc repository](https://github.com/noc-lang/vscode-noc)

**Comment by robertohuertasm** [comment]
@mortim why did you close it?

**Comment by mortim** [comment]
I have heard that a language with no fame is not accepted in this repository. So I closed this issue.

**Comment by robertohuertasm** [comment]
It's not about fame but about a minimal usage. In your case, I'm not sure if this is just a personal project or this is being used by others.

You know anyone can add custom icons with this extension, so for things that are for personal usage we don't use to add icons.

Let me know more about the noc language to see if it could be a good candidate.

**Comment by mortim** [comment]
It's personal project.

**Comment by mortim** [comment]
> It's not about fame but about a minimal usage. In your case, I'm not sure if this is just a personal project or this is being used by others.
> 
> You know anyone can add custom icons with this extension, so for things that are for personal usage we don't use to add icons.
> 
> Let me know more about the noc language to see if it could be a good candidate.

It's not developped enough but, I currently programming actively to add more features.
