### ISSUE TITLE
no scala

### ISSUE THREAD

**Issue by andyliumathematics** [vscode-icons/vscode-icons#2808]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
no .scala icon

**Comment by robertohuertasm** [comment]
@andyliumathematics you just have to install a [extension supporting the scala language](https://marketplace.visualstudio.com/items?itemName=scala-lang.scala). That will do the trick.
