### ISSUE TITLE
[Icon Request] Icon for router.js files 

### ISSUE THREAD

**Issue by EliasSalom** [vscode-icons/vscode-icons#2810]
in the node.js and express and make router.js or any another file in the router directory must have Icon this will help us the people a lot, for another extantion they Icon for the router.js or any js file in the project

**Comment by robertohuertasm** [comment]
Hi @EliasSalom, unfortunately this is not possible to accomplish due to limitations in the vscode api. We're already supporting `route`/`routes` folders. We could possibly consider adding `router` to it.

**Comment by EliasSalom** [comment]
hi @robertohuertasm thanks for your replay, sure no problem but the Icons help the developer a lot.
