### ISSUE TITLE
[Icon Request] Support for 'stryker' 

### ISSUE THREAD

**Issue by nicojs** [vscode-icons/vscode-icons#2817]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `stryker`
  - Sample original Icon: ![logo](https://stryker-mutator.io/images/stryker.svg)
  - Filenames: `stryker.conf.json`, `stryker.conf.js`, `stryker.conf.*.json`, `stryker.conf.*.js`, `stryker-config.json`, `stryker4s.conf`, `stryker-config.yaml`, `stryker-config.yml`

- More info: https://stryker-mutator.io

**Comment by robertohuertasm** [comment]
Closed by #2896
