### ISSUE TITLE
Does not recognise `.devcontainer.json` as devcontainer file

### ISSUE THREAD

**Issue by navneetkarnani** [vscode-icons/vscode-icons#2820]
Issue Type: <b>Bug</b>

Steps to reproduce the issue:

mkdir test-folder
cd test-folder
mkdir .devcontainer
touch devcontainer.json
touch .devcontainer.json

Expected:
`.devcontainer.json` and `.devcontainer` should have icon relevant for a `devcontainer` config file. `devcontainer.json` should not.

Actual behavior:
`devcontainer.json` and `.devcontainer` have icon relevant for a `devcontainer` config file. `.devcontainer.json` does not.

Extension version: 11.6.0
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.84GB free)|
|Process Argv|. --crash-reporter-id 0dec9fd0-c8fd-4152-a33c-72a9d4647e00|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by robertohuertasm** [comment]
This will be fixed with #2829
