### ISSUE TITLE
 [Icon Request] Support for vite.config.js

### ISSUE THREAD

**Issue by igorer88** [vscode-icons/vscode-icons#2825]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `viteconfig`
  - Sample original Icon: ![logo](https://vitejs.dev/logo.svg)
  - Extensions: `.config.js`
  - Filenames: `vite.config.js`
  - Language ids: `js`, `viteconfig`

- Language Extensions: ??
- More info:  Just like the Vue config file with the gear icon on #2205  
 the doc for this is at https://vitejs.dev/config/

**Comment by robertohuertasm** [comment]
Hi @igorer88, we already support that extension. Can you elaborate?

**Comment by igorer88** [comment]
Hi @robertohuertasm sorry for the late answer. It has it indeed, but it lacks the gear on top, as the vue config file.

**Comment by robertohuertasm** [comment]
No problem @igorer88 but I'm not sure I follow you. As far as I know, this is the only extension that vite is exposing. I don't see the need to add anything else to the icon. In the Vue case, one thing is the config file and the other one is the extension for the vue files. Here I don't see the paralellism, although I may be missing something.

**Comment by robertohuertasm** [comment]
Related to #2708.

**Comment by igorer88** [comment]
Ok ok @robertohuertasm I thought it could make more sense to have it like the Vue CLI config. But if there's no need, it's ok.

**Comment by robertohuertasm** [comment]
No problem @igorer88, thanks for your suggestion anyway!
