### ISSUE TITLE
suggestion: VS Code Web support

### ISSUE THREAD

**Issue by ajhalili2006** [vscode-icons/vscode-icons#2826]
- [X] I'm sure this issue is not a _duplicate_.

---

### About this Issue

I want to use this file icon theme on GitHub's web editor (aka VS Code Web) since I don't have access to Codespaces yet, but as I enable Settings Sync and searching the extension on the Marketplace, there's no Install/Disable/Uninstall button/s and a notice that this extension isn't supported in VS Code Web is shown instead.

Also from <https://code.visualstudio.com/docs/remote/codespaces#_why-is-an-extension-not-installable-in-the-browser>:

> There are a small number of extensions that have built-in assumptions or need to run on the desktop. Examples are when an extension accesses files from the VS Code installation on the desktop or when an extension depends on an executable that must run in a desktop environment. When you try to install such an extension in the browser, you will be informed that the extension is not available.

### Workarounds

* Use VS Code locally and access your GitHub Codespaces or remotely edit files [with `github.remotehub` extension](https://marketplace.visualstudio.com/items?itemName=GitHub.remotehub)
* Probably use alternatives like Gitpod and code-server (Google Cloud Shell Editor isn't an option because you can't install extensions)

**Comment by barnuri** [comment]
please add support to github.dev

**Comment by robertohuertasm** [comment]
Working on it.

**Comment by yiliang114** [comment]
In fact, the extension now supports `vscode.dev`.
![image](https://user-images.githubusercontent.com/11473889/222880185-8cf1c2e5-d1df-4b13-8df6-5fdacc1af567.png)
![image](https://user-images.githubusercontent.com/11473889/222880195-224c34d8-b503-4a0c-918c-12af837aab1f.png)

**Comment by robertohuertasm** [comment]
@yiliang114 thanks for bringing me this issue to my attention. You're right. Web support was added some months ago. Closing this.
