### ISSUE TITLE
Create an icon for .env file

### ISSUE THREAD

**Issue by Atul-Kumar-Official** [vscode-icons/vscode-icons#2844]
I suggest you to create an icon for .env file

**Comment by robertohuertasm** [comment]
This icon is already supported. You just have to install a .env extension like [this one](https://marketplace.visualstudio.com/items?itemName=mikestead.dotenv).

**Comment by robertohuertasm** [comment]
Sorry @Atul-Kumar-Official, I thought that it was already merged but it seems that it's not. I will arrive shortly as I'm just preparing a new extension release that will have support for .env files.

**Comment by Atul-Kumar-Official** [comment]
No problem; Glad to hear that :)

**Comment by VmiteOCE** [comment]
Hi just wondering what ever happened to the creation for the .env file icon as i don't believe its been added yet.

**Comment by kumartul** [comment]
@VmiteOCE True

**Comment by robertohuertasm** [comment]
@VmiteOCE @kumartul what do you mean? Have you installed the extension I recommended [here](https://github.com/vscode-icons/vscode-icons/issues/2844#issuecomment-955734761)?

![image](https://user-images.githubusercontent.com/696981/148693869-a4187801-c9f6-4a7d-902c-749b9416d18e.png)

**Comment by kumartul** [comment]
Yes yes it's working :)
