### ISSUE TITLE
Integration icon doesnt work

### ISSUE THREAD

**Issue by hetacz** [vscode-icons/vscode-icons#2846]
It is written, that folder named "integration" has icon same as spec (pipette at 45 degrees). Yet my integration folder in cypress has default icon.

**Comment by robertohuertasm** [comment]
It's working for me... not sure how to reproduce it. Press F1 > Icons: Apply Icons Customizations and let me know if that does the trick.

**Comment by hetacz** [comment]
it's ok now.
