### ISSUE TITLE
Support of docker-compose.*.yml

### ISSUE THREAD

**Issue by FedorLap2006** [vscode-icons/vscode-icons#2847]
- [x] I'm sure this issue is not a _duplicate_.

VSCode icons already has support for plenty of `docker-compose` configuration files, but lacks the support for custom overrides for the configuration, like: `docker-compose.prod.yml`, `docker-compose.debug.yml`, `docker-compose.admin.yml`, etc. I'm suggesting to add a glob icon for `docker-compose.*.yml` files or at least link the `docker-compose` icon with these three files.

**Comment by robertohuertasm** [comment]
Hi @FedorLap2006 but unfortunately vscode doesn't offer support for glob in icon themes. You can use custom configuration from our extension to achieve whatever you want.
