### ISSUE TITLE
[Icon Request] Support for ' .tf' file extension using existing Terraform icon

### ISSUE THREAD

**Issue by mjabrandao** [vscode-icons/vscode-icons#2849]
- [ ] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `file_type`
  - Icon Name: `terraform`
  - Extensions: `.tf`

- More info: associate existing Terraform icon with .tf file extension.

**Comment by robertohuertasm** [comment]
Hi @mjabrandao you have to install a terraform extension and ours will add the icon. You can use [this one](https://marketplace.visualstudio.com/items?itemName=HashiCorp.terraform).
