### ISSUE TITLE
[Icon Request] Support for RSS

### ISSUE THREAD

**Issue by VixieTSQ** [vscode-icons/vscode-icons#2851]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `feed/*.xml`
  - Icon Name: `RSS`
  - Sample original Icon: ![https://www.iconfinder.com/icons/341106/download/svg/4096]()
  - Filenames: `feed/*.xml`

**Comment by robertohuertasm** [comment]
Hi @VixieTSQ, unfortunately, vscode doesn't support globs in its icon API so we cannot offer something like this.
