### ISSUE TITLE
Icons for poetry

### ISSUE THREAD

**Issue by calvo-jp** [vscode-icons/vscode-icons#2861]
Hi! I am using [poetry](https://python-poetry.org/) as a dependency manager for my **python** projects. I noticed that `poetry.lock` file has an icon of `toml` and `pyproject.toml` does not have an icon. It would be nice to see the icon of [poetry](https://python-poetry.org/)  for `poetry.lock` and the icon of `toml` for `pyproject.toml`. Please see the image below

![Screenshot from 2021-11-10 18-13-44](https://user-images.githubusercontent.com/86353187/141094445-042371d2-f29d-480c-b1ce-9cdf48cae474.png)

Also, I hope `README.rst` gets an icon. PS: I really like the extension and thank you in advance :heart:

**Comment by robertohuertasm** [comment]
@calvo-jp not sure why you're not seeing the toml icon for `pyproject.toml`. Do you have `better.toml` extension installed? Most probably you have some extension overriding the toml defaults.

Anyway, I agree that we should be using a poetry icon for the poetry.lock file. We'll have to work on the icon.

**Comment by haydenfree** [comment]
<img width="208" alt="Screen Shot 2022-03-28 at 6 09 06 PM" src="https://user-images.githubusercontent.com/1368490/160495432-834d7066-e5fe-43b6-b4f1-7190d859f0d5.png">

I wanted to add I'm also not seeing the TOML icon. Not sure what other information might help you figure this out. I don't have the better toml extension installed.

**Comment by robertohuertasm** [comment]
@haydenfree for the toml extension to be shown, you have to have installed a toml extension. Do you have any?

**Comment by haydenfree** [comment]
> @haydenfree for the toml extension to be shown, you have to have installed a toml extension. Do you have any?

Here's a list of my installed extensions:

```
code --install-extension akamud.vscode-theme-onedark
code --install-extension coolbear.systemd-unit-file
code --install-extension eamodio.gitlens
code --install-extension James-Yu.latex-workshop
code --install-extension julialang.language-julia
code --install-extension karunamurti.haml
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension octref.vetur
code --install-extension rebornix.ruby
code --install-extension singularitti.vscode-julia-formatter
code --install-extension tomoki1207.pdf
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wingrunr21.vscode-ruby
```

**Comment by haydenfree** [comment]
> You don't have any. Just install a TOML extension and that will do.

I see. I misunderstood. I thought that if I **did** have an extension it could cause issues. Working now that I installed Better TOML.
