### ISSUE TITLE
[Icon Request] Support for .excalidraw

### ISSUE THREAD

**Issue by aymericbouzy** [vscode-icons/vscode-icons#2865]
- [x] [I'm sure this issue is not a _duplicate_](https://github.com/vscode-icons/vscode-icons/issues?q=excalidraw).
- [x] I'm submitting an icon request:
  - Type: `extension `
  - Icon Name: `excalidraw`
  - Sample original Icon: ![logo](https://pbs.twimg.com/profile_images/1220893792540221440/zgoZ6ucg_400x400.png)
  - Extensions: `.excalidraw`
  - Filenames: _not applicable_
  - Language ids: `json`

https://excalidraw.com/ is a virtual whiteboard. Files can be saved in JSON format with .excalidraw extension.

<details>
<summary>Example</summary>

```json
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "xBDPi4QTkpEBQhM6zKX_m",
      "type": "text",
      "x": 651,
      "y": 204.77288818359375,
      "width": 119,
      "height": 25,
      "angle": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "strokeSharpness": "sharp",
      "seed": 257432856,
      "version": 20,
      "versionNonce": 1069543784,
      "isDeleted": false,
      "boundElementIds": null,
      "text": "vscode-icons",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "verticalAlign": "top",
      "baseline": 18
    }
  ],
  "appState": {
    "gridSize": null,
    "viewBackgroundColor": "#ffffff"
  },
  "files": {}
}
```

</details>

**Comment by sasial-dev** [comment]
I had a go at implimenting it, but I'm not too sure about the icon:
![Code-DaH3j4lW](https://user-images.githubusercontent.com/44125644/156163586-f97eec0a-e4df-46bd-b8f3-431df26d259c.png)
I created a light and dark varient as you can see - but the icon doesn't really work vertically.

**Comment by sasial-dev** [comment]
It's at https://github.com/sasial-dev/vscode-icons/tree/excalidraw by the way!

**Comment by aymericbouzy** [comment]
Thanks @sasial-dev for giving it a go! Too bad it doesn't display well 😞 [I asked](https://twitter.com/AymericBouzy/status/1499706851574915073?s=20&t=bc9mSJVuKJn8ZqhLgUB11w) @excalidraw if they had a better logo, but got no answer 😕

**Comment by sasial-dev** [comment]
Yeah 😔 
I left it published, but didn't send a PR for that reason/
