### ISSUE TITLE
[Icon Request] Support for @master/cli

### ISSUE THREAD

**Issue by 0Miles** [vscode-icons/vscode-icons#2880]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `master`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/master-style/package/document/images/32x32.svg)
  - Filenames: `master.json`, `master.js`, `master.mjs`

- More info: Support for configuration file of @master/cli

**Comment by robertohuertasm** [comment]
@0Miles do you have a link where we can see what this is all about?

**Comment by 0Miles** [comment]
> @0Miles do you have a link where we can see what this is all about?

[https://github.com/master-style/package](https://github.com/master-style/package)

[@master/cli](https://github.com/master-style/cli/tree/alpha) can generate a package with master.json based on [@master/package](https://github.com/master-style/package)
And you can generate README.md and other files according to master.json at any time later

This is an example of [master.json](https://github.com/master-style/normal.css/blob/main/master.json)

**Comment by sasial-dev** [comment]
Can you confirm the differences between this & #2880 so I can combine them into a single PR?

**Comment by sasial-dev** [comment]
Can you confirm the differences between this and #2984 so I can combine them into a single PR?

**Comment by 0Miles** [comment]
#2984 is used to customize configurations for @master/styles
@master/package is a repo to get started a new project/package and we configure master.json via master.json
