### ISSUE TITLE
[Icon Request] Support for ShellCheck

### ISSUE THREAD

**Issue by tristan957** [vscode-icons/vscode-icons#2881]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `fliename`
  - Icon Name: `ShellCheck`
  - Sample original Icon: https://www.shellcheck.net/favicon.ico
  - Extensions: `.shellcheckrc`
  - Filenames: `.shellcheckrc`
  - Language ids: `shellcheckrc`

- Language Extensions:
- More info: https://github.com/koalaman/shellcheck

**Comment by remcohaszing** [comment]
Sample original icon: ![](https://raw.githubusercontent.com/koalaman/shellcheck.net/master/favicon.ico)

**Comment by tristan957** [comment]
Wanted to add that the filetype seems to be "shellcheckrc"

**Comment by carlocorradini** [comment]
Any news?

**Comment by sasial-dev** [comment]
We need an SVG icon for shellcheck to be able to impliment it. If anyone could point me in the direction of the icon that would be appricated! I can't seem to find any icons and we might need to resort to making our own (abelt simpler) icon.

**Comment by carlocorradini** [comment]
@sasial-dev 
The only available icon is a `.ico` at <https://www.shellcheck.net/favicon.ico> 😥

**Comment by carlocorradini** [comment]
Happy news!
SVG logo available:
<https://github.com/koalaman/shellcheck/blob/master/doc/shellcheck_logo.svg>

**Comment by trallnag** [comment]
Good that I found this issue. Was about to create a new issue & PR to map ShellCheck to the ordinary "config" icon 😄. Having a custom icon is definitely better
