### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cscbeyond** [vscode-icons/vscode-icons#2883]
- Issue Type: `Performance`
- Extension Name: `vscode-icons`
- Extension Version: `11.8.0`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.63.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/50/793tpccn5qx68xcrb1ndyrlc0000gn/T/vscode-icons-team.vscode-icons-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by robertohuertasm** [comment]
See #2392
