### ISSUE TITLE
[bug] New extension for folder does not support suffix.

### ISSUE THREAD

**Issue by Faurby** [vscode-icons/vscode-icons#2886]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:

Hello, I am trying to add a new extension to "test" but it only seems to work, if I write the whole word instead of the suffix. I have tried to follow it exactly like in the wiki. (have not copied all extensions for test, due to testing it out first).

Example in screenshots.
![billede](https://user-images.githubusercontent.com/37332429/146842725-e82893b1-626b-4419-b5ec-c64561e968a2.png)
![billede](https://user-images.githubusercontent.com/37332429/146842736-40441a4e-c846-46c7-9320-12bfa5f1406e.png)

**Comment by robertohuertasm** [comment]
@Faurby unfortunately this is not supported by the vscode API so there's not much that we can do here. Folders, as you've seen, only work by full name. There's no way to use proper extensions.

**Comment by Faurby** [comment]
Ah okay, thats too bad :( But thanks for the reply!
