### ISSUE TITLE
[Icon Request] Add LISP file extension .lsp and fix icon not showing

### ISSUE THREAD

**Issue by semkeijsper** [vscode-icons/vscode-icons#2893]
- [x] I'm sure this issue is not a _duplicate_.

There is a [LISP icon in this repo](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_lisp.svg) which should show up when a file ends with `.lisp`, but it doesn't show up for me.
Also, another common file extension for AutoLISP (AutoCAD) is `.lsp`, which I would like to see added.
Should be a pretty small fix but I don't know why it doesn't show up, nor do I know how to register multiple file extensions.

Thank you :)

**Comment by robertohuertasm** [comment]
This is mainly because this icon is only active if you have a lisp extension installed. Try this one: https://marketplace.visualstudio.com/items?itemName=mattn.Lisp
It will enable the icon for the proper extensions.

**Comment by semkeijsper** [comment]
Ahh okay. In that case, could you add https://marketplace.visualstudio.com/items?itemName=Autodesk.autolispext
This is a very popular extension for loading AutoLISP code into Autocad, which I use daily

thanks!

**Comment by robertohuertasm** [comment]
Oh, this extension is using a different language id but I think we can accommodate that. 👍🏻
