### ISSUE TITLE
[Icon Request] Support for Earthly (Earthfile and .earthlyignore)

### ISSUE THREAD

**Issue by svg153** [vscode-icons/vscode-icons#2898]
- [x] I'm sure this issue is not a [_duplicate_](https://github.com/vscode-icons/vscode-icons/search?q=earthly).
- [x] I'm submitting an icon request:
  - Type: `extension, filename, language id`
  - Icon Name: `earthly`
  - Sample original Icon: ![logo](https://raw.githubusercontent.com/earthly/website-output/main/assets/svg/earhtly-logo.svg)
  - Extensions: [`.earthlyignore`](https://docs.earthly.dev/docs/earthfile/earthignore) 
  - Filenames: [`Earthfile`](https://docs.earthly.dev/docs/earthfile)
  - Language ids: [`Earthfile`](https://docs.earthly.dev/docs/earthfile), but similar to `Dockerfile` and `Makefile`
  
- Language Extensions: [earthfile-syntax-highlighting](https://marketplace.visualstudio.com/items?itemName=earthly.earthfile-syntax-highlighting)
- More info: *[Earthly](https://earthly.dev/) is a build automation tool (it's like Dockerfile and Makefile had a baby). It allows you to execute all your builds in containers. This makes them self-contained, repeatable, portable and parallel. You can use Earthly to create Docker images and artifacts (e.g. binaries, packages, arbitrary files)*
  - Projects using it: [jekyll](https://github.com/jekyll/jekyll/blob/master/Earthfile), [Phoenix Framework](https://github.com/phoenixframework/phoenix/blob/master/Earthfile), [more...](https://github.com/earthly/awesome-earthly/tree/main)

**Comment by sasial-dev** [comment]
Can you find an icon that is a square and is preferable in SVG file format?

**Comment by vladaionescu** [comment]
Hi there, here are some SVG logos, although they are not square, unfortunately: https://drive.google.com/drive/folders/11svoJGaxkJ1i85bvSA5ww-UgfTEAdY2L?usp=sharing

**Comment by vladaionescu** [comment]
Oh I found one that is square (but not SVG):

![White bg - opaque - square](https://user-images.githubusercontent.com/446771/157590673-6d1f525b-09d1-4abf-aad3-4788b11c11d4.png)

**Comment by brumhard** [comment]
@sasial-dev do the provided SVGs fit your needs? I guess it should be possible to crop the files to only include the logo itself in a square format but I'm really not sure how to do that in the best way.

**Comment by svg153** [comment]
I have asked a [friend](https://anaboria.wixsite.com/portfolio) to adapt the logos. This afternoon I will do the PR with the changes. Thanks to everyone. :)
