### ISSUE TITLE
Adding Turborepo icon

### ISSUE THREAD

**Issue by MrNossiom** [vscode-icons/vscode-icons#2900]
Hi there,
I would like to add a new icon to the set.

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `Turborepo`
  - Sample original Icon: 
  		![logo](https://turborepo.org/images/favicon/favicon.ico)
  - Filenames: `turbo.json`

- More info: https://turborepo.org/

Thanks, I love this extension. Great work.

**Comment by xiaoxiangmoe** [comment]
fixed in v11.9.0
