### ISSUE TITLE
Support vscode new `explorer.experimental.fileNesting`

### ISSUE THREAD

**Issue by zzjin** [vscode-icons/vscode-icons#2909]
- [x] I'm sure this issue is not a _duplicate_.

vscode's new version  support experimental nesting files. @see: https://code.visualstudio.com/updates/v1_64#_explorer-file-nesting

bug when enabled this exp feature with vscode-icons 's `Hide Explorer Arrows: true` the files expand arrow disapled.

want screenshot:
![image](https://user-images.githubusercontent.com/679757/152947966-822ee12a-3f05-4350-868a-fd47e1c849a7.png)

 when set `Hide Explorer Arrows: true`:
![image](https://user-images.githubusercontent.com/679757/152948168-02df3190-3f33-492a-88da-726ee53e59ed.png)
 There is no way to expand/unexpand nesting files.

**Comment by robertohuertasm** [comment]
HI @zzjin, this is something completely out of our control and should be informed to the vscode team. I suggest you to open a new issue in their repo and reference this one. Thanks for reporting this, though.

**Comment by zzjin** [comment]
@cc https://github.com/microsoft/vscode/issues/141428
