### ISSUE TITLE
[Icon Request]: Cypress Logo Rebrand

### ISSUE THREAD

**Issue by JessicaSachs** [vscode-icons/vscode-icons#2910]
👋🏻 Hello! I'm excited to add the new Cypress logo!
We've rebranded, added a new config file type, and added a new extension to avoid conflicts with Jest/Mocha specs.
https://twitter.com/Cypress_io

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `folder`
  - Icon Name: `cypress`
  - Sample original Icon:  ![cypress-icon](https://user-images.githubusercontent.com/2801156/153322291-8b186487-5127-48f7-aa6d-b0ef350f8575.png)
  - Extensions: `.cy.*` (Just like how `.spec.*` works)
  - Filenames:
    - `cypress.config.{js,ts}`
    - `cypress.json`

**Comment by robertohuertasm** [comment]
Hi @JessicaSachs, do you happen to have a link to an svg version of the logo?

**Comment by JessicaSachs** [comment]
I tried, but for some reason the gradient on the outside is getting clipped
and I don't really know how to fix it.

**Comment by robertohuertasm** [comment]
Can you share the link so we can work on it? It's better if we have an svg for starters than making a new one from scratch.

**Comment by JessicaSachs** [comment]
Sure, here it is.
https://gist.github.com/JessicaSachs/7c81369fa11bb12604350c2cf9805a7e#file-cypress-logo-svg

**Comment by robertohuertasm** [comment]
What did you use to elaborate it?

**Comment by JessicaSachs** [comment]
Elaborate? Create you mean? Figma. [Lemme share the Figma](https://www.figma.com/file/n2AeT3XLEzC7uuyonDsjYD/Cypress-SVG-Logo?node-id=0%3A1)

**Comment by JessicaSachs** [comment]
👋🏻 how is this going? Do I need to provide another SVG?

**Comment by robertohuertasm** [comment]
Haven't have the time to look at this so if you have a better svg I'd really appreciate it.

**Comment by JessicaSachs** [comment]
No problem. I got a hand from @elevatebart to play around w it. Figma is just exporting corrupted gradients etc.

![cypress-logo](https://user-images.githubusercontent.com/2801156/155437160-5b6a9c12-a29b-4873-a1e2-b5ae5dd073bf.svg)

**Comment by sasial-dev** [comment]
Congrats on the new logo! I've created a PR with the new logo, although some help would be appriciated with the folder icons (I'm not the greatest designer!)

**Comment by JessicaSachs** [comment]
Thank you! Absolutely... Let me get back to you with some designs. @elylucas you had some already I believe?

**Comment by elylucas** [comment]
@sasial-dev I opened up #2982 to add the new icons. Thanks for your assistance!

**Comment by sasial-dev** [comment]
Awesome, just left a review with a minor change that needs to be made!
