### ISSUE TITLE
The button to see the changelog after an update links to the deprected changelog

### ISSUE THREAD

**Issue by THeK3nger** [vscode-icons/vscode-icons#2933]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:

- Language Extensions:
- More info:

Hi all. Today, after an update, vscode-icons prompted me with the usual celebratory notification. I clicked the button to see the changelog and it opened the browser to the old changelog (the one deprecated in December). I think the link should be updated to the new one. 

Cheers,

**Comment by robertohuertasm** [comment]
That's strange as this was already fixed in the latest version: https://github.com/vscode-icons/vscode-icons/pull/2920
What version of the extension are you using?

**Comment by THeK3nger** [comment]
I think it was my bad. I had an instance of VSCode running for some time, so that message was probably for the previous version. I just restarted VSCode again, and the button is now correct. :D Sorry.

**Comment by robertohuertasm** [comment]
No problem! Thanks anyway!
