### ISSUE TITLE
[Icon Request] Support for .wgsl

### ISSUE THREAD

**Issue by Dequog** [vscode-icons/vscode-icons#2939]
- [x] I'm submitting an icon request:
- [x] I'm sure this issue is not a _duplicate_.
- Type: `.wgsl`
  - Icon Name: `WGSL/WGPU Icon`
  - Sample original Icon: ![logo](https://gcdnb.pbrd.co/images/XxleAobT4A0I.png?o=1)
  - Extensions: `wgsl`
  - Language ids: `wgsl`

- Language Extensions: `wgsl`
- More info: https://sotrh.github.io/learn-wgpu/beginner/tutorial3-pipeline/#writing-the-shaders

**Comment by sasial-dev** [comment]
Do you have an SVG version of the logo?

**Comment by Dequog** [comment]
No, I do not.

**Comment by baby** [comment]
I would like to bump this issue as the official WebGPU repo has recently added a logo including various versions in svg format.

Additional versions can be found here: https://github.com/gpuweb/gpuweb/tree/main/logo
![No Text Version](https://raw.githubusercontent.com/gpuweb/gpuweb/7863716ea2233a5642c123b4c2b30acc193fb26e/logo/webgpu-notext.svg)
