### ISSUE TITLE
Make JSON icons work with JSON-Lines and NDJSON file extensions

### ISSUE THREAD

**Issue by alexkreidler** [vscode-icons/vscode-icons#2942]
[JSON Lines](https://jsonlines.org/) (`.jsonl`) and [NDJSON](http://ndjson.org/) (`.ndjson`) are common file formats for large JSON datasets, often used for bulk downloads from APIs or object storage, or bulk loading into databases, search engines, etc. They are very similar (JSONL additionally specifies that the file must be utf-8 encoded).

It would be great to add those file extensions to the existing JSON [icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles) `json`, `json_official`, and maybe `json2`. I understand users can do this themselves by modifying their `settings.json` like so:
```json
  "vsicons.associations.files": [
    {"icon": "json", "extensions": ["json", "jsonl", "ndjson"]}
  ],
```

I think it would be great to have this a default in the extension! I'd be happy to send a PR to update the relevant code if it is welcome: https://github.com/vscode-icons/vscode-icons/blob/5628062179754442985d4a4e047501adaaf9491f/src/iconsManifest/supportedExtensions.ts#L2187-L2207

Thanks!

**Comment by sasial-dev** [comment]
From what I've found, PR's are always welcome (_not like I've got 5 PR's open now..._), so go ahead and PR it if you like, or I'm happy to as well :)
