### ISSUE TITLE
Unable to install extension

### ISSUE THREAD

**Issue by deepindersinghbti** [vscode-icons/vscode-icons#2946]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: ``
  - Icon Name: ``
  - Sample original Icon: ![logo]()
  - Extensions: ``
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:
Whenever I try to install the extension, I get an error, "Error while installing vscode-icons extension. please check the log or more details.

**Comment by robertohuertasm** [comment]
Can you share the log with us? Have you tried disabling all your other extensions to see if there's a conflict with some other extension?

**Comment by deepindersinghbti** [comment]
I tried disabling all extensions by pressing F1 (to open the command palette) and then selecting **Disable All extensions**. Then I tried to install the extension, but in vain.

**Comment by robertohuertasm** [comment]
That's super strange... I guess you're using Windows... have you tried reinstalling vscode? I'll have to dig into this error you're getting about the zip being corrupted...

**Comment by robertohuertasm** [comment]
@deepindersinghbti the problem with this is that I cannot reproduce it as it seems very particular to your set up... I'll try to find something about this but it's really difficult without being able to reproduce it.

**Comment by deepindersinghbti** [comment]
ISSUE FIXED!

It has been many days since I'm trying to install this extension. Today, when I tried to install it, I was finally SUCCESSFUL.

**Comment by robertohuertasm** [comment]
Hi @deepindersinghbti, I'm really glad to hear that. Do you know what happened?

**Comment by deepindersinghbti** [comment]
No, I did not understand anything at all! But anyways, the issue has been fixed. Thank you very much!
