### ISSUE TITLE
.drawio.png is recogonized as .drawio

### ISSUE THREAD

**Issue by tjx666** [vscode-icons/vscode-icons#2947]
- [x] I'm sure this issue is not a _duplicate_.``

Version:

VSCode: 1.66 insiders
VSCode-icons: v11.10.0

![image](https://user-images.githubusercontent.com/41773861/156732611-de956257-6bf7-442d-9ef7-b20f23eca911.png)

**Comment by sasial-dev** [comment]
That seems to be deliberate.
https://github.com/vscode-icons/vscode-icons/blob/5628062179754442985d4a4e047501adaaf9491f/src/iconsManifest/supportedExtensions.ts#L1343-L1349

**Comment by robertohuertasm** [comment]
I think this may be a mistake on our side, as I cannot see why we would want to add the drawio icon to a png or an svg file. Let's change it. Thank you both @tjx666  and @sasial-dev!
