### ISSUE TITLE
Icon for assembly files

### ISSUE THREAD

**Issue by Brian-Pob** [vscode-icons/vscode-icons#2956]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `File Extension Icon`
  - Icon Name: `Assembly`
  - Sample original Icon: ![assembly](https://raw.githubusercontent.com/material-theme/vsc-material-theme-icons/afc5217daebb1c7af7410e76a4d53f31987604ad/src/icons/svgs/assembly.svg)
  - Extensions: `.asm .s`
  - Filenames: ``
  - Language ids: ``

- Language Extensions:
- More info:

**Comment by sasial-dev** [comment]
Do you have an SVG of that icon?

**Comment by Brian-Pob** [comment]
Can I change the icon for my request? I don't have the SVG for the original icon, but I created one that copies the icon from [here](https://plugins.jetbrains.com/plugin/9759-nasm-assembly-language).

Here is a [gist containing the file svg.](https://gist.github.com/Brian-Pob/4bcbe96a231ee35ffed4ac114a90dd32)

**Comment by sasial-dev** [comment]
It looks like we already have an assembly icon!
https://github.com/vscode-icons/vscode-icons/blob/33ca2911696d1c4d34bf193971b87b46a07514d4/src/iconsManifest/supportedExtensions.ts#L511-L516
Has it not been working for you? Should we modernise it? It is currently:

<img alt="Assembly Icon" src="https://raw.githubusercontent.com/vscode-icons/vscode-icons/33ca2911696d1c4d34bf193971b87b46a07514d4/icons/file_type_assembly.svg" height="35px">

**Comment by Exortions** [comment]
You should use the binary file icon

**Comment by mirao** [comment]
Is the existing icon for assembly language displayed at `asm` fiile? It doesn't work for me: https://github.com/vscode-icons/vscode-icons/issues/3079#issuecomment-1328206126

**Comment by AuracleTech** [comment]
![image](https://user-images.githubusercontent.com/40531871/224306271-c055c213-e1bf-4553-8196-61140dc7f9a8.png)
![image](https://user-images.githubusercontent.com/40531871/224306399-4c88f88a-01c4-40c8-844f-bda134c7fa84.png)
Why does it says its supported but its not working

**Comment by robertohuertasm** [comment]
For what I see this icon is supported through a language extension. You should install one so the icon is shown.

**Comment by robertohuertasm** [comment]
See [this](https://github.com/vscode-icons/vscode-icons/issues/3079#issuecomment-1464341309). We need a fix for this. Thanks for reporting it.
