### ISSUE TITLE
Icon for mongodb files

### ISSUE THREAD

**Issue by li1234yun** [vscode-icons/vscode-icons#2957]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `mongodb`
  - Icon Name: `mongodb`
  - Sample original Icon: None
  - Extensions: `mongodb`
  - Filenames: `xxx.mongodb`
  - Language ids: None

- Language Extensions: `MongoDB for VSCode`
- More info:
  - files with `.mongodb` suffix supported by `MongoDB for VSCode` official plugin.

**Comment by sasial-dev** [comment]
I checked the code and it's already supported! Are you having an issue with it?
https://github.com/vscode-icons/vscode-icons/blob/33ca2911696d1c4d34bf193971b87b46a07514d4/src/iconsManifest/supportedExtensions.ts#L2642-L2647

**Comment by li1234yun** [comment]
The language extension `MongoDB for VSCode` uses the `mongodb` suffix name, maybe also support `mongodb` suffix.

**Comment by robertohuertasm** [comment]
@li1234yun unfortunately, suffixes are not supported by vscode api. Let us know if you have any other problem. If not, please close this issue.

**Comment by li1234yun** [comment]
Thank you! @robertohuertasm
