### ISSUE TITLE
Inconsistent icon names

### ISSUE THREAD

**Issue by janosh** [vscode-icons/vscode-icons#2958]
- [x] I'm sure this issue is not a _duplicate_.

Wanted to highlight a few inconsistent icon names:

- [`file_type_js.svg`](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_js.svg) has abbreviated language name. All other languages are written out. E.g. [file_type_typescript.svg](https://github.com/vscode-icons/vscode-icons/tree/master/icons).
- [`file_type_dartlang.svg`](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_dartlang.svg) has `lang` suffix.
- There is [`file_type_delphi.svg`](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_delphi.svg) but no `file_type_pascal.svg`. Intentional? If not would be great if `file_type_pascal.svg` could be added.

**Comment by janosh** [comment]
@robertohuertasm Would you accept a PR standardizing the file names?

**Comment by robertohuertasm** [comment]
Let me review this. My first thought is that this may cause issues for people relying on customizations and would be a breaking change.

**Comment by janosh** [comment]
Yes, definitely a breaking change. Would have to be a major release, I guess? The only reason in favor of this change is it would make programmatic use of the icons easier. I.e. no more for need for special cases in file name construction like here:

https://github.com/janosh/svelte-multiselect/blob/main/src/components/LanguageSlot.svelte#L10-L15

**Comment by robertohuertasm** [comment]
@janosh the way I see it, the impact on 3rd libraries depending on our icons is not that huge compared to the amount of users that would probably be losing their icon customizations. I guess we'll have to live with that. Thanks anyway for raising this.

**Comment by janosh** [comment]
Understandable. Thanks for taking a look.
