### ISSUE TITLE
Add deno configuration file Icon

### ISSUE THREAD

**Issue by jim-junior** [vscode-icons/vscode-icons#2964]
👋🏻 Hello! I would like to ask if you would add an icon for the [deno configuration file](https://deno.land/manual@v1.20.4/getting_started/configuration_file) so it can also stand out in the project configuration file instead of looking like a normal json file.

- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `deno configuration`
  - Sample original Icon: ![logo](https://avatars.githubusercontent.com/u/42048915?s=200&v=4)
  - Filenames: `deno.json` `deno.jsonc`

**Comment by sasial-dev** [comment]
Is there some kind of light icon as well? As this icon doesn't seem to work well for dark mode users when I tried implimenting it.

**Comment by ayoreis** [comment]
I think we should use the simpler version since it's such a small icon (+ it's a SVG so its easy to change it to a light version):

<img height=200 src=https://user-images.githubusercontent.com/84969551/164706662-c8bb1c3d-f848-4a19-992e-b86dae31de34.svg>

**Comment by bartlomieju** [comment]
> I think we should use the simpler version since it's such a small icon (+ it's a SVG so its easy to change it to a light version):
> 
> <img alt="" height="200" src="https://user-images.githubusercontent.com/84969551/164706662-c8bb1c3d-f848-4a19-992e-b86dae31de34.svg">

Bartek from the Deno team here. I agree we should use this icon, since it contains fewer lines and should appear sharper, especially if it's supposed to be a small icon.
