### ISSUE TITLE
[Icon Request] Support `go.work` file icon

### ISSUE THREAD

**Issue by li1234yun** [vscode-icons/vscode-icons#2966]
- [x] I'm sure this issue is not a _duplicate_.
- [ ] I'm submitting an icon request:
  - Type: `go.work`
  - Icon Name: `go.work`
  - Sample original Icon: None
  - Extensions: `vscode-go`
  - Filenames: `go.work`
  - Language ids: `golang`

- Language Extensions: vscode-go
- More info:

[Go workspace tutorial](https://go.dev/doc/tutorial/workspaces)

**Comment by sasial-dev** [comment]
Is there a specific icon for `go.work`, or do you want to just have the go icon?

**Comment by li1234yun** [comment]
It's just my idea like go icon.
