### ISSUE TITLE
[Icon Request] Support for hardhat config file

### ISSUE THREAD

**Issue by edumudu** [vscode-icons/vscode-icons#2973]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `hardhat`
  - Sample original Icon: ![logo](https://user-images.githubusercontent.com/51760454/163883865-e3448285-4999-426c-9999-098b3ce49e7a.svg)
  - Filenames: `hardhat.config.js`, `hardhat.config.ts`

- More info: From the about section of their repository
> [Hardhat](https://hardhat.org/) is a development environment to compile, deploy, test, and debug your Ethereum software. Get Solidity stack traces & console.log.

**Comment by sasial-dev** [comment]
Could you source an svg icon for hardhat? Currently vscode-icons is only accepting SVG icons.

**Comment by edumudu** [comment]
Updated!
