### ISSUE TITLE
[ Icon Request ] Add support for the newer, 2021 Azure logo

### ISSUE THREAD

**Issue by hiteacheryouare** [vscode-icons/vscode-icons#2991]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Azure`
  - Sample original Icon: ![azure 2021 logo](https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Microsoft_Azure.svg/330px-Microsoft_Azure.svg.png)
  - Extensions: (folder) `azure`

- More info:

In 2021, Microsoft shifted the logo of their `Azure` cloud service from this: ![azure previous logo](https://static.wikia.nocookie.net/logopedia/images/9/9d/MicrosoftAzura_2017.svg/revision/latest/scale-to-width-down/150?cb=20210508142229) to a more "A" shaped logo, more fitting with their fluent design system.

**Comment by sasial-dev** [comment]
Do you have an SVG version of that icon?

**Comment by hiteacheryouare** [comment]
![Microsoft_Azure](https://user-images.githubusercontent.com/82683251/165519734-2b2e154e-217f-498a-a347-8e6f378e836d.svg)
