### ISSUE TITLE
[Icon Request] Support for AL Object ID Ninja configuration file

### ISSUE THREAD

**Issue by vjekob** [vscode-icons/vscode-icons#3003]
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:

  - Type: `filename`
  - Icon Name: `objidconfig`
  - Sample original Icon: ![logo](https://github.com/vjekob/al-objid/blob/master/vscode-extension/images/icon.png?raw=true)
  - Filenames: `.objidconfig`

- More info: https://marketplace.visualstudio.com/items?itemName=vjeko.vjeko-al-objid

**Comment by sasial-dev** [comment]
Do you have an SVG version of that icon?
Also an icon sutible for dark mode would be helpful :)

**Comment by vjekob** [comment]
I have actually prepared the pull request, I'm completing it in a minute. It has both light and dark versions of this.

**Comment by sasial-dev** [comment]
Awesome!
Just letting you know that we do not accept PNG icons anymore - they must be SVG.

**Comment by vjekob** [comment]
It is SVG, no worries. This logo here is PNG because I need it in PNG there. But the icons are both SVG.
