### ISSUE TITLE
How to use custom icons?

### ISSUE THREAD

**Issue by deepindersinghbti** [vscode-icons/vscode-icons#3008]
I want to test some custom icons for my personal projects. How can I choose my own icons, as I read in the extension description that it supports icon customization.

**Comment by robertohuertasm** [comment]
Please, check the [wiki](https://github.com/vscode-icons/vscode-icons/wiki/Customization).

**Comment by deepindersinghbti** [comment]
I followed the steps given [here](https://github.com/vscode-icons/vscode-icons/wiki/Custom).

I navigated to **C:\Users\Username\AppData\Roaming\Code\User\vsicons-custom-icons**, created a new folder named **vsicons-custom-icons** and placed my icons in that folder.

Please guide me further on how to apply these icons to my files as I didn't understand the further steps given in the documentation.

**Comment by robertohuertasm** [comment]
@deepindersinghbti you don't have to create a folder inside the **C:\Users\Username\AppData\Roaming\Code\User\vsicons-custom-icons**. 

Have you put the icons at the root of the previous path? Do they follow vscode-icons naming convention as stated in the wiki? Have you declared the icons in your vscode settings?

**Comment by robertohuertasm** [comment]
I guess you'll have visited [this page of the docs](https://github.com/vscode-icons/vscode-icons/wiki/Custom) explaining all the process of creating custom icons. 

Take a look at[ this one](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) to learn how to declare your icon customization

**Comment by deepindersinghbti** [comment]
I added  the following code to my `settings.json` file:

```
  "vsicons.associations.files": [
    {
      "icon": "js",
      "extensions": [".js"],
      "format": ".svg"
    }
  ]
```

And also added this setting:

`  "vsicons.customIconFolderPath": "C:\\Users\\Username\\AppData\\Roaming\\Code\\User\\vsicons-custom-icons",`

But it's not working. Please help!

**Comment by robertohuertasm** [comment]
Remove the dots from the extensions and format.

**Comment by deepindersinghbti** [comment]
I tried, but it's still not working.
