### ISSUE TITLE
[Icon Request] Support for SPWN

### ISSUE THREAD

**Issue by GGodPL** [vscode-icons/vscode-icons#3026]
- [x]  I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `languageId`
  - Icon Name: `SPWN`
  - Sample original Icon:
   ![logo](https://user-images.githubusercontent.com/46885632/170041941-8d117125-cf6b-401a-9ad7-d01a993885a9.svg)
  - Extensions: `spwn`
  - Language ids: `spwn`

- Language Extensions: [marketplace](https://marketplace.visualstudio.com/items?itemName=Spu7Nix.spwn-language-support)

**Comment by sasial-dev** [comment]
This image seems to be an SVG converted from PNG and seems to be crappy quality.
Do you have any better quality?

<img src="https://user-images.githubusercontent.com/44125644/170797215-66089c2b-2ae7-4f71-a433-bfda2ba918ff.png" width="200" />

**Comment by GGodPL** [comment]
The only other svg I found is this one: 
![spwn_logo_large](https://user-images.githubusercontent.com/46885632/170834010-6eb83b84-64d7-430c-a976-99632778deda.svg)
The

**Comment by GGodPL** [comment]
I accidentally closed it

**Comment by sasial-dev** [comment]
That's much better!
