### ISSUE TITLE
[Icon Request] Support for `markdownlint` configs

### ISSUE THREAD

**Issue by jjspace** [vscode-icons/vscode-icons#3027]
- [x] I'm sure this issue is not a _duplicate_. but it _is_ a follow up to https://github.com/vscode-icons/vscode-icons/issues/1092 and https://github.com/vscode-icons/vscode-icons/pull/1112
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `mdlint`
  - Sample original Icon: ![file_type_markdownlint.svg](https://raw.githubusercontent.com/DavidAnson/vscode-markdownlint/master/images/markdownlint-128.png)
  - Filenames:
      - `.markdownlint.json`
      - `.markdownlint.jsonc`
      - `.markdownlint.yml`
      - `.markdownlint.yaml`
      - `.markdownlint.cjs`
      - `.markdownlint-cli2.jsonc`
      - `.markdownlint-cli2.yaml`
      - `.markdownlint-cli2.cjs`
      - `.markdownlintrc` 

### More info:

This icon already exists it's just not set up to cover all the potential config filenames accepted by the markdownlint tooling

- [`markdownlint-cli`](https://github.com/igorshubovych/markdownlint-cli#configuration) accepts any of the above that don't contain "cli2"
- [`markdownlint-cli2`](https://github.com/DavidAnson/markdownlint-cli2#configuration) accepts all of the above _except_ the `.markdownlintrc` file
- the markdown [vscode extension](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint#configure) recognizes all of the above _except_ the `.markdownlintrc` file as well

![2022-05-26_13-26](https://user-images.githubusercontent.com/8007967/170543100-ed3fc39e-b717-4455-8418-3f3fa53e9340.png)

CC @DavidAnson as it's their tool and they might have more of an opinion on which files this icon should count for

**Comment by DavidAnson** [comment]
I think everything you said is accurate! I would recommend using the file types supported by the extension (i.e., excluding the "rc" one). I would recommend against the name "mdlint" because that is a different tool. The icon you show looks like the one I created in case anyone is worried about provenance: https://github.com/DavidAnson/vscode-markdownlint/blob/main/images/markdownlint-128.png

I could regenerate it at any size if that's desirable.

**Comment by sasial-dev** [comment]
We've already got a markdown lint icon!

@DavidAnson, do you want to update it? If so, we need an SVG icon.
Currently we have:

<img src="https://raw.githubusercontent.com/vscode-icons/vscode-icons/5b464452541190e67e5cacd0a8f5cb1d312156b7/icons/file_type_markdownlint.svg" width=100>

**Comment by DavidAnson** [comment]
@sasial-dev Here's a quick SVG for my original graphic. I rounded a few more of the corners for fun.

```svg
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
  <style>
    rect { stroke: black; stroke-width: 1; fill: white }
    path { stroke: black; stroke-linecap: round; stroke-linejoin: round; fill: none }
  </style>
  <rect x="0.5" y="0.5" width="15" height="15" rx= "1" ry="1"/>
  <path d="M 10.5,2.5 L 11.5,2.5 L 11.5,5.5 L 13,5.5 L 11,7.5 L 9,5.5 L 10.5,5.5 Z" style="fill:black"/>
  <path d="M 2.5 7.5 L 2.5 3 L 4.5 5 L 6.5 3 L 6.5 7.5"/>
  <path d="M 2.5,9.5 L 2.5,13.5 L 4,13.5"/>
  <path d="M 5.5,10 L 5.5,10 M 5.5,11.5 L 5.5,13.5"/>
  <path d="M 7.5,13.5 L 7.5,11.5 L 9.5,11.5 L 9.5,13.5"/>
  <path d="M 12.5,13.5 L 12.5,10 M 11.5,11.5 L 13.5,11.5"/>
</svg>
```
