### ISSUE TITLE
Meta: Update issue template to use forms

### ISSUE THREAD

**Issue by jjspace** [vscode-icons/vscode-icons#3028]
I just opened my first issue for an icon request and realized the issue template would probably be perfect for the newer Form issue templates which allow for multiple input fields, dropdowns and checkboxes. See [Creating issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)

![image](https://user-images.githubusercontent.com/8007967/170545061-f8d572b6-9f7a-423c-b648-963bcc8adadb.png)

I just wanted to suggest checking them out so you don't have to rely so much on people going to read the [Issue](https://github.com/vscode-icons/vscode-icons/wiki/Issue) wiki page

**Comment by sasial-dev** [comment]
Great idea!
