### ISSUE TITLE
Unable to customize file icons

### ISSUE THREAD

**Issue by deepindersinghbti** [vscode-icons/vscode-icons#3035]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I am trying to customize my JavaScript file icon. I wrote the following code in the `settings.json`  file, but it did not work:
`
"vsicons.customIconFolderPath": "C:\\Users\\Deepinder Singh\\AppData\\Roaming\\Code\\User\\vsicons-custom-icons",`

```
  "vsicons.associations.files": [
    {
      "icon": "file_type_js",
      "extensions": ["js"],
      "format": "svg",
      "filename": false,
      "filenamesGlob": ["js"],
      "extensionsGlob": ["production", "local"],
      "light": true
    }
  ]
```

Please tell me where I made a mistake in the code. Thank you for any help you can offer!

**Comment by robertohuertasm** [comment]
Closing this as there’s already another issue. #3008
