### ISSUE TITLE
[Icon Request]: WikiText

### ISSUE THREAD

**Issue by SandyTree** [vscode-icons/vscode-icons#3051]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [X] Filename
- [X] Language ID

### Original Icon

![image](https://user-images.githubusercontent.com/8256307/172050094-a7de7910-010c-4e10-aba9-edfb7d52d61a.png)

### Icon Information

Language ID: `wikitext`
Extensions: `.wt`
aliases: `WikiText`, `wt`, `wikitext`, `Wikitext`
Icon Name: `wt`

### More Information:

https://en.wikipedia.org/wiki/Help:Wikitext

**Comment by PAXANDDOS** [comment]
I believe the `wikitext` language ID is brought by [this extension](https://marketplace.visualstudio.com/items?itemName=RoweWilsonFrederiskHolme.wikitext)?
Everything else looks good, will make a PR tomorrow, already have made an SVG version of the icon you provided
