### ISSUE TITLE
How to make custom icons and change them in the extension?

### ISSUE THREAD

**Issue by nico-qwer** [vscode-icons/vscode-icons#3052]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I have went through the internet for about an hour and a half, and the most I have been able to do is hide the icons for a file type.

Yes, I have seen these links:
https://medium.com/@chih.hsi.chen/how-to-add-your-custom-icons-to-vscode-icons-9ab8c3f9abc1  
https://github.com/vscode-icons/vscode-icons/wiki/FineTuning  
https://github.com/vscode-icons/vscode-icons/issues/1565

I still don't understand how the naming convention works and how to associate an icon and a file extension/name.

Please help me!

**Comment by hamid814** [comment]
it's simple!
there are three parts to it:

One: is it an icon for a folder or a file?
if it's a file, add `file_type_` to the start of the name,
if it's a folder, add `folder_type_` to the start of the name and `_opened` to the end of it

Two: the arbitrary name you wanna give the icon
Example:
if your name is `my-awesome-icon` and it's for a file ( like a `.js` file or a `.py` one ), use this:
`file_type_my-awesome-icon`

Three: the format of the icon file ( SVG, PNG, ICO, ... )
Example: if your icon is an SVG file, use this:
`file_type_my-awesome-icon.svg`
this will be the final name of your file

*Note that for folders you have to make two icon files.*

**Comment by nico-qwer** [comment]
thanks
