### ISSUE TITLE
[Icon Request]: Brotli

### ISSUE THREAD

**Issue by SimonSiefke** [vscode-icons/vscode-icons#3070]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

![68747470733a2f2f62726f746c692e6f72672f62726f746c692e737667](https://user-images.githubusercontent.com/23744935/175832894-2ddb509e-089d-40c7-ae9f-4f4e2d3b12e8.svg)

### Icon Information

Brotli is a compression algorithm developed by Google and used by a lot of web servers. 

The icon from https://github.com/vscode-icons/vscode-icons/issues/2571 might also be a good fit for this, to be consistent with the other archive formats. 

![](https://user-images.githubusercontent.com/13915612/89097257-07802980-d3e6-11ea-8446-b6fd2a7eec6d.png)

### More Information:

https://github.com/google/brotli

**Comment by Snazzah** [comment]
@SimonSiefke What would be the proper extension here? Some searches would suggest `.br`, but not too sure.

**Comment by SimonSiefke** [comment]
Yes, I think the proper extension is `.br` https://github.com/google/brotli/blob/master/docs/brotli.1#L63
