### ISSUE TITLE
Add HTML extension

### ISSUE THREAD

**Issue by arsari** [vscode-icons/vscode-icons#3076]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

When I have a file with the extension `html` the icon does not show. If I change the file extension to `htm` the icon shows.

It is possible to use the same icon for `htm` and `html` file extensions?

**Comment by robertohuertasm** [comment]
@arsari that should be the case already. You may have some sort of specific configuration for `html` files. What icon are you getting with `html`? Can you check which is the associated language in the bottom bar?

<img width="402" alt="image" src="https://user-images.githubusercontent.com/696981/178242046-500044f9-e13f-464c-9f77-0eedddfb4c85.png">

**Comment by arsari** [comment]
Hi @robertohuertasm. I continue looking at what could be the issue on my end based on other laptop implementation that I have that shows the icon correctly. It seems that on the laptop where I was having the issue, I needed to modify the file association configuration by adding an HTML extension to it. After that, the icon shows up for any file with the extension HTML.
