### ISSUE TITLE
! Unable to create an HTML environment quickly

### ISSUE THREAD

**Issue by tumeo** [vscode-icons/vscode-icons#3090]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

![image](https://user-images.githubusercontent.com/104367546/178222318-6e7416f9-49e6-4be6-9412-543989684b21.png)

**Comment by sasial-dev** [comment]
This is an english-only repo, please translate your title to English!

**Comment by tumeo** [comment]
> 这是一个只有英文的repo，请把你的标题翻译成英文！

ok

**Comment by sasial-dev** [comment]
This shouldn't be a vscode icons, it should just work again if you hit <kbd>CTRL</kbd> - <kbd>Space</kbd> / <kbd>Command</kbd> - <kbd>Space</kbd>

**Comment by robertohuertasm** [comment]
@tumeo, I'm closing this as this doesn't seem related to our repo as @sasial-dev was pointing out. Feel free to counterargument here if you feel that that's not the case. Thanks!
