### ISSUE TITLE
Folder icon inheritance for sub-folder/nested folders

### ISSUE THREAD

**Issue by koanplaned** [vscode-icons/vscode-icons#3102]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Hi all,

I was playing around with custom folder icons as described here in the documentation: https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

Everything works pretty well, but I was not able to find any information about how to inherit icons to subfolders.

I have following folder structure:
<img width="143" alt="Bildschirmfoto 2022-07-28 um 12 04 00" src="https://user-images.githubusercontent.com/34692365/181479613-8cfb1773-4745-4094-b77a-b520b92e8487.png">

What I want to achieve is, that "audit", "message", "name.route" does all have the same icon as the parent folder "routes", but I don't want to explicitly add the names of the folders  in the vscode-icon configuration.

My current configuration looks like this:
`{"icon": "interfaces", "extensions": ["routes"], "format": "svg"},`

I tried to add "route" to the extensions array and hoped, that at least the folder "name._route_" would take over the icon configuration, but it didn't do the trick.

Thanks in advance for your feedback :-)

**Comment by robertohuertasm** [comment]
Hi @koanplaned, unfortunately that's not currently supported.

**Comment by koanplaned** [comment]
Hi @robertohuertasm, thank you for the feedback
