### ISSUE TITLE
Configuration for default (root-)folder icon

### ISSUE THREAD

**Issue by koanplaned** [vscode-icons/vscode-icons#3103]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Hi all,

I have troubles to change the default folder icon and default root_folder icon.

According to the documentation here (https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) the settings should be done in this way:

default folder:
`"vsicons.associations.folderDefault.folder": {"icon": "android", "format": "svg"}`

default root folder:
`"vsicons.associations.folderDefault.root_folder": {"icon": "android", "format": "svg"}`

Please note: 
I've chosen an icon "android" that should be working with folders, according to following documentation: https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders

Someone else also had troubles to configure this, but unfortunately her/his question was not answered on how to configure a default folder icon correctly:
https://github.com/vscode-icons/vscode-icons/issues/2541

Thanks in advance for your feedback :)

**Comment by koanplaned** [comment]
Addition: 
I found out, that you can indeed change the icon for the default folder with following configuration:

Change the default folder to the "root-folder"-icon
`"vsicons.associations.folderDefault.folder": {"icon": "root_folder", "format": "svg"}`
<img width="129" alt="Bildschirmfoto 2022-07-28 um 15 06 54" src="https://user-images.githubusercontent.com/34692365/181513467-0d7a091b-ee96-4303-9b41-29d4294ba1e5.png">

But it seems you can not use any other icon from the supported folder icons here: https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders

So if you set the icon to, e.g. android, it doesn't work:
`"vsicons.associations.folderDefault.folder": {"icon": "android", "format": "svg"}`
<img width="129" alt="Bildschirmfoto 2022-07-28 um 15 11 46" src="https://user-images.githubusercontent.com/34692365/181513536-c1157db3-0619-4e9c-a7a1-1034633a84a3.png">

**Comment by robertohuertasm** [comment]
We must provide a way to replace the `default` prefix with the one for `folders` and `files`. We should probably extend the `IDefaultExtension` interface and modify the logic in `manifestBuilder.ts > buildDefaultIconPath ln 100`. See [here](https://github.com/vscode-icons/vscode-icons/blob/734aa1ac9a0d6223507217ad23426bf558b57f8d/src/iconsManifest/manifestBuilder.ts#L100)
