### ISSUE TITLE
`go test` file use different icon 

### ISSUE THREAD

**Issue by li1234yun** [vscode-icons/vscode-icons#3104]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Now the `go test` files use same icon with other go files. Maybe go test files can use different file icon to distinguish.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/26505658/181878309-6e1eb0bd-b737-4d59-8a19-a0482876ced5.png">

Jetbrains has different icons between normal go files and go test files.

go test files is suffex with `_test.go`.

**Comment by robertohuertasm** [comment]
@li1234yun unfortunately this is not possible with the current vscode icons api. It only works with extensions. Not suffixes.

**Comment by li1234yun** [comment]
Thanks!
