### ISSUE TITLE
Flexible names docker-compose files

### ISSUE THREAD

**Issue by aladinoster** [vscode-icons/vscode-icons#3124]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I work with multiple `docker-compose` files in my folder.

Would it be possible to make files like `docker-compose.myconf1.yaml` or files of type `docker.compose.myconf1.yaml` detectable by the extension to label them as a `docker-compose.yaml` file? 

What are the good practices in this kind of situation?

**Comment by ldeluigi** [comment]
I'd like this feature too!

**Comment by JimiC** [comment]
At the moment this can only be done via https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by wokalek** [comment]
Solved for me:

`settings.json`

```json
"vsicons.associations.files": [
    {
        "icon": "docker",
        "extensions": [".dockerignore"],
        "filenamesGlob": [
            "docker-compose.dev",
            "docker-compose.prod",
        ],
        "extensionsGlob": ["yaml", "yml"],
        "filename": true,
        "languages": ["languages.dockerfile"],
        "format": "FileFormat.svg",
    },
],
```

**Comment by Eazash** [comment]
Is it possible to use file associations for this? Compose files have (and are often manually set to have) the 'dockercompose' file association if I'm not mistaken.
