### ISSUE TITLE
Hide explorer arrows in search

### ISSUE THREAD

**Issue by gillescoolen** [vscode-icons/vscode-icons#3152]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Visual Studio Code has recently got support for showing the files in the search widget in a tree structure. I'd like to hide the arrows there as well, same as in the file explorer with the `"vsicons.presets.hideExplorerArrows": true` setting.

Right now, my explorer looks like this:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/31668393/195517347-6ee5b81c-39d3-4dfe-a65d-18ae1544d4b3.png">

Whilst the search tree looks like:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/31668393/195517412-b4468c38-8c41-4b13-875a-0c9e2543360d.png">

**Comment by robertohuertasm** [comment]
hi @gillescoolen, thanks for your comment. This seems to be an issue in the VSCode side. They're not respecting that setting in the search view. Feel free to open an issue in their repo and link it to this if you want.
