### ISSUE TITLE
Install in Air Gapped Environment?

### ISSUE THREAD

**Issue by advra** [vscode-icons/vscode-icons#3179]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I have a network not connected to the internet. Typically I download a VSIX and transfer it over for install on machines. The releases and instructions show how to install it from the command pallete after installed from the extension marketplace but has no VSIX option. 

What is the procedure to install this in this scenario?

**Comment by JimiC** [comment]
![image](https://user-images.githubusercontent.com/1716442/202168432-b70e9f03-d3fc-4bf2-8bb9-6b20584a26c3.png)
Does this help?

**Comment by advra** [comment]
I know how to install VSIX but I cant find VSIX for this extension.

Typically I go to github, download the VSIX from Releases and then transfer to the offline machines. The Releases page only has [zipped/tar source code](https://github.com/vscode-icons/vscode-icons/releases/tag/v11.20.0 ). How do I download the VSIX and specific version?

**Comment by JimiC** [comment]
@advra The only alternative is the Marketplace but since you don't have access to Internet, your only other choice is File transfer.

**Comment by advra** [comment]
@JimiC Thanks. I see the link downloads the latest version. Is there a way to target a specific version? Ie 11.20. (My org only allows certain versions that were pre-approved)

**Comment by JimiC** [comment]
The only way I know is from inside `vscode`.

https://code.visualstudio.com/updates/v1_30#_install-previous-versions

**Comment by advra** [comment]
I attempted today in vscode and there is no version CMed to select. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/1753803/202777506-5fed6539-8ad6-411f-8e06-29c76df9ed68.png)

**Comment by JimiC** [comment]
![image](https://user-images.githubusercontent.com/1716442/202781343-bdb4b282-e16c-458b-9d8c-b1773f8d506b.png)

![image](https://user-images.githubusercontent.com/1716442/202781280-2938757e-e83a-4075-b84e-d64ab81ffd5b.png)

![image](https://user-images.githubusercontent.com/1716442/202781427-b5bcbb44-2eac-4dea-8a22-e28807c12413.png)

**Comment by advra** [comment]
Im on the business Wifi trying to download 11.20 (and not in the air gapped environment). It likely has blocked access to the version which Ill have to do offsite. When I install 11.20 on my laptop is it possible to then export that as a VSIX? If not then Im afraid I cannot install a specific version. ):?

**Comment by JimiC** [comment]
@advra Just found out that the marketplace extension page has a `Version History` tab.

![image](https://user-images.githubusercontent.com/1716442/202791864-0cf1ebe4-f322-40bc-8ab6-34947b814862.png)

**Comment by advra** [comment]
Thank you for pointing this out. Closing this as resolved!
