### ISSUE TITLE
[Icon Request]: deno.lock

### ISSUE THREAD

**Issue by Vehmloewff** [vscode-icons/vscode-icons#3181]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

![deno logo](https://user-images.githubusercontent.com/84969551/164706662-c8bb1c3d-f848-4a19-992e-b86dae31de34.svg)

### Icon Information

Icon is the Deno logo

### More Information:

Generating lock files with the Deno CLI is now a stable feature, and as of version `1.28.0`, it is enabled by default, automatically writing to the `deno.lock` file ([see release notes](https://deno.com/blog/v1.28#auto-discovery-of-the-lock-file)). The Deno CLI uses this this file to perform integrity checks on remote modules.

**Comment by hiteacheryouare** [comment]
I can do this if need be.

**Comment by robertohuertasm** [comment]
The icon [already exists ](https://github.com/vscode-icons/vscode-icons/blob/9539b8019699b397f146e1edfea6f256e7ee8340/src/iconsManifest/supportedExtensions.ts#L1304) for deno. This should be easy. Just adding `lock` to the `extensionsGlob` array.
