### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by DGAcode** [vscode-icons/vscode-icons#3195]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

This is the original icon for .txt files (https://blogs.windows.com/wp-content/uploads/prod/sites/44/2021/12/Win-Notepad.png)

![image](https://user-images.githubusercontent.com/15164527/208762486-e3f8afaa-929c-4e59-82ba-5fde21196f10.png)

### Icon Information

Notepad redesigned icon for windows 11, or the equivalent to .txt files type

### More Information:

Please I am using a lot of .txt files these days in storage, and I would appreciate your effort.

**Comment by robertohuertasm** [comment]
Note that this is not the official icon for txt files. This is the icon that Windows Notepad adds to those files. Remember that you can use the icon you want by using our [custom icons feature](https://github.com/vscode-icons/vscode-icons/wiki/Custom). Thanks for taking the time to open this issue.
