### ISSUE TITLE
[Icon Request]: License folder

### ISSUE THREAD

**Issue by argvchs** [vscode-icons/vscode-icons#3196]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [ ] File Icon
- [X] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

This icon should be a folder icon with a small license icon in the lower right corner,

Like this:

<img width="225" alt="image" src="https://user-images.githubusercontent.com/64528288/209973576-8f0d4de3-5a1c-4876-b339-cbcff25c4b5c.png">

But I don't know how to make nice icon in SVG format 😞. please help me.

### Icon Information

Icon for folder containing third-party licenses.
The name of folder could be "license" or "licenses".

**Comment by robertohuertasm** [comment]
Why did you close it?

**Comment by argvchs** [comment]
Because multiple licenses can be contained in one file...

```license
MIT License

Copyright (c) 2022 somebody
Copyright (c) 2021 another
Copyright (c) 2020 ...
```

**Comment by robertohuertasm** [comment]
Ok, makes sense! 👍🏻
