### ISSUE TITLE
Ignoring some icons

### ISSUE THREAD

**Issue by chrisk8er** [vscode-icons/vscode-icons#3207]
### Housekeeping

- [ ] I'm sure this issue is _not_ a duplicate

### Information:

I just searched this issue but can't find it anywhere.
Is there anywhere I can disable/ignore vscode-icons to replace some of these icons?
I want it to remain its default like another icon.

![Screen Shot 2023-01-16 at 12 45 15](https://user-images.githubusercontent.com/11579342/212600682-9eb61de4-87e4-420a-abc4-3aacd21e5bfb.png)

**Comment by robertohuertasm** [comment]
These icons are not from vscode-icons, they seem from another icon theme you may have installed.

**Comment by chrisk8er** [comment]
> These icons are not from vscode-icons, they seem from another icon theme you may have installed.

Hi @robertohuertasm , Thank you for your reply... I just updated the screenshot.

**Comment by robertohuertasm** [comment]
Did it solve your issue? Closing this. Feel free to reopen it if you have more questions.
