### ISSUE TITLE
One theme for files, another for folder

### ISSUE THREAD

**Issue by Koowah** [vscode-icons/vscode-icons#3208]
### Housekeeping

- [x] I'm sure this issue is _not_ a duplicate

### Information:

Hi all,

Apologies if this point has already been raised, but I just can't find an issue about it.
I'm looking for an efficient way to set Seti theme for all files (except hardhat config file), and VSCode-Icons theme for folders.

Thanks in advance for your help,
Cheers 😄

**Comment by robertohuertasm** [comment]
Hi @Koowah, you can only set one icon them as active at a time. Try asking in the `vscode` repo in case they're planning something like that.
