### ISSUE TITLE
Custom Top-Left VsCode icon

### ISSUE THREAD

**Issue by SamuelPozzobon** [vscode-icons/vscode-icons#3223]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

hi, I tried to change the top-left vscode icon but it doesn't work.

In settings.json I put:
    "vsicons.associations.files": [
     {
      "icon": "vscode",
      "extensions": [".vscodeignore", "launch.json", "tasks.json", "vscodeignore.json"],
      "format": "svg"
    }
    ]

and for the file name I tried both of: defaultvscode.svg / default_vscode.svg

Am I doing something wrong?

**Comment by robertohuertasm** [comment]
Not sure if I understand your question. Are you trying to modify this icon?
![image](https://user-images.githubusercontent.com/696981/214092647-edb7e6a3-0f67-4071-ac42-c944640377f8.png)

If that's the case, that's not possible.

**Comment by SamuelPozzobon** [comment]
yes. It is possible. 

This is an example found on github, but I don't know how to do it.

<img width="1280" alt="dwave-ide" src="https://user-images.githubusercontent.com/42522736/214259029-dc1b933e-949a-439b-b21d-d1854adbcb74.png">

**Comment by SamuelPozzobon** [comment]
yes, I am trying to replace that icon

**Comment by SamuelPozzobon** [comment]
<img width="1280" alt="dwave-ide" src="https://user-images.githubusercontent.com/42522736/214259903-c4388e49-fb9e-4e18-95c3-8b0dfc7c69bf.png">

**Comment by SamuelPozzobon** [comment]
> <img alt="dwave-ide" width="1280" src="https://user-images.githubusercontent.com/42522736/214259903-c4388e49-fb9e-4e18-95c3-8b0dfc7c69bf.png">

this is an example found on github

**Comment by robertohuertasm** [comment]
That's not possible with this extension. Please, refer to the `vscode` github repository to ask this question there. My guess is that that may be a custom build of vscode.
