### ISSUE TITLE
[Icon Request]: Support for Kotlin extensions (.kts, .ktm)

### ISSUE THREAD

**Issue by gillescoolen** [vscode-icons/vscode-icons#3230]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

Same as the kotlin icon.

### Icon Information

Should be the same as the kotlin icon.

### More Information:

The Kotlin language has multiple exensions (.kt, .kts, .ktm). It would be nice if they all had the kotlin icon. Currently, the .kts and .ktm file extensions show the default file icon.

**Comment by robertohuertasm** [comment]
If you install a Kotlin extension like [this one](https://marketplace.visualstudio.com/items?itemName=fwcd.kotlin) the icons should appear. These icons are supported via language id.

**Comment by robertohuertasm** [comment]
Reopening this as the `.ktm` extension is not supported by that extension. @gillescoolen could you provide more context for the `.ktm` extension?

**Comment by gillescoolen** [comment]
Alright, I have [this Kotlin extension](https://marketplace.visualstudio.com/items?itemName=mathiasfrohlich.Kotlin) installed, which does not activate the icons for `.kts` or `.ktm`, but does activate an icon for `.kt`.

As far as the `.ktm` file extension goes, some developers use it for Kotlin modules, but I personally never use it. Just thought I might as well incude it.

**Comment by robertohuertasm** [comment]
Ok, that extension uses several ids for the extensions. We will add it to support it given that it's one of the kotlin most downloaded extensions. Btw, thanks for the clarifications!

**Comment by gillescoolen** [comment]
No problem, thanks for the work!
