### ISSUE TITLE
[Icon Request]: Haskell

### ISSUE THREAD

**Issue by You-saku** [vscode-icons/vscode-icons#3238]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

![file_type_haskell_icon_130552](https://user-images.githubusercontent.com/53119949/220157757-5df7deaa-b7d7-4f07-9d3c-b26e9095eabf.svg)

### Icon Information

for ```.hs``` file. 

### More Information:

I downloaded this icon in [this site](https://icon-icons.com/icon/file-type-haskell/130552). 
I think the file I uploaded is too big. So, I'm worried.

**Comment by You-saku** [comment]
[BTW]
After I installed ```Haskell Syntax Highlighting(Extention)```, Haskell's Icon appear

**Comment by robertohuertasm** [comment]
That's because we do support haskell via language id.
