### ISSUE TITLE
Please improve webpack configuration files implementation 

### ISSUE THREAD

**Issue by noontz** [vscode-icons/vscode-icons#3246]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I was wondering why one of my file icons for webpack configurations was looking like this:

![image](https://user-images.githubusercontent.com/7408674/222352638-b735b111-bbce-4134-820f-495a3f4f5e90.png)

Eventually I found this page [https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles)

Please take a look:

`webpack.base.conf.js, webpack.base.conf.coffee, webpack.base.conf.ts, webpack.common.js, webpack.common.coffee, webpack.common.ts, webpack.config.js, webpack.config.coffee, webpack.config.ts, webpack.config.base.js, webpack.config.base.coffee, webpack.config.base.ts, webpack.config.common.js, webpack.config.common.coffee, webpack.config.common.ts, webpack.config.dev.js, webpack.config.dev.coffee, webpack.config.dev.ts, webpack.config.development.js, webpack.config.development.coffee, webpack.config.development.ts, webpack.config.staging.js, webpack.config.staging.coffee, webpack.config.staging.ts, webpack.config.test.js, webpack.config.test.coffee, webpack.config.test.ts, webpack.config.prod.js, webpack.config.prod.coffee, webpack.config.prod.ts, webpack.config.production.js, webpack.config.production.coffee, webpack.config.production.ts, webpack.config.babel.js, webpack.config.babel.coffee, webpack.config.babel.ts, webpack.config.base.babel.js, webpack.config.base.babel.coffee, webpack.config.base.babel.ts, webpack.config.common.babel.js, webpack.config.common.babel.coffee, webpack.config.common.babel.ts, webpack.config.dev.babel.js, webpack.config.dev.babel.coffee, webpack.config.dev.babel.ts, webpack.config.development.babel.js, webpack.config.development.babel.coffee, webpack.config.development.babel.ts, webpack.config.staging.babel.js, webpack.config.staging.babel.coffee, webpack.config.staging.babel.ts, webpack.config.test.babel.js, webpack.config.test.babel.coffee, webpack.config.test.babel.ts, webpack.config.prod.babel.js, webpack.config.prod.babel.coffee, webpack.config.prod.babel.ts, webpack.config.production.babel.js, webpack.config.production.babel.coffee, webpack.config.production.babel.ts, webpack.dev.js, webpack.dev.coffee, webpack.dev.ts, webpack.dev.conf.js, webpack.dev.conf.coffee, webpack.dev.conf.ts, webpack.prod.js, webpack.prod.coffee, webpack.prod.ts, webpack.prod.conf.js, webpack.prod.conf.coffee, webpack.prod.conf.ts, webpack.main.config.js, webpack.main.config.coffee, webpack.main.config.ts, webpack.mix.js, webpack.mix.coffee, webpack.mix.ts, webpack.plugins.js, webpack.plugins.coffee, webpack.plugins.ts, webpack.renderer.config.js, webpack.renderer.config.coffee, webpack.renderer.config.ts, webpack.rules.js, webpack.rules.coffee, webpack.rules.ts, webpack.test.conf.js, webpack.test.conf.coffee, webpack.test.conf.ts`

It immediately strikes me that a wildcard filter e.g.  ```webpack.*.js, webpack.*.coffee, webpack.*.ts``` would make life so much easier for code/documentation maintainers and us users alike ;)

Is there a technical constraint that dictates this rather verbose and rigid implementation?

Related: [https://github.com/vscode-icons/vscode-icons/issues/3203](https://github.com/vscode-icons/vscode-icons/issues/3203)

**Comment by JimiC** [comment]
If only `vscode` supported `wildcard`... we would have done that ages ago.

**Comment by robertohuertasm** [comment]
@JimiC is right. You can check [this issue](https://github.com/microsoft/vscode/issues/12493) that we opened in 2016. It seems that someone managed to create the feature 2 weeks ago. Not sure if that will get merged at some point or not. I'm watching that issue so I'll get notified if that's the case.

**Comment by noontz** [comment]
Thank you for the feedback.

**Comment by zm-cttae** [comment]
The feat needs reworking so it gets back to sanity.. for one we will not support 1 `*` for multiple dot segments nor chained wildcards like `webpack.*.*.js`

**Comment by JimiC** [comment]
@zm-cttae No rush. We have been waiting years for that. What's a few more months? The crucial part is to get something implemented that satisfies both parties (vscode devs & authors).
