### ISSUE TITLE
[Icon Request]: CRACO Configuration File

### ISSUE THREAD

**Issue by stag-enterprises** [vscode-icons/vscode-icons#3254]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

official craco logo converted to svg looks like this:
![craco logo ](https://user-images.githubusercontent.com/67909939/225161268-ca969e5a-3901-4bb4-90ac-5a75a7eac2ca.svg)

### Icon Information

CRACO supports the following files as configuration as of writing:
- `craco.config.ts`
- `craco.config.js`
- `craco.config.cjs`
- `.cracorc.ts`
- `.cracorc.js`
- `.cracorc`

### More Information:

CRACO is a tool that makes `create-react-app` more configurable.

**Comment by remcohaszing** [comment]
`create-react-app` is deprecated. However, projects may still use it. Do we want to support this @robertohuertasm?

**Comment by robertohuertasm** [comment]
If someone wants to contribute the icon, why not.
