### ISSUE TITLE
INOP Python folder icon

### ISSUE THREAD

**Issue by pabloqpacin** [vscode-icons/vscode-icons#3276]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

- The [**Python folder icon**](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#python) doesn't show up in the Explorer. 
- I have tried different names for the folder (*python, Python, PYTHON, py, ...*) but it always stays as a 'normal' folder.
- My installation is `v12.3.0`. I have disabled and enabled it back, but to no avail.
- Same behaviour in Linux, Windows and WSL.
- I believe it must be a **widespread** issue, not just my installation. I couldn't find any **reports** online tho so I really dunno.
- All other folder icons behave as expected.

**Comment by Zacky2613** [comment]
Hello, if you look at the table content information it shows that the folder name must be .venv, or .virtualenv not "python"

**Comment by pabloqpacin** [comment]
Wow ok thanks I didn't even expect that. Closing the issue.
