### ISSUE TITLE
[Icon Request]: tsconfig.[whatever].json

### ISSUE THREAD

**Issue by HarTstaRx** [vscode-icons/vscode-icons#3277]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

https://raw.githubusercontent.com/vscode-icons/vscode-icons/master/icons/file_type_tsconfig.svg

### Icon Information

This icon already exists inside vscode-icons, it's just not used for all tsconfig files.

### More Information:

When you have alternative names for tsconfig (like tsconfig.vite.json, tsconfig.custom.json, etc..) the icon suddenly changes from `file_type_tsconfig` to `file_type_json` or if you are creating the file vscode-icons just treats it like a json file, when it clearly it's not.

Can we get the tsconfig icon for all tsconfig files?

**Comment by HarTstaRx** [comment]
In the meantime, people can "override" this behaviour by adding this to their `settings.json`:
```
  "vsicons.associations.files": [
    { "icon": "tsconfig", "extensions": ["tsconfig.custom.json"], "filename": true, "format": "svg" }
  ]
```

**Comment by robertohuertasm** [comment]
@HarTstaRx that kind of thing is not supported yet by the vscode api. It's been requested for ages and hopefully it will make it to production soon. We'll implement that once the vscode api is there. Thanks!

**Comment by robertohuertasm** [comment]
@amitbeck as far as I know it has not been implemented yet. :(
