### ISSUE TITLE
[Icon Request]: 

### ISSUE THREAD

**Issue by FEDHIL** [vscode-icons/vscode-icons#3294]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [X] Folder Icon

### Icon Type

- [X] Extension
- [X] Filename
- [X] Language ID

### Original Icon

ffwefw

### Icon Information

efwwf

**Comment by remcohaszing** [comment]
This is spam.
