### ISSUE TITLE
Icons not displaying correctly...

### ISSUE THREAD

**Issue by bkj281** [vscode-icons/vscode-icons#3303]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

<img width="198" alt="image" src="https://github.com/vscode-icons/vscode-icons/assets/66874987/04938dac-9991-4c6f-8fb2-58af9ff2f7d6">

earlier in angular all this ".component", ".service", ".directive" (& any other might be possible to regarding angular) had different icons & that too with angular logo but now it is simply showing ".ts" icons...

**Comment by ctsstc** [comment]
I've noticed with `.module.ts` icons if I restart VSCode they'll display properly, but after some amount of time, or maybe relaunching a project they revert back to plain `.ts` icons.

<img width="192" alt="image" src="https://github.com/vscode-icons/vscode-icons/assets/416814/7892c0fc-418d-41f3-9e0a-e35f1a6aecc5">

Not sure if this is related though or needs its own ticket, or if there's a similar one out there yet.

Do your icons fix if you restart VSCode?

I tried switching my icon theme around thinking maybe that could fix it, but it does not. Neither does restarting the extension host.

**Comment by bkj281** [comment]
> I've noticed with `.module.ts` icons if I restart VSCode they'll display properly (they're supposed to show special NestJS icons), but after some amount of time, or maybe relaunching a project they revert back to plain `.ts` icons.
> 
> <img alt="image" width="192" src="https://user-images.githubusercontent.com/416814/261438096-7892c0fc-418d-41f3-9e0a-e35f1a6aecc5.png">
> Not sure if this is related though or needs its own ticket, or if there's a similar one out there yet.
> 
> Do your icons fix if you restart VSCode?
> 
> I tried switching my icon theme around thinking maybe that could fix it, but it does not. Neither does restarting the extension host.

No, it doesn't get fixed.

**Comment by jagomf** [comment]
Try to open command palette (Ctrl/Cmd + Shift + P) and select "Icons: Toggle Angular Preset".

**Comment by bkj281** [comment]
> Try to open command palette (Ctrl/Cmd + Shift + P) and select "Icons: Toggle Angular Preset".

Thanks, it worked!
