### ISSUE TITLE
.sql are gone

### ISSUE THREAD

**Issue by gunreio** [vscode-icons/vscode-icons#3346]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Icon for .sql are missing

**Comment by TurboCooler** [comment]
I am having the same issue

vscode-cons v12.8.0
vscode version August 2024 (version 1.93)
Windows 10 Enterprise

**Comment by JimiC** [comment]
Use a `vscode` extension that provides `sql` syntax highlighting.

**Comment by TurboCooler** [comment]
> Use a `vscode` extension that provides `sql` syntax highlighting.

That is not how it is supposed to work.  It had previously worked without needing an extension.  This is a recent bug either due to a VS Code change or a bug in the vscode-icons extension.

**Comment by JimiC** [comment]
If you believe so then please provide more info on your issue. Reporting that something just doesn't work, doesn't help us much.

**Comment by robertohuertasm** [comment]
@TurboCooler, @JimiC was right, you need to use a `sql` extension. The code is [here](https://github.com/vscode-icons/vscode-icons/blob/993d023c6357a378a1b14284c9542e233aea152b/src/iconsManifest/supportedExtensions.ts#L4608) and it has not been modified for years. 

The most probable cause is that you were already using a extension that supported `sql` without noticing it.

**Comment by JimiC** [comment]
Out of curiosity I look at vscode code base and found that `sql` is natively supported.
https://github.com/microsoft/vscode/blob/main/extensions/sql/package.json

Now if the icon is not showing the following cases may occur:
- The icon is missing from the icons folder
    - That means that the extensions integrity is corrupted and you will have to re-install it
- The icon is not missing from the icons folder
    - Probably another extension is messing things
    - Probably an icon customization in setting is messing things

**Comment by TurboCooler** [comment]
@JimiC  -- Uninstalling and reinstalling worked for me.  This is working now.
