### ISSUE TITLE
[Folder Name Request]

### ISSUE THREAD

**Issue by ghost** [vscode-icons/vscode-icons#3370]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

I've noticed that to have the Python folder icon, you have to name it ".venv" or ".virtualenv" and I was wondering why you can't just name it "Python" so that the icon applies.

**Comment by remcohaszing** [comment]
To me the issue is unclear and the author’s GitHub account has been deleted.
