### ISSUE TITLE
[Icon Request]: Terser

### ISSUE THREAD

**Issue by ari-party** [vscode-icons/vscode-icons#3398]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

![43502240](https://github.com/vscode-icons/vscode-icons/assets/49074962/6bc13653-00d3-4461-90d1-310e432bff63)
(converted to svg from png, source: [avatar](https://avatars.githubusercontent.com/u/43502240))

### Icon Information

Terser file icon for filenames such as `terser.config.js`

**Comment by remcohaszing** [comment]
Terser is great, but I’m not aware of it having a config file. Do you have a source for this?
