### ISSUE TITLE
graphql file extension is not showing the icon properly. [graphql]: 

### ISSUE THREAD

**Issue by navinkumaragilysys** [vscode-icons/vscode-icons#3441]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_graphql.svg

### Icon Information

I am not seeing the file icon for graphql

### More Information:

![image](https://github.com/vscode-icons/vscode-icons/assets/137290768/e809e9eb-1586-401c-9ce3-4eb9c20dbb46)

**Comment by dennohpeter** [comment]
works fine on my end  

<img width="338" alt="Screenshot 2024-04-17 at 01 25 46" src="https://github.com/vscode-icons/vscode-icons/assets/29105876/223c723d-3de3-42fa-9c1c-af31f7dfdeb0">

**Comment by remcohaszing** [comment]
The graphql icon is associated via the `graphql` language ID.

https://github.com/vscode-icons/vscode-icons/blob/75f297812e6a7f21c97e80cb950f71c47d0346a5/src/iconsManifest/supportedExtensions.ts#L2155-L2161

https://github.com/vscode-icons/vscode-icons/blob/75f297812e6a7f21c97e80cb950f71c47d0346a5/src/iconsManifest/languages.ts#L165

To see it, you need to install the GraphQL extension
