### ISSUE TITLE
[Icon Request]: Python 

### ISSUE THREAD

**Issue by AsadQurashi** [vscode-icons/vscode-icons#3466]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [X] Filename
- [X] Language ID

### Original Icon

not displaying python icon with .py

### Icon Information

Python Icon issue

**Comment by remcohaszing** [comment]
The Python icon is displayed for files using the `python` language ID, which by default includes `.py` files. You may have configured a custom language association using the VSCode setting `files.associations` or have an extension installed that overrides the file association.

**Comment by remcohaszing** [comment]
:100: agree

However, that extension doesn’t even register the `python` language ID. That’s registered by the builtin extension [Python Language Basics](https://github.com/microsoft/vscode/blob/main/extensions/python/package.json).

It’s unlikely, but it could be disabled. You can see by searching for `@builtin python` in the VSCode extensions view.

**Comment by JimiC** [comment]
> 💯 agree
> 
> However, that extension doesn’t even register the `python` language ID. That’s registered by the builtin extension [Python Language Basics](https://github.com/microsoft/vscode/blob/main/extensions/python/package.json).
> 
> It’s unlikely, but it could be disabled. You can see by searching for `@builtin python` in the VSCode extensions view.

You are totally right.
