### ISSUE TITLE
[Icon Request]: WXT

### ISSUE THREAD

**Issue by joealden** [vscode-icons/vscode-icons#3468]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

![logo](https://github.com/vscode-icons/vscode-icons/assets/10297243/b0b1b99c-e1a0-4c3d-a328-d70baa379d6f)

### Icon Information

For https://wxt.dev/ configs - applies to `wxt.config.js`/`wxt.config.ts`/`wxt.config.mts` files etc. (the same as Vite).

**Comment by remcohaszing** [comment]
This icon was added in #3480.
