### ISSUE TITLE
[Icon Request]: Reflex .web folder

### ISSUE THREAD

**Issue by Polygons1** [vscode-icons/vscode-icons#3487]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [ ] File Icon
- [X] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

![logo](https://github.com/vscode-icons/vscode-icons/assets/47899327/fe2f61d3-4852-439f-ace8-c8836c6dcc5d)

### Icon Information

the .web folder in a Reflex project where the Next.js app is located

**Comment by remcohaszing** [comment]
The name `.web` seems pretty generic. We already use a custom icon for the `web` folder, should we just use the same icon for `.web`?

**Comment by Polygons1** [comment]
sure
