### ISSUE TITLE
Vue icons do not reflect.

### ISSUE THREAD

**Issue by You-saku** [vscode-icons/vscode-icons#3498]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Type : **Bug** ?

When I open a Vue3 project.
Vue3 file don't reflect vscode-icons.

<img width="253" alt="スクリーンショット 2024-05-05 19 32 18" src="https://github.com/vscode-icons/vscode-icons/assets/53119949/ceb7446b-8e83-41af-840b-86230950c68d">

Is there anything additional settings ?

**Comment by remcohaszing** [comment]
This is likely, because you don’t have the [Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar) extension enabled.

**Comment by You-saku** [comment]
@remcohaszing 
Thanks!
I resolved this problem after install ```Vue - official``` extension
<img width="255" alt="スクリーンショット 2024-05-06 11 53 05" src="https://github.com/vscode-icons/vscode-icons/assets/53119949/0806f4a0-ccd6-4e17-a519-98c16e5525a5">
