### ISSUE TITLE
[Icon Request]: Add icon for safetensors

### ISSUE THREAD

**Issue by mayank31398** [vscode-icons/vscode-icons#3499]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

![safetensor logo](https://github.com/vscode-icons/vscode-icons/assets/32954280/311542cf-2bac-4ea7-9117-60ad33ce9f8f)

### Icon Information

Safetensors has become a prominent file format for saving tensors for deep learning.
This issue is for adding the safetensors icon to vscode-icons.

**Comment by SHADOW-LIGHTS** [comment]
i have finished adding and will create a pull request soon

**Comment by mayank31398** [comment]
hey this is awesome
