### ISSUE TITLE
why my react file doesn't show react icon 

### ISSUE THREAD

**Issue by Difkyear** [vscode-icons/vscode-icons#3501]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

 
<img width="217" alt="Screenshot 2024-05-07 094210" src="https://github.com/vscode-icons/vscode-icons/assets/55550427/16c3aa55-2f24-4987-ac6f-097cdea551cd">

**Comment by mrahmadhassankhan** [comment]
Can I see the code I'm willing to help

**Comment by remcohaszing** [comment]
The React icon is used for the `javascriptreact` language. The `.js` files use the `javascript` language. This is why you’re seeing the regular JavaScript icon, and not the React icon. This is also why syntax highlighting and other editor features don’t behave the way they should for you. It’s best to use the `.jsx` extension for JSX files.

**Comment by Difkyear** [comment]
> The React icon is used for the `javascriptreact` language. The `.js` files use the `javascript` language. This is why you’re seeing the regular JavaScript icon, and not the React icon. This is also why syntax highlighting and other editor features don’t behave the way they should for you. It’s best to use the `.jsx` extension for JSX files.

i'm trying to use .jsx extension , but it's the same results.
![image](https://github.com/vscode-icons/vscode-icons/assets/55550427/5149d1f8-bce0-4ac5-858c-32b94e3f24d5)

**Comment by Difkyear** [comment]
> Can I see the code I'm willing to help @Difkyear

that code it's just created automatically by using `npx create-react-app`,
so i don't think it's the code causing the problem

**Comment by Difkyear** [comment]
i'm solving this problem now, the reason cause react icon doesn't show up, it's because my vscode file association setting , i haven't associated .jsx extention to javascriptreact
![image](https://github.com/vscode-icons/vscode-icons/assets/55550427/14dd3f6f-e847-4007-8083-874f0f39d8f6)

**Comment by Difkyear** [comment]
i'm solving this problem now, the reason cause react icon doesn't show up, it's because my vscode file association setting , i haven't associated .jsx extention to javascriptreact
![image](https://github.com/vscode-icons/vscode-icons/assets/55550427/14dd3f6f-e847-4007-8083-874f0f39d8f6)
