### ISSUE TITLE
Custom icons are not being applied VSCode: 1.89.1

### ISSUE THREAD

**Issue by rhumbertgz** [vscode-icons/vscode-icons#3518]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Hello, 

I have been trying to set a custom icon for a particular config file (wws.json) without success.

I have followed the [Custom Icons](https://github.com/vscode-icons/vscode-icons/wiki/Custom) guide.

Here you can see some screenshots of my extension:

<img width="1201" alt="Screenshot 2024-06-02 at 23 59 11" src="https://github.com/vscode-icons/vscode-icons/assets/10393245/6b8b1e57-b89f-46b6-b67c-b4ec2ec6caa8">

<img width="1288" alt="Screenshot 2024-06-03 at 00 08 22" src="https://github.com/vscode-icons/vscode-icons/assets/10393245/f7167cbf-7cae-4c9c-b9b9-a1433309a14d">

I set the path to vsicons-custom-icons folder in both User and Workspace 
<img width="1566" alt="Screenshot 2024-06-03 at 00 11 04" src="https://github.com/vscode-icons/vscode-icons/assets/10393245/3c8c77f3-d664-4725-aa10-1fe4a998dbe5">

I don't see any problem on my setup, but it doesn't work :( 

Here is the icon that I'm trying to use

`<svg fill="#2a65cb" width="16" height="16" viewBox="0 0 134 134" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"><path d="M26.837,44.149c7.915,-13.866 22.857,-23.298 39.83,-23.298c17.294,0 32.481,9.793 40.27,24.088c-2.388,-0.434 -4.617,-0.682 -6.689,-0.744l-1.391,5.954c0.464,-0.066 0.956,-0.099 1.476,-0.099c2.425,-0 5.714,0.803 9.866,2.408c1.48,4.479 2.283,9.257 2.283,14.209c-0,1.616 -0.086,3.213 -0.252,4.785c-0.34,-0.775 -0.77,-1.499 -1.29,-2.172c-1.503,-1.947 -4.241,-4.077 -8.213,-6.391l-2.951,-1.706c-1.231,-0.72 -2.243,-1.377 -3.035,-1.971l-2.139,9.159c0.349,0.215 0.71,0.431 1.081,0.649l2.757,1.59c2.227,1.311 3.74,2.443 4.538,3.398c0.798,0.954 1.197,2.125 1.197,3.513c-0,1.755 -0.636,3.143 -1.907,4.164c-1.272,1.022 -3.012,1.533 -5.22,1.533c-1.716,0 -3.62,-0.285 -5.714,-0.854l-1.428,6.118c2.663,0.423 5.09,0.635 7.281,0.635c4.431,0 8.015,-0.888 10.75,-2.665c-7.439,15.344 -23.204,26.03 -41.27,26.03c-25.134,-0 -45.816,-20.682 -45.816,-45.815c0,-4.283 0.601,-8.437 1.721,-12.378l8.377,34.895l8.612,0l7.002,-30.885l6.68,30.885l10.547,0l7.002,-30.885l6.679,30.885l8.613,0l11.367,-45.035l-6.24,0l-8.32,32.772l-7.09,-32.772l-8.818,0l-7.243,28.531l-6.848,-28.531l-8.848,0l-7.47,32.955l-7.911,-32.955l-1.826,0Z" style="fill-rule:nonzero;"/></svg>`

Any suggestions?

**Comment by mateuszJS** [comment]
Custom icons stopped working, I believe with the new release two days ago.

**Comment by zakwear** [comment]
Same, custom icon config broke since update:

> "vsicons.associations.folders": [
>       { "icon": "api", "extensions": ["_api", "_apis"], "format": "svg" },
>       { "icon": "component", "extensions": ["_component", "_components"], "format": "svg" },
>       { "icon": "library", "extensions": ["_lib"], "format": "svg" },
>       { "icon": "hook", "extensions": ["_hook", "_hooks"], "format": "svg" },
>       { "icon": "helper", "extensions": ["_helper", "_helpers"], "format": "svg" },
>       { "icon": "services", "extensions": ["_service", "_services"], "format": "svg" },
>       { "icon": "style", "extensions": ["_style", "_styles"], "format": "svg" },
>       { "icon": "template", "extensions": ["_context", "_contexts"], "format": "svg" },
>       { "icon": "e2e", "extensions": ["_test", "_tests", "_journey", "_journeys"], "format": "svg" },
>       { "icon": "config", "extensions": ["_config", "_configs"], "format": "svg" },
>       { "icon": "interface", "extensions": ["_interface", "_interfaces"], "format": "svg" },
>       { "icon": "typings", "extensions": ["_type", "_types"], "format": "svg" },
>       { "icon": "module", "extensions": ["_module", "_modules"], "format": "svg" },
>       { "icon": "plugin", "extensions": ["_plugin", "_plugins"], "format": "svg" },
>       { "icon": "config", "extensions": ["config"], "format": "svg", "overrides": "src" },
>       { "icon": "package", "extensions": ["_feature", "_features"], "format": "svg" },
>       { "icon": "controller", "extensions": ["_consumer", "_consumers"], "format": "svg" },
>       { "icon": "nuget", "extensions": ["_container", "_containers"], "format": "svg" },
>       { "icon": "client", "extensions": ["_presenter", "_presenters"], "format": "svg" },
>       { "icon": "server", "extensions": ["_action", "_actions"], "format": "svg" },
>       { "icon": "redux", "extensions": ["_store", "_stores"], "format": "svg" },
>       { "icon": "composer", "extensions": ["_todo", "_todos", "todo", "todos"], "format": "svg" },
>       { "icon": "story", "extensions": ["_story", "_stories"], "format": "svg" }
>    ],
>    "vsicons.associations.files": [
>       { "icon": "testcafe", "extensions": ["fixture.ts", "fixtures.ts"], "filename": true, "format": "svg" },
>       { "icon": "todo", "extensions": ["todo.txt"], "filename": true, "format": "svg" },
>       { "icon": "dependencies", "extensions": [".route.ts"], "format": "svg" },
>       { "icon": "tuc", "extensions": [".model.ts"], "format": "svg" }
>    ],

**Comment by rhumbertgz** [comment]
Any workaround ideas how to fix it?

**Comment by robertohuertasm** [comment]
Hi, I've tested the feature, and it works for me. At least in Windows and WSL2. @rhumbertgz did you try to run the `Apply Icons Customization` command after applying your settings? Let me know if that helps.

**Comment by rhumbertgz** [comment]
Hello @robertohuertasm, yes I ran the `Apply Icons Customization` but It didn't work for me. I'm running VSCode 1.89.1 on MacOS 14.5 (23F79), VSCode-Icons: v12.8.0

**Comment by zakwear** [comment]
> Hello @robertohuertasm, yes I ran the `Apply Icons Customization` command, but It didn't work for me. I'm running VSCode 1.89.1 on MacOS 14.5 (23F79), VSCode-Icons: v12.8.0

Same, Apply Icons Customization didn't work on vsc@1.89.1, Ubuntu 22.04.4

**Comment by zakwear** [comment]
I reverted to previous release, muh icons are back.

How to control extension version in VSC:

https://stackoverflow.com/a/53755378/22389876

**Comment by robertohuertasm** [comment]
I tested this on my Mac, VSC 1.90 (they released today) and it seems to be working. At least with the default folder `/Users/<your_user>/Library/Application Support/<Code Folder>/User/vsicons-custom-icons`.

**Comment by robertohuertasm** [comment]
Tested now with `light` version and it also works for me. There must be something particular for your environments that I cannot reproduce.

**Comment by robertohuertasm** [comment]
Can you maybe use the `developers tools` to inspect the value of the (not shown) icon?

<img width="1047" alt="image" src="https://github.com/vscode-icons/vscode-icons/assets/696981/8585605b-54dd-42ca-8452-b6e3b45dbe2f">

At least, we will be able to know which is the path the extension is trying to load the icon from, and potentially understand what's going on.

**Comment by rhumbertgz** [comment]
Hi @robertohuertasm, first, thanks for your time. I updated VSCode and tried both custom and default location as your examples, but sadly for some reason it doesn't work. Using the dev-tools I see that custom icon is not override, it just uses the default one.

![image](https://github.com/vscode-icons/vscode-icons/assets/10393245/776fb60c-c348-4556-8c50-1371775fe53d)

**Comment by rhumbertgz** [comment]
I don't know what is wrong, but it seems to be something to my local setup. I even tried a new extension file "config.wws" and didn't work. I think I will leave it with the default icons.  I will closed this issue. Thanks for all your time.

**Comment by robertohuertasm** [comment]
@rhumbertgz just double checking.... Did you applied icon customization command after each change? that's really needed. If you don't do that, for sure this won't work.

**Comment by rhumbertgz** [comment]
Yes, I see that a new manifest was created in the console

![image](https://github.com/vscode-icons/vscode-icons/assets/10393245/38787a20-f3cc-4ca6-99fe-67671d8205aa)

My settings

![image](https://github.com/vscode-icons/vscode-icons/assets/10393245/fd4c6149-80d5-423c-9744-0cdecd662b76)

I double checked that icons theme is selected
![image](https://github.com/vscode-icons/vscode-icons/assets/10393245/0e973000-f5dc-41a7-b63e-b834e74a46da)

Custom path
![image](https://github.com/vscode-icons/vscode-icons/assets/10393245/ca7ee4fe-6296-49d8-9484-d173c9f348a4)

**Comment by rhumbertgz** [comment]
@robertohuertasm is there a way that I could check which custom icons are loaded?

**Comment by rhumbertgz** [comment]
Maybe could be useful to show some kind of log showing the loaded custom icons. For example using  `vscode.LogOutputChannel`

**Comment by robertohuertasm** [comment]
@rhumbertgz can you go to `.~/vscode/extensions/vscode-icons-team.vscode-icons-12.8.0/src/vsicons-icon-theme.json` and check there if the mapping has been correctly set? That is the manifest of the extension.

**Comment by rhumbertgz** [comment]
I checked, the path is there. I tried both default and local, no success although the path is updated. I even modified the path after I moved the icons to the "icons" folder and that neither work. Thanks again for your time!

**Comment by zakwear** [comment]
Latest VSC and vscode-icons work on ubuntu.
