### ISSUE TITLE
[Icon Request]: Update Firebase icon

### ISSUE THREAD

**Issue by remonke** [vscode-icons/vscode-icons#3521]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

![Logomark_Full Color](https://github.com/vscode-icons/vscode-icons/assets/102010617/03aa3fdb-8e6c-428a-8e0f-a336b69a5648)

### Icon Information

Firebase icon, used for .firebase and firestore.rules files.
The current icon doesn't use the latest logo.

**Comment by KingDarBoja** [comment]
Will take care of it ;)
