### ISSUE TITLE
`.db`, `.sqlite`, `.sqlite3` icons

### ISSUE THREAD

**Issue by Malix-Labs** [vscode-icons/vscode-icons#3539]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Despite being in the changelog:

https://github.com/vscode-icons/vscode-icons/blob/89a95757aed9a585f6f5256baa96f989b89a061c/CHANGELOG.md?plain=1#L1242

https://github.com/vscode-icons/vscode-icons/blob/89a95757aed9a585f6f5256baa96f989b89a061c/CHANGELOG.md?plain=1#L1401

`.db`, `.sqlite`, `.sqlite3` files doesn't have any icon currently, while `.sql` has one

#### Illustration

![image](https://github.com/vscode-icons/vscode-icons/assets/76160668/275f054a-4879-4af7-81f5-820941d971d8)

**Comment by Yizack** [comment]
It's weird because I actually see them!

![image](https://github.com/vscode-icons/vscode-icons/assets/16264115/dc1ddf0d-efa0-4a9f-a607-a934cfccc57b)

**Comment by Malix-off** [comment]
Do you have any theme enabled @Yizack ?

**Comment by SHADOW-LIGHTS** [comment]
I can see the icons too

**Comment by remcohaszing** [comment]
Your screenshot shows VSCode’s builtin fallback icons. I think you’re confusing vscode-icons with VSCode’s default default builtin icons. It’s an extension you need to install.

https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons
