### ISSUE TITLE
Biome icon is used for `biome.json` but not `biome.jsonc`

### ISSUE THREAD

**Issue by tylerlaprade** [vscode-icons/vscode-icons#3562]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

<img width="228" alt="image" src="https://github.com/user-attachments/assets/41bffd46-8670-4711-8bb7-3cd902cb0dcd">

Both of these are valid config files for Biome, so both should use the same icon.

Reference: https://biomejs.dev/guides/configure-biome

**Comment by remcohaszing** [comment]
This was fixed in #3517 and released in [v12.9.0](https://github.com/vscode-icons/vscode-icons/releases/tag/v12.9.0)
