### ISSUE TITLE
Why is this repo not under active maintainance anymore?

### ISSUE THREAD

**Issue by mayank31398** [vscode-icons/vscode-icons#3568]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

This repository houses one of my favorite extensions for vscode.
However, it seems like the development has stopped and no active icon additions or maintainence happening.

**Comment by robertohuertasm** [comment]
Hi @mayank31398, the repo is maintained. As soon as I have more time, I will review the currently opened PRs and create a release. Note that the last release was in June. Thanks for your concern!

**Comment by mayank31398** [comment]
Thanks @robertohuertasm
