### ISSUE TITLE
.razor files not detected as razor language files

### ISSUE THREAD

**Issue by JonathanLydall** [vscode-icons/vscode-icons#3587]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

Even though a language entry for razor exists:

<https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts#L333>

The manifest has not specified that `razor` is a valid file extension for them:

<https://github.com/vscode-icons/vscode-icons/blob/89a95757aed9a585f6f5256baa96f989b89a061c/src/iconsManifest/supportedExtensions.ts>

You can read more about .razor files here:

<https://learn.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-8.0>

**Comment by JimiC** [comment]
Whenever a file extension is mentioned in the `languages` manifest, it means that it's supported via a `vscode` extension.
I'm sure `microsoft` somehow is supporting those files.

**Comment by JonathanLydall** [comment]
Intriguing, it is working in VS Code, but I was looking to using this project's icon manifest not directly through VS Code's infrastructure and this particular file extension is the first I have come across (so far) where the file extension is not explicitly mentioned in either [languages.ts](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts) or [supportedExtensions.ts](https://github.com/vscode-icons/vscode-icons/blob/89a95757aed9a585f6f5256baa96f989b89a061c/src/iconsManifest/supportedExtensions.ts).

I presume it would be incorrect to assume a language name is also a file extension?

Would it be inappropriate to add this to the manifest as per my single line PR?

**Comment by JimiC** [comment]
Whenever a file extension can be supported via a `vscode` extension we implicitly support it in this way. Only file extensions that are not supported are added explicitly.

Any other case can be supported via the icon customization feature of this extension.
Start reading from [here](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning).

**Comment by JonathanLydall** [comment]
Closing as per conversation.
