### ISSUE TITLE
[Icon Request]: XAML Icon

### ISSUE THREAD

**Issue by gmcoates101** [vscode-icons/vscode-icons#3595]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

![xaml copy](https://github.com/user-attachments/assets/e1134d8d-71b4-46f1-bbfd-0a1ed5c81e40)

### Icon Information

XAML markup file for .NET Maui

**Comment by remcohaszing** [comment]
Duplicate of #3465
