### ISSUE TITLE
[Icon Request]: .git-blame-ignore-revs

### ISSUE THREAD

**Issue by davidsneighbour** [vscode-icons/vscode-icons#3600]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

The same icon we use for .gitignore

### Icon Information

https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

### More Information:

https://github.com/vscode-icons/vscode-icons/issues/3198 looks like it was working before. This is a file that defines what revisions to ignore in lists/histories.

**Comment by remcohaszing** [comment]
The icon is associated via a filename

https://github.com/vscode-icons/vscode-icons/blob/75f297812e6a7f21c97e80cb950f71c47d0346a5/src/iconsManifest/supportedExtensions.ts#L1971

Additionally, it’s associated via the `ignore` language ID.

Does this issue still exist? Is the file name lower case? What’s the language ID when you open the file?

**Comment by davidsneighbour** [comment]
It's working in the latest version. The language id was gitignore.
