### ISSUE TITLE
[Icon Request]: `postcss.config.mjs` and `patches` folder

### ISSUE THREAD

**Issue by AnYiEE** [vscode-icons/vscode-icons#3601]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [X] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

`postcss.config.mjs`: Simply reuse the `postcss.config.js` icon.

`patches` folder: Maybe a new icon needs to be created? I am not sure, but there is an icon for `*.patch` file.

### Icon Information

`postcss.config.js` has the icon, but `postcss.config.mjs` does not.

The `patches` folder is automatically generated after running `pnpm patch <package_name>`.

**Comment by AnYiEE** [comment]
Other issues related to the `patches` folder: https://github.com/vscode-icons/vscode-icons/issues/2992

**Comment by NeViNez** [comment]
also need to link `postcss.confg.mts` with `postcssconfig` icon to handle cases, when `postcss-load-config` and typescript for typing config object are used
