### ISSUE TITLE
How to keep using the Blue CSS3 icon Please

### ISSUE THREAD

**Issue by CRIMSON-CORP** [vscode-icons/vscode-icons#3651]
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Information:

i want to be able to continue using the Blue style of the CSS file icon, i dont like this purple type in the new update, how can i roll back only the CSS?

**Comment by robertohuertasm** [comment]
See https://github.com/vscode-icons/vscode-icons/issues/3643. The change was done because the css official logo has changed. We're considering bringing back the old icon as an option (through custom icons) in the future release.

**Comment by CRIMSON-CORP** [comment]
Thank you @robertohuertasm
