### ISSUE TITLE
Convert all icons to svg

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#380]
Photoshop is able to do it natively. So as a first step with a saved action we'll be able to generate a complete svg set easily. We should then revisit all the icons in order to provide the best quality for all of them.

Progress tracker: https://github.com/JimiC/vscode-icons-svg/issues

**Comment by jens1o** [comment]
Great idea. I'll help you.

**Comment by iRoachie** [comment]
Is there like I checklist where we can see what's done and what's not?

**Comment by jens1o** [comment]
@iRoachie Great idea. We could use the markdown checkboxes(use ```[ ]```)

**Comment by robertohuertasm** [comment]
I've started to deploy svg icons. I've created an `icons.ai` file as a template for you to use when creating new icons.

All you have to do now is to add the attribute `svg: true` to the supported extensions entry of your choice.

**Comment by jens1o** [comment]
Hmm. I don't have these Adobe Products 😢

**Comment by iRoachie** [comment]
SVG template then?

**Comment by robertohuertasm** [comment]
I guess there should be other open source software capable of editing .ai 
https://inkscape.org/en/

**Comment by JimiC** [comment]
**Update**
Just FYI. I'm working on this issue but the progress is slower than I expected, as I have to recreate the icons in some cases and do a lot of tweaking in others.

**Comment by JimiC** [comment]
The progress can be monitored via [this issue in my fork](https://github.com/JimiC/vscode-icons/issues/1).
And a preview of the SVG icons can be found [here](https://github.com/JimiC/vscode-icons/tree/PNG2SVG/icons/SVG).

**Comment by robertohuertasm** [comment]
@JimiC you're the man!!! Many thanks for your hard work!

**Comment by JimiC** [comment]
@robertohuertasm 
Just A quick question. Do we care about the size of the SVG logo?
Should it still be 32x32? I know it's irrelevant, as it's an SVG, so it scales, but just for consistency.
Or should the main purpose be the size of the SVG file?

**Comment by robertohuertasm** [comment]
Hi @JimiC, I certainly created `icons.ai` template using a 32x32 canvas but as you said, this doesn't really matter in our case. It's ok for me if the SVGs are in different sizes as long as they keep the same proportion and are rendered with a white space around them. I mean, they're not intended to take all the space that vscode provides and keep a padding. In our case, the padding is a 2px padding, taking into account that we're building the svg in a 32x32 canvas. That means that any other chosen proportion should keep the average of a 12.5% of padding.
![svg_build](https://cloud.githubusercontent.com/assets/696981/20465400/a26a5a7c-af5c-11e6-9abd-73e09426ef10.PNG)

**Comment by JimiC** [comment]
@robertohuertasm As I'm getting familiar with the Illustrator tool, I would like to suggest to replace the `icons.ai` file (which has the icons in a invisible stack), with an [`icon-per-artboard.ai`](https://github.com/JimiC/vscode-icons/tree/PNG2SVG/images) file.

This has the following benefits:
- Smaller file
- Ability to have all icons visible
- Export all icons on single click (File > Export > Export for Screens, Select tab `Artboards`)

Thoughts?

**Comment by robertohuertasm** [comment]
It seems ok to me. I created it just as a guide not really as an icon repository. Your suggestion makes perfect sense. :wink:

**Comment by JimiC** [comment]
@robertohuertasm What are the padding rules for folders?

**Comment by JimiC** [comment]
This is how they look inside the editor:

**100%**
***Closed***
![screenshot - 27_11_2016 16_44_10](https://cloud.githubusercontent.com/assets/1716442/20649146/de37c350-b4c0-11e6-942c-42d2c748d45d.png)
***Opened***
![screenshot - 27_11_2016 16_44_31](https://cloud.githubusercontent.com/assets/1716442/20649149/eb6a1fd2-b4c0-11e6-97bc-a18f1c68d08b.png)

**150%**
***Closed***
![screenshot - 27_11_2016 16_42_45](https://cloud.githubusercontent.com/assets/1716442/20649153/f7174a30-b4c0-11e6-983f-4b45047c9079.png)
***Opened***
![screenshot - 27_11_2016 16_43_27](https://cloud.githubusercontent.com/assets/1716442/20649156/000c5ae0-b4c1-11e6-9de1-2cdab569e339.png)

**Comment by JimiC** [comment]
After consulting my sister (which is a fashion designer, ad knows about colors), she proposed:

![screenshot - 27_11_2016 18_20_56](https://cloud.githubusercontent.com/assets/1716442/20649725/67adf818-b4ce-11e6-9b4e-eac2d5792ef1.png)

**Comment by robertohuertasm** [comment]
Hi @JimiC,

first of all, thanks again for your great work! 😄 

I would like to notice something prior to any discussion. The other day we were talking about removing the `.ai file with the layers`. I'm thinking that maybe we don't need it at all as `illustrator` or `inkscape` for that matter support direct `svg` edition. This way we wouldn't have to keep a record of propietary `.ai files` duplicating the `svg files`. What do you think of this?

The other thing I would like to comment is contrast in folders.  For me the idea is that the color of the folder must be the main colour not just a mere contrast of the icon. The reason behind this is that the icon, in most of the cases, is not the first thing you will see. You will recognize the folder because it's associated to a characteristic colour. In the case of Amazon be it the yellowish orange that they use in the case of VSCode its characteristic blue. 

In this case I would make the folder orange and use white for the cloud or just the colour from this black background version I post below:
![image](https://cloud.githubusercontent.com/assets/696981/20651482/91ec5896-b4e6-11e6-910a-fcc696b9596b.png)

That's the way I've created the folders, I'm not saying it's the best, of course, but changing this would require to change all the folders and I'm not really convinced of any reason to do that. We could argue about colour theory and lots of things but I really value the fact that the folder it's just an extension of the icon and so they share colours and are only separated by a gradient stroke, a small change in the tonality or a contrast colour if the corporative colours of the logo allows it. If we can find something that pleases us all, let's do it, but I do have a strong opinion on this and I would have to be really convinced in order to change.

Please, take all my opinions as opinions, nothing personal. When it comes to this kind of decisions which involve subjectivity I know it can be difficult or impossible to reason about and to find points of  union between different positions. I don't mean to disrespect the work or the opinions of anyone of you. That's for granted. I'm always happy to openly discuss with you 😉

**Comment by JimiC** [comment]
1. Yes, the `.ai` file can be removed. It's just convenient for me to keep it, and have all icons at a glance, until I'm done converting all icons.

2. No offence taken on the folder colors. As you can see, I'm discussing my ideas with you, as I can't be in your head to know the guidelines of the folders coloring. It would be nice if those guidelines, for the icons and the folders, would be documented, so anyone that comes along and wants to contribute, knows what to do.
Now that you made it clear, I know what to do.

**Comment by robertohuertasm** [comment]
@JimiC +1 to make some document about the style guides. I take note!
I would like to stress how happy I am with you collaborating with the project and the high value I have for your opinions and your work!! 😁

**Comment by JimiC** [comment]
@robertohuertasm So what about the size of the embedded icon? Are you OK with the size of the later example?
>The folders obey the 2px padding rule (sort of, as the opened folder gets a little outside), but the icon is padded with 1px from the bottom right corner.
Btw, I chose the size of the embedded icon to always be no more than 24x24 pixels.

**Comment by robertohuertasm** [comment]
@JimiC I'm ok with that. To be honest, I haven't thought about it seriously while doing the folder icons. I just  more or less tried to keep the same proportions but always subjected to the shape of the icon. See, for instance, the `less folder`. I was force to expand the logo through all the folder length so it could be visible.

**Comment by JimiC** [comment]
@robertohuertasm I saw it and that's what made me decide to go with no more than 24x24.

**Comment by JimiC** [comment]
The progress list and been moved to [#1](https://github.com/JimiC/vscode-icons-svg/issues/1)

**Comment by ginfuru** [comment]
@robertohuertasm Should I create a pull request for the icon's I've converted to SVG?

**Comment by jens1o** [comment]
Yeah, go for it @ginfuru !

**Comment by JimiC** [comment]
Guys, I'm starting to work on the folders again, and I think I found a golden rule for them.

How does those look?

![screenshot - 22_12_2016 22_08_32](https://cloud.githubusercontent.com/assets/1716442/21438780/6fe18f62-c893-11e6-8f77-0e9bb8648822.png)

**Comment by jens1o** [comment]
AWESOME! Go on further, it's nice!

**Comment by JimiC** [comment]
**Update**
![screenshot - 22_12_2016 23_33_05](https://cloud.githubusercontent.com/assets/1716442/21441099/14b75246-c89f-11e6-8ade-07d22d394f7f.png)

**Comment by robertohuertasm** [comment]
@JimiC great work man! I like the second version of `vscode folder`!

**Comment by robertohuertasm** [comment]
>P.S. The background folder has diff color than the default. The way I color it follows this simple principal:
Pick a color from the front icon.
Color the folder keeping the tone of the default.

@JimiC, what do you mean with the `default`?

For what I see in the creation of `vscode` icon, this seems the process you follow to me:
1. You take a color from the icon.
2. Use it a little bit lighter in the closed folder.
3. Even lighter for opened folder.

Maybe is the same that you said before but I didn't really grasp the process from your explanation.

Cool, cool folder icons @JimiC! Really great work! Hoping to integrate them for the Christmas release!!

**Comment by JimiC** [comment]
The `default` folders are those brown ones. The closed one is a little bit darker than the open one. They have a diff in tone. So I keep this diff in the colored ones too and using as base color one color of the front icon. I\ll explain everything in detail in the guide.

**Comment by robertohuertasm** [comment]
Are you using Illustrator or Inkscape?

**Comment by JimiC** [comment]
I use Illustrator. Inkscape doesn't help me so much with the icons. It requires some extra work to produce the same outcome as Illustrator does. Still though I'll try to cover both software in the guide.

**Comment by JimiC** [comment]
Guys, I need your help. I'm trying to decide which image pair looks best.

![screenshot - 26_12_2016 21_32_11](https://cloud.githubusercontent.com/assets/1716442/21485865/eda5fcea-cbb2-11e6-959e-1e75bf15fb4d.png)

Thoughts?

**Comment by robertohuertasm** [comment]
I personally would prefer not to have the black border in the test tube but a colored one.  But that's no surprise as they are the ones that we currently have 😁 
![file_type_testjs 2x](https://cloud.githubusercontent.com/assets/696981/21486588/318f1a1e-cbb7-11e6-8647-8977a371bb67.png)
![file_type_testts 2x](https://cloud.githubusercontent.com/assets/696981/21486587/2a1e9430-cbb7-11e6-8036-cd7dbc8c25f8.png)

The main reason behind this is that the black border may not be noticed in the dark themes.

**Comment by JimiC** [comment]
@robertohuertasm You mean something like this?

![screenshot - 26_12_2016 23_29_37](https://cloud.githubusercontent.com/assets/1716442/21486777/3a2e5fb6-cbc3-11e6-8fdb-85af75a41275.png)

**Comment by JimiC** [comment]
So here are the rest of the folder images.

![screenshot - 26_12_2016 23_36_29](https://cloud.githubusercontent.com/assets/1716442/21486838/2fff9fcc-cbc4-11e6-8b4b-de5a0cb71f93.png)

Awaiting your input.

**Comment by robertohuertasm** [comment]
Yes, but again, the problem here is that in the JS one the font and the background is too similar. My solution was to use a black border for the fonts and making the background yellow darker, which will help separating the background while making the font limits clearer in lighter themes.

**Comment by JimiC** [comment]
Now that we can support `light` versions of an image I don't think our concern is about light themes in this case. I could make a `light` version with the JS in black.(?)

**Comment by robertohuertasm** [comment]
@JimiC I like your folder proposal very much! The only thing that caught my eye was why you've decided to use green for `less` folder instead of blue? I love these folder icons! Congratulations!

**Comment by JimiC** [comment]
The guideline I use to chose the folder color turned the folder green. Will have a look at it again.

**Comment by robertohuertasm** [comment]
You're right about light versions. I'm still not used to think about it. 😜
Then the only thing pending is the fonts melting with the background. I would say it won't be easily readable but it should have to be tested. Maybe it works.

**Comment by JimiC** [comment]
@robertohuertasm It turned out that the color of `less` is `gradient` and messed with me.

Now that I figure it out, here are the new versions.

![screenshot - 27_12_2016 00_00_44](https://cloud.githubusercontent.com/assets/1716442/21487005/b3411ebc-cbc7-11e6-9928-e29843b29e00.png)

Are we OK with those?

**Comment by JimiC** [comment]
All icons that we have converted are available at https://github.com/JimiC/vscode-icons-svg/tree/master/icons. @robertohuertasm if you have the time please test the `testjs` image and let me know.

**Comment by robertohuertasm** [comment]
Love the latest `less` color! 
I'll try to test the icons myself and let you know. Thanks @JimiC!

**Comment by robertohuertasm** [comment]
![original](https://cloud.githubusercontent.com/assets/696981/21487388/083f2760-cbc8-11e6-89e8-eb2f493bb5b8.PNG)
![new](https://cloud.githubusercontent.com/assets/696981/21487387/081ccbde-cbc8-11e6-8dea-0ae72e0aa92d.PNG)

I think the old ones work better.

**Comment by jens1o** [comment]
Yeah, I agree with you.

**Comment by ginfuru** [comment]
All I could use some feed back for the `erb'
Old version has HTML5 ![old version](https://raw.githubusercontent.com/robertohuertasm/vscode-icons/master/icons/file_type_erb%402x.png)
I'm proposing a more flat version: ![icons](http://rdm.d.pr/dL2E+)

**Comment by JimiC** [comment]
Guys I think this is it.
 
![screenshot - 27_12_2016 18_43_24](https://cloud.githubusercontent.com/assets/1716442/21507516/aad0c5b0-cc81-11e6-9a21-15da7ddbef09.png)

**Comment by ginfuru** [comment]
@JimiC The closed folder is really hard for me to see personally. Maybe if you add a slight dark brown drop shadow to the test tude it might stand out more?

**Comment by JimiC** [comment]
Originally the red tube was brighter (see above) but after @robertohuertasm comments I made it darken to align with the dark version of the simple icons. After all the original is also dark.

**Comment by JimiC** [comment]
@ginfuru Regarding the `erb` I would choose the tilted version.

**Comment by robertohuertasm** [comment]
![new](https://cloud.githubusercontent.com/assets/696981/21507939/f38d48b4-cc7c-11e6-84ed-7c12891e41fd.png)
![old](https://cloud.githubusercontent.com/assets/696981/21507940/f3a287f6-cc7c-11e6-85ac-f19cefd7f9d6.png)
![closed](https://cloud.githubusercontent.com/assets/696981/21508020/b1208a26-cc7d-11e6-92e7-7bec56d2b650.png)
![open](https://cloud.githubusercontent.com/assets/696981/21508021/b121c436-cc7d-11e6-8512-69b3602d36ef.png)

I agree with @ginfuru about the test folder.  I would make the folder more red and the tube lighter. 
Regarding the test icons I still like more the original ones. The fonts in the new ones are too big for my taste. I thing the important thing here is the icon, not the font, which exists just to reinforce what the color indicates (js or ts).

**Comment by robertohuertasm** [comment]
![closed-src](https://cloud.githubusercontent.com/assets/696981/21508181/20429fd8-cc7f-11e6-97b1-3fa27499ed6b.png)
![src-closed](https://cloud.githubusercontent.com/assets/696981/21508183/2044542c-cc7f-11e6-9605-20115bb0b2f9.png)
![src-open](https://cloud.githubusercontent.com/assets/696981/21508182/204371c4-cc7f-11e6-9d75-ee5f9cb8c515.png)
![src-open-old](https://cloud.githubusercontent.com/assets/696981/21508184/2044b1e2-cc7f-11e6-9b95-20320bc6354b.png)

I think the new `src` folder doesn't work. I barely can distinguish the icon. We need more contrast.

**Comment by jens1o** [comment]
Well, I'm fine with the old one. Can't we convert it to svg without any changes?

**Comment by robertohuertasm** [comment]
In general I think that we don't have to be constraint by our own guidelines when it's clear that the resulting color combination is not working. Design is not as mechanical as we would desire.

**Comment by JimiC** [comment]
Regarding the fonts, I'm considering removing them completely. How about that? After all the color wires the brain, right? 

Regarding the 'test' folder I could replicate the contrast of the original.

Regarding the 'source' folder, I still haven't done any visual testing, so I mostly rely on your feedback. Yes, we can keep the original colors but in my eyes the front icon got lost in the folder's color. Will try to find a more suitable color combination.

**Comment by robertohuertasm** [comment]
I agree with @jens1o . I don't want to sound like I'm not open to suggestions but I think the old icons worked well like they were (I'm referring here mainly to the `test` ones) and I don't see any reason to change them drastically.

**Comment by jens1o** [comment]
> Yes, we can keep the original colors but in my eyes the front icon got lost in the folder's color. 
I don't agree on that. I'm using this folder all the time in my php projects, so I kinda love it like it is. And I know exactly on a look that this is the source folder.

**Comment by JimiC** [comment]
@jens1o You brain is wired to the color. There is no other folder that is dark green. The point here is to make also the front icon noticeable.

**Comment by JimiC** [comment]
Another try

![screenshot - 28_12_2016 10_54_55](https://cloud.githubusercontent.com/assets/1716442/21518021/232fc2ee-ccec-11e6-99b2-da9df763eb3d.png)

*
`spec` The original icons with original color converted to SVG.
`spec-1` No front icon, colored using the official color.
`spec-2` No font icon, colored using the original color.

Thoughts?

**Comment by JimiC** [comment]
Side by side comparison

![screenshot - 28_12_2016 13_50_24](https://cloud.githubusercontent.com/assets/1716442/21521326/a2b20a28-cd04-11e6-8c2c-e98775bb98ba.png)

`test` Original icon converted to SVG.
`test2` Proposed icon.

Personally I believe the proposed icon isn't that bad.

**Comment by jens1o** [comment]
I would prefer the first one. I don't like it when there is much contrast.

**Comment by JimiC** [comment]
@jens1o Are you referring to the file of folder icon?

**Comment by jens1o** [comment]
Yes, I do.

**Comment by JimiC** [comment]
@jens1o Sorry I meant `or`.

**Comment by JimiC** [comment]
I reworked the `src` folder. I believe these look much much better.

![screenshot - 28_12_2016 15_14_24](https://cloud.githubusercontent.com/assets/1716442/21522686/782cdb46-cd10-11e6-9fc8-d4030b7a2740.png)

![screenshot - 28_12_2016 15_16_17](https://cloud.githubusercontent.com/assets/1716442/21522708/a1bfd116-cd10-11e6-823c-a6e118f594c0.png)

**Comment by robertohuertasm** [comment]
Let's see. This is how I see it:
1. Test icons: I would go with older icons but official colors.
2. Test folder: I like the first one.
3. Source folder: I like it but I'm not still convinced about the color of the icon, as in the dark theme the low part of the icon gets confused with the background. (I haven't had the time to test it myself in my editor so my comment refers strictly to what I see in the picture you past).

**Comment by JimiC** [comment]
@robertohuertasm I haven't uploaded the icons on my repo yet so they aren't available.
95% of the front icon has the folder as background, so I don't think it's much of an issue.
In order for the front icon to be more visible it need to be thinker so it occupies more space. This means that if this icon gets rejected we will have to change the front icon to something else with more color mass.

**Comment by JimiC** [comment]
![screenshot - 30_12_2016 01_17_53](https://cloud.githubusercontent.com/assets/1716442/21556919/d453298e-ce2d-11e6-8e77-f15146c8312c.png)

* Left: old
* Right: new

**Comment by robertohuertasm** [comment]
@JimiC sorry to be so picky but doesn't the icon of the `source` folder take too much space compared to the rest of the new folders that you've been creating?

I like it but it seems to me that the icon takes the same space as the folder.

**Comment by JimiC** [comment]
![screenshot - 30_12_2016 12_28_06](https://cloud.githubusercontent.com/assets/1716442/21563471/76b1a0b8-ce8b-11e6-95f2-4d3104a21eba.png)

* Left: old
* Right: new

@robertohuertasm @jens1o In order to been with this and move forward, are we OK with those?

**Comment by robertohuertasm** [comment]
This seems ok to me! Many thanks @JimiC 👍

**Comment by jens1o** [comment]
Seems okey to me, too. Thank you for holding out my wishes with patience. 😉

**Comment by JimiC** [comment]
Which of the two do you prefer as first icon for `json`?

![screenshot - 08_01_2017 16_43_41](https://cloud.githubusercontent.com/assets/1716442/21750753/413cde90-d5c3-11e6-9178-13cfdc5603d2.png)
![screenshot - 08_01_2017 16_42_47](https://cloud.githubusercontent.com/assets/1716442/21750754/46153d04-d5c3-11e6-8a3a-fd6e6e0e2ca5.png)

**Comment by jens1o** [comment]
As first one, the former. But I would love to have the current icon as default. Maybe many user worries about this icon?

**Comment by JimiC** [comment]
The second is a combination of what we have now and the official logo. I think that icon has the potential to please everyone.

**Comment by robertohuertasm** [comment]
I also prefer the former. What icon is that? Is the official one? I've never seen it.

**Comment by jens1o** [comment]
I've also never seen it... I don't think other would recognize that this should recognize json.

**Comment by JimiC** [comment]
Guys, http://json.org/

**Comment by robertohuertasm** [comment]
I think I would go:
1. Former icon.
2. Official icon.
3. Optional toggle preset.

Although the icon is the official one, I think people is really used to the former one. That is the icon used in most editors so users are really used to it. I guess that's why you worked in the second alternative but I don't like it much because I don't think the icon really brings something new to the table.

**Comment by JimiC** [comment]
Let me get this straight. By former you mean ![screenshot - 08_01_2017 16_42_47](https://cloud.githubusercontent.com/assets/1716442/21750754/46153d04-d5c3-11e6-8a3a-fd6e6e0e2ca5.png) without the official logo in it? Cause I believe that this icon is a good introduction to the official logo.

**Comment by robertohuertasm** [comment]
Yes, former would be that one without the logo inside. I've already thought about it but I guess that I'm not really convinced. I would rather go with the official one than with this hybrid one. Let me think about it. For sure it won't be an easy change. 😉

**Comment by JimiC** [comment]
The thing that most editors use the former is a good reason for me to go with the hybrid (as you call it). We innovate!

Never the less I could go with:
1. Former
2. Official
3. Hybrid

Also, I can add a toggle command to switch between Former and Official.

**Comment by robertohuertasm** [comment]
Do you have the icons in your repo?

**Comment by JimiC** [comment]
Yes.

**Comment by robertohuertasm** [comment]
After testing the icons and thinking a little bit more about this, I think I'm still considering more valuable the fact that the icon is easily recognizable by the users than the fact of being the official one. So:

1. Former
2. Official
3. Hybrid
4. Toogle (optional)

**Comment by JimiC** [comment]
Exactly what I thought the decision would be. I have the exact order already in place. I'm having though a small problem with the test. Once I have it resolved I'll do the PR.

**Comment by JimiC** [comment]
# ICON ALERT #
[MOST WANTED ICONS](https://github.com/JimiC/vscode-icons-svg/issues/4)

**Comment by JimiC** [comment]
Time for another voting. This time it's about `*proj` icons.

# Concept 1
![screenshot - 22_01_2017 13_46_30](https://cloud.githubusercontent.com/assets/1716442/22182383/fb6ef444-e0ac-11e6-9344-044f719699b2.png)
![screenshot - 22_01_2017 13_46_54](https://cloud.githubusercontent.com/assets/1716442/22182384/003e378c-e0ad-11e6-910d-907e409aff7c.png)

Original colored VS icon with project logo on the lower left (project icon max-height: 15px).

# Concept 2
![screenshot - 22_01_2017 13_56_45](https://cloud.githubusercontent.com/assets/1716442/22182387/0eff7268-e0ad-11e6-98d6-daea25cbb4f4.png)
![screenshot - 22_01_2017 13_57_01](https://cloud.githubusercontent.com/assets/1716442/22182389/131c0320-e0ad-11e6-9c24-b43be7c72527.png)

VS icon colored according to project icon color (no lower left icon).

# Concept 3
![screenshot - 22_01_2017 14_11_08](https://cloud.githubusercontent.com/assets/1716442/22182392/1cc6ec78-e0ad-11e6-865e-45511e7a5f90.png)
![screenshot - 22_01_2017 14_11_28](https://cloud.githubusercontent.com/assets/1716442/22182395/22aa346a-e0ad-11e6-8b1d-913d453188d2.png)

VS icon contrasted colored according to project icon color, with project logo on the lower left (project icon max-height: 15px).

**Comment by robertohuertasm** [comment]
I like concept 1

**Comment by Daylien** [comment]
My vote goes to concept 2.

**Comment by JimiC** [comment]
I also like concept 2 as they are clearer to the eye.

**Comment by jens1o** [comment]
My vote goes also to concept 2.

**Comment by robertohuertasm** [comment]
Concept 2 has several issues:
1. Assumes that the user knows the color correlation between the kind of project, which may not be true.
2. `fs` and `cs` projects use the icon of `vscode` and `vscode insiders` respectively. 

I agree that Concept 1 is less clear in graphical terms but that's mainly due to the fact that the `subicon` indicating the type of the project would need some kind of border sorrunding it in order to make it more readable. For me, this is the concept that makes more sense because all of these projects belong to `visual studio`.  Take into account that Microsoft has decided to use a different color for each one of the `visual studio` flavors, thus, changing the color of the main logo can induce to a semantic confusion.

**Comment by JimiC** [comment]
1. The user does know the color correlation. He's using `VS` after all. Only `fs` and `njs` are off as it's purple and red-ish in `VS`. But I think that we aren't following the `VS` coloring to closely.
2. Not true. Colors aren't the same.

Your only valid point is `MS` changing colors for various flavors of the same version or even for diff versions.

I tried the bordering and it doesn't look good. I'll give it another shot, though.

**Comment by jens1o** [comment]
> Assumes that the user knows the color correlation between the kind of project, which may not be true.

In daily-production-setup, I don't see the point. I still know that Visual Studio for Windows Phone is red, like Visual Basic is dark-blue. I'm searching for them explictly, so in fact it's pretty nice that they have the colors.

> fs and cs projects use the icon of vscode and vscode insiders, respectively, which is confusing.

I don't think the colors are exact the same?

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/22185240/42640c6a-e0e2-11e6-9b9c-d7d1d7910106.png)
@jens1o, if not the same, they are almost the same. The average user (me) would find it the same. Not everybody has that kind of color sharp perception.

On the other hand, you said Visual Studio for Windows Phone is red but I've been programming for Windows Phone for years and never seen that kind of association. I'm curious to know where you've seen that. This is just to make an example of someone that has been exposed to a determinate tech and may not be aware of latest color correlations.

Finally, the latest point is maybe the clearer one. We would be subverting the meaning that `Microsoft` has given to the coloring: `Change of color` equals to `different IDE version` and not `different kind of project`.

**Comment by JimiC** [comment]
> We would be subverting the meaning that Microsoft has given to the coloring: Change of color equals to different IDE version and not different kind of project.

This is your strongest point which makes me wonna re-design the icons.

**Comment by jens1o** [comment]
![image](https://cloud.githubusercontent.com/assets/11234139/22185342/1846b8e0-e0e4-11e6-80e3-2bb29fbf7031.png)
Okey, well it isn't red.

The last point is a good point...

**Comment by robertohuertasm** [comment]
Please guys, don't get me wrong. I like the colorful approach but I'd also like to be consistent with the graphical semantics that `Microsoft` has stablished for their IDE logos. I'm trying to thing of some solution that could bring more colors to the table while keeping the main icon purple but obviously it all comes to the `sub-icon` (c#, vb...)

**Comment by JimiC** [comment]
Take 4.

![screenshot - 23_01_2017 00_12_47](https://cloud.githubusercontent.com/assets/1716442/22186610/d8b0e396-e100-11e6-9c18-a9ccd229ca11.png)
![screenshot - 23_01_2017 00_13_04](https://cloud.githubusercontent.com/assets/1716442/22186611/ded131a4-e100-11e6-8acd-4b08298c0c12.png)

**Comment by robertohuertasm** [comment]
I like it! But that's not a surprise given my previous statements 😉

**Comment by JimiC** [comment]
Here is another issue. I've been searching to find an `svg` version for  `storyboard` and `xib` but can't find any.
I would like to suggest to replace the `storyboard` and `xib` icons to a generic on I found [here]( https://www.iconfinder.com/icons/1099097/build_develop_developing_folder_xcode_icon#size=512).

**Comment by JimiC** [comment]
@robertohuertasm @jens1o I would really like an answer to the above suggestions as we are very close to finishing the icons conversion.

**Comment by jens1o** [comment]
I'm fine with your suggestions.

**Comment by robertohuertasm** [comment]
1. I would rather keep the ones that we have now. I'll convert them to `svg` if necessary.
2. I'm ok with this icon for `.master`, `layout.html` and `*.layout.html` (I guess we should also cover the `.htm` version. I'm not fond of assimilating the `index.html` to the same icon of a `layout page`.

**Comment by JimiC** [comment]
For:
1. OK, then. The conversion is easy to be done (I could use elements from the icon I found).
2. Will cover also `.htm`, and exclude `index.html`.
