### ISSUE TITLE
Add folder icons for different application folders

### ISSUE THREAD

**Issue by amit-srivastava-007** [vscode-icons/vscode-icons#436]
Hi 
This is really nice and I like it very much.
Now a days when we are working with standard folder structures for Angular and Ember Apps it will be nice to have folder icons for following folders as well

- /app
- /components
- /models
- /routes
- /serializers
- /controllers
- /helpers
- /initializers
- /services
- /templates

Regards

**Comment by jens1o** [comment]
The only problem is, that these folder names aren't used by angular only... Many PHP Frameworks are using this structure too...

**Comment by amit-srivastava-007** [comment]
Even though these same folder names are being used by many languages but there purpose are moreover or completely same so such icon can be suggested that serve the purpose by name and not by specific language

**Comment by JimiC** [comment]
As long as we find suitable icons this is totally doable.

**Comment by JimiC** [comment]
Moving this issue to #650.
