### ISSUE TITLE
Folder Icons Request

### ISSUE THREAD

**Issue by Kainax** [vscode-icons/vscode-icons#456]
- Type: extension
      - File Name: .conf (same icon as for .config)

      - Type: folder
      - Folder Name: php
      - Folder Name: js
      - Folder Name: tools
      - Folder Name: assets
      - Folder Name: tmp (+ "temp" folder)
      - Folder Name: .ebextensions          (aws elastic beanstalk default folder starting with dot)
      - Folder Name: .elasticbeanstalk      (aws elastic beanstalk default folder, starting with dot)

      Amazon AWS services icons zip:
https://media.amazonwebservices.com/AWS-Design/Arch-Center/16.2.22_Update/AWS_Simple_Icons_EPS-SVG_v16.2.22.zip

PS - Thanks for the extension, you are doing great!

      EDIT:
      - Folder Name: resources (same icon as for assets folder)

**Comment by Kainax** [comment]
Hi, I think it should be labeled both "file icons" and "folder icons". Thanks.

**Comment by jens1o** [comment]
Surely ;) But I'm busy... Is there a logo for aws in svg? Since we're upgrading to svg, it would be nice if we don't have to convert all stuff.

**Comment by robertohuertasm** [comment]
@jens1o, @Kainax has attached a zip with lots of icons from Amazon AWS in png and svg format, I guess as a suggestion to use. We'll evaluate this and see how many of them we'll eventually implement. 😉

**Comment by Kainax** [comment]
Yes, as it says in a filename of the provided link  :) However, it is more appropriate if folder's icon will be not AWS, but Elastic Beanstalk's application icon. You can get .svg version of it here:

https://upload.wikimedia.org/wikipedia/commons/0/03/AWS_Simple_Icons_Deployment_Management_AWS_Elastic_BeanStalk_Applicaton.svg

Speaking of AWS icon (orange cloud), it would be nice to have it over ".aws" and "aws" folders. You can find aws cloud .svg icon here:

https://upload.wikimedia.org/wikipedia/commons/5/5c/AWS_Simple_Icons_AWS_Cloud.svg

This four folders:
.aws
aws
.ebextensions
.elasticbeanstalk

are probably most popular among AWS users.

It would be totally perfect to draw them on top of default folder icon though. Cheers!

**Comment by JimiC** [comment]
@robertohuertasm @jens1o @Kainax I'll have a look at them on the weekend.

**Comment by jens1o** [comment]
Thank you @JimiC 😉

**Comment by JimiC** [comment]
@Kainax We haven't forgotten about this. Hopefully we'll have it shipped before New Year's release.

**Comment by JimiC** [comment]
Moving this issue #650.
