### ISSUE TITLE
[Task] Write guide for contributing icons in SVG

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#489]
It's essential to write a detail guide on how to create/modify an SVG icon so that it complies with our art creation guideline.

Ideally this guide should include hints and tips for usage of the following software:
- Adobe Illustrator
- Inkscape

**Comment by jens1o** [comment]
YEAH. Thank you! Then I can contribute as before. I don't understand how to work with SVG, Photoshop was pretty cool, but the testing time was way too short ;)
