### ISSUE TITLE
[Task] Review possible extensions that should benefit from language support

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#522]
Extends #476.

**Comment by robertohuertasm** [comment]
I leave the comment here for #527 PR so it can be easily found.

The thing is that the order of precedence when deciding which icon to use is:

1. file name
2. file extension
3. file language

According to this, if we set the `languageId` and leave the extension, this extension will be completely attached to the file extension icon. This maybe something desirable in some cases but maybe not in others.

We have to think of some of these cases so the user can decide if she uses the default icon or maybe she wants to use another one.

For the moment, it's ok like that. But the idea behind `language ids` is that the extensions should be reduced to the minimum and as long as the community provides language extensions users will be able to decide which icon to use for every extension based on the `language id`. But this, of course, is ideally, and it's not the scenario we have at the moment. 

It's paradoxical, the more extensions we support the less flexibility we provide. All filenames and extensions are strongly linked to the icons so they could never be altered by following the current API. LanguageId will be only useful for those extensions that we don't provide support.

**Comment by JimiC** [comment]
@robertohuertasm I'm aware of that and decided to leave the extension deliberately. Originally I removed the extension name but when I tried to use the example generator, those that didn't had an entry, as they relied on the language id failed to be generated. So I left it there knowing that this might be an issue.

**Comment by robertohuertasm** [comment]
Let's keep this at it is (with the new changes you applied). In case of unsupported extensions it will be useful anyway and whenever we face a conflict or a user reports us one, we may think on how to resolve it.

**Comment by JimiC** [comment]
Now that the icons conversion has been completed, it's time to review the `language ids`. I'll keep a list here with language support that exists for `vscode` to track the integration progress .

- [ ] elixir
