### ISSUE TITLE
[Task] Provide messages in available VSCode languages

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#526]
- [x] I'm sure this issue is not a *duplicate*?

I know this was experimented on at some point but I think it will add value to this extension.

VSCode available languages:

- [x] English (US)	[en]
- [x] Simplified Chinese [zh-CN]
- [ ] Traditional Chinese [zh-TW]
- [x] French	[fr]
- [x] German	[de]
- [x] Italian	[it]
- [x] Japanese [ja]
- [ ] Korean	[ko]
- [x] Russian	[ru]
- [x] Spanish [es]

**Comment by jens1o** [comment]
I'll do German, since I am German.

**Comment by JimiC** [comment]
@jens1o Only mark the language when it's done with a PR.

**Comment by jens1o** [comment]
Oh, sorry. I misunderstood. But how should the file be called?

**Comment by JimiC** [comment]
May have to consult @robertohuertasm .

**Comment by robertohuertasm** [comment]
The only file containing strings is called `messages.js` but I don't really care much about the naming. If you come up with a cooler name, it is ok for me.

In fact, this is for me a very low priority issue, that's why I dismissed it. I didn't want to loose time in translations every time I changed a string.

**Comment by sabinrimni** [comment]
I saw you were missing the Italian translation so I was working on it following the examples of the other translations. Is there anything else to translate other than `package.nls.json` and `lang.en.ts`? If you still need it of course.

**Comment by JimiC** [comment]
@sabinrimni Sure. It also requires some wiring but if you aren't familiar with `Typescript` just provide the translations and we'll do the wiring.

**Comment by JimiC** [comment]
`vscode-icons` now uses `Crowdin` as it's translation service. All respectful translations contributors, who wish to continue providing their services, are kindly requested to create an account with `Crodwin`, using their `GitHub` account and register with the language they provide translations for.
Thanks in advance.

/cc @MonsieurMan @mariotsi @sabinrimni @ksvitkovsky @iFun @g-plane

**Comment by JimiC** [comment]
Closing in favor of https://github.com/vscode-icons/vscode-icons/wiki/Translation
