### ISSUE TITLE
[Icon Request] Support for .VCXPROJ

### ISSUE THREAD

**Issue by jozefizso** [vscode-icons/vscode-icons#528]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: vcxproj
      - Sample original Icon (32x32/svg/transparent whenever possible): (I don't have a sample)
      - Extensions: .vcxproj

**Comment by JimiC** [comment]
Already supported by the `xml` language id. The icon shown is that of the `xml`.

**Comment by jens1o** [comment]
I think so. Since it's not related to XML, but to VSCode

**Comment by JimiC** [comment]
Any proposed icon?

**Comment by robertohuertasm** [comment]
I think this icon is related to c++ projects in VS so I would propose the [VS icon](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Visual_Studio_2013_Logo.svg/990px-Visual_Studio_2013_Logo.svg.png).

We already have the `svg` for `vscode` so the only thing that we should do is just change the color accordingly. What do you think?

**Comment by JimiC** [comment]
From what I'm seeing we use the `Visual Studio` versions for `csproj` and `vbproj`. I think we should stick to that.

P.S. And while we are at I'll look into adding `jsproj` also.

**Comment by robertohuertasm** [comment]
I'm willing to change those icons, too. I don't like how they look. But we can keep them eventually.

**Comment by JimiC** [comment]
@robertohuertasm It's just that they are `Visual Studio` specific icons and it makes sense to keep those.

**Comment by robertohuertasm** [comment]
Yes, but as I said I'm intended to change them eventually. They don't blend in nicely with vscode.

**Comment by JimiC** [comment]
This changes a lot of things. Cause I'm currently in the process of converting them to SVG (by hand).
So what's your idea?

**Comment by robertohuertasm** [comment]
Don't touch these icons for the moment. I will do a custom version myself and see if it works.
