### ISSUE TITLE
hpp files use same icon as cpp, should use a separate icon similar to c and h

### ISSUE THREAD

**Issue by BillDenton** [vscode-icons/vscode-icons#571]
C++ header files (hpp) use the same icon as C++ source files (cpp). C header files (h) uses a different icon C source files (c). Could so hpp files uses a different icon so they can be seen easily. Suggest an H++ similar to the C++ used for cpp files.

**Comment by jens1o** [comment]
Nice idea, your opinions @robertohuertasm & @JimiC ?
