### ISSUE TITLE
[Suggestion] Create new logo image in SVG

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#575]
I'm suggesting to create a new logo for the extension in SVG or convert the existing one to SVG.

Thoughts?

**Comment by jens1o** [comment]
I agree with you.

**Comment by robertohuertasm** [comment]
I don't know if svg is supported as extension for the logo. I'm in mobile now and can't look for this at the moment.

Regarding the icon, make your proposal and we'll see. :wink:

**Comment by JimiC** [comment]
It's supported. I tested it.

**Comment by JimiC** [comment]
I already have a design idea for the new logo. I'll present it when it's ready.

**Comment by JimiC** [comment]
Here are some ideas I have for a new logo.


# Concept 1
![logo 1](https://cloud.githubusercontent.com/assets/1716442/22306564/598f8622-e348-11e6-8729-84c31d4d09fd.png)

# Concept 2
![logo 2](https://cloud.githubusercontent.com/assets/1716442/22306559/57a3b14e-e348-11e6-9914-39a2a8674bdd.png)

# Concept 3
![logo 3](https://cloud.githubusercontent.com/assets/1716442/22306560/57daaf96-e348-11e6-8ad8-16a8671a0d36.png)

# Concept 4
![logo 4](https://cloud.githubusercontent.com/assets/1716442/22306561/57de82c4-e348-11e6-89bd-3fc748c36f62.png)

# Concept 5
![logo 5](https://cloud.githubusercontent.com/assets/1716442/22306562/57e21ede-e348-11e6-9c8d-d8758364c7c2.png)

**Notes:** 1 and 5 are not SVG friendly as they create a big file. If chosen they can only be used in PNG.

**Comment by jens1o** [comment]
I like the former.

**Comment by robertohuertasm** [comment]
For me the first one is the one I like most!

**Comment by JimiC** [comment]
I like it too (no wonder it's `#1`). The only problem is that the `SVG` version is a 13MB file. Maybe I make an exception for this one and embed the background as an `image` to make the file size smaller.

**Comment by robertohuertasm** [comment]
I don't think it's an issue here the use of PNG. The icon is only used in the store as far as I know.

**Comment by JimiC** [comment]
You are right and the size has to be maximum 128x128. The idea of changing the logo was to use an `SVG` one.

**Comment by JimiC** [comment]
An 140KB SVG version

![logo](https://cdn.rawgit.com/JimiC/vscode-icons-svg/master/assets/new-logo.svg)

**Comment by robertohuertasm** [comment]
@JimiC,  I think the link doesn't work.

**Comment by JimiC** [comment]
Intentionally. Waiting for the CDN to update to the correct one. Once it's done I'll update the link.

**Comment by JimiC** [comment]
There you go.

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/22621703/2cf38656-eb2a-11e6-9ffe-eabe75e0b92d.png)
![image](https://cloud.githubusercontent.com/assets/696981/22621717/694ff030-eb2a-11e6-9753-0a92a92ea2ab.png)
![image](https://cloud.githubusercontent.com/assets/696981/22621711/40f48204-eb2a-11e6-9754-f22e06413222.png)

I was just testing the new icon when I've noticed how it looks into the extensions sidebar. As you can see it looses all definition. I think we cannot do much about this :(

**Comment by JimiC** [comment]
If you don't like it, revert it.

**Comment by robertohuertasm** [comment]
The thing is I like it. But I don't like the way it looks when in reduced mode. Let's give it a try.

**Comment by JimiC** [comment]
It's because the background is PNG and as know, those doesn't scale well.
