### ISSUE TITLE
[Icon Request] Support for .AU3

### ISSUE THREAD

**Issue by erroledge87** [vscode-icons/vscode-icons#584]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: Au3Script or AutoIT
      - Sample original Icon: [AutoIT](http://seeklogo.com/images/A/autoit-logo-CC4B097310-seeklogo.com.png)
      - Extensions: .au3

**Comment by ginfuru** [comment]
@JimiC - I've got the SVG for this ready.

**Comment by JimiC** [comment]
I already have it. Why haven't checked with the repo?

**Comment by ginfuru** [comment]
@JimiC my bad - I pulled the master of `vscode-icon-svg` didn't see it.   But no worries I can stand down.

**Comment by JimiC** [comment]
@ginfuru https://www.autoitscript.com/site/
