### ISSUE TITLE
[Icon Request] Own icon for fonts folders

### ISSUE THREAD

**Issue by totkeks** [vscode-icons/vscode-icons#585]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: folder
      - Icon Name: FontFolder
      - Sample original Icon: [Icon](http://findicons.com/icon/download/35678/fonts/32/png) (hint: does not display in browser but pops up a download window)
      - Extensions: fonts

**Comment by jens1o** [comment]
Great idea, but I think this icon does not match our style guidelines. Your thoughts @robertohuertasm and @JimiC ?

**Comment by JimiC** [comment]
See this [comment](https://github.com/robertohuertasm/vscode-icons/issues/514#issuecomment-267320799).

**Comment by JimiC** [comment]
I think that changing the folder icons will not have too much value as we also use those icons as a background for the specific named folder icons.
Having a watermark on the folder icon and on top the folder specific icon will definitely bloat the icon.

**Comment by totkeks** [comment]
@JimiC I think you might misunderstand me. Of course I want to keep things as they are, with the folder background and then the specific named folder icons on top of them. Just one more for fonts.
![image](https://cloud.githubusercontent.com/assets/2941389/21860721/35dd73a4-d832-11e6-8c7c-66955578ce5e.png)
Like in this picture. Though instead of the little image icon in front of the folder icon, just put a little "Aa" or something that represents fonts in general very well.

**Comment by JimiC** [comment]
Oh for a folder **containing** fonts? I totally misread you if this is the case. If so it's totally doable.
