### ISSUE TITLE
tfignore icon

### ISSUE THREAD

**Issue by rafakwolf** [vscode-icons/vscode-icons#616]
![image](https://cloud.githubusercontent.com/assets/2060578/21764780/f9305ab2-d64b-11e6-9b0e-31f2f6d6a60b.png)

**Comment by robertohuertasm** [comment]
Can you propose an icon? Give us some more information? thanks!

**Comment by JimiC** [comment]
It's a TSF related file.

**Comment by rafakwolf** [comment]
@JimiC  exactly ... i think something like that 
![image](https://cloud.githubusercontent.com/assets/2060578/21765195/745843a6-d64e-11e6-9b5c-b70a1e10116f.png)

**Comment by robertohuertasm** [comment]
Thanks @rafakwolf, @JimiC . The point was not knowing about the file type but to try to follow the issue template whenever possible. 😉

**Comment by JimiC** [comment]
Yeah. We are all in for protocol. 😉

**Comment by rafakwolf** [comment]
Sorry guys, .. i promise I'll follow the protocol more closely next time.... :simple_smile:
Thanks
