### ISSUE TITLE
Lerna icon is too dark (dark theme)

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#644]
- [x] I'm sure this issue is not a *duplicate*?

We should provide a better icon for dark themes.

**Comment by rohithramachandran** [comment]
hbs icon also too dark in vscode dark theme .. 
![screenshot at 2017-01-19 15-57-21](https://cloud.githubusercontent.com/assets/2727960/22103151/0419f6f6-de60-11e6-8281-24cb80521624.png)

**Comment by JimiC** [comment]
@rohithramachandran Please make a new issue.

**Comment by rohithramachandran** [comment]
@JimiC Sure .. 

Thanks
