### ISSUE TITLE
Config light version icon overrides associated icons in light themes

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#649]
Currently noticeable on `.editorconfig` and `.gitattributes`.

A possible solution is to change colors of `config` icon, so it's viewable in both themes, and remove the `light` version.

**Comment by JimiC** [comment]
The other solution is to fill the `light` section of the icon manifest file with the dark theme version of the icons that don't have a light version. This will create a slightly bigger file but will give a permanent solution in case of another similar case.

@robertohuertasm @jens1o Thoughts?

**Comment by jens1o** [comment]
I love your suggestion and I'm fine with it.
