### ISSUE TITLE
[Icon Request] .idea folder

### ISSUE THREAD

**Issue by Daylien** [vscode-icons/vscode-icons#652]
-  I'm sure this issue is not a *duplicate*?
- I want to create an icon request:
      - Type: folder
      - Icon Name: .idea
      - Sample original Icon: [Jetbrains](http://resources.jetbrains.com/assets/media/open-graph/jetbrains_250x250.png)
      - Extensions: .idea

Thanks :)

**Comment by JimiC** [comment]
Sorry to say but the icon you reference isn't that of `IntelliJ IDEA` but of the company that owns the product `JetBrains`.

Once we clear any licensing issues and find a suited icon we'll see about adding this to our collection.

**Comment by Daylien** [comment]
Yeah i understand. But for example we take the icon of IntelliJ IDEA. IntelliJ IDEA and all other Jetbrains IDE's will create an folder called .idea in the project root. So when we take the IntelliJ Idea icon it could be  very annoying when you only work with WebStorm for example. And because of that i thought that the company logo is an good alternative. :)  Perhaps this is an alternative [icon](https://p7.zdassets.com/hc/settings_assets/787891/200177531/j2s8FaltEjj9dI5XTLZuXQ-favicon.ico).

Greetings :)

**Comment by JimiC** [comment]
@Daylien I'm not familiar with any `JetBrains` IDE so I can't confirm your statement. My impression was that `.idea` had to be an `IntelliJ IDEA` folder, hence the name.  Maybe @jens1o could help us out here.

**Comment by JimiC** [comment]
Looking around in `StackOverflow` I confirmed your claim.

I also found a suitable SVG version of the [logo](https://gist.github.com/JimiC/d05fecfe58e95646c9a2f6a737180afd).

And while we are at it we may also add a folder icon for `.vs`.

**Comment by Daylien** [comment]
Great news ! Thank you for the work @JimiC !

**Comment by robertohuertasm** [comment]
This is the icon that it's used in `Webstorm` to notice that the folder has an `.idea` folder.
![idea_icon](https://cloud.githubusercontent.com/assets/696981/22128703/3b94ace2-dea2-11e6-8eaf-7cbb444dd9be.png)

![ideaproject 2x](https://cloud.githubusercontent.com/assets/696981/22128886/262191bc-dea3-11e6-84b4-36fc53e9a718.png)

Unfortunately, I only found the png version.

**Comment by Daylien** [comment]
Hello @robertohuertasm.

I haven't seen this icon before. My structure of the project in Webstorm (2016.3.1) is the following:

![unbenannt3](https://cloud.githubusercontent.com/assets/22529605/22139923/9b1fc3b2-dee9-11e6-98a4-f8eb377433bf.png)

And the icon doesn't appear as you can see.

Greetings :)

**Comment by JimiC** [comment]
@robertohuertasm That icons you mention is the old `IntelliJ IDEA` one. We better go with the generic `JetBrains` logo without the brand name.

**Comment by robertohuertasm** [comment]
@Daylien @JimiC I just wanted to point out what the latest version of `Webstorm` is using to notice that some folder contains a project. 

@Daylien, try to open a folder directly from the IDE and you'll see the icon.

**Comment by JimiC** [comment]
I have already created the icons based on the `JetBrains` logo.

![untitled](https://cloud.githubusercontent.com/assets/1716442/22145432/033c98f6-df0a-11e6-8b73-52d0f4bd7c6c.png)

**Comment by robertohuertasm** [comment]
I like it! Awesome work! I like you removed the black square. 👍

**Comment by JimiC** [comment]
@robertohuertasm Yeah, the brand name was too much on the icon and it would ruin it. That's why I mentioned from the start that I would remove it.

**Comment by Daylien** [comment]
@JimiC Awesome ! 

@robertohuertasm unfortunateli I dont know what you mean with open a folder directly from the IDE. When i open up the .idea folder, there are some xml setting files nothing else.

**Comment by robertohuertasm** [comment]
@Daylien File > Open

But don't worry. The icons introduced by @JimiC look really nice so I don't have any doubt about going with them.

**Comment by Daylien** [comment]
@robertohuertasm Ah got it thanks :)

Yeah the icon looks very cool. But what are your thoughts about an darker folder background color ? I mean some grey or something else this would be very cool behind the orange-red color.

**Comment by JimiC** [comment]
We have decided to go with art guidelines for the icons, meaning there are specific rules when choosing colors.

That said, you can customize the icon, once it's public, put your color of choice to the folder and override the icon. Read all about it on README.

**Comment by Daylien** [comment]
Okay many thanks @JimiC and @robertohuertasm !
