### ISSUE TITLE
[Icon request] angular controller

### ISSUE THREAD

**Issue by josegoncalveswho** [vscode-icons/vscode-icons#653]
- [X] I'm sure this issue is not a *duplicate*?
- [X] I want to create an icon request(if not, remove these lines below):
      - Type: folder
      - Icon Name: controller
      - Sample original Icon (32x32/svg/transparent whenever possible): [url]
      - Extensions: .controller.js

**Comment by JimiC** [comment]
Regarding a request for a folder icon this has been already added in the list of #650.
Regarding a request for a filename icon, we'll see what we can do.

**Comment by JimiC** [comment]
@robertohuertasm can you provide an icon for `controller` or should we use the `component` one?

**Comment by josegoncalveswho** [comment]
Sorry Roberto,

I never got to think about one. I just figured that, for angular 1 projects, it still helps to have some way to distinguish files. Although, most of the times, controllers are coded alongside the directives.

I would go with component, at least.

Sorry I can't be of more help, but I'm on the road! :)

Sent from my iPhone

On 28 Jan 2017, at 16:24, Jimi (Dimitris) Charalampidis <notifications@github.com<mailto:notifications@github.com>> wrote:


@robertohuertasm<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_robertohuertasm&d=DwMCaQ&c=pWn2jKJ-j-AhxLuiRFe-Qw&r=9E3i1tw7ceGN-8DOzq68mU7K4ouHcWCBa-M2aVKQaMw&m=97gE4pSiNnm1gzE9uctyZL2KOK4HqC-f1w1uRjwTpPk&s=n0B06uPRFTHd2Q2o7PxO-f5a1fCjlrJOxofKS8bHtsg&e=> can you provide an icon for controller or should we use the component one?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_vscode-2Dicons_vscode-2Dicons_issues_653-23issuecomment-2D275854277&d=DwMCaQ&c=pWn2jKJ-j-AhxLuiRFe-Qw&r=9E3i1tw7ceGN-8DOzq68mU7K4ouHcWCBa-M2aVKQaMw&m=97gE4pSiNnm1gzE9uctyZL2KOK4HqC-f1w1uRjwTpPk&s=WfZXuaiQ_B10d_DC5PoerlN9ihF2Q__unE4ksy1efg4&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQSlMmtP3ld6-2D-2D11YBanfVc-2DMs7sZxkJks5rW13CgaJpZM4LqECa&d=DwMCaQ&c=pWn2jKJ-j-AhxLuiRFe-Qw&r=9E3i1tw7ceGN-8DOzq68mU7K4ouHcWCBa-M2aVKQaMw&m=97gE4pSiNnm1gzE9uctyZL2KOK4HqC-f1w1uRjwTpPk&s=70MxAiUPDq8WoNxMnCyYoZC8vKyIt0zyQOgHEZKFAXE&e=>.

Confidentiality: The contents of this e-mail and any attachments transmitted with it are intended to be confidential to the intended recipient; and may be privileged or otherwise protected from disclosure. If you are not an intended recipient of this e-mail, do not duplicate or redistribute it by any means. Please delete it and any attachments and notify the sender that you have received it in error. This e-mail is sent by a William Hill PLC group company. The William Hill group companies include, among others, William Hill PLC (registered number 4212563), William Hill Organization Limited (registered number 278208), William Hill US HoldCo Inc, William Hill Australia Holdings Pty Limited (registered number ACN 161 652 955) and WHG (International) Limited (registered number 99191). Each of William Hill PLC, William Hill Organization Limited is registered in England and Wales and has its registered office at Greenside House, 50 Station Road, Wood Green, London N22 7TP. William Hill U.S. HoldCo, Inc. is 160 Greentree Drive, Suite 101, Dover 19904, Kent, Delaware, United States of America. William Hill Australia Holdings Pty Limited is registered in Australia and has its registered office at Level 30, 2 Park Street, Sydney, NSW 2000, Australia. WHG (International) Limited is registered in Gibraltar and has its registered office at 6/1 Waterport Place, Gibraltar. Unless specifically indicated otherwise, the contents of this e-mail are subject to contract; and are not an official statement, and do not necessarily represent the views, of William Hill PLC, its subsidiaries or affiliated companies. Please note that neither William Hill PLC, nor its subsidiaries and affiliated companies can accept any responsibility for any viruses contained within this e-mail and it is your responsibility to scan any emails and their attachments. William Hill PLC, its subsidiaries and affiliated companies may monitor e-mail traffic data and also the content of e-mails for effective operation of the e-mail system, or for security, purposes.

**Comment by robertohuertasm** [comment]
I will provide one for `controller`, given that Angular 1.5 introduced components.

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/22630009/f06bc126-ebf1-11e6-904c-e738ff634e05.png)

**Comment by robertohuertasm** [comment]
Folder is still pending but as pointed out by @JimiC it will be followed in #650
