### ISSUE TITLE
log and shell icon improvement

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#669]
Today I've stumbled upon the new `. log` icon. 

I have to say that my eyes were immediately drawn to it:

1. It was completely different from what I was used to.
2. The big mass of light green color.
3. At first I thought it was some rendering error. Later  could notice that it was a notebook but I barely could see the tabs.

![image](https://cloud.githubusercontent.com/assets/696981/22203425/4b8c1af4-e16d-11e6-9a78-381081c76d76.png)

I think that we should rework it so it is more recognizable. What do you think?

**Comment by JimiC** [comment]
This was one of the hardest choices I made. I couldn't find a proper icon that expresses the `logging` concept. I believe that the icon is the closest thing to a `log`.
Of course, the colors can be changed and the tabs can be enhanced to make them more visible, although I believe they aren't that critical. Certainly, this icon shines on a [Retina Display](https://en.wikipedia.org/wiki/Retina_Display).

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/22224574/69e08cc2-e1bf-11e6-8a03-72a3f28bf858.png)

Here you are my suggestion for `log` and `sh` files. Back to the minimalism we got before.

**Comment by JimiC** [comment]
I don't disagree being minimalistic. But the icon for `log` looks more fitting for `monitor` than `log.`
I too thought that the `shellscript` icon was too much but was waiting for feedback from the community about it.

**Comment by robertohuertasm** [comment]
Yes, it is indeed more suitable for some kind of `monitor` but `logs`, somehow, are some kind of monitoring. They're a record of something, so in a strict sense you're monitoring something. 

I'm not saying that this is perfect but I like it more than the one we have right now which is not clear enough and it's not pleasant to the eye.

Regarding the `shell` icon, I have to confess that it seemed to me that it was like an old school icon, with way too much lines and details. I tend to favour simplicity in icons, too. 

The truth is that I didn't say anything because I haven't opened one of my script projects until a few days ago. And now that we were discussing the `log` icon and I opened Illustrator I made two icons for the price of one! 😉

**Comment by jens1o** [comment]
I like your suggestion. I like minimalistic things. 😉

**Comment by JimiC** [comment]
`monitoring` means observing a live event on a monitor, thus the word.
> `monitoring` means, observe and check the progress or quality of (something) over a period of time; keep under systematic review. (https://www.google.gr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=monitoring%20means)

`logging` means to record an event for later process.
>an official record of events (https://www.google.gr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=log+means)

There is a distinguishing difference between them.

Bottom line, it's your project and you have the last word on what icons will be used. That said, I rest my case.
Please feel free to submit and merge those icons.

**Comment by robertohuertasm** [comment]
@JimiC  thanks for making your case. Of course, I cannot refute what it's obvious. I was not trying to imply they're the same concept but that they have some kind of similarity, and thus, it's not like using a completely foreign icon.

I'll try to rework the icon and see if I can come up with something more suitable 😉

**Comment by JimiC** [comment]
Fixed in #706 and #707 .
