### ISSUE TITLE
Git icon not used for .gitignore anymore

### ISSUE THREAD

**Issue by Gama11** [vscode-icons/vscode-icons#671]
Somehow it only affects `.gitignore`, but not other Git files:

![](http://i.imgur.com/1rYBHLp.png)

Pretty sure this worked at some point, not sure when it stopped working exactly.
I'm on vscode-icons 7.1.2 (latest).

**Comment by robertohuertasm** [comment]
I works ok for me... Try F1 > Icons: Restore Default Icon Manifest

**Comment by Gama11** [comment]
Hm... didn't help. Neither did reinstalling the extension.

**Comment by Gama11** [comment]
On another note: Isn't `"vsicons.presets.angular": false` supposed to disable that `VSCode-Icons has detected a non Angular project. 'Restart' to disable the Angular icons.` note? That's what "disable inspection" adds.

`"vsicons.projectDetection.disableDetect": true` works though.

**Comment by JimiC** [comment]
@Gama11 Git icon will work correctly again in `vscode v1.9.0` (it's working on `insiders`) which will include a patch @robertohuertasm submitted.

`vsicons.presets.angular` disables the use on `Angular` icons, not the project type detection.
`vsicons.projectDetection.disableDetect` is the correct setting for that.

**Comment by robertohuertasm** [comment]
@Gama11 see [this](https://github.com/Microsoft/vscode/issues/17864) for more info. 
Thanks @JimiC for noticing it!

**Comment by Gama11** [comment]
Thanks! It does indeed work correctly in the latest Insider's build. :)
