### ISSUE TITLE
Icons For .reg and .VBS

### ISSUE THREAD

**Issue by ThomasRunting** [vscode-icons/vscode-icons#674]
- Type: .reg .vbs
      - Icon Name: Registry setting export, Visual Bascis Script
      - Extensions: .reg, .vbs

**Comment by JimiC** [comment]
`.vbs` is already covert.
Any icon proposal for `.reg`?

**Comment by robertohuertasm** [comment]
I think that something similar to [this](https://icons8.com/web-app/3030/registry-editor) could be easily done with our illustrator skills 😉 (the Win10 version)

If that looks good to you I can do it.

**Comment by JimiC** [comment]
It's exactly the icon I'm processing.
