### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by arimourao** [vscode-icons/vscode-icons#676]
I've used this plugin before when I was testing VSCode for the first time. It worked back then, but now I downloaded the most recent version of VSCode (Version 1.8.1), installed the plugin using the "extensions" panel and it doesn't show any icon. Tried on several kinds of projects and nothing. I'm running on Debian 8 Jessie. Not sure how can I debug this problem. Any thoughts?

**Comment by JimiC** [comment]
Did you enabled it? https://github.com/vscode-icons/vscode-icons#enable-the-extension

**Comment by robertohuertasm** [comment]
@arimourao have you been able to make it work?

**Comment by arimourao** [comment]
Thanks @JimiC. I guess it is a bit odd you install an extension and still have to fuzz around the preferences to make it work. If I installed it is obvious that I want it to work. @robertohuertasm yes, now it is working!

**Comment by robertohuertasm** [comment]
@arimourao vscode supports now having many icon extensions so it provides a way for you to enable/disable the extension that you want as you may have several icon extensions installed at the same time.
