### ISSUE TITLE
[Icon Request] Certificate and Key icons

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#680]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `cert`
      - Sample original Icon: N/A
      - Extensions: `.csr`, `.crt`, .`cer`, `.der`, `.pfx`, `.p12`, `.p7b`, `.p7r`, `.src`, `.crl`, `.sst`, `.stl`

- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `key`
      - Sample original Icon: N/A
      - Extensions: `.pem`, `.key`

**Comment by JimiC** [comment]
Guys, I need some help. I created some icons for this issue but I can't decide which to chose.

Group 1
----
![screenshot - 21_07_2017 21_14_54](https://user-images.githubusercontent.com/1716442/28476845-2eef0dbe-6e5a-11e7-973f-605f77849b7c.png)![screenshot - 21_07_2017 21_15_22](https://user-images.githubusercontent.com/1716442/28476858-401bc23a-6e5a-11e7-88e7-1721ebd31f47.png)

Group 2
----
![screenshot - 21_07_2017 21_17_37](https://user-images.githubusercontent.com/1716442/28476873-50d66d3c-6e5a-11e7-8c6a-387821eaacd6.png)![screenshot - 21_07_2017 21_18_11](https://user-images.githubusercontent.com/1716442/28476883-57fc593c-6e5a-11e7-9cfd-a0211cce43fb.png)

I do have a personal preference but I'll tell you after yours.

**Comment by jens1o** [comment]
I like the style of the second one, but I think the green is a bit worrying and I can't get why it's there... I think users shouldn't have a question about a icon which should improve the recognizably.

**Comment by JimiC** [comment]
If you zoom in you'll see it's a locket.

**Comment by jens1o** [comment]
oh. lol. Didn't saw that. But I think the contrast is a bit worse :/

**Comment by JimiC** [comment]
You are right. Too much dark colors in there.
How about those ones?
![screenshot - 21_07_2017 23_47_58](https://user-images.githubusercontent.com/1716442/28482020-34d03612-6e6f-11e7-934c-0a8818242147.png)![screenshot - 21_07_2017 23_48_24](https://user-images.githubusercontent.com/1716442/28482023-38ef7b36-6e6f-11e7-9be7-d9f5d8217608.png)

**Comment by jens1o** [comment]
I could get used to it. :)

**Comment by robertohuertasm** [comment]
I like Group 1. It's simpler and ads less noise to the icon. Straight to the point.

**Comment by JimiC** [comment]
Guys, you aren't making my life any easier. 🤕
I'm lining towards Group 2 as they are more distinguishable to the eye.

**Comment by JimiC** [comment]
Trivia: When those get merged we will surpass the 500 icons mark.

**Comment by jens1o** [comment]
Let's flip a coin. 👅

(and wait until it says we're using the second one)
