### ISSUE TITLE
[Icon Request] Drone icon

### ISSUE THREAD

**Issue by salaxander** [vscode-icons/vscode-icons#681]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: Drone
      - Sample original Icon (32x32/svg/transparent whenever possible): have a PNG locally, can create an svg
      - Extensions: .drone.yml

I think I have this worked up correctly on my fork, so I'm happy to submit a PR! :)

**Comment by salaxander** [comment]
For those not familiar [Drone](https://github.com/drone/drone) is an awesome open source CI tool

**Comment by jens1o** [comment]
Could you upload your png? Feel free to show us an svg icon, that would be awesome!

**Comment by salaxander** [comment]
![file_type_drone](https://cloud.githubusercontent.com/assets/1063495/22337026/9a09fba4-e3a9-11e6-86b0-e829d8745c53.png)

Here's the PNG, I can try for an SVG too, not the best with Illustrator though :p

**Comment by JimiC** [comment]
The SVG logo is already available from the main site (http://readme.drone.io/logo.svg)

**Comment by salaxander** [comment]
Great find!
