### ISSUE TITLE
[Icon Request] Dustjs .dust icon

### ISSUE THREAD

**Issue by rixrix** [vscode-icons/vscode-icons#682]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: dust
      - Extensions: .dust

A bit of info about Dust - It's JavaScript templating engine built by the engineering team from LinkedIn

* http://www.dustjs.com/
* https://engineering.linkedin.com/frontend/leaving-jsps-dust-moving-linkedin-dustjs-client-side-templates

**Comment by rixrix** [comment]
thank you!

**Comment by JimiC** [comment]
@rixrix It took me some time to find a suitable icon. But, better late than never, right?

**Comment by rixrix** [comment]
@JimiC looks fantastic, can't wait for the official release - better late than never, great work! ;)
