### ISSUE TITLE
Howt to use associations files settting?

### ISSUE THREAD

**Issue by Shababsoft** [vscode-icons/vscode-icons#683]
The following setting are not working, I want to associate icons to the Salesforce page and class extensions.

`"vsicons.associations.files": [
        { "icon": "html", "extensions": ["page","component"], "format": "svg" },
        { "icon": "java", "extensions": ["cls"], "format": "svg" }
 ]`

**Comment by JimiC** [comment]
It's unclear what you are trying to achieve. Please provide reproduction steps or read the instruction more carefully.

**Comment by Shababsoft** [comment]
The following file extensions are not supported by vscode-icons plugin.
- .page
- .cls
- .component

I am trying to associate the existing html & java class icons to these file extensions.  Please can you let me know if this is possible and how can I achieve this?

**Comment by JimiC** [comment]
Although the proper extension for `java` `class` is `.class` (which we btw support) I'm not going to debate your preference.

Obviously, you are not doing

"Quote from README"
> It's also important to say that if you choose to make a manual modification you will have to execute the Apply Icons Customization command (see below).

**Comment by Shababsoft** [comment]
@JimiC  I didn't know I have to run the command. Thanks
