### ISSUE TITLE
[Icon Request] Support for Solidity

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#690]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `solidity`
      - Sample original Icon: ![logo](https://cdn.rawgit.com/ethereum/browser-solidity/master/assets/img/remix_logo_512x512.svg)
      - Extensions: `.sol`

**Comment by JimiC** [comment]
@robertohuertasm @jens1o Currently `.sol` is associated with `Adobe Flash`. I strongly suggest we remove that association and assign it to `solitidy`.

**Comment by jens1o** [comment]
Well, Adobe Flash uses this. Can we provide both?

**Comment by JimiC** [comment]
No.

**Comment by jens1o** [comment]
Why not? I'm thinking of something like this: https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L213-L214

**Comment by JimiC** [comment]
Not the same.

**Comment by jens1o** [comment]
Then, go for it. 😢

**Comment by JimiC** [comment]
It's necessary to switch the association if we want to support `solitidy` `languageid` (https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity).
