### ISSUE TITLE
[Icon Request] Support for Dylan-lang

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#693]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `dylanlang`
      - Sample original Icon: ![logo](https://avatars3.githubusercontent.com/u/490490?v=3&s=200)
      - Extensions: `.dylan`, `.intr`

**Comment by jens1o** [comment]
Where did you see these extension? I've never seen them. I didn't know that sooo much languages exists.

**Comment by JimiC** [comment]
I didn't know either. My head hurts. I'm just browsing the language support that exists for `vscode` and adding those we are missing.

To answer your question: https://github.com/dylan-lang/vscode-dylan/blob/master/package.json#L39

**Comment by jens1o** [comment]
Thanks to you. I couldn't do that. 😉
