### ISSUE TITLE
[Icon Request] Git icon for .gitignore

### ISSUE THREAD

**Issue by norlando** [vscode-icons/vscode-icons#694]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: `extension`
      - Icon Name: `file_type_git.svg`
      - Sample original Icon (32x32/svg/transparent whenever possible): [Git icon](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_git.svg)
      - Extensions: `.gitignore`

**Comment by norlando** [comment]
Appears there should already be support for git, but some reason my .gitignore file doesn't get the icon unless I add the line below to my settings.json.
`"vsicons.associations.files": [{"icon": "git", "extensions": [".gitignore"], "filename": true, "format": "svg", "overrides": "git"}]`

**Comment by robertohuertasm** [comment]
This is a known bug that will be solved in the next `vscode` release. See #671

**Comment by JimiC** [comment]
@norlando You don't need to set any overriding for the icons.
You can workaround this for the moment by:
1. Open `.gitignore` file.
2. Click on the lower right corner of `vscode` (right side at the status bar) where it says `Plain Text`.
3. Select for the opened menu `Configure File Association for '.gitignore'`.
4. Select `Properties`.

This will add the following in your `User` settings.
```
"files.associations": {
      ".gitignore": "properties"
    }
```
You can also at this snippet directly, if the steps above are confusing.

Just rememeber to delete it after `vscode 1.9.x` will be released.

**Comment by norlando** [comment]
@JimiC, cool thanks. :+1:
