### ISSUE TITLE
[Performance] Slim icon has too many details

### ISSUE THREAD

**Issue by caudatecoder** [vscode-icons/vscode-icons#701]
**[Slim icon](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_slim.svg) slows down tree-view scrolling**

Even 2-3 icons cause perceptible lags. So when there are, say, 10 — it's unbearable
Please, consider replacing of it

**Thanks :pray:**

**Comment by JimiC** [comment]
Indeed. Thanks for bringing this in our attention. We'll replace it asap.
