### ISSUE TITLE
Add .qvs as one of the default extension for QlikView/Qlik Sense

### ISSUE THREAD

**Issue by vinayaugustine** [vscode-icons/vscode-icons#709]
I would like to propose `.qvs` as an added extension for Qlik View/Sense scripts. At least among the Qlik users I know, the two popular extensions are `.qvs` and `.qvw`. (`.qvd` is used for binary qlik data files). I can submit a pull request, but I'm not sure if I need to modify languages.ts, supportedExtensions.ts or both.

- [x] I'm sure this issue is not a *duplicate*?

**Comment by JimiC** [comment]
This is going to be supported via #522.
