### ISSUE TITLE
Missed icons for vue-files

### ISSUE THREAD

**Issue by Alex-Sokolov** [vscode-icons/vscode-icons#725]
After latest update to vscode-icons 7.2.0 icons for vue-files not showed
![default](https://cloud.githubusercontent.com/assets/4497128/22636608/95e8f10e-ec4d-11e6-8c8f-dc07dd181e81.PNG)

In previous version showed correct logo

**Comment by JimiC** [comment]
Those are now supported under `language id`. https://marketplace.visualstudio.com/items?itemName=liuji-jim.vue

**Comment by Alex-Sokolov** [comment]
Thanks for answer! I used that extension too and yet no icon in sidebar. What I am doing wrong?

**Comment by JimiC** [comment]
Looks like an `vscode` issue. I'll investigate to find what goes wrong.

**Comment by JimiC** [comment]
Turns out that `vscode` is overriding us via its own language support for `html` https://github.com/Microsoft/vscode/blob/master/extensions/html/package.json#L37.

We'll have to investigate further on how to properly resolve this.

**Comment by JimiC** [comment]
@robertohuertasm Do you think that we should address this with the `vscode` team? I believe that external language id association should override the internal one.

**Comment by robertohuertasm** [comment]
@JimiC, yes I do. I agree with your point of view.
@Alex-Sokolov, as a temporary solution you can add a new `association` to your settings:
```
"vsicons.associations.files": [
  { "icon": "vue", "extensions": ["vue"], "format": "svg" }
]
```

**Comment by robertohuertasm** [comment]
I've seen now that if you set the association using 'vscode' it will work as expected without the need of using our 'custom associations'. 

Click over `HTML`  in the lower rigth corner of you vscode.  You will see a popup with several options. Choose `Configure file association with .vue`

That should do the trick.

**Comment by robertohuertasm** [comment]
Or the easiest path. Add this to your settings:
```
"files.associations": {
    "*.vue": "vue"
  }
```

**Comment by JimiC** [comment]
@robertohuertasm Are you going to open an issue in `vscode` or should I do it? (You know you have bigger influence than I do there).

**Comment by robertohuertasm** [comment]
I'm not so sure of that but I'll try it. 😉 
I will reference you and the issue so we all be in the loop.

**Comment by Alex-Sokolov** [comment]
Thanks! Temporary solution works

> Click over HTML in the lower rigth corner of your vscode. You will see a popup with several options. Choose Configure file association with .vue

Trying, before temporary solution and there is HTML-icon at vue-option

![default](https://cloud.githubusercontent.com/assets/4497128/22647545/3f9c2056-ec83-11e6-98ef-c4e1c30d2401.png)

**Comment by mudrz** [comment]
@robertohuertasm  I would like to add that:
```json
"files.associations": {
    "*.vue": "vue"
  }
```
is **NOT** a viable workaround, because Vue's language plugin is neither up-to-date nor does it seem to be actively supported. As a result of that it is much better to leave Vue files handling by VS Code's HTML syntax highlight and IntelliSense. Additionally other plugins (like vue eslint https://github.com/mysticatea/vue-eslint-parser) don't work when using .vue files association

This on the other hand is the correct workaround:
```json
"vsicons.associations.files": [
  { "icon": "vue", "extensions": ["vue"], "format": "svg" }
]
```
Don't forget to F1 > Icons: Apply Icons Customizations

So until there is proper .vue files language support in VS Code, the raised issue https://github.com/Microsoft/vscode/issues/20074 will not be that useful (if I understood correctly the proposed fix is if there is a file/language association only then to take the correct icon)

**Comment by JimiC** [comment]
@mudrz If you don't install the `Vue` extension then `vsode` will handle the syntax highlighting. Our debate isn't about the highlighting or the `IntelliSense`. It's about icon association.

**Comment by mudrz** [comment]
@JimiC My comment is a direct response to a proposed workaround to get the icons working, which was to associate .vue files with "vue":
> Or the easiest path. Add this to your settings:
> 
> "files.associations": {
>     "*.vue": "vue"
>   }

If you do this and don't have a Vue extension vscode will not handle the syntax highlighting.
Highlighting and IntelliSense are just some of the reasons listed, why the proposed workaround is not a good option at the moment, and why a much preferred solution to **get correct icon association** is the previously proposed solution:

> "vsicons.associations.files": [
>   { "icon": "vue", "extensions": ["vue"], "format": "svg" }
> ]
> Don't forget to F1 > Icons: Apply Icons Customizations

My comment has very much to do with the correct icon association fix and very little to do with the Vue extension itself

**Comment by JimiC** [comment]
[I figured out where the problem lies](https://github.com/Microsoft/vscode/issues/20074#issuecomment-279844054).

**Comment by JimiC** [comment]
@mudrz If you don't install the extension the workaround is:

>"vsicons.associations.files": [
{ "icon": "vue", "extensions": ["vue"], "format": "svg" }
]
Don't forget to F1 > Icons: Apply Icons Customizations

If you install the extension the workaround is:

>"files.associations": {
"*.vue": "vue"
}

**Comment by JimiC** [comment]
Quoting from Release Notes 1.10.1

> Vue
While Vue.js files may look like HTML files, they are much more than that. For that reason, the .vue file extension is no longer associated with HTML by default. However we do recommend you use a Vue.js specific extension for language support and the vetur extension is a good choice.

**Comment by Alex-Sokolov** [comment]
Thanks!

**Comment by MannyDiera** [comment]
> Or the easiest path. Add this to your settings:
> 
> ```
> "files.associations": {
>     "*.vue": "vue"
>   }
> ```

As of April 2020 this worked for me.
