### ISSUE TITLE
typescript folder

### ISSUE THREAD

**Issue by g5codyswartz** [vscode-icons/vscode-icons#726]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: folder
      - Icon Name: typescript
      - Sample original Icon (32x32/svg/transparent whenever possible): Not sure if there's any standard since there's already a .ts icon.
      - Extensions: .ts

**Comment by JimiC** [comment]
Please see #650.

**Comment by g5codyswartz** [comment]
Thanks @JimiC I think the issue template should be updated to reflect this.
