### ISSUE TITLE
New extension setting ignored

### ISSUE THREAD

**Issue by SamMackrill** [vscode-icons/vscode-icons#728]
I have added this to prefs:

    "vsicons.associations.files": [
        { "icon": "text", "extensions": ["mac"], "format": "svg" }
    ],

but I do not get an icon for my xxxx.mac files

**Comment by robertohuertasm** [comment]
Have you tried `F1> Icons: Apply Icons Customization`?

**Comment by SamMackrill** [comment]
No, I was just restarting VS Code :)

**Comment by SamMackrill** [comment]
RTFM
