### ISSUE TITLE
Laravel icon for .blade files is missing

### ISSUE THREAD

**Issue by adamk33n3r** [vscode-icons/vscode-icons#731]
Looks like .blade icons were introduced in 1.3.7 according to #67 but it seems that they went missing in 7.2.0. I'm pretty sure they were in 7.1.2.

- [x] I'm sure this issue is not a *duplicate*?

**Comment by robertohuertasm** [comment]
@adamk33n3r, indeed, `.blade` icons are still supported but they're supported via `language id`. This means you should have to install a `blade` language extension for that. 😉

**Comment by adamk33n3r** [comment]
@robertohuertasm gotcha! Thanks. `onecentlin.laravel-blade` seems to do the trick

**Comment by Klodovsky** [comment]
All IDE settings can be found under **C:\Users\Username\AppData\Roaming\Code\User\settings.json** file.


Also changing files associations might do the trick : 

```
     "files.associations": {
        "*.blade.php": "blade",
        "*.tpl": "html"
    },
```

Or if you're using beautify extension :

```
"beautify.language": {
        "html": [
            "blade",
            "html"
        ]
    },
```

**Comment by Klodovsky** [comment]
For anyone who might still face this issue, I found out that the icons/extensions wasnt working correctly because of invalid settings.json format , make sure your json format is correct.

You can check that by visiting https://jsonlint.com/
