### ISSUE TITLE
.codeclimate.yml not using CodeClimate icon anymore

### ISSUE THREAD

**Issue by Gama11** [vscode-icons/vscode-icons#732]
I contributed an icon for `.codeclimate.yml` files a while back: #225

However, even though the icon is [still there](https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_codeclimate.svg), it's not used anymore:

![](http://i.imgur.com/cmHQAp8.png)

Using latest vscode-icons (7.2.0) and VSCode 1.9.1.

**Comment by JimiC** [comment]
Just FYI. This bug comes from a long time ago (before we changed to `Typescript`). It was probably introduced when we removed the dots in front of declarations for file extensions. We probably missed that this was a filename.
