### ISSUE TITLE
Incorrect icon for tsconfig.json

### ISSUE THREAD

**Issue by ZanderBrown** [vscode-icons/vscode-icons#735]
The icon used for `tsconfig.json` is that of VSCode. Instead a modified version of the TypeScript logo should be used.

- [X] I'm sure this issue is not a *duplicate*?
- [X] I want to create an icon request(if not, remove these lines below):
      - Type: folder
      - Icon Name: tsconfig
      - Sample original Icon (32x32/svg/transparent whenever possible): [https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_typescript_official.svg]
      - Extensions: n/a

**Comment by JimiC** [comment]
This is intended (see #33). It's still debatable, though.

**Comment by ZanderBrown** [comment]
Ah didn't see that.

Whilst i understand the reasoning for the current icon it's not a VSCode config file, it's the config for the TypeScript compiler (`tsc`) thus will also be used by other editors

**Comment by JimiC** [comment]
That's why I said it's debatable. I would change it but @robertohuertasm has the final saying.

**Comment by robertohuertasm** [comment]
Go on with the change. I would create 2 new icons, one according to the default `typescript` icons and another one for the `official` icon set, and then add them to the `typescript icon toggle` functionality.

Maybe we could use purple as the color (similar to Visual Studio icon). These are just ideas so don't get them as the way it should be. What do you think?

**Comment by JimiC** [comment]
The think is that it's a config file. So, I was thinking more like combining the `config` and the simple `ts` icons. Same goes for `jsconfig` (while we are at it). Thoughts?

**Comment by ZanderBrown** [comment]
Icon Design realy isn't a skill i posses but here's a rough drawing of my initial idea
![image](https://cloud.githubusercontent.com/assets/17074021/22860788/0846a064-f100-11e6-91c7-e6bdd20cb653.png)

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/22998703/3a77b8ae-f3d8-11e6-8352-a1f9581c55d3.png)
I'm proposing this, aligned with @JimiC's idea.

**Comment by JimiC** [comment]
I'm still experimenting with icons. One idea was to use the `config` icon and make it `js-yellow` for `jsconfig` and `ts-blue` for the `tsconfig`.

**Comment by robertohuertasm** [comment]
We should have to see it. I'm really happy with the simple approach of the `js` and `ts` icons with the gear. You get the idea without any doubt. I'm concerned about the color association not being enough to fire the association in the mind of the user. Of course, once they read the name of the file it will be obvious but, as I said, I think your initial idea was the best for those. @jens1o, @ZanderBrown  what do you think?

**Comment by ZanderBrown** [comment]
Whilst i like the icon with the gear the demonstration shows that it's fairly unnoticeable at the small size.

Perhaps a simple cog but in the two respective colours would be better? Possibly with the ts/js overlaid in white? (Sort of flip your example the other way round)

**Comment by JimiC** [comment]
@ZanderBrown Something like this?

[Samples](https://gist.github.com/JimiC/2867244e14500cc9f4fa43385122bf0b)

## Preview: ##
![screenshot - 19_02_2017 17_18_40](https://cloud.githubusercontent.com/assets/1716442/23103661/79b2cd28-f6c7-11e6-8a70-7f48f9cfd034.png)

**Comment by robertohuertasm** [comment]
Hi guys, I like the concept but not the icons. They remind me these `web 2.0` logos that populated the web a few years ago. 

I think the problem is the gear icon that we're using. It works in gray because the color reinforces the meaning of the shape. In my opinion, without the inner circle and so full of color the icon is far from recalling a gear.

For the record, I've also tested it with the inner circle, but still it doesn't work for me, it seems more like a daisy flower than a config icon.

For the moment, although not being perfect, I prefer the first proposal as It's aligned with the `js` and `ts` and it only supposes a slight and subtle modification.

![image](https://cloud.githubusercontent.com/assets/696981/23104883/74d32bd6-f6d6-11e6-8548-2b8c041da7b9.png)

**Comment by robertohuertasm** [comment]
For the moment, I've pushed the previous icons. They will be published in the next release.
