### ISSUE TITLE
[Icon Request] Support for stylus

### ISSUE THREAD

**Issue by BodyaSeniv** [vscode-icons/vscode-icons#738]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`, `folder`
      - Icon Name: `stylus`
      - Sample original Icon: N/A
      - Extensions: `.styl`
More info @ http://stylus-lang.com/
**Thanks :smiley:**

**Comment by JimiC** [comment]
Already supported via `Stylus` extensions.

**Comment by BodyaSeniv** [comment]
Thanks for information. But no folder icon.

**Comment by BodyaSeniv** [comment]
@JimiC Thanks for information. But no folder icon.

**Comment by JimiC** [comment]
Please see #650.
