### ISSUE TITLE
Hide Folder icons is not working

### ISSUE THREAD

**Issue by jared-christensen** [vscode-icons/vscode-icons#739]
I think I have the setting correct but I still see the folder icons. It looks like this was an issue in the past and was closed. I created a new issue because it looks like it's back.

![settings_json_-_customer_assets](https://cloud.githubusercontent.com/assets/1406482/22890594/72c9e9a0-f1d2-11e6-98fa-48b7226825f9.png)

**Comment by jens1o** [comment]
Cannot reproduce. Did you run `>Icons: Apply Icons Customization`

**Comment by jared-christensen** [comment]
Running `Apply Icons Customization` did the trick, thanks! Somehow I missed that step.
