### ISSUE TITLE
[Icon Request] AngularJS .config.js .states.js .routes.js .const.js .util.js

### ISSUE THREAD

**Issue by BrunnerLivio** [vscode-icons/vscode-icons#740]
**Checklist:**
I want to add the following extension to the AngularJS Icon pack

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: extension
      - Icon Name: AngularJS
      - Extensions: 
*.config.js : purple icon, like .module.js
*.states.js & *.routes.js  : yellow icon, like .routing.js
*.const.js & *.constant.js : dont care the icon color
*.util.js : don't care the icon color

**Comment by JimiC** [comment]
@BrunnerLivio Can you provide any documentation where those extensions are recommended to be uses in an AngularJS project structure?

**Comment by robertohuertasm** [comment]
@JimiC is right. We are not willing to support generic extensions like `.const.js`, `util.js` and so on. For that, you have the ability to create your own icon associations. Just take a look to [the documentation](https://github.com/vscode-icons/vscode-icons#fine-tuning) to see how it works.

**Comment by BrunnerLivio** [comment]
@JimiC I often use the [UI-Router example ](https://github.com/ui-router/sample-app-ng1) christopherthielen, which features most of the named extensions. util.js, const.js, routes.js, constant.js are not featured in this example project and are not in a documentation, but I thought they are nice to have. Unfortunately I did not find a written documentation, just this example. I don't know if this is enough as a reference...

**Comment by robertohuertasm** [comment]
From my point of view these extensions are not really Angular scoped so I don't see the point on supporting them. We already support `custom associations` which was explicitely created to fulfill this kind of needs.

**Comment by JimiC** [comment]
@BrunnerLivio We have already talked about AngularJS support (#686) with @robertohuertasm and we agreed to only support `route.js`, `route.ts` by associating to `ng_routing_*` icons. As I have worked on an AngularJS project in the past, we used the UI-router but the states were declared inside the `app.js`. I'm going to investigate your request a little further when time allows.

**Comment by robertohuertasm** [comment]
@JimiC, do you have some further suggestion about this issue? If not I think we could close it.

**Comment by JimiC** [comment]
@robertohuertasm I'm leaving this open to iterate on it when I have some time to work on implementing the `AngularJS` detection.
