### ISSUE TITLE
Support regex or Ant-style full filepath matching

### ISSUE THREAD

**Issue by rnemec** [vscode-icons/vscode-icons#743]
Hi, did you consider supporting broader matching so that somebody can customize 'server/api/**/*.js' to have different icon from 'server/lib/**/*.js' and from 'client/lib/*.js'?

I think that (along with custom icons) would be extremely powerful. You may later consider allowing people to package their customizations and publish them on github.

**Comment by JimiC** [comment]
I believe this is not supported by `vscode`... yet.

**Comment by robertohuertasm** [comment]
@rnemec as @JimiC said, this is not still supported by `vscode`. Check [vscode#12493](https://github.com/Microsoft/vscode/issues/12493#issuecomment-249117649) and #328
