### ISSUE TITLE
[Icon Request] Support for HTTP file

### ISSUE THREAD

**Issue by Huachao** [vscode-icons/vscode-icons#748]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [extension]
      - Icon Name: [http]
      - Extensions: .http

**Comment by JimiC** [comment]
Any suggestions for an icon?

**Comment by Huachao** [comment]
@JimiC sorry I didn't have any good idea on the icon

**Comment by JimiC** [comment]
@Huachao Sorry, but I can't find any reference to this type of file extension. Can you provide additional info?

**Comment by JimiC** [comment]
Closing due to lack of response.

**Comment by RobPethick** [comment]
@JimiC this would be to support HTTP request files, for use with the extension https://marketplace.visualstudio.com/items?itemName=humao.rest-client

Maybe take their {} as inspiration (though that kinda suggests JSON which is no limitation of the file in general) or an up-down arrow pair to symbolise request response?

**Comment by jens1o** [comment]
@RobPethick May you open a new issue instead?

**Comment by RobPethick** [comment]
of course :)
