### ISSUE TITLE
Make json icon smaller

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#749]
In my opinion, `json` icon is way to big. I think we should reduce its size a little.

**Comment by JimiC** [comment]
The current size is already 2px smaller than the guideline, meaning it's actually 28x28 px. I believe its size is just fine for it to be distinguishable and noticeable.

(Joke) Maybe you should join me in the O.C.D. therapy class.

**Comment by robertohuertasm** [comment]
![image](https://cloud.githubusercontent.com/assets/696981/23061294/81c03fb8-f501-11e6-8aa4-0b29569e5f2f.png)
As you can see here it's considerably bigger than other icons that we have. Or maybe some other icons are considerably smaller than this one. Anyway, from a perceptual point of view, leaving aside numbers, this icon looks huge.

**Comment by JimiC** [comment]
No, it's not. You just picked the `ts` icon that happens to have a size of 24px width (because you chose to make it so) and the proportional height (15.8px). `json` icon also has proportional size.

Speaking of "perceptual point of view", we have released this icon for a while now and you are the only one complaining.

**Comment by jens1o** [comment]
I disagree with you Roberto, I think the json icon needs to be smaller.

**Comment by robertohuertasm** [comment]
@jens1o you agree with me or disagree? Because I'm saying that the icon should be smaller.

**Comment by robertohuertasm** [comment]
@JimiC, I'm the one complaining for the moment, but I could argue that you're the only one defending it. That's not a valid argument at all.

**Comment by JimiC** [comment]
@robertohuertasm You realize that we two are the only ones discussing this (I don't count @jens1o because he always agrees with you whenever we have a dispute).

So I return your comment 
>...That's not a valid argument at all.

**Comment by robertohuertasm** [comment]
Sorry @JimiC but I think you've totally lost your point. You don't count @jens1o because he always agrees with me? That would make 2 of us complaining. We may think alike but he has his own criteria.

**Comment by robertohuertasm** [comment]
I'm under the impression that you think I want it to make it tiny. But that's not the case.

It's a matter of 2 pixels or so. Check out the first `json` icon size.

![image](https://cloud.githubusercontent.com/assets/696981/23068255/381ea6fc-f523-11e6-95d4-4b391cffe380.png)

**Comment by JimiC** [comment]
No joke this time. 
> Maybe you should join me in the O.C.D. therapy class.

**Comment by jens1o** [comment]
Fixed my statement. I think the json icon is just in the perfect size.

**Comment by robertohuertasm** [comment]
Thanks @jens1o for your clarification. I do value your opinion. 

Being the only one of the team thinking like this I will leave this open for a few days in case anyone else wants to say something (be it in one way or another) and close it.

@JimiC, I really value your ideas and I know you don't meant any bad but in general I would ask you to soften your tone. It's difficult to know what are the real intentions of people behind a keyboard so let's try to avoid misunderstandings and be more delicate when addressing to each other.

**Comment by JimiC** [comment]
@robertohuertasm I only have to say this. Being involved in this project has stopped being fun. I'll explain why in private.

**Comment by robertohuertasm** [comment]
@JimiC fair enough.

**Comment by robertohuertasm** [comment]
Closing this for good.
