### ISSUE TITLE
.idea folder icon is hard to see

### ISSUE THREAD

**Issue by Gama11** [vscode-icons/vscode-icons#752]
In this example, it's fairly hard to tell the difference between the default folder icon and the one for `.idea`:

![](http://i.imgur.com/azgDTUw.png)

I think the `.idea` folder needs to be colored differently for improved contrast.

**Comment by jens1o** [comment]
Any alternative idea?

**Comment by Gama11** [comment]
A black folder, maybe? IntelliJ's logo is black after all.

**Comment by robertohuertasm** [comment]
Hi @Gama11, although I agree that the color is pretty similar to the color of the normal folder I think the logo is colorful enough to make this folder noticeable. The problem with dark colors or black is that they don't work well with dark themes. It would work great in light themes though, but we have to think in all kind of themes. Surely, we could do two versions of the icon but although this is a common approach with some of the icons, folders are usually keeping the same look and feel.

**Comment by robertohuertasm** [comment]
I'm closing this for the moment.
