### ISSUE TITLE
Translation won't be shown?

### ISSUE THREAD

**Issue by jens1o** [vscode-icons/vscode-icons#771]
**Checklist:**

- [X] I'm sure this issue is not a *duplicate*?

![image](https://cloud.githubusercontent.com/assets/11234139/23344118/01f97858-fc77-11e6-9eca-1fbbadb23881.png)
![image](https://cloud.githubusercontent.com/assets/11234139/23344124/19e9163a-fc77-11e6-9c66-c2020473bd90.png)

**Comment by JimiC** [comment]
This is not supported from `vscode`. I intended to raise an issue at their repo. Do you want to do it?

**Comment by jens1o** [comment]
Why did we even implemented that?

Okay, I can do it. But don't get angry with my English 😄

**Comment by jens1o** [comment]
Please don't kill me: https://github.com/Microsoft/vscode/issues/21458

**Comment by JimiC** [comment]
Fixes in #790.
