### ISSUE TITLE
How to get rid of association icon for "view" or "views" folder?

### ISSUE THREAD

**Issue by noNameInCity** [vscode-icons/vscode-icons#787]
How to get rid of association icon for "view" or "views" folder?
I try set this up in settings but it doesn't work.

![obraz](https://cloud.githubusercontent.com/assets/17949132/23456740/00e3af74-fe75-11e6-96cd-31fb2a8260f7.png)

**Comment by JimiC** [comment]
Do you want specifically this one or all folders to show the default icon?

**Comment by noNameInCity** [comment]
Only this one.

**Comment by JimiC** [comment]
Go to `File > Preferences > Settings` and add in `User Settings` the following:

```
"vsicons.associations.folders": [
    { "icon": "view", "disabled": true }
]
```

then press `F1` and type `Icons`, select `Apply Icons Customization`.

**Comment by noNameInCity** [comment]
Doesn't work.
Also worth to mention I tried also:
```
"vsicons.associations.folders": 
[
	{ 
		"icon": "view",
		"extensions": ["view", "views"], 
		"format": "FileFormat.svg",
		"disabled": true
	}
]
```

**Comment by JimiC** [comment]
It works. I tested it. Check again.
Don't use your way it's wrong association.

**Comment by JimiC** [comment]
@noNameInCity Try
```
"vsicons.associations.folders": [
    { "icon": "view", "extensions": [], "disabled": true }
]
```
you may've been hitting a bug I found.

**Comment by noNameInCity** [comment]
Terribly sorry, you right. After reinstall plugin it works.
