### ISSUE TITLE
[Icon Request] Support for nyc (Istanbuljs)

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#810]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension\filename`
      - Icon Name: `nyc`
      - Sample original Icon: ![logo](https://avatars2.githubusercontent.com/u/13523395?v=3&s=200)
      - Filename: `.nycrc`

More info @ https://github.com/istanbuljs

**Comment by JimiC** [comment]
I have requested an SVG version of the logo on the official [repo](https://github.com/istanbuljs/istanbuljs.github.io/issues/34).

**Comment by lednhatkhanh** [comment]
+1 for this!
