### ISSUE TITLE
extension available as vsix

### ISSUE THREAD

**Issue by KhmerBoi1** [vscode-icons/vscode-icons#815]
Would like to request your icon set be published and available as a .vsix for use with Visual Studio Community / Professional / Enterprise.

**Comment by robertohuertasm** [comment]
Have you seen [@madskristensen FileIcons](https://github.com/madskristensen/FileIcons)? He seems to be using some of our icons.

**Comment by KhmerBoi1** [comment]
Maybe I should write an Issue/Request on his repository. I liked yours so much and your so much and yours does folders as well.

**Comment by robertohuertasm** [comment]
The objective of this extension is not to cover Visual Studio. I guess it would be best to reach to @madskristensen repo and ask him.

**Comment by robertohuertasm** [comment]
Thanks! I'm closing this.
