### ISSUE TITLE
With the last update, the Angular icons stopped working

### ISSUE THREAD

**Issue by rafaelbatistamarcilio** [vscode-icons/vscode-icons#818]
I updated the plugin and the Angular icons are gone

![image](https://cloud.githubusercontent.com/assets/16135328/24076255/d8555cd0-0c0a-11e7-8469-1babc9a83897.png)

**Comment by robertohuertasm** [comment]
Hi @rafaelbatistamarcilio, now the angular icons are disabled by default. If you want to enable them you'll have to toggle the angular preset manually (F1 > Icons: Toggle Angular preset) or enable the `project detection` .

Unfortunately, I think we've got a bug here. As the folders will disappear... Let me check this until I can offer you a proper solution.

**Comment by robertohuertasm** [comment]
@rafaelbatistamarcilio, if you're using Windows you shouldn't find any issue. Just apply the Angular toggle or enable `project detection` (F1 > Icons: Reset Project Detection Defaults).

**Comment by rafaelbatistamarcilio** [comment]
Worked perfectly! Thank you very much!
