### ISSUE TITLE
[Icon request] Support for CMake files

### ISSUE THREAD

**Issue by ffes** [vscode-icons/vscode-icons#823]
**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request

From https://cmake.org/

> CMake is an open-source, cross-platform family of tools designed to build, test and package software.

Both the full filename `CMakeList.txt` as well as the file extension `*.cmake` are used.

An icon can be found at https://openclipart.org/detail/214008/cmake
In this icon the colors have be reduced, which I think could help when it is being used as icon.

**Comment by JimiC** [comment]
Already supported via extension. Look in Marketplace.

**Comment by robertohuertasm** [comment]
Just to make this clearer. We do support  `.cmake` already but we only show the icon when you have a `CMake` extension installed. That's the way icons and files are associated in certain cases. That allows us to only worry about the icon and not so much about the associations, which are provided by the `CMake` extension.

**Comment by ffes** [comment]
@robertohuertasm Thanks for clarifying this

**Comment by JimiC** [comment]
@robertohuertasm I suppose it's prudent to add another section in README for what icons are supported via installed extensions.

**Comment by robertohuertasm** [comment]
I think so. This is a point that can lead to a lot of confusion. People expect their icons to work out of the box. That's a thing we already discussed. I can't stop thinking that we maybe should provide some associations even if they already have a `language id` association.
