### ISSUE TITLE
[Icon Request] CAKE folder

### ISSUE THREAD

**Issue by mmisztal1980** [vscode-icons/vscode-icons#824]
vscode-icons already supports **.cake** files, however it would also be nice if it would highlight CAKE's folder in a similar way that **.nuget** folder is being highlighted:

the folder's name is **CAKE** and it's typically located within the **tools** folder.

![cakefolder](https://cloud.githubusercontent.com/assets/1357057/24100617/498dcd04-0d75-11e7-9bf7-8d90359432f4.png)

**Comment by JimiC** [comment]
Please see #650.
