### ISSUE TITLE
Restoring the icon manifest doesn't reset the presets.

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#826]
- [x] I'm sure this issue is not a *duplicate*?

While I was testing the toggle functionality on some improvements I'm making, I noticed that restoring the icon manifest has a side effect because the presets don't get reset.

Steps to reproduce:
 1. Toggle any preset.
 2. Restore the icon manifest.
 3. Toggle the preset again.

Notice here that on step 3 the toggle message is wrong and upon toggling in step 3 any other set preset is reapplied.

Awaiting confirmation.

**Comment by jens1o** [comment]
I thought this is a feature 😆 Do we need to fix it? I like the way how it goes.

**Comment by JimiC** [comment]
@jens1o Some fix is needed but I'm not sure which one, cause there are two ways to fix this.

**Comment by jens1o** [comment]
What are the options?

**Comment by JimiC** [comment]
Either reset the presets or scan the `icons.json` file to determine the state of the icons, in order to present the correct message..

**Comment by robertohuertasm** [comment]
I would go with the second option.
