### ISSUE TITLE
Support .jestrc extension for Jest

### ISSUE THREAD

**Issue by Thiht** [vscode-icons/vscode-icons#828]
- [x] I'm sure this issue is not a *duplicate*?

Hi,

Following the issue https://github.com/vscode-icons/vscode-icons/issues/496 the extensions "jest.json" and  "jest.config.json" are supported for Jest config files. In the code: https://github.com/vscode-icons/vscode-icons/blob/95aadbbd92949a94af372effeb502d47f6821fb1/src/icon-manifest/supportedExtensions.ts#L178

Could you also support ".jestrc"?

Some real examples of existing .jestrc files for reference:

* https://github.com/gilbarbara/react-joyride/blob/master/.jestrc
* https://github.com/kuitos/es6-http-utils/blob/master/.jestrc
* ...

Thanks!

**Comment by JimiC** [comment]
I'm not sure how we should proceed with this.
According to `Jest` [`.jetrc` is not yet officially supported](https://github.com/facebook/jest/pull/2445).

@robertohuertasm You have worked with `Jest` more than me. I leave this to you.

**Comment by Thiht** [comment]
Officially Jest doesn't support a dedicated config file, other than package.json. It's possible to give it a custom config file but the name can be anything, hence the "jest.json" and "jest.config.json" currently supported by vscode-icon. I'm pretty sure these two filenames are not more standard than .jestrc.

**Comment by JimiC** [comment]
@Thiht You are wrong. In early `Jest` docs the proposed way was the `package.json` and alternative `jest.json` or `jest.config.json`, hence the support.

**Comment by Thiht** [comment]
I didn't know that!

I'm encline to believe you but I can't find [any reference on that](https://www.google.fr/search?q=jest.config.json&rlz=1C1CHBF_frFR734FR734&oq=jest.config.json&aqs=chrome..69i57j0.2895j0j4&sourceid=chrome&ie=UTF-8#q=%22jest.config.json%22&*), do you have one?

**Comment by JimiC** [comment]
Unfortunately, I can't find the reference on the `Jest` docs. The page has been changed and there is no evidence anymore to support my claim.

**Comment by robertohuertasm** [comment]
In my opinion, we could add this filename. Although not official there are some projects that are already using it and it may become eventually the preferred configuration file name. I see no harm in including it given that many people is using this convention.

**Comment by Thiht** [comment]
Also I guess it's worth mentioning that it's very unlikely ".jestrc" will ever conflict with something else :)
