### ISSUE TITLE
Improvement on angular detection

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#833]
Now, if you have the Angular preset on (let's say you're working on an Angular project with a specific vscode instance) and you decide to open a non-Angular project, the extension will warn you that you're not in an Angular project anymore. So far, so good.

The problem is that it will also set `"vsicons.presets.angular": false`, and even if you choose `Close` it will modify the `settings.json`.

I was thinking that this modification is not necessary. We don't need to mark every project as `angular: false` as that's the default state for the Angular preset. So if we find a non-Angular project and we happen to have the Angular preset on, we should have to only toggle the preset and not write into the `settings.json`.

**Comment by JimiC** [comment]
I'm already working on that but gave a priority on code coverage,

**Comment by robertohuertasm** [comment]
Cool @JimiC! I forgot to mention the case where we're currently having the Angular preset on and we access into another Angular project. Detection rises again asking for a restart. In this case, nothing should happen or, at least, only suggest to the `settings.json` modification as the restart is unnecessary.

**Comment by JimiC** [comment]
Also noticed it and preparing a fix. The whole detection logic will get a refactor as some things have been fixed from the side of the `vscode` team and the pre-preseting is now redundant. Preset will now change upon selecting an action and in the case of a `Close` actions, no actions will be taken resulting in a cleaner handling.

**Comment by Canaan-Jin** [comment]
I also met.
When i set ``vsicons.presets.angular`` as ``true`` and restart.
Then vscode will restart automatically two times, also set ``vsicons.presets.angular`` as ``false``.
Please forgive me for my poor English.
I don't know if I'm right.

**Comment by Okoyl** [comment]
I don't get angular icons, even when I set `"vsicons.presets.angular": true` at workspace settings.
Used to work flawlessly a few versions back without messing with any settings file.
my user settings:
```json
{
  "vsicons.projectDetection.disableDetect": false,
  "vsicons.projectDetection.autoReload": true,
  "vsicons.presets.foldersAllDefaultIcon": false
}
```

my workspace settings:
```json
{
  "vsicons.projectDetection.disableDetect": false,
  "vsicons.presets.angular": true
}
```

**Comment by JimiC** [comment]
@Okoyl It's mandatory to perform `F1 > Icons: Apply Icons Customizations` whenever you set a preset.
