### ISSUE TITLE
[Icon Request] Support for graphql files

### ISSUE THREAD

**Issue by AndrewShapel** [vscode-icons/vscode-icons#845]
**Current state**
![screen shot 2017-04-03 at 5 32 00 pm](https://cloud.githubusercontent.com/assets/7026419/24618595/38b15060-18a0-11e7-84e3-80e4ecb439ec.png)

**Expected state**
![screen shot 2017-04-03 at 5 28 06 pm](https://cloud.githubusercontent.com/assets/7026419/24618580/2bd0761e-18a0-11e7-8957-c924dc3022ad.png)

**Description:**

Add missed ".graphql" and ".gql" extensions for files to support graphql icon.

**Checklist:**

- [x] I'm sure this issue is not a *duplicate*?

Thanks.

**Comment by JimiC** [comment]
Install any from https://marketplace.visualstudio.com/search?term=graphql&target=VSCode&category=All%20categories&sortBy=Relevance
