### ISSUE TITLE
Suggestion: light theme icons

### ISSUE THREAD

**Issue by calrsom** [vscode-icons/vscode-icons#848]
It would be nice to have icons that work well with a light VSCode theme.  I use "Light+" which I believe is the default light theme.

In particular the javascript, JSON, babel and other yellow icons are hard to see on light gray.  I don't know if it makes sense to tweak said icons for better readability on all backgrounds, or try to build a light icon set.

**Comment by JimiC** [comment]
How about turning those yellow-ish icons into a more orange-ish one?

**Comment by calrsom** [comment]
Some kind of subtle outlining or shadowing could also improve the visibility without impacting dark theme too much.

**Comment by JimiC** [comment]
Looking again at this issue here is a screeny on how the yellow-ish icons look on `Light+` theme.

![screenshot - 08_07_2017 19_36_46](https://user-images.githubusercontent.com/1716442/27987355-0343c47e-6415-11e7-99e7-8333c7518f19.png)

In my opinion, those that are hard to see are:
- babel
- json
- js
- vash

I have included the `bolt` icon in the screeny cause I'm considering using its color. Thought?

**Comment by jens1o** [comment]
gosh...

The color of bolt is quite cool.

**Comment by JimiC** [comment]
@calrsom I experimented with the idea of adding a shadow/glow around the logos but the result is disappointing. I think I'm gonna stick with the idea of using a darker yellow-ish color.

**Comment by JimiC** [comment]
Here is how they look after switching to the `bolt` color :

![screenshot - 08_07_2017 20_12_01](https://user-images.githubusercontent.com/1716442/27987661-cb21d964-6419-11e7-86b7-457cd9928d7d.png)

**Comment by jens1o** [comment]
I think we ran into another problem... the icons where at the lower right hand corner is the js symbols are hard to recognize, I think.

**Comment by JimiC** [comment]
@robertohuertasm Any thoughts on this?

**Comment by robertohuertasm** [comment]
I like the new yellow! 👍

**Comment by JimiC** [comment]
Now the next question is: Should these yellow-ish icons be only for the light themes or should they be generic?

**Comment by robertohuertasm** [comment]
Good question... I would keep them specific. Although it means more work, we only avoid the real yellow for users not using darker themes. What do you think?

**Comment by JimiC** [comment]
Specific it is then.

**Comment by calrsom** [comment]
Definitely an improvement.  Thanks for working on this!
