### ISSUE TITLE
[Icon Request] Git Submodules Folder Icon

### ISSUE THREAD

**Issue by msqaddura** [vscode-icons/vscode-icons#853]
It would really great and I would be really thankful if you could add a distinct icon for git submodules.

Thanks :smile:

**Checklist:**

- [x] I'm sure this issue is not a *duplicate*
- [x] I want to create an icon request:
      - Type: [extension/folder]
      - Icon Name: [Git Submodule]
      - Extensions: folder

**Comment by JimiC** [comment]
Anyone has an artistic opinion on the icon?

**Comment by JimiC** [comment]
Although this should have been requested in #650, I'll make an exception to discuss the artistic concept here and then move it to the said issue.

**Comment by JimiC** [comment]
@msqaddura Because I once worked with a repo that had `git-submodules` but it was a long time ago, can you remind me what is the name of the folder that `git submodule` command creates or is it just `submodule`?

**Comment by msqaddura** [comment]
My apologies for missing 650
As per the naming,Usually the name of the folder is up to cloner, but conventionally people use 'submodules'. maybe some people prefer adding a suffix or prefix.

**Comment by JimiC** [comment]
@MarcosMeli We can only support fixed names.

**Comment by msqaddura** [comment]
'submodules' should do fine

**Comment by JimiC** [comment]
@robertohuertasm @jens1o @msqaddura Should we associate this to the [`git` folder icon](https://github.com/vscode-icons/vscode-icons/blob/master/icons/folder_type_git.svg)?

**Comment by robertohuertasm** [comment]
I was about to suggest the same... so it's ok for me.

**Comment by jens1o** [comment]
It's ok for me too!

**Comment by msqaddura** [comment]
yup that is perfect, thanks alot for your quick response and collaboration.
this is the only icon extension i used and i believe it will be the only one forever ;)
keep it up (y)
