### ISSUE TITLE
[Suggestion] Add Greenkeeper to DevOps.

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#855]
As discussed adding [Greenkeeper](https://greenkeeper.io) service would be a nice addition to our DevOps.

In order to activate it see: https://github.com/integration/greenkeeper

@robertohuertasm I would suggest giving it access only to this repo.

**Comment by robertohuertasm** [comment]
@JimiC I already granted Greenkeeper to this repo.

**Comment by JimiC** [comment]
It should had created a PR to upgrade the dependencies. I'm currently out of town for the weekend. If it does not resolve talk on Monday.
