### ISSUE TITLE
After last update individual icons for jsx are gone

### ISSUE THREAD

**Issue by bigkrp** [vscode-icons/vscode-icons#859]
### Gones jsx icon
![default](https://cloud.githubusercontent.com/assets/11586744/24740584/8fff20a2-1aaa-11e7-8f34-2bcd9483cae1.JPG)

- [ ] OS: Windows 10
- [ ] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: file_type_reactjs
      - Sample original Icon (32x32/svg/transparent whenever possible): https://github.com/vscode-icons/vscode-icons/blob/master/icons/file_type_reactjs.svg
      - Extensions: .jsx
-[ ] VSCode verion: 1.11.0
-[ ] vscode-icons version: 7.5.1

**Comment by jarshwah** [comment]
Thank you! I wasn't sure if it was the update or something with my system. I'm also missing jsx icons.

**Comment by JamesRamm** [comment]
I have the same problem on Ubuntu. I dont even get JS icons - just a generic file icon.

**Comment by robertohuertasm** [comment]
@JamesRamm I've just tested in Ubuntu and it seems to be working fine. I'd suggest you to reinstall the extension and see if it works.

**Comment by robertohuertasm** [comment]
![jsreact](https://cloud.githubusercontent.com/assets/696981/24743389/5191f778-1aae-11e7-8d60-b0c9c2c42c03.png)

@bigkrp @JamesRamm can you let me know what you see when you have a `jsx` file selected? You should see something similar to the image above.

**Comment by bigkrp** [comment]
I have Javascript (Babel).
![babel](https://cloud.githubusercontent.com/assets/11586744/24743574/697c03ca-1ab7-11e7-93dd-cea72a3656b7.JPG)

When I try to select react, there are also no icon
![no_react_js](https://cloud.githubusercontent.com/assets/11586744/24743593/7f13d94c-1ab7-11e7-89e5-c7c69b44f6d2.JPG)

**Comment by robertohuertasm** [comment]
That would explain everything. `jsx` association is done via language id. Which babel extension are you using to get that language id?

**Comment by robertohuertasm** [comment]
Is this [one](https://marketplace.visualstudio.com/items?itemName=dzannotti.vscode-babel-coloring)?

**Comment by bigkrp** [comment]
@robertohuertasm yes, i use this extension for colorize code!
Should i turn off this extension?

**Comment by robertohuertasm** [comment]
The problem lies on how the babel extension is configured. It associates `jsx` files to `javascript` instead of `javascriptreact`.

[Check this out](https://github.com/microsoft/vscode/blob/master/extensions/javascript/package.json#L24-L54) to see how default vscode extensions deal with this.

Babel extension, instead, just does [this other thing](https://github.com/dzannotti/vscode-babel/blob/master/package.json#L31-L43).

The way to fix it would be either manually associate `jsx` files again with `Javascript React` or tell the author of the plugin about this and see if he/she can fix it.

**Comment by robertohuertasm** [comment]
On the other hand, if none of the other is an option to you, you can always use `custom file associations` by putting something similar to this in your `settings.json`.

```
"vsicons.associations.files": [
    { "icon": "reactjs",  "extensions": ["jsx"], "format": "svg" }
  ]
```` 

After that, `F1 > Icons: Apply Icons Customization`

**Comment by JimiC** [comment]
Looks like our extension exposes bugs on other extensions due to the `language id` support.

**Comment by bigkrp** [comment]
@robertohuertasm thx! It's helped me!
I think it's problem, when vendor plugins could not get agree for filename associations between themselves

**Comment by jarshwah** [comment]
Thanks for leading me to the problem. For my issue, the problem extension was https://marketplace.visualstudio.com/items?itemName=TwentyChung.jsx which takes the file association, that doesn't map to an icon set. Either uninstalling that extension, or setting the following in settings.json solves the problem.

```
"files.associations": {
        "*.jsx": "javascriptreact"
    },
```

**Comment by mindwarrior** [comment]
For me it was as simple as click on the language shown at bottom right > Configure file association > select Javascript React.

**Comment by JoyAhmed** [comment]
I added the followings in ### settings.json and it worked 
	
	"material-icon-theme.activeIconPack": "react_redux",
	"workbench.iconTheme": "material-icon-theme"

**Comment by robertohuertasm** [comment]
@JoyAhmed It seems you're just using another theme.
