### ISSUE TITLE
How do you set the changed the menu bar

### ISSUE THREAD

**Issue by jose-a-sa** [vscode-icons/vscode-icons#860]
How did you managed to make the Windows bar have the same background as the menu bar ? (image on README.md)

![sem titulo](https://cloud.githubusercontent.com/assets/13206784/24731706/b22512dc-1a63-11e7-8233-d5495cc0afc3.png)

Regards, José

**Comment by JimiC** [comment]
Yeah @robertohuertasm tell us what color theme you us? 🥇

**Comment by robertohuertasm** [comment]
I think this was something from previous VSCode versions. Now I see it like you. 

If you're curious about my theme of choice I'm using [Atom One Dark Theme](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark). With today VSCode's update you can unify the color of the sidebar like this:

```
"workbench.experimental.colorCustomizations": {
    "sideBarBackground": "#282c34"
  },
```

Pretty cool! 😁

**Comment by jens1o** [comment]
I would passed this on the readme. There it was... Was. Consider add it again?

**Comment by robertohuertasm** [comment]
@jens1o you mean recreate the animated gif?

**Comment by jens1o** [comment]
Nah, we had a caption under the gif, with the theme name.

**Comment by jose-a-sa** [comment]
@robertohuertasm I'm talking about the difference between the `File Edit ...` bar and the vscode window title bar not the workbench themes. Mine have diferente background and in the gif they are the same.

**Comment by JimiC** [comment]
@jose-a-sa If I'm not wrong that color is set by `Electron` itself. Probably when @robertohuertasm made the gif the `Electron` menu bar had the same color with the title bar. `vscode` now uses `Electron` 1.4.6.
