### ISSUE TITLE
React icons in Vue project after recent update

### ISSUE THREAD

**Issue by palemajki** [vscode-icons/vscode-icons#863]
**Checklist:**
- [x] I'm sure this issue is not a *duplicate*?

Hi,
thank you very much for you great work! But I've noticed, after one of the latest updates, in my Vue project, my normal *.js files got React icons.
I suppose it's because of the folders structure, but I'm not sure.
Any ideas how to restore normal "JS" symbols next to those files?

Thanks,
W.
![image](https://cloud.githubusercontent.com/assets/16974866/24816857/bcb554fa-1bda-11e7-8ac5-80f31a2b275b.png)

**Comment by jens1o** [comment]
Huuh. Same thing here. I'm waiting for the others to verify it.

In the meantime add this to your settings:
```js
"files.associations": {
        "*.js": "javascript"
}
```

**Comment by JimiC** [comment]
Please provide version of VS Code.

**Comment by palemajki** [comment]
Hi, 1.11.1

**Comment by JimiC** [comment]
I can't recall seeing it on mine. Could the cause be one of the extensions you use?

**Comment by JimiC** [comment]
I can't recall seeing it on mine. Could the cause be one of the extensions you use?

**Comment by JimiC** [comment]
@palemajki One of the extensions you use is causing the side effect. My copy shows `js` files with the correct icon.

**Comment by palemajki** [comment]
@JimiC thank you for checking it out, I guess we can close this issue - solution provided by @jens1o is good enough.
It's hard to tell which extension is causing it, as I have no React-specific extensions.

**Comment by JimiC** [comment]
You can always try to  disable them one by one and observe the results.
