### ISSUE TITLE
JSX icons missing

### ISSUE THREAD

**Issue by coRz** [vscode-icons/vscode-icons#867]
JSX file type icons missing

**Comment by robertohuertasm** [comment]
@coRz have you checked out #859? Can you let me know if you use any special extension? It should be working.

**Comment by coRz** [comment]
` "files.associations": {
    "*.jsx": "javascriptreact"
  },`

This has solved the issue, I thought it was configured to have this as default.

**Comment by robertohuertasm** [comment]
`jsx` is managed via language id. The fact that you're not seeing this association as default is indicating that some of your extensions has changed this association. Doing what you did forces the association and doesn't care about language id settings.
