### ISSUE TITLE
[Icon Request] Support More files in Laravel

### ISSUE THREAD

**Issue by mamadoo** [vscode-icons/vscode-icons#870]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: filename
      - Icon Name: artisan
- [x] I want to create an icon request:
      - Type: filename
      - Icon Name: webpack
      - Extensions: .mix.js
- [x] I want to create an icon request:
      - Type: extension
      - Extensions: .htaccess

VSCode-icons doesn't support Laravel project icons completely.

![laravel icons](https://cloud.githubusercontent.com/assets/6822354/24898538/8604a5d4-1eb2-11e7-8d7a-683c518ed968.png)

Please add this icon.

**Comment by jens1o** [comment]
.htaccess should be covered by apache, I added it.

**Comment by mamadoo** [comment]
I don't want to install another extension for support Apache.
No i don't have suggestion for that.

**Comment by mamadoo** [comment]
I don't want to install another extension for support Apache.
No i don't have suggestion for that.

**Comment by JimiC** [comment]
@mamadoo If you don't want to install another extension your only other options is to use the `customization` feature.

**Comment by JimiC** [comment]
`laravel` is supported by `id: blade`. Looking at the extensions in the market we need to add also support for `id: laravel-blade`.

`webpack.mix.js` seems to be also used in many projects so it's a candidate for addition.

`.htaccess` is already supported by `language id`.

@robertohuertasm Thoughts?

**Comment by mamadoo** [comment]
Thanks @JimiC

**Comment by Dronax** [comment]
-----
da

**Comment by Dronax** [comment]
------
da
------
==========================

**Comment by jens1o** [comment]
@dronax what's up?
