### ISSUE TITLE
[Icon Request] Support for Harbour [xBase] file

### ISSUE THREAD

**Issue by riverbr** [vscode-icons/vscode-icons#876]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: extension
      - Icon Name: harbour
      - Extensions: .prg, .fmg, .hbp, .hbp, .rc

**Comment by JimiC** [comment]
Icon: https://harbour.github.io/images/harbour-full.svg
More info @ https://harbour.github.io/
