### ISSUE TITLE
Folder icons for `configs` and `public`

### ISSUE THREAD

**Issue by svipben** [vscode-icons/vscode-icons#877]
Hello,

It will be very cool to have icons for folders like `configs` and `public`.

**My opinion `public` can be something like that:**

![matt-icons_folder-internet-300px](https://cloud.githubusercontent.com/assets/10441177/25149878/a5f2e6ae-2488-11e7-9dad-93418a695af3.png)

![globe](https://cloud.githubusercontent.com/assets/10441177/25149888/b0cdf8b6-2488-11e7-98af-e22cc1de7b60.png)

**My opinion `configs` can be something like that:**
![1492562777_prefs](https://cloud.githubusercontent.com/assets/10441177/25149935/e9a4289a-2488-11e7-85ae-1411f77c7aca.png)

![option_folder](https://cloud.githubusercontent.com/assets/10441177/25149945/f0de8808-2488-11e7-89d1-67b7fab203d8.png)

**Comment by JimiC** [comment]
Please read #650.
