### ISSUE TITLE
Support for Shopify liquid file

### ISSUE THREAD

**Issue by martinBadin** [vscode-icons/vscode-icons#878]
- [x] I want to create an icon request
      - Type: extension
      - Icon Name: liquid
      - Sample original Icon: [link](https://cdn.shopify.com/assets2/partners/shopify-cheat-sheet/shopify-cheat-sheet-social-790bf73396459c098c9b401e45debf7f28d65746b6dafe5a9317ac68d97f746a.png)
      - Extensions: .liquid

**Comment by martinBadin** [comment]
Hi, please change color for this icon. Not see her. Thank you.

![snimka obrazovky 2017-04-25 o 6 54 39](https://cloud.githubusercontent.com/assets/5845264/25369474/6578dc04-2984-11e7-9d49-8cbed805f5bf.png)

**Comment by martinBadin** [comment]
Hi, please change color for this icon. Not see her. Thank you.

![snimka obrazovky 2017-04-25 o 6 54 39](https://cloud.githubusercontent.com/assets/5845264/25369474/6578dc04-2984-11e7-9d49-8cbed805f5bf.png)

**Comment by JimiC** [comment]
To be honest I didn't check how it looked in the diff themes. Indeed it has to change.

**Comment by martinBadin** [comment]
This is default theme
