### ISSUE TITLE
VSCode reloads multiple times

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [vscode-icons/vscode-icons#897]
I have noticed that once vscode-icons extension is enabled each time on project opening (switching) vscode window reloads few times.

v.7.6.0 (I have noticed this behavior few versions earlier)

**Comment by JimiC** [comment]
You have `Project Auto Detection` `Auto-Reload` enabled.
To disable it `F1 > Icons: Reset Project Detection Defaults`.

**Comment by vytautas-pranskunas-** [comment]
Thank you. Why it cannot be disabled by default when installing / updating package?

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/issues/857#issuecomment-291614857
https://github.com/vscode-icons/vscode-icons/issues/857#issuecomment-291792459

**Comment by aellis** [comment]
Thanks for the tip @JimiC

**Comment by robertohuertasm** [comment]
@vytautas-pranskunas- do you still need some more feedback on this or can we close this issue?
