### ISSUE TITLE
[Icon Request] Support for Smali Language

### ISSUE THREAD

**Issue by LnsooXD** [vscode-icons/vscode-icons#898]
- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: `extension`
      - Icon Name: `smali`
      - Sample original Icon: N/A
      - Extensions: `.smali`

More info @ http://baksmali.com/

**Comment by robertohuertasm** [comment]
@LnsooXD why did you close it?
