### ISSUE TITLE
[Feature request] Extend webpack config file match pattern

### ISSUE THREAD

**Issue by Verbon** [vscode-icons/vscode-icons#907]
Please, extend webpack config file match pattern.

For now, if I have multiple webpack config files that have names other than 'webpack.config.js', I see the following picture:
![image](https://cloud.githubusercontent.com/assets/9406367/25637842/072e3c78-2f8f-11e7-9844-1a71f071c7db.png)

It confuses me a little bit, so I would love all files matching the regexp "webpack(\\..+)+.js" 'webpack.common.js', etc. to have the same icons as 'webpack.config.js' file.

Actually, [Material Icon Theme VS Code extension](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) has this feature:
![image](https://cloud.githubusercontent.com/assets/9406367/25637749/c4bb49ee-2f8e-11e7-966d-b4079f572321.png)

I really love vscode-icons, so I would like to see this feature in one of the next releases.

**Comment by jens1o** [comment]
There are some extension already added regarding webpack, but these are missing, yeah. (Since we can't have glob support 😢 )

https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L380-L425

I created a pr for this.  #910

**Comment by dyst5422** [comment]
Why no glob support?

**Comment by jens1o** [comment]
@dyst5422 Ask the `vscode` team, that was their decision... 😭
