### ISSUE TITLE
[Icon Request] Support for .bolt 

### ISSUE THREAD

**Issue by orouz** [vscode-icons/vscode-icons#908]
firebase has a security rules language that can be written in `.bolt` files 
they seem to have an icon too 
- Type: .bolt 
- Icon Name:  [bolt](https://github.com/firebase/bolt/blob/master/docs/images/flash.png)
- Extensions: .bolt

**Comment by jens1o** [comment]
I think we implemented that. Let me check.

**Comment by JimiC** [comment]
This should be supported via https://marketplace.visualstudio.com/search?term=bolt&target=VSCode&category=All%20categories&sortBy=Relevance with `language id: bolt`

**Comment by jens1o** [comment]
ah, I searched for extensions...

**Comment by robertohuertasm** [comment]
For what I see we don't have this icon yet. @JimiC was just pointing out that we have to support it via language id.
