### ISSUE TITLE
[Conflict] HTML Icon not visible with Aurelia plugin

### ISSUE THREAD

**Issue by sabinrimni** [vscode-icons/vscode-icons#909]
.html file icons set to generic icons when the [aurelia](https://github.com/aurelia/vscode-extension) plugin for VSCode is installed:

![html_icons](https://cloud.githubusercontent.com/assets/6349949/25639391/044947ee-2f8c-11e7-8484-7d78c1148650.jpg)

Encountered with:
Windows 10 Education build 1607
aurelia plugin version: 0.3.2
vscode-icons version: 7.6.0
VSCode version: 1.11.2

**Comment by JimiC** [comment]
This is not a `vscode-icons` issue. The installed extension is causing the side-effect you are reporting. Currently, we are not supporting the `aurelia-html` `language id` and I'm not sure if we should also.
To restore to the default icon do the following:

- Open the `html` file.
- On the lower right corner of `vscode` click on the `Language Mode` or alternatively `F1 > Change Language Mode`.
- Select `HTML` from the list.

**Comment by sabinrimni** [comment]
Well this process is manual for each file and you also lose the Aurelia plugin advantages on html files.
I can see that the [materia-icon-theme](https://github.com/PKief/vscode-material-icon-theme) bypasses the problem while maintaining the Aurelia plugins functionality so it is possible.
![material](https://cloud.githubusercontent.com/assets/6349949/25664749/da18c28e-301b-11e7-97ed-11e99f5e8c3a.jpg)

I would suggest to override individual extension preferences since, as a user, I expect all the icons to be uniform, hence the use of a theme pack.

**Comment by jens1o** [comment]
Then you might want to use this workaround:
```
"files.associations": {
        "*.html": "html"
 },
```
just put this inside your user settings.

**Comment by JimiC** [comment]
Material-icon-theme isn't bypassing the so called problem. It just doesn't use language ids to associate icons with extensions. You are comparing different functionalities so it's unfair to point fingers.

**Comment by sabinrimni** [comment]
I must admit I'm not familiar with the implementation of either of these extensions. And I'm definitely not pointing any fingers.
What I wanted to highlight was that, as a user of this extension, I somehow expect it to override individual extensions that change the icon scheme. Now how possible (if at all) is this with the current implementation, I don't know.

**Comment by JimiC** [comment]
@sabinrimni Let me be more clear. The problem lies in the fact that `aurelia` extension is overriding `vscode` internal `html` extension and thus our extension that uses it to associate icons. Expecting from our extension to know and handle all individual extensions is somehow utopic.
We are aware that in some cases some things will not function as expected. But there is so much that we can do.

Never the less, I'm going to discuss this further with the team to see what is possible to do about it.

**Comment by JimiC** [comment]
This has been resolved since as of `0.3.3`.

Issue: https://github.com/aurelia/vscode-extension/issues/45
Fix commit: https://github.com/aurelia/vscode-extension/commit/4048c8deadb97e477bcd25e120bb909b4cc28c0f
