### ISSUE TITLE
[Icon Request] Google Cloud Platform

### ISSUE THREAD

**Issue by wayneashleyberry** [vscode-icons/vscode-icons#913]
I see there's an icon for AWS, it'd be nice to have one for Google Cloud :)

**Checklist:**

- [X] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request(if not, remove these lines below):
      - Type: [folder]
      - Icon Name: [gcp]

**Comment by JimiC** [comment]
Please see #650.
