### ISSUE TITLE
[Icon Request] React.js/ts

### ISSUE THREAD

**Issue by t-hughes** [vscode-icons/vscode-icons#916]
I want to create an icon request! This is available in Atom with the file-icon extension. 
      - Type: [js/jsx/javascript]
      - Icon Name: [test.react]
      - Sample original Icon (32x32/svg/transparent whenever possible): https://cdn.rawgit.com/file-icons/source/master/svg/Test-React.svg

**Comment by jens1o** [comment]
This is already supported via language id. Or do you mean an new icon for react tests(since the icon proposed looks like this)?

**Comment by t-hughes** [comment]
I am not 100% sure what you mean, but I was wondering if this icon could be added or how I go about applying it?

I think this code would work:

`<svg viewBox="0 0 32 32"xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <title>react test</title>
 <g>
  <title>Layer 1</title>
  <path d="m23.792461,21.97634c0,-1.243167 -1.311112,-2.024365 -2.354337,-1.402782c-1.043226,0.621583 -1.043226,2.183981 0,2.805562c1.043226,0.621583 2.354337,-0.159615 2.354337,-1.40278zm3.722192,-3.062502c1.038662,-5.097401 -1.374304,-6.775425 -5.2589,-3.085678c-3.656089,-3.519125 -6.389205,-2.333591 -5.281299,3.062402c-5.108921,1.581302 -4.77183,4.713977 0.040144,6.234454c-1.100982,4.969432 1.085316,6.856629 5.239966,3.102895c4.030007,3.711078 6.299054,1.896503 5.198897,-3.126949c5.248705,-1.827103 4.776715,-4.623072 0.061191,-6.187126l0,0.000002l0.000001,0zm-0.917477,-0.25091c-0.823401,-0.190693 -1.475401,-0.302328 -2.285734,-0.378058c-0.426937,-0.640944 -0.828502,-1.169852 -1.399962,-1.765528c3.046053,-3.050667 4.523564,-1.796516 3.685696,2.143588l0,-0.000002zm-7.945807,4.575909c0.308138,0.675387 0.490476,0.87432 0.79515,1.393304c-0.496119,-0.052098 -0.66974,-0.081853 -1.238682,-0.185254c0.182304,-0.523935 0.23828,-0.679839 0.443533,-1.208051l-0.000001,0.000001zm-0.039494,-2.381775c-0.226645,-0.558578 -0.299786,-0.746349 -0.468748,-1.248267c0.587339,-0.124999 0.80274,-0.188691 1.301715,-0.227468c-0.37136,0.598959 -0.497621,0.824058 -0.832967,1.475736l0,-0.000001zm0.547735,1.203887c0.507983,-1.044513 0.981616,-1.924857 1.577367,-2.810827c1.057086,-0.062413 1.982515,-0.057714 3.016338,0.020499c0.579825,0.829496 1.057439,1.711801 1.577529,2.791495c-0.389202,0.825754 -0.881746,1.667668 -1.518664,2.684233c-1.063414,0.082677 -2.028008,0.070465 -3.135581,-0.000779c-0.561354,-0.882973 -1.026776,-1.703644 -1.516989,-2.68462l0,-0.000001zm6.675365,1.163224c0.201719,0.502554 0.256506,0.662707 0.42925,1.183554c-0.533166,0.115265 -0.695232,0.14457 -1.214879,0.20125c0.355687,-0.565808 0.460849,-0.759828 0.785626,-1.384804l0.000002,0l0.000001,0zm-0.782868,-3.830629c0.56641,0.07961 0.747617,0.115896 1.275149,0.235467c-0.176481,0.53844 -0.239531,0.71651 -0.46496,1.230103c-0.321539,-0.651118 -0.438287,-0.866473 -0.810189,-1.465572l0,0.000002zm-2.050007,-1.207552c-0.646976,-0.026058 -0.844834,-0.024833 -1.513147,0.000389c0.292578,-0.395073 0.390907,-0.514487 0.748567,-0.943757c0.348554,0.386284 0.44626,0.508403 0.764581,0.943366l0,0.000002l-0.000001,0zm-1.423877,-1.666709c-0.571462,0.595679 -0.972973,1.10331 -1.39991,1.744254c-0.810335,0.075732 -1.481698,0.187089 -2.305103,0.37778c-0.826518,-4.009893 0.538105,-5.104985 3.705014,-2.122036l0,0.000002l-0.000001,0zm-4.318647,7.682862c-3.880902,-1.219161 -4.118894,-3.137524 -0.040416,-4.36744c0.249488,0.77729 0.501407,1.427692 0.843139,2.185747c-0.332056,0.783967 -0.577044,1.446114 -0.802722,2.181693l-0.000001,0zm0.69311,1.174057c0.733987,0.184844 1.369831,0.24462 2.184618,0.333619c0.490252,0.710353 0.902249,1.259435 1.441514,1.829518c-2.766204,2.786015 -4.701631,2.127362 -3.62613,-2.163139l-0.000002,0.000002zm4.281803,1.468625c-0.375806,-0.399551 -0.509678,-0.569248 -0.842435,-1.060627c0.741732,0.016045 1.021188,0.018546 1.702723,0.00072c-0.330071,0.480763 -0.470633,0.644439 -0.860288,1.059907zm0.674662,0.692403c0.57863,-0.645475 0.994162,-1.184729 1.442651,-1.847072c0.765478,-0.057827 1.397984,-0.152342 2.183588,-0.336343c0.96368,4.014045 -0.647646,5.099825 -3.626239,2.183415zm4.300416,-3.378524c-0.222519,-0.735577 -0.45508,-1.354341 -0.78249,-2.13831c0.336949,-0.758055 0.576858,-1.386074 0.822849,-2.163362c3.483193,1.064018 4.301248,2.929567 -0.040359,4.301671l0,0.000002l0,-0.000001zm-14.81534,-1.024115l-5.931421,0l4.914899,-8.416796l4.311408,0.000004c-0.237327,0.95246 -0.241942,1.59105 0.009401,3.062157c-2.509358,0.92037 -4.056663,2.431471 -3.304285,5.354635l-0.000002,0zm6.646428,-19.270736l-1.510884,0l0,7.482549l0.811158,1.305825c-0.556574,0.05371 -1.064298,0.25988 -1.484453,0.600843l-0.946958,-1.487229l0,-7.901988l-4.742845,0l0,7.901966l-7.646006,13.016955l8.665303,0l0,1.641626l-9.0373,0c-1.526672,0 -1.977963,-0.784927 -1.259051,-2.041067l7.656805,-13.036951l0,-7.482529l-1.510853,0c-1.130116,0 -1.130116,-1.641626 0.000029,-1.641626l11.005061,0c1.130144,0 1.130144,1.641626 0,1.641626l-0.000006,0z" id="svg_1" fill="#00d8ff"/>
 </g>
</svg>`

**Comment by JimiC** [comment]
Test icons are already implemented. You need to follow test file extensions naming convention. For regular files icons are activated by installing any syntax highlighting extension.
