### ISSUE TITLE
Support for .pcd files

### ISSUE THREAD

**Issue by sweetim** [vscode-icons/vscode-icons#917]
Support for .pcd files icon which is mainly used to store information for point cloud data

**Comment by JimiC** [comment]
Please point to any documentation or suggested icon.

**Comment by sweetim** [comment]
Below is the reference for .pcd file
http://vml.sakura.ne.jp/koeda/PCL/tutorials/html/pcd_file_format.html

For the icon, either use that image, or someone redesign a new .pcd file icon ;)
