### ISSUE TITLE
[Extend Icon Matching] Extend Angular 2 routing file matching

### ISSUE THREAD

**Issue by Verbon** [vscode-icons/vscode-icons#919]
When using Angular 2 routing modules, extension only recognizes app-routing.module.ts as a routing module. Is there any chance to support any *-routing.module.ts pattern?
![image](https://cloud.githubusercontent.com/assets/9406367/25783161/16d8d3f2-3360-11e7-9d11-c03d87edbdfa.png)

Because now, heroes-routing.module.ts confuses me, and at a first glance I see 2 modules in this folder.
It would be great, if you could support custom routing modules.

**Comment by jens1o** [comment]
Nop, this is not supported by vscode. We are wanting this feature, but so far it hasn't been implemented. Currently, we need to define very **each** extension. I'm sorry.

**Comment by JimiC** [comment]
@jens1o I believe you have the rights to create `labels` yourself.

**Comment by jens1o** [comment]
I know, but this is usually a job the main maintainer/creator of the project does.

**Comment by robertohuertasm** [comment]
@jens1o, please feel free!

**Comment by michael-letcher** [comment]
@jens1o  Is there a ticket in VSCode for this feature so that we can get out pitchforks and send some +1's there way?

**Comment by jens1o** [comment]
@michael-letcher Sure, here you go: https://github.com/Microsoft/vscode/issues/12493

Thanks!
