### ISSUE TITLE
Support for mjml files

### ISSUE THREAD

**Issue by balexandre** [vscode-icons/vscode-icons#920]
used a lot with the [mjml extension](https://marketplace.visualstudio.com/items?itemName=attilabuti.vscode-mjml).

MjMl website: https://mjml.io

**mjml icon** can be found on the Visual Studio marketplace link above, where the icon (128x128) is found on the link below:
`https://attilabuti.gallerycdn.vsassets.io/extensions/attilabuti/vscode-mjml/0.0.2/1494197716664/Microsoft.VisualStudio.Services.Icons.Default`

![](https://attilabuti.gallerycdn.vsassets.io/extensions/attilabuti/vscode-mjml/0.0.2/1494197716664/Microsoft.VisualStudio.Services.Icons.Default)

***

[![](http://s6.postimg.org/47qxdb6sh/screenshot_36.png)](http://s6.postimg.org/47qxdb6sh/screenshot_36.png)

**Comment by jens1o** [comment]
Please do one request per issue, otherwise, we have problems mapping it.

**Comment by balexandre** [comment]
will do :)
