### ISSUE TITLE
Support for jsbeautifyrc files

### ISSUE THREAD

**Issue by balexandre** [vscode-icons/vscode-icons#921]
`.jsbeautifyrc` is also not supported (a settings file for [js-beautify](https://github.com/beautify-web/js-beautify)), a **normal "Js" icon** like `.jshintrc` would suffice :)

***

[![](http://s6.postimg.org/ak62n59up/screenshot_35.png)](http://s6.postimg.org/ak62n59up/screenshot_35.png)

**Comment by JimiC** [comment]
Duplicate #736
