### ISSUE TITLE
Angular icons not shown

### ISSUE THREAD

**Issue by ampeixoto** [vscode-icons/vscode-icons#923]
The icons for Angular were shown but somehow they are not there anymore.

I already tried some solutions like editing the workspace settings:
![vs icons](https://cloud.githubusercontent.com/assets/6080796/25942466/364f9d62-363d-11e7-8814-0072f466a0cf.PNG)

But no changes:
![vs icons explorer](https://cloud.githubusercontent.com/assets/6080796/25942522/5d5a9088-363d-11e7-90cd-3036a640b760.PNG)

The .angular-cli.json is shown correctly.

I'm using version 7.7.0.

What could be the problem?

**Comment by robertohuertasm** [comment]
Remove your last two `vsicons` settings and restart the IDE. You should get a message stating that this is an `Angular` project and asking if you want to enable the icons. Let me know what you get.

**Comment by ampeixoto** [comment]
Did that but it didn't ask me anything.

Maybe is because my angular application is not at the root of the folder... My Project is something like this:

```
.vscode
my-nodejs-app
   - nodejs files...
my-angular-app
   - angular files...
```

Is that a problem?

**Comment by robertohuertasm** [comment]
Set the `vsicons.presets.angular: true` inside the `settings.json` of your `.vscode` folder, restart and try again.

**Comment by ampeixoto** [comment]
Same result, icons don't change...

**Comment by robertohuertasm** [comment]
That's strange... Press F1 > Icons: Apply Icons Customization

**Comment by ampeixoto** [comment]
Didn't work... But I noted something strange (maybe not related): after Apply Icons Customization, the message to restart appeared:
![vs icons restart](https://cloud.githubusercontent.com/assets/6080796/25943893/b21a0ffa-3641-11e7-8b03-135774086807.PNG)

But when I clicked restart, nothing happened, I had to restart VS manually...

**Comment by robertohuertasm** [comment]
Could you open the Dev tools and see if you got some kind of error there?

**Comment by ampeixoto** [comment]
Before clicking the restart button, there is no error in the console. As soon as I hit the restart button, the following error is raised:
![vs icons error](https://cloud.githubusercontent.com/assets/6080796/25944371/5ada707a-3643-11e7-8215-eb7504d5600a.PNG)

**Comment by robertohuertasm** [comment]
Have you tried to reinstall the extension?

**Comment by ampeixoto** [comment]
Tried now. Same error when restarting...

**Comment by ampeixoto** [comment]
Ok, it is working now.

I had to do the following steps:
 - Added ```"vsicons.projectDetection.autoReload": false``` to user and workspace settings;
 - Select VSCode Icons theme;
 - Apply Icons Customization and restart;

And it worked.

The problem is in the following line of the index.js os the extension:

```
const angularPreset = vsicons.projectDetection.autoReload ||
        (projectDetectionResult && typeof projectDetectionResult === 'object' && 'value' in projectDetectionResult)
        ? projectDetectionResult.value
        : vsicons.presets.angular;````

When vsicons.projectDetection.autoReload is true it will access the projectDetectionResult object, which is null....

**Comment by robertohuertasm** [comment]
Thanks @ampeixoto for reporting this. 

Unfortunately, I don't have much time now to look deeper into this. Hopefully, I will tonight. 😄

**Comment by JimiC** [comment]
I had a feeling that this code will bite me eventually. I'll prepare a fix.

**Comment by thrivenibasappa** [comment]
In VS code try File > Preferences > File Icon Theme > VSCode Icons. MacOS => Code > Preferences > File Icon Theme > VSCode Icons.
