### ISSUE TITLE
Wildcards in Filenames

### ISSUE THREAD

**Issue by ciel** [vscode-icons/vscode-icons#932]
- [x] I'm sure this issue is not a *duplicate*?

Is it possible to entertain the idea of allowing wildcards in file or folder names for icon matching, especially in overrides at the local level? For example ... I would love to be able to put this into my `settings.json` file. The ability to customize the icons alone has been so wonderful.

```
{ "icon": "node", "extensions: [ ".node" ], match: [ "*Node" ], format: "svg", extends: "node" }
```

**Comment by jens1o** [comment]
This is highly request from us, but so far vscode hasn't this feature(I don't even know wether they work on it.)...

I'm sorry, but unfortunately we can't do that.

**Comment by ciel** [comment]
Thank you for responding! I'm really glad to know you're open to the idea if Microsoft makes such behavior possible. 

I just learned last night that I can customize the icons at a user level, and a workspace level, and I REALLY enjoy it. You've done an amazing job with this extension.

**Comment by jens1o** [comment]
Thank you very much!

**Comment by Gliptal** [comment]
I guess this prevents something like a customization in the lines of 

> give all `.tex` files in the `tables` folder only icon `mjml`

right?

**Comment by jens1o** [comment]
@Gliptal Yeah, that's true.

**Comment by zypA13510** [comment]
If using wildcard is not possible, is matching against the beginning of a filename achievable? In my case, I wish to associate all `i18n_<lang_code>.properties` files with icon `locale`. Because otherwise, there is no way to tell a locale file from a config file which use `.properties` extension.
Atm, I have to add every language manually to the list.

**Comment by andreatondelli** [comment]
No news about? 

Thanks

**Comment by robertohuertasm** [comment]
Unfortunately, no.

**Comment by andreatondelli** [comment]
Very very bad news! :-(
Thanks for quick reply @robertohuertasm .

**Comment by JustinGrote** [comment]
No way to expand the suffix too I assume? It's very common for go tests to be named myfunction_test.go, so if I could just match "ahead" of the period e.g. `*_test.go`

**Comment by robertohuertasm** [comment]
No luck

**Comment by pawlakmaly** [comment]
Any update ?

**Comment by robertohuertasm** [comment]
For reference, this is a VS Code API limitation. It would be nice for users interested in this feature to open an issue in the vscode repo itself.
