### ISSUE TITLE
Why is the custom icon path unable to be part of the project's .vscode folder?

### ISSUE THREAD

**Issue by ciel** [vscode-icons/vscode-icons#933]
- [x] I'm sure this issue is not a *duplicate*

I don't like the "not a duplicate" check box because I'm not 100% sure it isn't, but I've been browsing the issue tracker for a few hours now and didn't find it.

The path for custom icons is different for each operating system, but is there a technical reason it can't be told to map from a given folder relative to the project root?

I would think `/.vscode/extensions/vscode-icons` would be pretty simple and clear. Is this a choice you made, or a limitation of Visual Studio Code?

The big reason I'd love to be able to do customization at the project level is for persisting it all with the project in the git repository.

**Comment by JimiC** [comment]
@ciel I can't see any reasoning behind your suggestion to do icon customization at the project level and have them added to the VCS. Icons are associated to a file name or file extension and don't change (with the exception of associating `Angular` specific namings). Is there any specific project structure file naming you have in mind?

The path for custom icons is a decision made by the team. Having it at the `extension` folder isn't feasible for two reasons.

1. Usage of a folder created by an application is a bad practice as the application can be installed and uninstalled multiple time. Uninstalling an app should not let remnants.
2. Using the extension folder will delete your icon customization folder every time the extension updates.

The standard practice is to put user data in the user folder that the OS provides. And as professional developers, we are obliged to follow the standards.

I hope I provided the answers you sought.

**Comment by ciel** [comment]
I think I was unclear about what I meant. I'm basically saying that it would make custom icon setups more portable if we could specify a source directory. But I understand the decisions you've made. Thank you for the reply!

**Comment by robertohuertasm** [comment]
For now, if a team uses custom icons, they have to be manually imported into the proper folder and once the importation has been done, then apply the icons customization feature. 

The idea is that you have already added to your repository the `workspace` configuration (see #934 - this should be solved) with all your custom configuration so all your team members will have these settings when working in the same project.

This is cool, and the work of copying the custom icons to the folder specified in vsicons docs is a one time process. Hence, the only thing that lacks to complete your exact scenario is the ability to specify a custom `custom icons folder`, so your team mates don't even have to copy the files manually.

Maybe it's not a bad idea to implement something like this, where a user's defined custom icon folder can also be used alongside the default custom icon folder defined by our project. The user's defined custom icon folder will have precedence over the default (the same that it's happening now with workspace and user's configurations).

In the case where the manifest is generated using this custom folder and then someone deletes the folder, the worst case scenario is having some errors in the dev console and showing the default file or folder icon.

Maybe another cool feature to think about would be to offer an option to import all these configurations to the user configuration and import the icons to our defined folder. I'm just thinking out loud but I think we should consider exploring these possibilities.

**Comment by ciel** [comment]
I don't agree, but I understand your point and you obviously know what you're doing better than I do! Thank you again, so much, for creating this extension, it is absolutely marvelous and I love it dearly.

I'm a single developer, so for me, the desire was to make it easy to keep my custom icons **and** the `settings.json` in my _github_ repository so that when I do a reformat, or move to a new machine, or recover from something, it's just innate to pulling my repository.

Your explanation makes sense, and I understand it. The design of the extension is amazing, so I must assume that you're right and what I'm asking for is just a bad idea.

**Comment by robertohuertasm** [comment]
@ciel, my comment was indeed supporting the exploration of your ideas and I was explaining to you how your problem should be tackled under the current statu quo. 

Certainly, we don't currently support the customization of the `custom icons folder path`, so the project's custom icons should be manually copied, but all the icon customization settings could be included in your `settings.json` (workspace settings) making easy for your team to share this.

**Comment by JimiC** [comment]
@robertohuertasm You mind if I work on this one?

**Comment by robertohuertasm** [comment]
All yours @JimiC! 👍

**Comment by JimiC** [comment]
I only need to add some tests for it and I'm done. Hopefully tomorrow I'll submit a PR.

**Comment by robertohuertasm** [comment]
Cool!
