### ISSUE TITLE
Change workspace configuration behavior

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#934]
Now, if you define some icons in your workspace configuration it will override the user configuration, so you will end up losing all the customizations you have. 

Ideally, the workspace configuration should be merged to the user configuration. It seems that `vscode.workspace.getConfiguration` method does the overriding so the only way to overcome this is to provide a slighty different syntax in the workspace. 

The idea is to keep backwards compatibility so the current behavior will be kept and people will not lose what they already have but also to provide this new syntax that will allow to keep both workspace and user customizations.

**Comment by JimiC** [comment]
@robertohuertasm I just had an epiphany. How about adding a setting (user level) where the user can set a path to the custom icon folder? This way the user could also point to a cloud service folder.

**Comment by jens1o** [comment]
Good idea!

**Comment by robertohuertasm** [comment]
This was what we were discussing in #933, isn't it? or am I missing something?

**Comment by JimiC** [comment]
Honestly? I couldn't figure out what your plan is from your comments.

**Comment by robertohuertasm** [comment]
Well, as you can see in my previous comments excerpt, it was exactly what @ciel was demanding: the ability for the user to specify the custom icon folder. I was talking about which folder would have precedence over the other and even introduced the idea of an importing system to import the custom icons from the user's custom folder into the default `custom icon folder`.

**Comment by JimiC** [comment]
What I don't get is `How` you going to implement it. I'll wait to see the code in the PR.

**Comment by robertohuertasm** [comment]
@jimic, if it's ok for you I think I'll get to you over Slack because maybe we're mixing things up and it's always a better tool to clarify things 😉

**Comment by ciel** [comment]
@robertohuertasm I did not mean to sound as if I was "demanding" anything. I am very, very sorry if it came across that way. It was merely an idea.

**Comment by robertohuertasm** [comment]
@ciel never mind, I meant `asking for`. I'm not an English native so I often forget the subtleties of the language.

**Comment by JimiC** [comment]
@robertohuertasm I'll be available later in the day probably after your sunset.

**Comment by ciel** [comment]
@robertohuertasm I understand. Thank you for clarifying. I just didn't want to seem like I was asking for something unreasonable.

**Comment by jens1o** [comment]
Is this up to date?

**Comment by robertohuertasm** [comment]
@jens1o what do you mean?

**Comment by jens1o** [comment]
As far as I can see, this is scheduled for the next release, but there is no pr there, yet.

**Comment by robertohuertasm** [comment]
Ah, no problem. I tend to push myself by assigning issues to next releases but many times I don't have the time.

**Comment by jens1o** [comment]
Okay.
