### ISSUE TITLE
request: ravendb icon

### ISSUE THREAD

**Issue by ciel** [vscode-icons/vscode-icons#935]
- [X] I'm sure this issue is not a *duplicate*?
- [X] I want to create an icon request(if not, remove these lines below):
      - Type: [**folder**]
      - Icon Name: [**ravendb**]
      - Sample original Icon: [transparent png (256x256)](http://i.xomf.com/zzhnm.png)
      - Extensions: raven, ravendb

    ![RavenDB](http://i.xomf.com/zzhnm.png)

**Comment by jens1o** [comment]
Do you want to create a folder request? If true, please do it here: #650

**Comment by robertohuertasm** [comment]
I think that #650 is getting unmanageable and it's best to keep track of these request the way we track normal icons. It will be better too to reference possible pro.

**Comment by JimiC** [comment]
@robertohuertasm I disagree. #650 isn't getting unmanageable as long as the user does the intended issue request as a comment on that thread.
