### ISSUE TITLE
has deletected a non angular project?

### ISSUE THREAD

**Issue by Ncage1974** [vscode-icons/vscode-icons#940]
vscode-icons v.7.7.0
vscode v.1.12.2
ubuntu linux 17.04

I have a react project i'm working on and every time i open the project i get the following warning every time which is starting to get annoying:

> Info: vscode-icons has deted a non Angular project. Select 'Restart' to disable the Angular icons.

I never work on angular projects so i don't know what gives. The project is a react project.

.vscode/settings.json
`{
    "vsicons.presets.angular": false
}`

**Comment by jens1o** [comment]
remove the line in your settings should fix it.

**Comment by JimiC** [comment]
@Ncage1974 This means that `Angular` icons are enabled in the icon manifest (either they got enabled when you opened another project that is an `Angular` project or you toggled the icons from the menu). By restarting they will get disabled.
You can either choose to disable them by restarting the editor or disable the project detection when the message appears (if you find it so annoying).

**Comment by jens1o** [comment]
Just a question: Removing the line should fix it too, since the pointer is based on this?

**Comment by Ncage1974** [comment]
@JimiC  thanks a lot. That fixed it. I think the reason the dialog never went away initially (it would be there after machine reboots or restarting vscode) was because i never dealt with the dialog. I always just clicked close. This time i clicked restart and  then reopened vscode and it seems to have gone away.

**Comment by JimiC** [comment]
@jens1o No. It will not fix it. Project detection has become smarter and fro `7.7.0` it looks into the icon manifest to determine if the icons are disabled or not.

**Comment by jens1o** [comment]
Ah, I just didn't get the change. I still things it is like back the early-days.
