### ISSUE TITLE
docker-compose.*.yml uses YML icon and not Docker

### ISSUE THREAD

**Issue by gfogle** [vscode-icons/vscode-icons#944]
<img width="314" alt="screen shot 2017-05-24 at 10 48 54 am" src="https://cloud.githubusercontent.com/assets/7015773/26409470/a2a8cc32-406e-11e7-927e-386445012a66.png">

**Comment by JimiC** [comment]
vscode doesn't support glob expressions. You can though use our icons customization feature.

**Comment by muuvmuuv** [comment]
@gfogle How did u solved it?

**Comment by JimiC** [comment]
@muuvmuuv checkout our wiki "Fine Tuning" section.
