### ISSUE TITLE
setting icon for specific file

### ISSUE THREAD

**Issue by ciel** [vscode-icons/vscode-icons#946]
- [X] I'm sure this issue is not a *duplicate*?

Is it possible to assign an icon to a specific file by name? I can only seem to to do it based on extension.

**Comment by ciel** [comment]
Closing this, as I finally [found a duplicate here](https://github.com/vscode-icons/vscode-icons/issues/100)

**Comment by robertohuertasm** [comment]
@ciel check this out (it's in the readme):
// Adding new filename extensions to an already supported icon.
// note: the format must match the existing one. If not, it will use the extension you provide.
"vsicons.associations.files": [
    { "icon": "webpack",  "extensions": ["webpack.config.test.js"], "filename": true, "format": "svg" }

**Comment by ciel** [comment]
Wow you're fast!

**Comment by ciel** [comment]
**YES!** THAT WORKED! THANK YOU SO MUCH! The only thing I've got to figure out now is whether I can assign icons based on parent folders!

**Comment by robertohuertasm** [comment]
@ciel, that's not possible at the moment. See #899

**Comment by GalGreenfield** [comment]
> @ciel, that's not possible at the moment. See #899

I think that it'd be great if you just added the ability to provide regexes for paths - the only  thing you'd have to handle is rules clashing, and you can solve that with overrides.
