### ISSUE TITLE
Support for PLSQL file

### ISSUE THREAD

**Issue by Danieleeee** [vscode-icons/vscode-icons#949]
Hi,
it's possible to have more icons for PLSQL language?
This is how many file appear:
![1](https://cloud.githubusercontent.com/assets/22749175/26522521/2d43c4fa-4303-11e7-931a-6e7ebb7ef5e9.png)

1. No icon for package file (.pkg)
~~2. No icon for test file (.tst)~~
~~3. No difference between header and body package (_h.sql, _b.sql)~~

Thanks.

**Comment by jens1o** [comment]
Hi,
please separate all the requests, so we can work properly.

Concerning the third request, this is not possible due to `vscode` limitations.

**Comment by robertohuertasm** [comment]
Do you have any proposed icons?

**Comment by Danieleeee** [comment]
> Concerning the third request, this is not possible due to vscode limitations.

Ok.

> please separate all the requests, so we can work properly.

All requests are related to PLSQL programming language files. 
I have to insert one issue for each file extension?

> Do you have any proposed icons?

This is Oralce Sql Developer style for package ".pkg":
![1](https://cloud.githubusercontent.com/assets/22749175/26522704/a6499a8e-4306-11e7-9ad9-3a6dc51bcfd0.png)

This is Toad style for test ".tst":
![2](https://cloud.githubusercontent.com/assets/22749175/26522766/0fda6004-4308-11e7-87ad-47cca1b0d663.png)

**Comment by jens1o** [comment]
ah, my bad.
