### ISSUE TITLE
Support for TST file

### ISSUE THREAD

**Issue by Danieleeee** [vscode-icons/vscode-icons#950]
Hi,
it's possible to have support for file.tst?

Support for PLSQL file #949

Thanks.

**Comment by JimiC** [comment]
@robertohuertasm @jens1o @Danieleeee How about we use the `test` icon we already have (stripping it from the language specific icon)?

**Comment by jens1o** [comment]
I'm okay with that.

**Comment by Danieleeee** [comment]
Ok
