### ISSUE TITLE
Support for PKG file

### ISSUE THREAD

**Issue by Danieleeee** [vscode-icons/vscode-icons#951]
Hi,
it's possible to have support for file.pkg?

Support for PLSQL file #949

Thanks.

**Comment by JimiC** [comment]
I'm not sure that `pkg` extension is only PLSQL related.

**Comment by Danieleeee** [comment]
You are probably right. 
Surely indicates a set of elements. 
I think the icon I have indicated  here #949 (or something like that) is appropriate.

**Comment by JimiC** [comment]
As expected https://en.wikipedia.org/wiki/.pkg. What we could do is to use the `paket` icon with different colors.

**Comment by Danieleeee** [comment]
Ok.
Surely it is better than now ;)

**Comment by JimiC** [comment]
@Danieleeee The thing is the icon you are suggesting contains also an `SQL` icon something that will confuse users.

**Comment by Danieleeee** [comment]
![1](https://cloud.githubusercontent.com/assets/22749175/26523119/bcc4f632-4310-11e7-81bf-cbf5a3148b22.png)

**Comment by JimiC** [comment]
@Danieleeee We prefer `SVG` icons.

**Comment by Danieleeee** [comment]
Here are more icons, and can convert in svg format:
[findicons.com](http://findicons.com/search/package)

**Comment by robertohuertasm** [comment]
I'm good with the `paket` icon. 

It seems though that [it is different](https://fsprojects.github.io/Paket/img/logo.png) from the one we curently  have. I don't remember if we did this deliberately or it just changed.

**Comment by JimiC** [comment]
@robertohuertasm It is as I couldn't find a suitable `SVG` of the official icon, so I chose the first I found.

**Comment by JimiC** [comment]
Found it @ http://www.flaticon.com/free-icon/box_214273
