### ISSUE TITLE
Support for PKH and PKB

### ISSUE THREAD

**Issue by Danieleeee** [vscode-icons/vscode-icons#955]
Hi,
relatively to Support for PKG file #951, i found the correct extension for PLSQL language.
file.**pkh** => package header
file.**pkb** => package body

You can use icon I mentioned in _Support for PLSQL_ file #949

**Comment by JimiC** [comment]
Those are already supported via 3rd party extensions (https://marketplace.visualstudio.com/search?term=plsql&target=VSCode&category=All%20categories&sortBy=Relevance)
