### ISSUE TITLE
Support for .sequelizerc

### ISSUE THREAD

**Issue by lekhnath** [vscode-icons/vscode-icons#969]
Please add file icon for `.sequelizerc` files also. This file is created for quite popular Node.js ORM for some SQL database system. It is called [Sequelize](https://github.com/sequelize/sequelize). When using sequelize in Node.js projects it allows us to create `.sequelizerc` file. Its logo can be found [here](http://docs.sequelizejs.com/)

Thank you

**Comment by JimiC** [comment]
Please use the issue temple. It's there for a reason.

**Comment by lekhnath** [comment]
Sorry 🙏 from next time I'll sure use the template for filing an issue
