### ISSUE TITLE
[Icon Request] Support for GameMaker Language

### ISSUE THREAD

**Issue by LiarOnce** [vscode-icons/vscode-icons#970]
Notice:There are three different versions of the language that correspond to three different versions,but the extensions are `.gml`.

- [x] I'm sure this issue is not a *duplicate*?
- [x] I want to create an icon request:
      - Type: extension/language id
      - Icon Name: gml-gm81
      - Sample original Icon: ![gm81](https://cloud.githubusercontent.com/assets/11171892/26552964/05ff0b06-44bc-11e7-98b5-bdb60d208f87.png)
      - Extensions: `.gml`
      - Type: extension/language id
      - Icon Name: gml-gms
      - Sample original Icon: ![gms](https://cloud.githubusercontent.com/assets/11171892/26552972/16489edc-44bc-11e7-81b2-6f14954a8189.png)
      - Extensions: `.gml`
      - Type: extension/language id
      - Icon Name: gml-gms2
      - Sample original Icon: ![gms2](https://cloud.githubusercontent.com/assets/11171892/26553019/50c535ac-44bc-11e7-8130-3cfb7a0af7e3.png)
      - Extensions: `.gml`

More information:[https://yal.cc/gamemaker-split-string/](https://yal.cc/gamemaker-split-string/)
[https://help.yoyogames.com/hc/en-us](https://help.yoyogames.com/hc/en-us)

**Comment by jens1o** [comment]
We can't determine what version the file is, sorry.

Thoughts? @robertohuertasm @JimiC

**Comment by JimiC** [comment]
At the moment I propose to support only https://marketplace.visualstudio.com/items?itemName=liaronce.gml-support

**Comment by LiarOnce** [comment]
Sorry, this plugin is what I wrote/(ㄒoㄒ)/~~.

**Comment by JimiC** [comment]
@LiarOnce I know.

**Comment by JimiC** [comment]
It turns out that because @LiarOnce has different `language id` in the extension we can associate different icons even when it's for the same file extension (`.gml`).

The shown icon will depend on the association the user will make.
But since I only found an `SVG` logo for `gml-gms` we'll support that for the moment.

**Comment by JimiC** [comment]
Found `SVG` icon for `gms2` also.

**Comment by LiarOnce** [comment]
Don't worry. I have an SVG logo for 'gml-gm81'

**Comment by LiarOnce** [comment]
This is the SVG logo for `gml-gm81`.
![gml-gm81](https://wiki.liaronce.win/images/gml-gm81.svg)

**Comment by JimiC** [comment]
@LiarOnce Thanks a lot I'll add it later today (hopefully).

**Comment by JimiC** [comment]
@LiarOnce Sorry but this is not a true `SVG` icon. Rasterized icons wrapped in an `svg` tag aren't considered true `SVG` icons.

**Comment by LiarOnce** [comment]
Just now I updated the icon.
Can this logo be?

**Comment by JimiC** [comment]
I made one but it's far from perfect:

![gamemaker81](https://cdn.rawgit.com/JimiC/vscode-icons/support_gml81/icons/file_type_gamemaker81.svg)

**Comment by LiarOnce** [comment]
It seems to stick with this logo appears to be a good choice.
![gml-gm81](https://wiki.liaronce.win/images/gml-gm81.svg)

**Comment by JimiC** [comment]
@LiarOnce I saw yours but I'll leave that for `Atom` as they like monochrome icons...
