### ISSUE TITLE
Multiple Icons from Angular , what is the difference ?

### ISSUE THREAD

**Issue by binayacharya** [vscode-icons/vscode-icons#974]
![capture](https://cloud.githubusercontent.com/assets/7564325/26577799/563c72b6-454d-11e7-84a8-0eb76349bd0f.JPG)

Why multi colored angular Icon. Is it possible I use same icon for same extension or type 

Thanks,
Binaya

**Comment by robertohuertasm** [comment]
The different colors help you to distinguish between different file types (modules, components, smart components, pipes and so on).

If you want to have only one color, please override the default settings by using the [custom file association](https://github.com/vscode-icons/vscode-icons#fine-tuning).

**Comment by JimiC** [comment]
I believe the question has been answered.
