### ISSUE TITLE
Support Terraform's .tf file format

### ISSUE THREAD

**Issue by mmisztal1980** [vscode-icons/vscode-icons#975]
Hi, I'd like to request that terraform's  file formats get supported:

      - Type: *.tf
      - Icon Name: terraform
      - Sample original Icon: SVG can be found (here)[https://www.terraform.io/]
      - Extensions: *.tf *.tf.json

Cheers!

**Comment by JimiC** [comment]
Already supported via `terraform` extensions. Find one at the marketplace.
