### ISSUE TITLE
Support for SBT

### ISSUE THREAD

**Issue by kggp1995** [vscode-icons/vscode-icons#977]
_**Need support for .sbt files in VS Code**_

**CURRENT VIEW:**
![image](https://cloud.githubusercontent.com/assets/11145839/26591022/fa617626-4579-11e7-808a-0cd65f563257.png)

**Request to use the following icon from official source:**

[Small Icon](http://www.scala-sbt.org/assets/favicon.ico) :
![image](https://cloud.githubusercontent.com/assets/11145839/26591852/8e760ad2-457c-11e7-82f7-4404c43883b4.png)

[Vector Link](http://www.scala-sbt.org/assets/typesafe_sbt_svg.svg)

Keep up the great work! :smile:

**Comment by JimiC** [comment]
Should be supported via `language id` `sbt`.

**Comment by robertohuertasm** [comment]
@kggp1995, what @JimiC  means is that if you install [this extension](https://marketplace.visualstudio.com/items?itemName=daltonjorge.scala), for instance, you'll get at least the default Scala logo from us.

In order to have this specific logo for `sbt` files will have to do some changes. 😉

**Comment by JimiC** [comment]
[This extension](https://marketplace.visualstudio.com/items?itemName=itryapitsin.Sbt) seems better and distinguishes the `scala` and `sbt` support via different `language ids`.

**Comment by kggp1995** [comment]
Hi, despite adding the SBT plugin, I have this issue. The screenshot of the workspace has the mentioned plugin installed.
Could you please consider adding the icon support in one of the PRs?

**Comment by jens1o** [comment]
This is supported in the next release.

**Comment by robertohuertasm** [comment]
@jens1o you can close it. @JimiC added support for this in #979.

@kggp1995 you will have to wait until next release 😉

**Comment by jens1o** [comment]
Okay.

**Comment by kggp1995** [comment]
👍
