### ISSUE TITLE
Not showing folder icons

### ISSUE THREAD

**Issue by Alex-Sokolov** [vscode-icons/vscode-icons#989]
After update extension to version 7.8.1 folder icons not showed anymore.

![2017-06-03 10 54 06](https://cloud.githubusercontent.com/assets/4497128/26751804/239aacf0-484b-11e7-84be-3f2ec46fa057.png)

**Comment by jens1o** [comment]
should be a duplicate of #924.

**Comment by JimiC** [comment]
Uninstall and re-install the extension.

**Comment by Alex-Sokolov** [comment]
Thanks! Reinstalling helps
