### ISSUE TITLE
[Proposal] Switch to npm 5 from yarn

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#995]
- [x] I'm sure this issue is not a *duplicate*?

`npm 5` now includes the goodies that `yarn` offers.

Consider switching to it? Discuss.

**Comment by JimiC** [comment]
Note here that we can keep `yarn` and add support for `npm 5` (which adds a `package-lock.json` file similar to that of `yarn`).
The other option is to drop `yarn` but add a constraint that the user needs `npm 5+` in order to manage the packages.

**Comment by jens1o** [comment]
I wanted to suggest that, too... So, I think it's the right idea! 🗡

**Comment by robertohuertasm** [comment]
As far as I know npm5 is shipped with node 8 and our CI is running on node 6. I have no problem keeping the new npm lock file. I'm already using the latest npm version so... But If we are willing to keep our CI node versions aligned with vscode node version then I guess we'll have to keep yarn for the moment.

**Comment by JimiC** [comment]
`npm` can be updated independently. I see the option to keep them both as preferable (this way we can keep everyone happy).
