### ISSUE TITLE
Provide mechanism to map folder names to underscored and dotted ones in icons manifest

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#998]
- [x] I'm sure this issue is not a *duplicate*?

**Comment by JimiC** [comment]
@robertohuertasm @jens1o 
1. I'm terrible at naming. What should we name this new `enum`?
2. I'm thinking of making this `enum` as flag* type like in `.NET`.

Thoughts?

* https://www.typescriptlang.org/docs/handbook/enums.html
https://basarat.gitbooks.io/typescript/docs/enums.html#enums-as-flags

**Comment by jens1o** [comment]
`AdditionalFileextensionTypes`

**Comment by JimiC** [comment]
@jens1o May I remind you that we are atalking about folders.

**Comment by jens1o** [comment]
I had written to many php files today(around 35 to get something done). Sorry.

`AdditionalFolderExtensionTypes`

An extension of folders grouped together... somehow?

**Comment by JimiC** [comment]
Forget `flags` enum they create confusion in the `supportFolders` API.
Naming still pending...

**Comment by JimiC** [comment]
@jens1o I'm looking something for something descriptive like the `languages` we have in `supportedFiles`.

**Comment by jens1o** [comment]
brainfuck got real.

**Comment by robertohuertasm** [comment]
Sorry @JimiC what would be the idea here? I'm not sure to understand how you want to tackle this.

**Comment by robertohuertasm** [comment]
If I understand correctly. You're planning to create some sort of automation that will allow the folders to support `_` and `.` syntax.  I guess these flags will affect all the extensions in a specific folder definition.If that's the case I think this would not be a desirable scenario.

Let's take this as an example:
```
{ icon: 'git', extensions: ['.github', '.git', 'submodules', '.submodules'], format: FileFormat.svg },
```
Let's say I want to support underscores for `submodules` and only dots for the others. How would a flag support this?

In my opinion, just adding the `_`  as another extension is the easiest an clearer way to proceed. Unless your idea solves this issue :wink:

**Comment by JimiC** [comment]
@robertohuertasm By introducing a new flags `enum`.

```
enum Map {
  none,
  dotted = 1 << 1,
  leadingUnderscore = 1 << 2,
  trailingUnderscore = 1 << 3,

  leadingUnderscoreAndDotted = leadingUnderscore | dotted,
  fullyUnderscored = leadingUnderscore | trailingUnderscore,
  all = dotted | fullyUnderscored,
}
```
and API like:
```
    { icon: 'aws', extensions: ['aws'], map: [map.dotted], format: FileFormat.svg },
```

**Comment by robertohuertasm** [comment]
Still I don't see the point of doing this. I mean, I don't see it solving any issue but adding complexity instead.  

In the case I presented before, I would need to split the entry in order to support the scenario while just by adding one string it would be solved. And still, it would be all grouped into one entry.

**Comment by JimiC** [comment]
After discussing this with @robertohuertasm, we decided to drop the implementation of this feature.

@jens1o You can restore #996.
